config.sgmlのPostgreSQL 12.4対応です。
pgsql-jp/jpug-doc pull request #1747
Opened 2020-08-23 01:17 UTC by tatsuo-ishii

2020-08-26 13:27 UTC, KenichiroTanaka requested changes

2020-08-26 13:27 UTC, KenichiroTanaka commented on doc/src/sgml/config.sgml
>  セキュアな接続で使用できる<acronym>SSL</acronym>暗号スイートのリストを指定します。
原文が
Specifies a list of <acronym>SSL</acronym> cipher suites that are allow
used on secure connections. 
↓
Specifies a list of <acronym>SSL</acronym> cipher suites that are
allowed to be used by SSL connections. 

に変更されていますので、
「セキュアな接続で使用できる」→「SSL接続で使われる」

とするのはどうでしょうか。

2020-08-26 13:27 UTC, KenichiroTanaka commented on doc/src/sgml/config.sgml
>  このパラメータは、<filename>postgresql.conf</filename>ファイルか、サーバのコマンドラインでのみ設定可能です。
>このパラメータは、<filename>postgresql.conf</filename>ファイルか、サーバのコマンドラインでのみ設定可能です。

前からの箇所ですが、上記の一文はもう存在していないので削除して良いと思います。(本ブロックの末尾に移動しています。)

2020-08-28 13:09 UTC, koizumistr commented on doc/src/sgml/config.sgml
>  セキュアな接続で使用できる<acronym>SSL</acronym>暗号スイートのリストを指定します。
もう少し厳密に行くなら
SSL接続で使うことのできる（SSL暗号スイート）
辺りでどうでしょうか。

TLSで使える暗号スイートは当然仕様で決まっていますが、「俺のサーバではそのうちのこれとこれを使うんだ」というのをここで列挙するのでしょうから。

2020-08-29 03:07 UTC, tatsuo-ishii commented on doc/src/sgml/config.sgml
>  セキュアな接続で使用できる<acronym>SSL</acronym>暗号スイートのリストを指定します。
「SSL接続で使うことのできる<acronym>SSL</acronym>暗号スイートのリストを指定します」
としました。

2020-08-29 03:08 UTC, tatsuo-ishii commented on doc/src/sgml/config.sgml
>  このパラメータは、<filename>postgresql.conf</filename>ファイルか、サーバのコマンドラインでのみ設定可能です。
おっとそうですね。

2020-09-01 22:47 UTC, KenichiroTanaka approved these changes
小泉さん
補足ありがとうございます。

石井さん
対応ありがとうございます。
いただいている内容でマージします。

2020-09-01 22:47 UTC, merged