update create_extension for 12.4
pgsql-jp/jpug-doc pull request #1775
Opened 2020-09-26 11:22 UTC by koizumistr

ref/create_extension.sgml の12.4対応です。

2020-09-28 23:58 UTC, tatsuo-ishii requested changes

2020-09-28 23:58 UTC, tatsuo-ishii commented on doc/src/sgml/ref/create_extension.sgml
> +各拡張の文書で述べているように、拡張は安全なスキーマにインストールするか、依存する拡張と同じスキーマにインストールするか、その両方をすべきです。
「その両方をすべき」だと、2つのスキーマに拡張をインストールすることになってしまうのではないでしょうか？たぶんここで原文が意図しているのは、「安全」かつ「拡張と同じ」スキーマにインストールする、ということではないかと思います。以下ではどうでしょう？

...安全なスキーマ、または拡張が依存しているスキーマ、あるいはその両方であるスキーマにインストールするべきです

2020-10-12 10:58 UTC, koizumistr commented on doc/src/sgml/ref/create_extension.sgml
> +各拡張の文書で述べているように、拡張は安全なスキーマにインストールするか、依存する拡張と同じスキーマにインストールするか、その両方をすべきです。
確認ありがとうございます。

> たぶんここで原文が意図しているのは、「安全」かつ「拡張と同じ」スキーマにインストールする、ということではないかと思います。

はい、私もその理解です。

2020-10-17 21:16 UTC, tatsuo-ishii approved these changes

2020-10-18 23:36 UTC, merged