extensionの12.4対応です。
pgsql-jp/jpug-doc pull request #1780
Opened 2020-10-12 13:05 UTC by KenichiroTanaka

2020-10-18 03:55 UTC, tatsuo-ishii requested changes

2020-10-18 03:55 UTC, tatsuo-ishii commented on doc/src/sgml/extend.sgml
> + <varname>superuser</varname>プロパティを真にしている拡張はインストールやアップデートスクリプトの中で行われるアクションのセキュリティ面での危険も考慮しなければなりません。悪意あるユーザが不用意に書かれた拡張スクリプトを悪用してトロイの木馬を作成し、ユーザにスーパーユーザ権限を獲得させることは、そう難しくありません。
「ユーザにスーパーユーザ権限を獲得させる」の「ユーザ」は悪意のあるユーザを指していると思うので、そのことを明確にしたほうが良いと思います。以下のような感じではいかがでしょう？

スーパーユーザ権限を獲得できるようにすることは、そう難しくありません。

2020-10-18 03:55 UTC, tatsuo-ishii commented on doc/src/sgml/extend.sgml
> +XXX 名前を(スキーマ)修飾するだけでは十分ではありません。なぜなら修飾されていない名前を使っているおオブジェクトに修飾された名前を書くかもしれないためです。
「おオブジェクト」→「オブジェクト」

2020-10-18 03:55 UTC, tatsuo-ishii commented on doc/src/sgml/extend.sgml
> +汎用の拡張は通常、安全なスキーマにインストールされることを想定していないため、スキーマ修飾された自身のオブジェクトであっても完全にリスクがないわけではないことを意味しています。
"A general-purpose extension usually should not assume..."は、
「汎用の拡張は通常、安全なスキーマにインストールされることを想定するべきではありません」ではないでしょうか。

2020-10-21 12:03 UTC, KenichiroTanaka commented on doc/src/sgml/extend.sgml
> + <varname>superuser</varname>プロパティを真にしている拡張はインストールやアップデートスクリプトの中で行われるアクションのセキュリティ面での危険も考慮しなければなりません。悪意あるユーザが不用意に書かれた拡張スクリプトを悪用してトロイの木馬を作成し、ユーザにスーパーユーザ権限を獲得させることは、そう難しくありません。
ありがとうございます。シンプルで誤解もないので、案をいただきます。

2020-10-21 12:04 UTC, KenichiroTanaka commented on doc/src/sgml/extend.sgml
> +XXX 名前を(スキーマ)修飾するだけでは十分ではありません。なぜなら修飾されていない名前を使っているおオブジェクトに修飾された名前を書くかもしれないためです。
失礼しました。。

2020-10-21 12:08 UTC, KenichiroTanaka commented on doc/src/sgml/extend.sgml
> +汎用の拡張は通常、安全なスキーマにインストールされることを想定していないため、スキーマ修飾された自身のオブジェクトであっても完全にリスクがないわけではないことを意味しています。
ありがとうございます。notのかかる場所を間違えました。

2020-10-21 14:19 UTC, koizumistr reviewed
確認しました。

2020-10-21 14:19 UTC, koizumistr commented on doc/src/sgml/extend.sgml
> +拡張により提供されるSQL言語とPL言語関数は実行されるときにサーチパスによる攻撃を受ける危険性があります。
下の方では、「サーチパスに基づく攻撃」になっています。すくなくとも揃えるべきかと。

2020-10-21 14:19 UTC, koizumistr commented on doc/src/sgml/extend.sgml
> +拡張には汎用SQLを実行する必要があることがあります。
拡張→拡張スクリプト

2020-10-21 14:19 UTC, koizumistr commented on doc/src/sgml/extend.sgml
> +理由の一つに、他の拡張のスキーマがどのスキーマにあるのか定かではないことがあります。
他の拡張のスキーマがどのスキーマにあるのか
→ 他の拡張がどのスキーマにあるのか

2020-10-21 14:19 UTC, koizumistr commented on doc/src/sgml/extend.sgml
> +インストール時の<varname>search_path</varname>に悪意あるオブジェクトを参照された拡張の前に置くことができないからです。
どこがどこに係るかが分かりにくいです。

悪意あるオブジェクトをインストール時のsearch_path内で参照された拡張の前に

あたりでしょうか。

2020-10-21 14:19 UTC, koizumistr commented on doc/src/sgml/extend.sgml
> +拡張のインストールやアップデートスクリプトはスクリプト実行時にサーチパスに基づく攻撃を防ぐように記述されなければなりません。
「更新スクリプト」となっているところがあります。少なくとも揃えるべきでしょう。

2020-10-21 14:19 UTC, koizumistr commented on doc/src/sgml/extend.sgml
> +<literal>OR REPLACE</literal> を不必要に使うことは他の誰かの別の関数を誤って上書きしてしまうだけでなく、上書きされた関数は元の所有者のまま、変更できる状態となってしまい、セキュリティの脆弱性を作成してしまうリスクがあります。
誤って上書きしてしまうリスク(risk)があるだけでなく、上書きされた関数は元の所有者に所有されたままであり、元の所有者が変更できるので、セキュリティのリスク(hazard)になります。

というのがより原文に忠実かと。

2020-10-27 14:16 UTC, KenichiroTanaka commented on doc/src/sgml/extend.sgml
> +何らかの事前に必要な拡張が制御ファイル内の<varname>requires</varname>に列挙されていた場合、それらの対象スキーマが<varname>search_path</varname>の初期設定に続いて新しい拡張対象のスキーマが追加されます。
ありがとうございます。語順や主語の重複を修正しました。

2020-10-27 14:17 UTC, KenichiroTanaka commented on doc/src/sgml/extend.sgml
> + <varname>superuser</varname>プロパティを真にしている拡張はインストールやアップデートスクリプトの中で行われるアクションのセキュリティ面での危険も考慮しなければなりません。
空白を削除しました。また、更新スクリプトとしました。

2020-10-27 14:18 UTC, KenichiroTanaka commented on doc/src/sgml/extend.sgml
> +<title>Security Considerations for Extension Functions</title>
修正しました。

2020-10-27 14:19 UTC, KenichiroTanaka commented on doc/src/sgml/extend.sgml
> +しかし、これは参照されるオブジェクトの欠陥なので影響を受けるクエリは少ないでしょう。
修正しました。

2020-10-27 14:22 UTC, KenichiroTanaka commented on doc/src/sgml/extend.sgml
> +拡張には汎用SQLを実行する必要があることがあります。
修正しました

2020-10-27 14:24 UTC, KenichiroTanaka commented on doc/src/sgml/extend.sgml
> +理由の一つに、他の拡張のスキーマがどのスキーマにあるのか定かではないことがあります。
修正しました。

2020-10-27 14:25 UTC, KenichiroTanaka commented on doc/src/sgml/extend.sgml
> +インストール時の<varname>search_path</varname>に悪意あるオブジェクトを参照された拡張の前に置くことができないからです。
ありがとうございます。案をいただきます。

2020-10-27 14:28 UTC, KenichiroTanaka commented on doc/src/sgml/extend.sgml
> +拡張のインストールやアップデートスクリプトはスクリプト実行時にサーチパスに基づく攻撃を防ぐように記述されなければなりません。
更新スクリプトに合わせました。

2020-10-27 14:36 UTC, KenichiroTanaka commented on doc/src/sgml/extend.sgml
> +<literal>OR REPLACE</literal> を不必要に使うことは他の誰かの別の関数を誤って上書きしてしまうだけでなく、上書きされた関数は元の所有者のまま、変更できる状態となってしまい、セキュリティの脆弱性を作成してしまうリスクがあります。
修正しました。

2020-10-28 08:39 UTC, KenichiroTanaka commented on doc/src/sgml/extend.sgml
> +そのため、中心のPostgreSQLにはそのような欠陥が含まれないように拡張の作成者を誘導して下さい。
いただいている案が正しいように思いますので、修正しました。
また、「中心のPostgreSQL」も分かりにくいので、「コアのPostgreSQLには」としました。

2020-10-28 08:40 UTC, KenichiroTanaka commented
小泉さんからの指摘に対応しました。

2020-10-29 11:52 UTC, koizumistr commented
対応ありがとうございます。確認しました。
1653行目と1566行目の指摘の対応が漏れているようです（ブラウザーで表示すると最初は隠れているみたいです）。
また、search-path-based attacksに関して、他のところでも「サーチパスによる攻撃」となっているのを見つけました。「サーチパスによる攻撃」の方が多数派かもしれないですが、少なくとも揃えるべきかと。

2020-11-01 09:22 UTC, KenichiroTanaka commented on doc/src/sgml/extend.sgml
> +
失礼しました。削除しました。

2020-11-01 09:40 UTC, KenichiroTanaka commented
ありがとうございます。
「サーチパスによる攻撃側」に合わせました。

2020-11-03 02:00 UTC, koizumistr approved these changes
確認しました。対応ありがとうございます。

2020-11-03 02:01 UTC, koizumistr commented
私で二人目のレビューアーということで、マージまで進めようと思ったのですが、今の状況だと石井さんでないとマージまでできない、ということなのでしょうか。

2020-11-03 03:30 UTC, tatsuo-ishii approved these changes
確認しました。

2020-11-03 03:31 UTC, tatsuo-ishii commented
失礼しました。approveしてmergeします。

2020-11-03 03:31 UTC, merged