update xoper for 13.1
pgsql-jp/jpug-doc pull request #1795
Opened 2020-11-18 09:17 UTC by koizumistr

xoper.sgml の13.1対応です。

が、何が書いてあるのか自分でもよく分かっていません(T_T)

2020-11-20 21:35 UTC, KenichiroTanaka requested changes

2020-11-20 21:35 UTC, KenichiroTanaka commented on doc/src/sgml/xoper.sgml
> +デフォルトの評価は<function>eqsel</function>で設定されているデフォルトの評価の2倍に設定されています。
> making   it most suitable for comparison operators that are somewhat less   strict than equality. 
の訳出が抜けているようです。

2020-11-22 12:12 UTC, koizumistr commented on doc/src/sgml/xoper.sgml
> +デフォルトの評価は<function>eqsel</function>で設定されているデフォルトの評価の2倍に設定されています。
確認ありがとうございます。対応しました。

2020-12-01 22:50 UTC, KenichiroTanaka requested changes

2020-12-01 22:50 UTC, KenichiroTanaka commented on doc/src/sgml/xoper.sgml
> +デフォルトの評価は<function>eqsel</function>で設定されているデフォルトの評価の2倍に設定されており、等価性ほど厳密でないような比較演算子にはとてもふさわしいものとなっています。
>比較演算子にはとてもふさわしいものとなっています。
mostなので最上級で表現する方が良いように思います。
また、関数を「ふさわしい」と表現する点に違和感(好みの問題かもです)がありました。

「比較演算子に最も適しています。」

くらいの訳ではどうでしょうか。

2020-12-09 05:40 UTC, koizumistr commented on doc/src/sgml/xoper.sgml
> +デフォルトの評価は<function>eqsel</function>で設定されているデフォルトの評価の2倍に設定されており、等価性ほど厳密でないような比較演算子にはとてもふさわしいものとなっています。
「最適です」にしてみました。いかがでしょう。

2020-12-14 22:47 UTC, KenichiroTanaka commented on doc/src/sgml/xoper.sgml
> +デフォルトの評価は<function>eqsel</function>で設定されているデフォルトの評価の2倍に設定されており、等価性ほど厳密でないような比較演算子にはとてもふさわしいものとなっています。
良いと思います。対応ありがとうございます。

2020-12-14 22:49 UTC, KenichiroTanaka approved these changes

2020-12-14 22:49 UTC, merged