update xml2 for 13.1
pgsql-jp/jpug-doc pull request #1796
Opened 2020-11-18 09:52 UTC by koizumistr

xml2.sgml の13.1対応です。

「表のマージ云々」と話題になっていたのはこの件だったのか、とようやく分かりました。微妙に文も変わっているので自動は厳しいですね、、、

2020-12-02 13:38 UTC, KenichiroTanaka requested changes
一通り確認しました。

2020-12-02 13:38 UTC, KenichiroTanaka commented on doc/src/sgml/xml2.sgml
> +<!--
Parses the given document and returns true if the  document is well-formed XML.
の箇所は少しですが変更があるため、訳出した方が良いように思います。
「パラメータとして与えられた」を削除するだけかと思いますが。

2020-12-09 05:45 UTC, koizumistr commented
確認ありがとうございます。原文により忠実になるよう修正しました。

2020-12-14 22:50 UTC, KenichiroTanaka approved these changes
一通り確認しました。

2020-12-14 22:50 UTC, merged