config.sgmlのPostgreSQL 13.1対応です。
pgsql-jp/jpug-doc pull request #1802
Opened 2020-11-22 07:54 UTC by tatsuo-ishii

いつものように、レビューはconfig[0-3].sgmlに対してお願いします。

2020-12-11 06:19 UTC, koizumistr reviewed
まだconfig0.sgml だけしか見ていませんが、取り急ぎコメントします。

2020-12-11 06:19 UTC, koizumistr commented on doc/src/sgml/config0.sgml
>  こうしたシステムでは、制限したいユーザだけが検索パーミッションを持つディレクトリを<varname>unix_socket_directories</varname>で指すようにすることによって同じような効果を得ることができます。
今回の修正部分ではないですが、「制限したいユーザだけが検索パーミッションを持つディレクトリ」というのは逆の意味にとられてしまうように思います。「許可されたユーザに対してだけ検索パーミッションを設定する」ということかと思いますが、、、

2020-12-11 06:19 UTC, koizumistr commented on doc/src/sgml/config0.sgml
> +一時メモリへの書き込み開始の前に、それぞれの操作にこの値が指定するのと同じメモリ容量の使用が許容されます。
一時メモリ → 一時ファイル

2020-12-11 06:19 UTC, koizumistr commented on doc/src/sgml/config0.sgml
> +一時ディスクファイルに書き込むようになる前に、クエリ操作（たとえば並べ替えとハッシュテーブル操作）が使用する基本的な最大のメモリ容量を指定します。
前からのようですが
クエリ操作 → 問い合わせ操作

2020-12-11 06:35 UTC, koizumistr reviewed
config3も見ました。とりあえず今はここまで。

2020-12-11 06:35 UTC, koizumistr commented on doc/src/sgml/config3.sgml
> +     </para>
もの凄く細かいことですが、＜/para＞の前の空白の数が変わってしまっているようです。

2020-12-11 06:35 UTC, koizumistr commented on doc/src/sgml/config3.sgml
> +このパラメータがサーバ起動時にのみ設定できます。
この前にあるHowever, it may allow you to get..が訳されていないようです。

2020-12-11 06:35 UTC, koizumistr commented on doc/src/sgml/config3.sgml
> +<literal>off</literal>（デフォルトです）に設定すると、無効なページを参照しているWALレコードは<productname>PostgreSQL</productname>に対してPANICレベルのエラーを引き起こし、リカバリをアボートします。
during recoveryが訳されていませんが、意図的なものでしょうか。

2020-12-11 08:23 UTC, tatsuo-ishii commented on doc/src/sgml/config0.sgml
>  こうしたシステムでは、制限したいユーザだけが検索パーミッションを持つディレクトリを<varname>unix_socket_directories</varname>で指すようにすることによって同じような効果を得ることができます。
たしかに。修正します。

2020-12-11 08:24 UTC, tatsuo-ishii commented on doc/src/sgml/config0.sgml
> +一時メモリへの書き込み開始の前に、それぞれの操作にこの値が指定するのと同じメモリ容量の使用が許容されます。
おっと、失礼しました。

2020-12-11 08:26 UTC, tatsuo-ishii commented on doc/src/sgml/config0.sgml
> +一時ディスクファイルに書き込むようになる前に、クエリ操作（たとえば並べ替えとハッシュテーブル操作）が使用する基本的な最大のメモリ容量を指定します。
修正します。

2020-12-11 08:30 UTC, tatsuo-ishii commented on doc/src/sgml/config3.sgml
> +<literal>off</literal>（デフォルトです）に設定すると、無効なページを参照しているWALレコードは<productname>PostgreSQL</productname>に対してPANICレベルのエラーを引き起こし、リカバリをアボートします。
一応「リカバリ、」とあるのですが、分かりにくいかも知れないので
「リカバリ中、あるいはスタンバイモードでのみ効果があります。」
とします。

2020-12-15 08:11 UTC, koizumistr commented
対応ありがとうございます。確認しました。

config3に対する「この前にあるHowever, it may allow you to get..が訳されていないようです。」の指摘への対応がまだのようです。（中央付近の指摘なので、ブラウザーや画面の大きさによっては、折りたたまれていて見えなくなっているかもです。）

2020-12-15 22:44 UTC, KenichiroTanaka requested changes
一通り確認しました。
時間がかかってしまったので、小泉さんと重複があるかもしれません。

2020-12-16 00:31 UTC, tatsuo-ishii commented on doc/src/sgml/config0.sgml
> +デフォルトは<literal>TLSv1.2</literal>で、本校執筆時点では業界のベストプラクティスを満たしています。
失礼しました。

2020-12-16 00:32 UTC, tatsuo-ishii commented on doc/src/sgml/config0.sgml
> +一般に、ハッシュに基づく操作はソートに基づく操作よりも利用可能なメモリに敏感です。
「一般的に」の方が良いですね。

2020-12-16 00:36 UTC, tatsuo-ishii commented on doc/src/sgml/config1.sgml
>          In any case, if a recovery target is configured but the archive
翻訳漏れ失礼しました。

2020-12-16 00:52 UTC, tatsuo-ishii commented on doc/src/sgml/config1.sgml
> +WAL受信プロセスが実行中にこのパラメータが変更されると、そのプロセスにシグナルが送られ、新しい設定で再起動するために停止します（<varname>primary_conninfo</varname>が空文字の場合を除きます。）
実際WAL recieverプロセスが停止してしまうようです。(primary_coninfoを変更してreloadで停止します)

2020-12-16 13:11 UTC, KenichiroTanaka commented on doc/src/sgml/config1.sgml
> +WAL受信プロセスが実行中にこのパラメータが変更されると、そのプロセスにシグナルが送られ、新しい設定で再起動するために停止します（<varname>primary_conninfo</varname>が空文字の場合を除きます。）
私の理解不足でした。上記了解です。

2020-12-16 13:36 UTC, KenichiroTanaka commented on doc/src/sgml/config1.sgml
>          In any case, if a recovery target is configured but the archive
対応ありがとうございます。
いただいている内容で問題無いと思います。

1点、(仕組みの理解が誤っていたらすみません)
本修正はconfig.sgmlには反映されていますが、config1.sgmには反映されていないように見えます。
両方への反映が必要と理解していますが、この指摘は合っているでしょうか。

2020-12-17 09:28 UTC, tatsuo-ishii commented on doc/src/sgml/config1.sgml
>          In any case, if a recovery target is configured but the archive
済みません。config1,sgmlの更新を忘れていました。

2020-12-17 13:18 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。
確認しました。

2020-12-22 13:11 UTC, merged