update contrib for 13.1
pgsql-jp/jpug-doc pull request #1834
Opened 2021-01-05 08:09 UTC by kitayama

2021-01-06 14:26 UTC, koizumistr reviewed
確認しました。
下の方に行くにつれて自信がなくなっていくので、誰か見てほしいな、と。

2021-01-06 14:26 UTC, koizumistr commented on doc/src/sgml/contrib.sgml
>  以下に例を示します。
今回の変更部分ではないですが、余分だと思います。ひとつ前ですでに「以下のように」とありますので。

2021-01-06 14:26 UTC, koizumistr commented on doc/src/sgml/contrib.sgml
> +このコマンドは現在のデータベースの中にのみ新しいオブジェクトを登録します。
ここも元々がそうだったみたいですが、より原文に忠実にするなら「SQLオブジェクト」かと。

2021-01-06 14:26 UTC, koizumistr commented on doc/src/sgml/contrib.sgml
> +これら全てのモジュールについて、モジュールが<quote>trusted</quote>と見なされない限り<command>CREATE EXTENSION</command>はデータベーススーパーユーザによって実行される必要がありますが、現在のデータベースに対して<literal>CREATE</literal>権限を持つユーザであれば誰でも実行することができます。
モジュールがtrustedと見なされない限りCREATE EXTENSIONはデータベーススーパーユーザによって実行される必要があります
というのはその通りだと思いますが、
現在のデータベースに対してCREATE権限を持つユーザであれば誰でも実行することができます。 
というのは「モジュールがtrustedと見なされる場合」について述べているのだと思います。

2021-01-09 12:27 UTC, kitayama commented on doc/src/sgml/contrib.sgml
>  以下に例を示します。
「以下のように」の実行例としてコマンドそのものが示されているので、この文は削除します。

2021-01-09 12:28 UTC, kitayama commented on doc/src/sgml/contrib.sgml
> +このコマンドは現在のデータベースの中にのみ新しいオブジェクトを登録します。
SQL objectsは本テキストファイルに二か所出てきますので、両方とも「SQLオブジェクト」に修正します。

2021-01-09 12:29 UTC, kitayama commented on doc/src/sgml/contrib.sgml
> +これら全てのモジュールについて、モジュールが<quote>trusted</quote>と見なされない限り<command>CREATE EXTENSION</command>はデータベーススーパーユーザによって実行される必要がありますが、現在のデータベースに対して<literal>CREATE</literal>権限を持つユーザであれば誰でも実行することができます。
ご指摘の通りだと思いますので修正します。in which case のかかりをきちんと理解できてませんでした。

2021-01-10 14:58 UTC, koizumistr commented
確認しました。
- 「以下のように」云々
- もう一つあるSQLオブジェクト
の対応が入っていないように見えますが、、、（私の見方が間違っている？）

2021-01-11 12:47 UTC, kitayama commented
●「以下のように」云々
→こちらは「これは<xref linkend="sql-createextention"/> コマンドを実行することで行われます。」を削除する対応をしました。考えられていた対応とは違う可能性はあるかと思います。
●「もう一つあるSQLオブジェクト」
→SQLオブジェクトは「コードをインストールした後に、新しいSQLオブジェクト」と「現在のデータベースの中にのみ新しいSQLオブジェクト」の二か所です。

2021-01-12 14:00 UTC, KenichiroTanaka commented
>●「以下のように」云々
>→こちらは「これは コマンドを実行することで行われます。」を削除する対応をしました。考えられていた対応とは違う可能性>はあるかと思います。
「これは コマンドを実行することで行われます。」は原文もありますし、削除しない方が良いのではないかと思います。
代わりに「以下に例を示します。」は原文もありませんし、小泉さんご指摘の通り「以下〜」が２箇所出てくるので、
こちらを削除するのはどうでしょうか。

2021-01-12 14:05 UTC, KenichiroTanaka commented
>もう一つあるSQLオブジェクト
は問題無く修正いただいているように見えます。

2021-01-12 14:08 UTC, KenichiroTanaka commented on doc/src/sgml/contrib.sgml
> +これら全てのモジュールは<command>CREATE EXTENSION</command>はデータベーススーパーユーザによって実行される必要がありますが、モジュールが<quote>trusted</quote>と見なされる場合は現在のデータベースに対して<literal>CREATE</literal>権限を持つユーザであれば誰でも実行することができます。
>これら全てのモジュールは<command>CREATE EXTENSION</command>は
「〜は〜は」と続いて主語がパッと読み取りにくく感じます。
「これら全てのモジュールについて、<command>CREATE EXTENSION</command>は」
などとするのはどうでしょうか。

2021-01-12 14:09 UTC, KenichiroTanaka requested changes
一通り確認しました。

2021-01-13 06:29 UTC, kitayama commented
田中さんの指摘事項を反映して更新しました。再度レビューをお願いします。

2021-01-13 22:51 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。
私のコメント箇所は対応されていることを確認しました。

2021-01-18 10:44 UTC, merged