update ref/vacuum.sgml for 13.1
pgsql-jp/jpug-doc pull request #1838
Opened 2021-01-10 10:18 UTC by kitayama

2021-01-14 10:43 UTC, KenichiroTanaka requested changes
一通り確認しました。
いくつか気づいたことがありますので対応をお願いします。

2021-01-14 10:43 UTC, KenichiroTanaka commented on doc/src/sgml/ref/vacuum.sgml
> +また、インデックスを処理するために複数のCPUを活用することもできます。 この機能は、並列バキュームとして知られています。 この機能を無効にするには、PARALLELオプションでパラレルワーカーの数をゼロに指定します。
< firstterm >のタグが抜けてしまっているので加えていただけますでしょうか。
また、お手数ですが1文1行での翻訳をお願いできますでしょうか。

2021-01-14 10:43 UTC, KenichiroTanaka commented on doc/src/sgml/ref/vacuum.sgml
> +PARALLELオプションはバキュームの用途でのみ使用されます。このオプションをANALYZEオプションで指定した場合、ANALYZEには影響しません。
２箇所、<option>タグが抜けてしまっているため、追記をお願いします。

2021-01-14 11:48 UTC, kitayama commented on doc/src/sgml/ref/vacuum.sgml
> +また、インデックスを処理するために複数のCPUを活用することもできます。 この機能は、並列バキュームとして知られています。 この機能を無効にするには、PARALLELオプションでパラレルワーカーの数をゼロに指定します。
上記の二点、対応しました。

2021-01-14 11:49 UTC, kitayama commented on doc/src/sgml/ref/vacuum.sgml
> +PARALLELオプションはバキュームの用途でのみ使用されます。このオプションをANALYZEオプションで指定した場合、ANALYZEには影響しません。
追記しました。また原文一行、翻訳一行の対応をしました。

2021-01-15 13:11 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。
確認しました。
並列ワーカーも修正いただいた内容が良いと思います。

2021-01-15 13:12 UTC, merged