update pg_rewind for 13.1
pgsql-jp/jpug-doc pull request #1839
Opened 2021-01-10 14:46 UTC by koizumistr

ref/pg_rewind.sgml の13.1対応です。

2021-01-16 01:54 UTC, tatsuo-ishii requested changes

2021-01-16 01:54 UTC, tatsuo-ishii commented on doc/src/sgml/ref/pg_rewind.sgml
> +これでリレーションファイルは、ソースとターゲットのWALタイムラインが分岐した時点より前で最後に完了したチェックポイントの時点に加えて、分岐後にターゲットで変更されたブロックのソースでの現在の状態に相当する状態になります。
> plus the current state on the source of any  blocks changed on the target after that divergence.

ここの訳が難しいのですが、原文の意図は、「分岐後にターゲットで変更されたブロックを含んだ現在のソースの状態を加える」ではないかと思います。

ですから、ここの訳は、

「分岐後にターゲットで変更されたブロックを含んだソースでの現在の状態に相当する状態になります。」

ではどうでしょう？

2021-01-18 15:24 UTC, koizumistr commented on doc/src/sgml/ref/pg_rewind.sgml
> +これでリレーションファイルは、ソースとターゲットのWALタイムラインが分岐した時点より前で最後に完了したチェックポイントの時点に加えて、分岐後にターゲットで変更されたブロックのソースでの現在の状態に相当する状態になります。
確認ありがとうございます。提案の訳が良いように思いましたので、そのまま採用させてもらいました。
（ただ、自分の頭が付いて行っている自信はありません(T_T)）

2021-01-24 07:05 UTC, tatsuo-ishii approved these changes
確認したのでマージします。

2021-01-24 07:05 UTC, merged