update datetime.sgml for 13.1
pgsql-jp/jpug-doc pull request #1841
Opened 2021-01-14 11:19 UTC by kitayama

2021-01-16 02:14 UTC, tatsuo-ishii requested changes
一通り確認しました。

2021-01-16 02:14 UTC, tatsuo-ishii commented on doc/src/sgml/datetime.sgml
> +夏時間の省略形が与えられているが移行ルールフィールドが省略されている場合、代替の動作には2020年のアメリカ合衆国の習慣と照合される<literal>M3.2.0,M11.1.0</literal>(3月の第2日曜日に夏時間に切り替わり、11月の第1日曜日に戻ります。両方の変換はその時進んでいる時間の午前2時に行われます)が使用されます。
"transition"は「変換」ではなく「移行」ないし「遷移」と訳すほうが良いと思います。

2021-01-20 01:32 UTC, kitayama commented on doc/src/sgml/datetime.sgml
> +夏時間の省略形が与えられているが移行ルールフィールドが省略されている場合、代替の動作には2020年のアメリカ合衆国の習慣と照合される<literal>M3.2.0,M11.1.0</literal>(3月の第2日曜日に夏時間に切り替わり、11月の第1日曜日に戻ります。両方の変換はその時進んでいる時間の午前2時に行われます)が使用されます。
"transition" は「移行」にしました。また訳語の不統一に気付いたので "time zone abbreviation" は 「時間帯省略形」に統一などをしました。

2021-01-24 07:07 UTC, tatsuo-ishii approved these changes
確認したのでマージします。

2021-01-24 07:07 UTC, merged