isn.sgmlの13.1対応です。
pgsql-jp/jpug-doc pull request #1844
Opened 2021-01-19 06:04 UTC by noborus

更新された部分以外に以下の変更をしました。
「弱め」→「weak」
「検査桁」→「チェックディジット」

weakは「isn_weak」のために使用していて「弱め」と表現する例が他に無さそうなので、
そのままweakに変更しました。

「チェックディジット」は既に広く使われている様なので変更しました。

2021-01-27 22:59 UTC, KenichiroTanaka requested changes
ありがとうございます。weak、チェックディジットへの変更は分かりやすくなったと思います。
1箇所だけ、対応をお願いします。

2021-01-27 22:59 UTC, KenichiroTanaka commented on doc/src/sgml/isn.sgml
> +<firstterm>Weak</firstterm>モードは無効なデータをテーブルに挿入できるようにするために使用されます。
細かいですが、全体を通して小文字なのでweakの「w」は小文字が良いと思います。
※原文は行頭なので大文字になっているのだと思います。

2021-01-29 03:06 UTC, noborus commented on doc/src/sgml/isn.sgml
> +<firstterm>Weak</firstterm>モードは無効なデータをテーブルに挿入できるようにするために使用されます。
ありがとうございます。修正します。

2021-02-01 21:41 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。
マージします。

2021-02-01 21:41 UTC, merged