update earthdistance for 13.1
pgsql-jp/jpug-doc pull request #1850
Opened 2021-01-23 04:10 UTC by koizumistr

earthdistance.sgml の13.1対応です。

2021-02-03 23:04 UTC, KenichiroTanaka requested changes
細かいですが１箇所だけ修正をお願いします。

2021-02-03 23:04 UTC, KenichiroTanaka commented on doc/src/sgml/earthdistance.sgml
> +位置から指定した大圏距離内の点に対するcubeの<literal>@&gt;</literal>演算子を使用するインデックス検索に適した矩形を返します。
cubeのタグが外れてしまっています。

2021-02-06 08:23 UTC, koizumistr commented on doc/src/sgml/earthdistance.sgml
> +位置から指定した大圏距離内の点に対するcubeの<literal>@&gt;</literal>演算子を使用するインデックス検索に適した矩形を返します。
確認ありがとうございます。対応しました。

2021-02-13 13:35 UTC, KenichiroTanaka approved these changes
一通り確認しました。

2021-02-13 13:35 UTC, merged