リリースノートの13, 13.1 バージョン対応翻訳。
pgsql-jp/jpug-doc pull request #1857
Opened 2021-01-31 07:46 UTC by harukat

2021-02-13 15:31 UTC, KenichiroTanaka requested changes
大量の翻訳対応ありがとうございました。
細かなことも含めて気づいたところがありましたのでコメントしました。
対応をお願いします。

2021-02-13 15:31 UTC, KenichiroTanaka commented on doc/src/sgml/release-13.sgml
> +★
訳が抜けているようです。

2021-02-13 15:31 UTC, KenichiroTanaka commented on doc/src/sgml/release-13.sgml
下のブロックにある「 Add <function>min()</function> and〜」の訳が抜けているようです。

2021-02-13 15:31 UTC, KenichiroTanaka commented on doc/src/sgml/release-13.sgml
> +<application>psql</application>の<link linkend="app-psql-meta-commands"><literal>\g</literal></link>と<literal>\gx</literal>コマンドで単一コマンドの間について<link linkend="app-psql-meta-commands">\pset</link>出力オプションを変
(Tom Lane)が抜けているようです。

2021-02-13 15:31 UTC, KenichiroTanaka commented on doc/src/sgml/release-13.sgml
> +pgbenchが<quote>accounts</quote>テーブルをパーティション分割できるようにしました。
(Fabien Coelho)が抜けているようです。

2021-02-13 15:31 UTC, KenichiroTanaka commented on doc/src/sgml/release-13.sgml
> +
不要な空行が入っています。

2021-02-13 15:31 UTC, KenichiroTanaka commented on doc/src/sgml/release-13.sgml
> +これらは一部のバージョン0のC関数との互換性のために必要とされていましたが、それらも最早サポートされません。
細かいですが、最早は他では「もはや」とひらがなで記載されているようです。

2021-02-13 15:31 UTC, KenichiroTanaka commented on doc/src/sgml/release-13.sgml
>        </para>
(Andrew Dunstan)が抜けているようです。

2021-02-13 15:31 UTC, KenichiroTanaka commented on doc/src/sgml/release-13.sgml
> +<xref linkend="ltree"/>のlquery構文を<literal>NOT</literal> (!)をより論理的に処理するように作り直しました。
〜を、〜をと続いているので少し分かりづらくなっているように思います。
<xref linkend="ltree"/>のlquery構文が<literal>NOT</literal> (!)をより論理的に処理するように作り直しました。
とするのはどうでしょうか。

2021-02-27 14:38 UTC, koizumistr reviewed
13.0の変更点の手前まで見ました。

2021-02-27 14:38 UTC, koizumistr commented on doc/src/sgml/release-13.sgml
> -
原文の空行が消えてます？

2021-02-27 14:38 UTC, koizumistr commented on doc/src/sgml/release-13.sgml
> +これはオペレーションシステムのクラッシュ後に起こりうるデータ損失を防止します。
原文通りに行くと「オペレーティングシステム」と思いますが、意図的なものでしょうか。

2021-02-27 14:38 UTC, koizumistr commented on doc/src/sgml/release-13.sgml
> +これにより、<quote>missing chunk number 0 for toast value NNN（TOAST値NNNのためのチャック番号0がありません）</quote>のようなエラーが生じる可能性がありました。
チャック番号 → チャンク

2021-02-27 14:38 UTC, koizumistr commented on doc/src/sgml/release-13.sgml
> +<xref linkend="app-pg-dumpall"/>を利用したダンプとリストア、あるいは<xref linkend="pgupgrade"/>の使用が必要です。
logical replicationが抜けているようです。

2021-03-06 05:50 UTC, koizumistr reviewed
最後まで見ました。

2021-03-06 05:50 UTC, koizumistr commented on doc/src/sgml/release-13.sgml
> +Windwosで照合順序バージョンに対応しました。
Windwos → Windows

2021-03-06 05:50 UTC, koizumistr commented on doc/src/sgml/release-13.sgml
> +これらに対応するより望ましい既存オプションは<option>--superuser</option>と<option>--no-superuser</option>です。
long-supportedに対応する訳がないようです。（入れるとごたごたする気もしますが、、）

2021-03-06 05:50 UTC, koizumistr commented on doc/src/sgml/release-13.sgml
> +<xref linkend="pageinspect"/>に<structfield>t_infomask</structfield>/<structfield>t_infomask2</structfield>値の人間に読みやすい書式で出力する関数を追加しました。
t_infomask2値の → t_infomask2値を

2021-05-05 05:03 UTC, harukat commented on doc/src/sgml/release-13.sgml
> +4および8バイトの<link linkend="intarray">整数配列</link>、<link linkend="textsearch">tsvector</link>、<xref linkend="pgtrgm"/>、<xref linkend="ltree"/>、および、<xref linkend="hstore"/>の列に対して作成されたインデックスは、デフォルト値を使うのではなく
「インデックスがインデックスパラメータを制御する」は断じて変だと思うのですが、
日本語としては「これらのインデックスはインデックスパラメータを制御できる」と書いてあったら「これらのインデックスについて言えばインデックスパラメータを制御できる」と読めますから、素直に訳しても良いですね。

2021-05-05 05:20 UTC, harukat commented on doc/src/sgml/release-13.sgml
> +これらに対応するより望ましい既存オプションは<option>--superuser</option>と<option>--no-superuser</option>です。
「log-supported」を「既存」で済ませていました。もう少し「long」を尊重して「以前からある」としました。

2021-06-07 14:18 UTC, KenichiroTanaka requested changes
確認が遅くなりました。
修正されていることを確認しました。

2021-06-07 14:19 UTC, KenichiroTanaka approved these changes
マージします。

2021-06-07 14:19 UTC, merged