fdwhandler.sgml の13.1対応です。
pgsql-jp/jpug-doc pull request #1863
Opened 2021-02-05 06:04 UTC by noborus

前半はマージ時に消えた12.4の訳の復活です。

2021-02-14 11:13 UTC, tatsuo-ishii requested changes
一通り確認しました。

2021-02-14 11:13 UTC, tatsuo-ishii commented on doc/src/sgml/fdwhandler.sgml
> +また、外部テーブルの総行数の見積もりをより正しく計算できる場合、この関数は、<literal>baserel-&gt;tuples</literal>を上書きします。
"may update"を「上書きします」とするのは少し意訳過ぎるかも知れないですね。
「更新しても構いません」くらいではどうでしょう？

2021-02-15 06:21 UTC, noborus commented on doc/src/sgml/fdwhandler.sgml
> +また、外部テーブルの総行数の見積もりをより正しく計算できる場合、この関数は、<literal>baserel-&gt;tuples</literal>を上書きします。
ありがとうございます。
修正しました。

2021-02-20 00:43 UTC, tatsuo-ishii approved these changes
確信しました。対応ありがとうございます。

2021-02-20 00:43 UTC, merged