update pgbench for 13.1
pgsql-jp/jpug-doc pull request #1869
Opened 2021-02-14 10:42 UTC by koizumistr

ref/pgbench.sgmlの13.1対応です。

2021-02-14 10:44 UTC, koizumistr commented
zipfianですが、「ジップ分布」と「ジフ分布」が混ざっていたので、ジップ分布としました。
ただし、「ジフ分布」も誤りではないようですので、「この業界では『ジフ分布』が優勢だ」とかありましたらお知らせください。

2021-02-21 00:17 UTC, tatsuo-ishii requested changes
一通り確認しました。

2021-02-21 00:17 UTC, tatsuo-ishii commented on doc/src/sgml/ref/pgbench.sgml
> +<literal>g</literal>を使うと、<structname>pgbench_accounts</structname>テーブルのためにデータを生成する間、100000行毎にメッセージを1つログ出力するようになります。
細かい話ですが、「100000行毎」だとぱっと見、桁が良くわからないので、原文通りカンマを入れて「100,000行毎」の方が良いと思います。

2021-02-21 00:17 UTC, tatsuo-ishii commented on doc/src/sgml/ref/pgbench.sgml
> +こちらは大域を著しく要求することはありませんが、サーバが、より多くの作業をすることになります。
大域→帯域

2021-02-21 00:17 UTC, tatsuo-ishii commented on doc/src/sgml/ref/pgbench.sgml
> +デフォルトのログ処理では、100000行毎にメッセージを１つ出力し、（特に優れたハードウェアでは）1秒当たりに多くのメッセージを出力します。
こちらも「100000行毎」→「100,000行毎」の方が良いかと。

2021-02-21 07:34 UTC, koizumistr commented
確認ありがとうございます。対応しました。

2021-02-21 11:13 UTC, tatsuo-ishii approved these changes
対応ありがとうございます。

2021-02-21 11:13 UTC, merged