update create_database & role for 13.1
pgsql-jp/jpug-doc pull request #1872
Opened 2021-02-14 13:45 UTC by koizumistr

以下のファイルの13.1対応です。

- ref/create_database.sgml
- ref/create_role.sgml

2021-02-14 13:49 UTC, koizumistr commented
訳には影響ありませんが、原文でvirginがpristineに変更されているのに気づきました。こういう変更もあるんですね。

＃ これ以上は会長の辞任に追い込まれかねないのでコメントは控えさせていただきます:-p

2021-02-17 23:16 UTC, KenichiroTanaka requested changes
細かなところを含みますが２箇所ほど対応をお願いします。

2021-02-17 23:16 UTC, KenichiroTanaka commented on doc/src/sgml/ref/create_database.sgml
> +特に、<literal>TEMPLATE template0</literal>と記述することで、そのバージョンの<application>PostgreSQL</application>によって定義済みの標準オブジェクトのみを持つ、(そこではユーザ定義オブジェクトは存在せず、システムオブジェクトは変更されていない)新しいデータベースを作ることができます。
前からの訳ですが、a pristine database(以前はa virgin database)は「新しいデータベース」では汚れていない、新品同様な、というニュアンスが無く少し足りないように思います。「初期状態のデータベース」などの訳ではどうでしょうか。

2021-02-17 23:16 UTC, KenichiroTanaka commented on doc/src/sgml/ref/create_role.sgml
> +-->
少し上にある変更分が反映されていないようです。
```
@@ -181,6 +181,8 @@ in sync when changing the above synopsis!
         highly privileged role, and should only be used on roles actually
         used for replication. If not specified,
         <literal>NOREPLICATION</literal> is the default.
+        You must be a superuser to create a new role having the
+        <literal>REPLICATION</literal> attribute.
        </para>
       </listitem>
      </varlistentry>
```

2021-02-19 23:45 UTC, koizumistr commented
確認ありがとうございます。対応しました。

2021-02-22 20:08 UTC, KenichiroTanaka approved these changes
一通り確認しました。

2021-02-22 20:08 UTC, merged