update hstore for 13.1
pgsql-jp/jpug-doc pull request #1874
Opened 2021-02-18 15:34 UTC by koizumistr

hstore.sgml の13.1対応です。

2021-02-23 07:36 UTC, tatsuo-ishii requested changes
一通り確認しました。

2021-02-23 07:36 UTC, tatsuo-ishii commented on doc/src/sgml/hstore.sgml
> +非nullの値をすべてJSON文字列に変換し、<type>hstore</type>を<type>json</type>値に変換します。
「〜変換し、〜に変換します。」だと、最初の変換を完了してから次の変換を行うように取れるので、
「非nullの値をすべてJSON文字列に変換しながら、」としてはどうでしょう？

2021-02-23 07:36 UTC, tatsuo-ishii commented on doc/src/sgml/hstore.sgml
> +非nullの値をすべてJSON文字列に変換し、<type>hstore</type>を<type>jsonb</type>値に変換します。
同上。

2021-02-23 08:54 UTC, koizumistr commented
確認ありがとうございます。対応しました。

2021-02-27 11:09 UTC, tatsuo-ishii approved these changes
確認しました。対応ありがとうございます。

2021-02-27 11:09 UTC, merged