update intallation for 13.1
pgsql-jp/jpug-doc pull request #1880
Opened 2021-02-27 07:26 UTC by koizumistr

installation.sgml  の 13.1 対応です。

2021-03-07 10:46 UTC, tatsuo-ishii requested changes
一通り確認しました。

2021-03-07 10:46 UTC, tatsuo-ishii commented on doc/src/sgml/installation.sgml
> +<xref linkend="regress"/>にはテスト結果の表示に関する詳しい情報があります。
"intepreting"なので、「表示」ではなくて「解釈」といったあたりではないでしょうか？

2021-03-07 10:46 UTC, tatsuo-ishii commented on doc/src/sgml/installation.sgml
> +しかし、異なるサブディレクトリの相対的な位置を変更した場合、インストレーションは位置再変更不可になります。つまり、インストールの後にディレクトリを移動できないことに注意してください。
"non-relocatable"は「再配置不能」と訳すことが多いような気がします。

2021-03-07 10:46 UTC, tatsuo-ishii commented on doc/src/sgml/installation.sgml
> +インストールの位置再変更のために、後述の<literal>--disable-rpath</literal>を使用しようと考えるかもしれません。
"For relocatable installation"は、「再配置可能インストール」あたりでしょうか。

2021-03-07 10:46 UTC, tatsuo-ishii commented on doc/src/sgml/installation.sgml
> +スレッドのサポートに血管があるプラットフォームでのみ、これを使ってください。
血管→欠陥

2021-03-08 13:39 UTC, koizumistr commented on doc/src/sgml/installation.sgml
> +スレッドのサポートに血管があるプラットフォームでのみ、これを使ってください。
、、、、orz

2021-03-08 13:39 UTC, koizumistr commented
確認ありがとうございます。対応しました。

2021-03-10 08:40 UTC, tatsuo-ishii commented
対応ありがとうございました。

2021-03-10 08:41 UTC, tatsuo-ishii approved these changes
対応ありがとうございました。

2021-03-10 08:41 UTC, merged