update textsearch for 13.1
pgsql-jp/jpug-doc pull request #1887
Opened 2021-03-14 09:09 UTC by koizumistr

textsearch.sgml の 13.1 対応です。

2021-03-21 05:06 UTC, tatsuo-ishii requested changes
一通り確認しました。

2021-03-21 05:06 UTC, tatsuo-ishii commented on doc/src/sgml/textsearch.sgml
> +オプションのパラメータ<literal>siglen</literal>は署名の長さを決定します(詳細は以下を参照してください)。
"integer"および"in bytes"が訳出されていません。

2021-03-24 08:53 UTC, koizumistr commented
確認ありがとうございます。こちらも対応しました。

2021-03-25 02:00 UTC, tatsuo-ishii approved these changes
確認しました。対応ありがとうございます。

2021-03-25 02:00 UTC, merged