update typeconv for 13.1
pgsql-jp/jpug-doc pull request #1888
Opened 2021-03-16 15:06 UTC by koizumistr

typeconv.sgml の 13.1 対応です。

2021-03-22 10:43 UTC, tatsuo-ishii requested changes
一通り確認しました。

2021-03-22 10:43 UTC, tatsuo-ishii commented on doc/src/sgml/typeconv.sgml
>  演算子や関数に対するドメイン入力の取り扱いとある程度似ていて、この振舞いにより、利用者が注意して入力をすべて厳密な型であると保証する限り、ドメイン型を<literal>UNION</literal>や類似の構成体に保存できます。
"implicitly or explicitly"が訳出されていません。

2021-03-24 08:50 UTC, koizumistr commented
確認ありがとうございます。対応しました。

2021-03-25 02:01 UTC, tatsuo-ishii approved these changes
確認しました。対応ありがとうございます。

2021-03-25 02:01 UTC, merged