update git for 13.1
pgsql-jp/jpug-doc pull request #1899
Opened 2021-03-27 07:16 UTC by koizumistr

gist.sgml の 13.1 対応です。

2021-03-28 04:30 UTC, tatsuo-ishii approved these changes
一通り確認しました。

2021-03-29 22:52 UTC, KenichiroTanaka requested changes

2021-03-29 22:52 UTC, KenichiroTanaka commented on doc/src/sgml/gist.sgml
> +     * 渡されます。しかしながら、'options'メソッドを既存の演算子クラスに追加し場合、
細かいですが、
追加し場合→追加した場合
のTYPOのようです。

2021-03-30 08:38 UTC, koizumistr commented
確認ありがとうございます。対応しました。

2021-03-31 23:14 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。

2021-03-31 23:15 UTC, merged