datatype.sgmlのv13対応
pgsql-jp/jpug-doc pull request #1901
Opened 2021-03-31 23:15 UTC by KenichiroTanaka

2021-04-06 09:19 UTC, koizumistr reviewed
確認しました。

2021-04-06 09:19 UTC, koizumistr commented on doc/src/sgml/datatype.sgml
> +例えば、<literal>'tomorrow'::date</literal>よりも<literal>CURRENT_DATE + 1</literal>の方が安全です。
Use one of the SQL functions instead in such contexts. に対応する訳がないようです。

2021-04-06 09:19 UTC, koizumistr commented on doc/src/sgml/datatype.sgml
> +</para>
いくつかのparaをまとめて一気に訳しているようですが、特に理由がなければ他のところと同じようにparaごとに訳すべきかと。

2021-04-06 09:19 UTC, koizumistr commented on doc/src/sgml/datatype.sgml
> +<entry>関数が範囲データ型を受け入れるることを示します(<xref linkend="extend-types-polymorphic"/> と <xref linkend="rangetypes"/>を参照してください)。</entry>
を受け入れるること → を受け入れること

2021-04-06 09:19 UTC, koizumistr commented on doc/src/sgml/datatype.sgml
> +<entry>関数が複数の引数を一般的なデータ型に自動的に昇格させるどのようなデータ型でも受け入れることを示します。(<xref linkend="extend-types-polymorphic"/>)を参照してください)。</entry>
示します。の「。」は不要かと。

2021-06-18 14:48 UTC, KenichiroTanaka commented on doc/src/sgml/datatype.sgml
> +例えば、<literal>'tomorrow'::date</literal>よりも<literal>CURRENT_DATE + 1</literal>の方が安全です。
抜けていました。追記しました。

2021-06-18 14:48 UTC, KenichiroTanaka commented on doc/src/sgml/datatype.sgml
> +</para>
ご指摘の通りです。修正しました。

2021-06-18 14:49 UTC, KenichiroTanaka commented on doc/src/sgml/datatype.sgml
> +<entry>関数が範囲データ型を受け入れるることを示します(<xref linkend="extend-types-polymorphic"/> と <xref linkend="rangetypes"/>を参照してください)。</entry>
修正します。

2021-06-18 14:51 UTC, KenichiroTanaka commented
大変遅くなりました。小泉さんのご指摘に対応しました。

2021-07-18 06:45 UTC, tatsuo-ishii requested changes
確認しました。

2021-07-18 06:45 UTC, tatsuo-ishii commented on doc/src/sgml/datatype.sgml
> +入力する文字列として<literal>now</literal>、<literal>today</literal>、<literal>tomorrow</literal>及び<literal>yesterday</literal>はインタラクティブなSQLコマンドの中で利用する時は良いですが、コマンドが保存され後に実行されるような時には驚く挙動になることがあります。例えば、プリペアドステートメン
prepared statementは「準備された文」、functionは「関数」と他のファイルでは訳しているので、合わせたほうが良いと思います。

2021-07-22 10:17 UTC, KenichiroTanaka commented on doc/src/sgml/datatype.sgml
> +入力する文字列として<literal>now</literal>、<literal>today</literal>、<literal>tomorrow</literal>及び<literal>yesterday</literal>はインタラクティブなSQLコマンドの中で利用する時は良いですが、コマンドが保存され後に実行されるような時には驚く挙動になることがあります。例えば、プリペアドステートメン
レビューありがとうございます。
いただいたご指摘を反映しました。

2021-08-01 04:19 UTC, tatsuo-ishii approved these changes
良さそうなのでマージします。

2021-08-01 04:19 UTC, merged