update psql-ref for 13.1
pgsql-jp/jpug-doc pull request #1908
Opened 2021-04-12 14:34 UTC by koizumistr

ref/psql-ref.sgml の 13.1 対応です。

2021-05-01 21:33 UTC, KenichiroTanaka requested changes
一通り確認しました。１点確認いただけないでしょうか。

2021-05-02 06:19 UTC, koizumistr commented
確認ありがとうございます。対応しました。

2021-05-15 09:49 UTC, KenichiroTanaka approved these changes

2021-05-15 09:50 UTC, KenichiroTanaka commented
対応ありがとうございます。
マージします。

2021-05-15 09:50 UTC, merged