13.1 バージョン btree.sgml の翻訳
pgsql-jp/jpug-doc pull request #1913
Opened 2021-04-29 06:26 UTC by harukat

2021-05-09 10:23 UTC, tatsuo-ishii requested changes
まだ途中ですが、コメントが見えなくなってしまったので一旦終了します。

2021-05-09 10:23 UTC, tatsuo-ishii commented on doc/src/sgml/btree.sgml
> +これはbtreeインデックス操作中には使われません。どちらかといえば、演算子族のセマンティクスを<literal>RANGE</literal> <replaceable>offset</replaceable> <literal>PRECEDING</literal>と<literal>RANGE</literal> <replaceable>offset</replaceable> <lit
ここで"rather”を「どちらかというと」に訳すのは不適切だと思います。訳出するなら「むしろ」だと思いますが、日本語としては単に「これはbtreeインデックス操作中には使われませが、演算子族のセマンティクスを...」とした方が自然だと思います。

2021-05-09 10:23 UTC, tatsuo-ishii commented on doc/src/sgml/btree.sgml
> +整列されている型(<type>type1</type>)が照合可能であるなら、標準のPG_GET_COLLATION()機構を使って、<function>in_range</function>関数に適切な照合順序のOIDが渡されます。
「整列されている型」は「整列しようとしている型」なのでは？

2021-05-09 10:23 UTC, tatsuo-ishii commented on doc/src/sgml/btree.sgml
> +この関数は、コアコードがbtree重複排除の最適化を適用するのが安全かを決定できるようにします。
"core code"は上の方では「中核コード」と訳しています。統一すべきでは？

2021-05-09 10:23 UTC, tatsuo-ishii commented on doc/src/sgml/btree.sgml
> +<literal>true</literal>を返すことは、<replaceable>A</replaceable>および<replaceable>B</replaceable>引数が何らセマンティック情報を損失すること無しに交換可能でもあるとき、演算子クラスに対する<function>order</function>関数が<literal>0</literal>（<quote>引数が等しい</
"Not registering"以下が訳されていません。

2021-05-09 11:07 UTC, tatsuo-ishii requested changes
一通り確認しました。

2021-05-09 11:07 UTC, tatsuo-ishii commented on doc/src/sgml/btree.sgml
> +これは、しばしばリーフページ分割まで連続してスキップして、無益な重複排除パスでの無駄なサイクルによる性能ペナルティを回避できます。
「しばしばリーフページ分割まで連続してスキップして」→「しばしばリーフページ分割まで直接進んで」

2021-05-10 09:18 UTC, tatsuo-ishii requested changes

2021-05-10 09:18 UTC, tatsuo-ishii commented on doc/src/sgml/btree.sgml
> +btreeの演算子族が比較演算子を提供する各データ型の組み合わせに対して、比較サポート関数を提供しなければなりません。それらはサポート関数1番で<structname>pg_amproc</structname>に、また、比較での左右のデータ型と等しい<structfield>amproclefttype</structfield>/<structfield>amprocrighttype</s
(すなわち、<structname>pg_amop</structname>に登録されている演算子が対応するものと同じデータ型です。)
カッコ内の句点は不要ですね。

2021-05-10 09:37 UTC, tatsuo-ishii commented on doc/src/sgml/btree.sgml
> +btreeの演算子族が比較演算子を提供する各データ型の組み合わせに対して、比較サポート関数を提供しなければなりません。それらはサポート関数1番で<structname>pg_amproc</structname>に、また、比較での左右のデータ型と等しい<structfield>amproclefttype</structfield>/<structfield>amprocrighttype</s
以下の指摘以降に対応されていないようです。

「配布物を含む」→「配布物に含まれる」
"stock"はこの場合、「標準の」という意味なのでは？

2021-06-24 11:05 UTC, tatsuo-ishii approved these changes
一通り確認しました。

2021-06-25 06:36 UTC, noborus commented on doc/src/sgml/btree.sgml
>         <para>
この後のリストも翻訳対象じゃないでしょうか？

2021-06-25 06:36 UTC, noborus commented on doc/src/sgml/btree.sgml
> +<replaceable>less</replaceable> = trueの<function>in_range</function>が、いくつかの<replaceable>val1</replaceable>と<replaceable>base</replaceable>に対して偽であるなら、同じ<replaceable>base</replaceable>の全ての<replaceable>
上の一番目の項目が「もし」で始まってますが、こちらは始まってません。リストの並びなので統一されている必要があると思います。

2021-06-26 21:00 UTC, noborus commented
確認しました。レビュー済みでしたのでマージします。

2021-06-26 21:00 UTC, merged