update alter type etc. for 13.1
pgsql-jp/jpug-doc pull request #1914
Opened 2021-05-08 04:48 UTC by koizumistr

以下のファイルの13.1対応です。

- ref/alter_opfamily.sgml
- ref/alter_type.sgml

2021-05-09 23:46 UTC, harukat commented on doc/src/sgml/ref/alter_opfamily.sgml
> +B-treeソートサポート関数、B-tree等価像関数とGiST、SP-GiST、GIN演算子クラスのすべての関数では、関数が使用する入力データ型を指定する必要があります。
btree.sgml の訳で image equality を「イメージ等価」としたので、等価イメージ関数としたいです。

2021-05-09 23:48 UTC, harukat commented
（まだすべては見れていません）

2021-05-11 11:25 UTC, harukat commented on doc/src/sgml/ref/alter_type.sgml
> +このオプションを変更することは、それだけでは保存されたデータを変更せず、今後作成されるテーブル列で使われるデフォルトのTOAST戦略を設定するだけであることに注意してください。
store は「保存」よりも他ページの慣例に倣って「格納」にしてはどうでしょうか。

2021-05-11 11:30 UTC, harukat commented on doc/src/sgml/ref/alter_type.sgml
> +このオプションを変更することは、それだけでは保存されたデータを変更せず、今後作成されるテーブル列で使われるデフォルトのTOAST戦略を設定するだけであることに注意してください。
このパラグラフは、「<literal>STORAGE</literal>は、」から始まるべきかと思います。

2021-07-02 12:31 UTC, koizumistr commented
確認ありがとうございます。また、対応が遅くなりましてすみません。

「等価イメージ関数」はもう1ヶ所同時に直しています。

2021-07-18 07:01 UTC, tatsuo-ishii requested changes
今回の修正ではありませんが、ちょっと気になるところを見つけました。

2021-07-18 07:01 UTC, tatsuo-ishii commented on doc/src/sgml/ref/create_opclass.sgml
>  このため、しかしデータ型を跨がる比較をサポートする予定のB-treeソートサポート関数は除き、<literal>FUNCTION</literal>句で<replaceable class="parameter">op_type</replaceable>を指定する必要はありません。
今回の箇所ではありませんが、「しかしデータ型を跨がる比較を...」の「しかし」は不要だと思います。

2021-07-26 09:00 UTC, koizumistr commented
確認ありがとうございます。対応しました。

2021-08-01 04:20 UTC, tatsuo-ishii approved these changes
確認しました。マージします。

2021-08-01 04:20 UTC, merged