13.x で追加された backup-manifest を翻訳。
pgsql-jp/jpug-doc pull request #1924
Opened 2021-06-05 13:38 UTC by harukat

2021-06-17 01:14 UTC, noborus commented on doc/src/sgml/backup-manifest.sgml
> +関連付けられた文字列値はファイルのバックディレクトリからの相対パスです。
バックディレクトリ → バックアップディレクトリ

2021-06-17 01:23 UTC, noborus commented on doc/src/sgml/backup-manifest.sgml
> +このLSNは<productname>PostgreSQL</productname>で標準的に使われる書式で格納されます。すなわち、スラッシュで区切られた1から8の長さの16進数文字列2つから構成される文字列です。
> すなわち、スラッシュで区切られた1から8の長さの16進数文字列2つから構成される文字列です。

数字がいくつか出てくるので、並べ替えると理解しづらくなると思いました。原文のままの並びで良いように思います。

「すなわち、2つの16進文字列で構成され、それぞれの長さが1～8で、スラッシュで区切られた文字列です。」

2021-06-26 21:03 UTC, noborus approved these changes
確認しました。

2021-06-27 07:25 UTC, tatsuo-ishii requested changes
一通り確認しました。

2021-06-27 07:25 UTC, tatsuo-ishii commented on doc/src/sgml/backup-manifest.sgml
> +通常、ここでは単一のWAL範囲のみになります。
「ここでは」は原文にはないですし、意味が不明瞭になると思います。ここは原文は次の文に対比させて"there will be only a single..."と強調しているので、以下でいかがでしょう？
「通常、単一のWAL範囲だけが存在します。」

2021-06-27 07:25 UTC, tatsuo-ishii commented on doc/src/sgml/backup-manifest.sgml
> +しかしながら、バックアップが、上流の昇格のためにバックアップ中にタイムラインを変更したスタンバイから取得された場合、それぞれ異なるタイムラインを持つ複数の範囲になる可能性があります。
「複数の範囲になる」は原文の"present"のニュアンスが訳出されていないですし、原文通り「存在する」を訳出した方がわかりやすいと思います。
「しかしながら、バックアップが、上流の昇格のためにバックアップ中にタイムラインを変更したスタンバイから取得された場合、それぞれ異なるタイムラインを持つ複数の範囲が存在する可能性があります。」

2021-07-04 10:16 UTC, tatsuo-ishii approved these changes
確認しました。マージします。

2021-07-04 10:16 UTC, merged