catalogs.sgmlの前バージョンからの自動組み込み
pgsql-jp/jpug-doc pull request #1928
Opened 2021-06-07 01:21 UTC by noborus

12.4の翻訳部分を適用しました。 #1845 の対応です。

大変遅くなりましたが、 #1845の対応として自動変換して入れてみました。
ずっとxmlをパースして出来ないか試していましたが、どうしてもインデント等の問題が解決出来ないため、
単純に正規表現で抽出して適用する方法で 入れてみました。

2021-06-08 14:45 UTC, KenichiroTanaka commented
斉藤さん、ありがとうございます。
とても助かります。
１０００行くらい見ましたが良い感じのように思います。
@tatsuo-ishii さん
簡単で構いませんので見ていただいてもいいでしょうか。問題なさそうでしたらマージします。
また、ISSUESでも話題になった分割も不要そうでしょうか。

2021-06-09 00:22 UTC, noborus commented
追加でインデントが違って適用されていなかった12.4の翻訳を適用しました。

2021-06-19 08:22 UTC, tatsuo-ishii requested changes
とりあえず見はじめて一箇所気になるところを見つけたところで、このpull requestの目的が気になりました。
とりあえず12.4の翻訳を再利用し、13.1で追加変更になったところは別のpull requestで実施、ということなんでしょうか？
それであれば、細かく見るのは後にしてとりあえずマージしてしまうので良いと思います。
それとも、13.1の変更点もこのpull requestに入っているつもりなので、見てほしいということなんでしょうか？
さっくり見た感じでは、13.1の変更点は考慮されて無さそうですが...

2021-06-19 08:22 UTC, tatsuo-ishii commented on doc/src/sgml/catalogs.sgml
> +プロシージャのOID
「プロシジャ」→「関数」

2021-06-19 09:28 UTC, noborus commented
はい。自動で前バージョンの訳を入れただけです。

2021-06-19 10:51 UTC, tatsuo-ishii commented
>「プロシジャ」→「関数」
とりあえずこのレビューはdraftに戻しましたので、これで一旦マージします。
13.1での変更点については、私からpull requestを出します。

2021-06-19 10:56 UTC, tatsuo-ishii approved these changes
一旦マージします。

2021-06-19 10:58 UTC, tatsuo-ishii approved these changes
マージ進めます。

2021-06-19 10:59 UTC, tatsuo-ishii approved these changes

2021-06-19 11:00 UTC, merged