13.x で追加された color.sgml を翻訳
pgsql-jp/jpug-doc pull request #1933
Opened 2021-06-08 13:20 UTC by harukat

2021-06-17 01:32 UTC, noborus reviewed
確認しました。

最初なので指摘事項ではなく方針についてですが、
基本的にColorを「色付け」ではなく「色」でも良いと思いました。
（または、「カラー」）

2021-06-18 15:38 UTC, KenichiroTanaka commented
ref/vacuumdb.sgml などの既存役では以下のように色となっています。
```

<!--
      Specifies whether to use color in diagnostic messages. Possible values
      are <literal>always</literal>, <literal>auto</literal> and
      <literal>never</literal>.
-->
診断メッセージで色を使うかどうかを指定します。
可能な値は<literal>always</literal>、<literal>auto</literal>、<literal>never</literal>です。
```

確かに色とした方がいいかもしれません。

2021-06-27 06:49 UTC, tatsuo-ishii requested changes
一通り確認しました。

2021-06-27 06:49 UTC, tatsuo-ishii commented on doc/src/sgml/color.sgml
> +実際に使われる色は環境変数<envar>PG_COLORS</envar><indexterm><primary>PG_COLORS</primary></indexterm>（複数であることに注意）を使って設定されます。
pluralは、「複数」よりも「複数形」と訳した方が、原文の意図が伝わりやすいのではないかと思います。

2021-06-27 06:49 UTC, tatsuo-ishii commented on doc/src/sgml/color.sgml
> +      <para>エラーメッセージでテキスト<quote>error</quote>を協調するのに使われます</para>
「協調」→「強調」

2021-06-27 06:49 UTC, tatsuo-ishii commented on doc/src/sgml/color.sgml
> +      <para>警告メッセージでテキスト<quote>warning</quote>を協調するのに使われます</para>
「協調」→「強調」

2021-06-27 06:49 UTC, tatsuo-ishii commented on doc/src/sgml/color.sgml
> +      <para>メッセージで位置情報を協調するのに使われます（例えば、プログラム名やファイル名)</para>
「協調」→「強調」

2021-07-04 10:13 UTC, tatsuo-ishii approved these changes
確認しました。問題ないのでマージします、。

2021-07-04 10:14 UTC, merged