plpgsqlの13.1対応です。
pgsql-jp/jpug-doc pull request #1952
Opened 2021-06-19 13:37 UTC by noborus

https://www.postgresql.jp/document/12/html/plpgsql-porting.html#PLPGSQL-PORTING-APPENDIX
でコメントが見えてたのでCDATAを調整しました。

2021-06-24 12:21 UTC, KenichiroTanaka requested changes
一通り確認しました。１箇所確認をお願いします。

2021-06-24 12:21 UTC, KenichiroTanaka commented on doc/src/sgml/plpgsql.sgml
> +<application>PL/pgSQL</application>関数の戻り値が多様型として宣言されると、特別な<literal>$0</literal>パラメータが作成されます。
(see <xref linkend="extend-types-polymorphic"/>),の位置が違ったり、
 This allows the function to access its actual return type as shown in <xref linkend="plpgsql-declaration-type"/>.
が訳出されていなかったりするようです。

2021-06-25 06:16 UTC, noborus commented on doc/src/sgml/plpgsql.sgml
> +<application>PL/pgSQL</application>関数の戻り値が多様型として宣言されると、特別な<literal>$0</literal>パラメータが作成されます。
ありがとうございます。修正しました。

2021-07-01 14:52 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。

2021-07-01 14:53 UTC, merged