catalogs.sgmlのPostgreSQL 13.1対応です。
pgsql-jp/jpug-doc pull request #1953
Opened 2021-06-19 13:47 UTC by tatsuo-ishii

斉藤さんのPostgreSQL 12翻訳の取り込みに対する更新分です。

2021-07-01 15:19 UTC, KenichiroTanaka requested changes
１箇所修正をお願いします。

2021-07-01 15:19 UTC, KenichiroTanaka commented on doc/src/sgml/catalogs.sgml
> +使用可能な値は以下の通りです。
”The alignment reference is the beginning of the first datum in the sequence.”
の訳文が抜けているようです。

2021-07-02 03:48 UTC, tatsuo-ishii commented on doc/src/sgml/catalogs.sgml
> +使用可能な値は以下の通りです。
失礼しました。修正します。

2021-07-13 22:06 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。

2021-07-13 22:06 UTC, merged