update monitoring for 13.1
pgsql-jp/jpug-doc pull request #1960
Opened 2021-06-24 23:02 UTC by koizumistr

monitoring.sgml の 13.1 対応です。

既存の訳を再利用できた部分も多かったのですが、そのためには結局全体を見ないといけないことになって、その時気になった統一感のなさにも同時に対応してます。 #1955 や #1957 もこの作業からの派生です。

2021-07-02 02:57 UTC, noborus reviewed
前からの修正漏れですが、間違いを見つけたので修正お願いします。

もう一つ 189行あたりからのの
```
-この3条件を全て満たさないと、各サーバプロセスの<command>ps</command>の出力は、元の<application>postgres</application>のコマンドラインのものになってしまいます。
+この3条件を全て満たさないと、各サーバプロセスの<command>ps</command>の出力は、元の<command>postgres</command>のコマンドラインのものになってしまいます。
```
の変更漏れです。

2021-07-02 02:57 UTC, noborus commented on doc/src/sgml/monitoring.sgml
> +指定されたプロセスIDに該当するバックエンドの情報のレコードを、<symbol>NULL</symbol>が指定された場合はシステム上のアクティブな各バックエンドに関するレコードを返します。
\<literal\>NULL\<\/literal\> に変更されてました。

2021-07-02 02:57 UTC, noborus commented on doc/src/sgml/monitoring.sgml
> +この関数はデフォルトでスーパーユーザに限定されていますが、関数を実行できるように他のユーザにEXCUTE権限を付与できます。
EXECUTE のtypoです。

2021-07-02 02:57 UTC, noborus commented on doc/src/sgml/monitoring.sgml
> +この関数はデフォルトでスーパーユーザに限定されていますが、関数を実行できるように他のユーザにEXCUTE権限を付与できます。
EXECUTE のtypoです。

2021-07-02 02:57 UTC, noborus commented on doc/src/sgml/monitoring.sgml
> +この関数はデフォルトでスーパーユーザに限定されていますが、関数を実行できるように他のユーザにEXCUTE権限を付与できます。
EXECUTE のtypoです。

2021-07-02 02:57 UTC, noborus commented on doc/src/sgml/monitoring.sgml
> +この他に、データベース活動状況の監視に役立つツールとして<literal>pg_locks</literal>システムテーブルがあります。
\<structname\>pg_locks\<\/structname\> に変更されてました。

2021-07-02 02:57 UTC, noborus commented on doc/src/sgml/monitoring.sgml
> +WAL送信プロセスは、バックアップを終了するために現在<function>pg_start_backup</function>を実行し、ベースバックアップに必要なWALファイルすべてのアーカイブに成功するのを待っています。
\<function\>pg_stop_backup\<\/function\> です。

2021-07-02 12:23 UTC, koizumistr commented
確認ありがとうございます。対応しました（のつもりです）。

2021-07-14 02:16 UTC, noborus commented
対応ありがとうございました。確認しました。

2021-07-14 02:17 UTC, noborus approved these changes

2021-07-22 08:13 UTC, KenichiroTanaka requested changes
２箇所気づくところがありましたので修正をお願いします。

2021-07-26 09:07 UTC, koizumistr commented
確認ありがとうございます。対応しました。

2021-07-29 14:13 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。

2021-07-29 14:13 UTC, merged