perform.sgmlの13.1対応です
pgsql-jp/jpug-doc pull request #1964
Opened 2021-07-06 06:23 UTC by noborus

2021-07-22 10:06 UTC, KenichiroTanaka requested changes
細かいですが２箇所修正をお願いできないでしょうか。

2021-07-22 10:06 UTC, KenichiroTanaka commented on doc/src/sgml/perform.sgml
> +プランナは 明示的な<literal>sort</literal>ステップを追加もします。
細かいですが、「プランナは 」の後に空白が入ってしまっています。

2021-07-22 10:06 UTC, KenichiroTanaka commented on doc/src/sgml/perform.sgml
> +また、メモリ使用量が削減され、ソートがディスクにオーバーフローする可能性が減少しますが、結果セットを複数のソートバッチに分割するオーバーヘッドが増加します。
こちらも細かいですがcostが訳出されていないように思います。
「結果セットを複数のソートバッチに分割するオーバーヘッドのコストが増加します。」
くらいでいかがでしょうか。

2021-07-25 22:31 UTC, noborus commented on doc/src/sgml/perform.sgml
> +プランナは 明示的な<literal>sort</literal>ステップを追加もします。
修正します。

2021-07-25 22:40 UTC, noborus commented on doc/src/sgml/perform.sgml
> +また、メモリ使用量が削減され、ソートがディスクにオーバーフローする可能性が減少しますが、結果セットを複数のソートバッチに分割するオーバーヘッドが増加します。
at the cost of 〜　なので、
「結果セットを複数のソートバッチに分割するオーバーヘッドの増加という代償を払うことになります。」
とするのはどうでしょうか？

2021-08-03 00:15 UTC, KenichiroTanaka commented on doc/src/sgml/perform.sgml
> +また、メモリ使用量が削減され、ソートがディスクにオーバーフローする可能性が減少しますが、結果セットを複数のソートバッチに分割するオーバーヘッドが増加します。
すみません、レスが遅くなりました。
はい、いただいている案が良いと思います。

2021-08-10 13:00 UTC, KenichiroTanaka approved these changes
対応ありがとうございます

2021-08-10 13:02 UTC, KenichiroTanaka commented
一通り確認しました。マージします。

2021-08-10 13:03 UTC, merged