extend.sgml の v13.1 の変更点を翻訳。
pgsql-jp/jpug-doc pull request #1966
Opened 2021-07-11 05:22 UTC by harukat

2021-08-01 04:52 UTC, tatsuo-ishii requested changes
一通り確認しました。

2021-08-01 04:52 UTC, tatsuo-ishii commented on doc/src/sgml/extend.sgml
> +引数を一致させ、実際の結果型を決めるために、こうした関数は<type>anynonarray</type>または<type>anycompatiblenonarray</type>パラメータを適切な個数記述した場合と同様に動作します
"as if"を訳出しないと意味が伝わらないように思います。
「...適切な個数記述した場合...」→「...あたかも適切な個数記述した場合...」
でどうでしょう？

2021-08-12 00:25 UTC, tatsuo-ishii approved these changes
確認しました。

2021-08-12 23:10 UTC, KenichiroTanaka commented
チェックでエラーが出ていますが、ラベル関係のものようです。test/buildは成功していますのでマージして良い認識です。

2021-08-13 06:12 UTC, noborus commented
はい。マージします。

2021-08-13 06:13 UTC, merged