runtime.sgmlの13.1対応です
pgsql-jp/jpug-doc pull request #1970
Opened 2021-08-03 07:57 UTC by noborus

2021-08-11 11:21 UTC, KenichiroTanaka requested changes
2点気づくところがありましたので対応をお願いします。

2021-08-11 11:21 UTC, KenichiroTanaka commented on doc/src/sgml/runtime.sgml
> +<literal>shared_memory_type</literal>を<literal>sysv</literal>に設定していない限り、通常はデフォルトの共有メモリ設定で十分です。
細かいですが、The default shared memory and semaphore settingsのsemaphoreの箇所が訳出されていません。

2021-08-11 11:21 UTC, KenichiroTanaka commented on doc/src/sgml/runtime.sgml
> +<varname>SHMMAX</varname>を4096の倍数以外に設定しようとすると無視しますので、注意してください。
前からの訳ですが、ちょっと意訳しすぎのように思います。
原文通り
<varname>SHMMAX</varname>は4096の倍数のみ設定できます。
くらいの訳でどうでしょうか。

2021-08-13 06:08 UTC, noborus commented on doc/src/sgml/runtime.sgml
> +<varname>SHMMAX</varname>を4096の倍数以外に設定しようとすると無視しますので、注意してください。
すみません。13での変更箇所でしたが、訳がそのままでした。修正しました。

2021-08-17 11:20 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。

2021-08-17 11:21 UTC, KenichiroTanaka commented
一通り確認しましたのでマージします。

2021-08-17 11:21 UTC, merged