pageinspect.sgmlの13.1対応です
pgsql-jp/jpug-doc pull request #1974
Opened 2021-08-14 21:54 UTC by noborus

pageinspectを使ったことなかったので、自信がないです。
一部表現を統一するように変更してます。

2021-08-18 11:42 UTC, KenichiroTanaka requested changes
１箇所気づくところがありましたのでコメントしました。
ご確認をお願いします。

2021-08-18 11:42 UTC, KenichiroTanaka commented on doc/src/sgml/pageinspect.sgml
> +この値は、<structfield>ctid</structfield>と一致する場合もあれば、リストタプルおよび内部ページのタプルを転機する際に使用される代替表現からデコードされる場合もあります。
「転機する」はTYPOか変換ミスだと思うのですが、パッと分かりませんでした。転記？でしょうか？

2021-08-19 05:15 UTC, noborus commented on doc/src/sgml/pageinspect.sgml
> +この値は、<structfield>ctid</structfield>と一致する場合もあれば、リストタプルおよび内部ページのタプルを転機する際に使用される代替表現からデコードされる場合もあります。
すみません。これは意味がわからないまま書いた間違いでした。

2021-08-23 22:45 UTC, KenichiroTanaka approved these changes
対応ありがとうございます

2021-08-23 22:45 UTC, merged