libpq.sgml の V13 対応翻訳
pgsql-jp/jpug-doc pull request #1979
Opened 2021-08-16 14:08 UTC by harukat

2021-08-21 07:55 UTC, tatsuo-ishii requested changes
ひと通り見ました。

2021-08-21 07:55 UTC, tatsuo-ishii commented on doc/src/sgml/libpq.sgml
"encrypted"が訳出されていないようです。

2021-08-21 07:55 UTC, tatsuo-ishii commented on doc/src/sgml/libpq.sgml
> +コールバックはキーに対するパスワードを決定して、それを<parameter>size</parameter>サイズの結果バッファ<parameter>buf</parameter>にコピーすべきです。
「sizeサイズ」だとわかりにくいので、「sizeの大きさを持つ結果バッファ」ではどうでしょう？

2021-08-21 07:55 UTC, tatsuo-ishii commented on doc/src/sgml/libpq.sgml
> +アプリケーションのコールバックが対応していない場合を<function>PQdefaultSSLKeyPassHook_OpenSSL</function>に委託したり、最初に呼び出して0が返った場合に何らか他のことを試みたり、あるいは完全に上書きしたりすることにしても良いです。
「対応していない場合を」はちょっと日本語として不自然なので「対応していない場合は」ではどうでしょう？

2021-08-21 07:55 UTC, tatsuo-ishii commented on doc/src/sgml/libpq.sgml
>  ホスト要素は<xref linkend="libpq-connect-host"/>で説明したように解釈されます。
前からですが「the parameter」が訳出されていないようです。

2021-08-21 07:55 UTC, tatsuo-ishii commented on doc/src/sgml/libpq.sgml
> +具体的には、ホスト部品が空または絶対パス名のように見える場合、Unixドメインソケット接続が選択され、さもなければTCP/IP接続で初期化されます。
「ホスト部品」→「ホスト部」

2021-08-21 07:55 UTC, tatsuo-ishii commented on doc/src/sgml/libpq.sgml
> +このパラメータは<literal>sslkey</literal>で指定される秘密鍵に対するパスワードを指定します。
"allowing"以下が訳出されていません。

2021-08-21 07:55 UTC, tatsuo-ishii commented on doc/src/sgml/libpq.sgml
> +より高度な使用法のためには、OpenSSLエンジンとPKCS#11やUSB暗号オフロードデバイスといったツールの利用を検討すべきです。
"Users"が訳出されていません。入れるとしたら、「...ツールの利用を」の後に入れて「...ツールの利用をユーザは」あたりでしょうか。

2021-08-21 07:55 UTC, tatsuo-ishii commented on doc/src/sgml/libpq.sgml
> +指定しない場合、デフォルトは<literal>TLSv1.2</literal>で、これは執筆時点では業務上の規範を満たします。
"industry best practices"の訳はここでは「業界標準」くらいに訳すのが適当と思います。

2021-08-24 12:15 UTC, harukat commented on doc/src/sgml/libpq.sgml
> +アプリケーションのコールバックが対応していない場合を<function>PQdefaultSSLKeyPassHook_OpenSSL</function>に委託したり、最初に呼び出して0が返った場合に何らか他のことを試みたり、あるいは完全に上書きしたりすることにしても良いです。
「対応していない場合について」にしました。また、余計な空行もありましたね。

2021-08-24 12:23 UTC, harukat commented on doc/src/sgml/libpq.sgml
> +より高度な使用法のためには、OpenSSLエンジンとPKCS#11やUSB暗号オフロードデバイスといったツールの利用を検討すべきです。
外すのが良いかと考えましたが、含めるなら素直に「より高度な使用法を用いるユーザは・・・」でどうでしょうか。

2021-08-28 01:25 UTC, tatsuo-ishii approved these changes
確認しました。

2021-08-28 14:28 UTC, koizumistr reviewed
確認しました。指摘があることはあるのですが、そもそもいま私が見ているブラウザーでの表示が信用できないので、「指摘が意味不明だ」と思ったら無視してください。

2021-08-28 14:28 UTC, koizumistr commented on doc/src/sgml/libpq.sgml
> +アプリケーションはクライアント証明書のプロンプトと<literal>sslpassword</literal>パラメータの操作を、自身のキーパスワードコールバックを供給することで置き換えできます。
see   ＜xref linkend="libpq-pqsetsslkeypasshook-openssl"/＞.
に対応する訳がないように見えます。

それ以外にも原文と一致していないところがあるように見えるのですが、（手元のブラウザーでは）原文の行数が飛んでますので、これもconfigとかと同様にGitHubの限界の行数を越えてしまったのではないかと思います。（が、もしかしたら私の環境のせいかもしれませんので、その場合にはここは無視してください。）

2021-08-29 11:29 UTC, harukat commented on doc/src/sgml/libpq.sgml
> +アプリケーションはクライアント証明書のプロンプトと<literal>sslpassword</literal>パラメータの操作を、自身のキーパスワードコールバックを供給することで置き換えできます。
「それ以外にも原文と一致していない・・」は、このパラグラフということですよね。
それであれば「文として一致していない」「欠落している」類は無いかと思います。
（一方で従来からの訳については十分なチェックできていないです）

2021-08-29 11:47 UTC, tatsuo-ishii commented
>それ以外にも原文と一致していないところがあるように見えるのですが、（手元のブラウザーでは）原文の行数が飛んでますので、これもconfigとかと同様にGitHubの限界の行数を越えてしまったのではないかと思います。

私の環境でも起こります。最近限界を超えてしまったっぽいcatalogs.sgmlが18000行くらいなのに対し、libpq.sgmlが13000行くらいなので、まだ余裕があるのかと思ったら、意外とGithubの余裕は少ないのかもしれませんね。

2021-08-30 11:52 UTC, koizumistr approved these changes
確認しました。対応ありがとうございます。

すみません。いろいろ詰め込みすぎてしまったようで。
> 「それ以外にも原文と一致していない・・」は、このパラグラフということですよね。

というのはその通りです。

2021-08-30 11:53 UTC, koizumistr commented
二人でレビューしたということでマージします。

2021-08-30 11:53 UTC, merged