charset.sgmlの13対応の翻訳
pgsql-jp/jpug-doc pull request #1984
Opened 2021-08-26 01:53 UTC by thoshiai

charset.sgmlの13対応の翻訳を作成しました

2021-08-28 01:45 UTC, tatsuo-ishii requested changes
すみません。操作を間違えてレビューではなくコメント記入になってしまいましたが、一通り確認しました。

2021-08-28 13:57 UTC, koizumistr reviewed
確認しました。

2021-08-28 13:57 UTC, koizumistr commented on doc/src/sgml/charset.sgml
> -
元々あった空白行を消してしまっていませんか。

2021-08-28 13:57 UTC, koizumistr commented on doc/src/sgml/charset.sgml
> +したがって、これらの名前は、<xref linkend = "charset-table" />に示されている通常の符号化方式名と異なる場合があります。
xrefの中身が原文とちょっと異なります。原文から変えないでおいたほうがいろいろと便利かと。

2021-08-31 00:27 UTC, thoshiai commented
いただいたコメントをもとにファイル修正しました

2021-08-31 00:33 UTC, tatsuo-ishii approved these changes
修正対応ありがとうございます。一通り確認しました。

2021-08-31 01:48 UTC, KenichiroTanaka commented
2名以上にレビューいただきましたのでマージします。
翻訳及びレビューありがとうございました。

2021-08-31 01:48 UTC, merged