glossary.sgmlのPostgreSQL 13.1対応です。Constraint、"g"から"i"まで。
pgsql-jp/jpug-doc pull request #2008
Opened 2021-09-14 11:41 UTC by tatsuo-ishii

2021-09-14 22:07 UTC, KenichiroTanaka requested changes
細かいですが１箇所だけ気づくところがありましたので対応をお願いします。

2021-09-14 22:07 UTC, KenichiroTanaka commented on doc/src/sgml/glossary.sgml
> +インスタンスは、ファイルと共有メモリへのアクセス、<acronym>ACID</acronym>性の保障、<glossterm linkend="glossary-client">クライアントプロセス</glossterm>への<glossterm linkend="glossary-connection">接続</glossterm>、権限の検証、クラッシュからの回復、レプリケーションその他の
>read and write access to files and shared memory

「read and write 」が訳出されていないようです。

ファイルと共有メモリへの読み書きのアクセス

などでどうでしょうか。

2021-09-15 00:43 UTC, tatsuo-ishii commented on doc/src/sgml/glossary.sgml
> +インスタンスは、ファイルと共有メモリへのアクセス、<acronym>ACID</acronym>性の保障、<glossterm linkend="glossary-client">クライアントプロセス</glossterm>への<glossterm linkend="glossary-connection">接続</glossterm>、権限の検証、クラッシュからの回復、レプリケーションその他の
ご指摘ありがとうございます。「ファイルと共有メモリからの読み出しおよび書き込みアクセス」としました。

2021-09-16 04:51 UTC, noborus approved these changes
確認しました。
マージします。

2021-09-16 04:51 UTC, merged