glossary.sgmlのPostgreSQL 13.1対応です。("q"から"r"まで)
pgsql-jp/jpug-doc pull request #2020
Opened 2021-09-18 07:30 UTC by tatsuo-ishii

2021-09-18 22:42 UTC, KenichiroTanaka requested changes
いくつか気づくことがありましたので確認をお願いします。

2021-09-18 22:42 UTC, KenichiroTanaka commented on doc/src/sgml/glossary.sgml
> +<glossterm linkend="glossary-query">問い合わせ</glossterm>を実行する最も効率の良い方法を決定するために使われる<productname>PostgreSQL</productname>の一部分。
determiningの後の(<firstterm>planning</firstterm>)
が無くなっているようです。

2021-09-18 22:42 UTC, KenichiroTanaka commented on doc/src/sgml/glossary.sgml
> +<glossterm linkend="glossary-primary-server">プライマリ</glossterm>データベースと対になり、プライマリデータベースのデータのある部分、あるいはすべてのコピーを維持する<glossterm linkend="glossary-database">データベース</glossterm>。
The foremost reasons〜以下が訳出されていないようです。

2021-09-18 22:42 UTC, KenichiroTanaka commented on doc/src/sgml/glossary.sgml
> +   <glossterm>Result set（結果集合）</glossterm>
$find . -name "*.sgml"|xargs grep "結果集合"|wc -l
      39
$find . -name "*.sgml"|xargs grep "結果セット"|wc -l
      65

とぶれてますが、結果セットの方が多いようです。「結果セット」もしくは「結果セット/結果集合」とするのはどうでしょうか。

2021-09-19 07:02 UTC, tatsuo-ishii commented on doc/src/sgml/glossary.sgml
> +結果を返す、あるいはデータベース上のデータを変更するためにクライアントから<glossterm linkend="glossary-backend">バックエンド</glossterm>に送信される要求。
訳出すべきですね。修正します。

2021-09-19 07:04 UTC, tatsuo-ishii commented on doc/src/sgml/glossary.sgml
> +<glossterm linkend="glossary-query">問い合わせ</glossterm>を実行する最も効率の良い方法を決定するために使われる<productname>PostgreSQL</productname>の一部分。
おっと失礼しました。

2021-09-19 07:09 UTC, tatsuo-ishii commented on doc/src/sgml/glossary.sgml
> +<glossterm linkend="glossary-primary-server">プライマリ</glossterm>データベースと対になり、プライマリデータベースのデータのある部分、あるいはすべてのコピーを維持する<glossterm linkend="glossary-database">データベース</glossterm>。
失礼しました。

2021-09-19 07:12 UTC, tatsuo-ishii commented on doc/src/sgml/glossary.sgml
> +   <glossterm>Result set（結果集合）</glossterm>
後で議論して統一することにして、ここは「結果集合」のままにさせていただけませんか？

2021-09-19 07:30 UTC, KenichiroTanaka commented on doc/src/sgml/glossary.sgml
> +   <glossterm>Result set（結果集合）</glossterm>
後で、ということで承知しました。他もあるので後で良いと思います。

2021-09-19 07:34 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。

2021-09-19 07:36 UTC, merged