glossary.sgmlの13.1対応(t)
pgsql-jp/jpug-doc pull request #2022
Opened 2021-09-19 01:03 UTC by noborus

2021-09-19 07:00 UTC, tatsuo-ishii requested changes
一通り確認しました。

2021-09-19 23:02 UTC, noborus commented on doc/src/sgml/glossary.sgml
> +作成時に指定された<glossterm linkend="glossary-session">セッション</glossterm>または<glossterm linkend="glossary-transaction">トランザクション</glossterm>の特定期間にのみ存在する<glossterm linkend="glossary-table">テーブル</glossterm>。
はい。日本語の方がうまく出てこず変でした。

2021-09-19 23:02 UTC, noborus commented on doc/src/sgml/glossary.sgml
> +テーブル行の大きな属性を分割して副テーブルに格納される機構。
修正します。

2021-09-20 05:01 UTC, tatsuo-ishii approved these changes
対応ありがとうざいます。確認しました。マージします。

2021-09-20 05:01 UTC, merged