ACIDの文言の統一（調整）
pgsql-jp/jpug-doc pull request #2030
Opened 2021-09-22 23:19 UTC by noborus

「 This is one of the <acronym>ACID</acronym> properties.」は同じ文言なので統一。
ACIDのIsolationの場合は「独立性」に変更。
末尾の「。」の抜け修正。
「.」が残っていたミスの修正。

2021-09-22 23:21 UTC, noborus commented
これで #2021 の修正が終わります。

2021-09-23 00:40 UTC, tatsuo-ishii requested changes
一通り確認しました。

2021-09-23 00:40 UTC, tatsuo-ishii commented on doc/src/sgml/glossary.sgml
> +これは<acronym>ACID</acronym>性質の一部です。
検索すると、「ACID性質」というのは上位には出てこなくて、「ACID特性」がほとんどのようです。

2021-09-23 01:37 UTC, noborus commented on doc/src/sgml/glossary.sgml
> +これは<acronym>ACID</acronym>性質の一部です。
なるほど。文章内で統一することだけ考えてました。
全部「特性」に変更しようと思います。

2021-09-23 04:55 UTC, tatsuo-ishii approved these changes
確認しました。マージします。

2021-09-23 04:55 UTC, merged