update sslinfo for 14.0
pgsql-jp/jpug-doc pull request #2053
Opened 2021-10-30 07:24 UTC by koizumistr

sslinfo.sgmlの14.0対応です。

2021-11-13 09:18 UTC, KenichiroTanaka requested changes
1箇所気づくところがあったので対応をお願いします。

2021-11-13 09:18 UTC, KenichiroTanaka commented on doc/src/sgml/sslinfo.sgml
>       Returns the name of the protocol used for the SSL connection (e.g., TLSv1.0,
githubの制限でコメントできませんが、
以下の箇所が少し変わっています。対応をお願いできないでしょうか。

```
  This extension won't build at all unless the installation was
  configured with <literal>&#045;&#045;with-openssl</literal>.

```

diffだと以下の箇所です。
```
$git diff REL_13_1 REL_14_0 sslinfo.sgml 
diff --git a/doc/src/sgml/sslinfo.sgml b/doc/src/sgml/sslinfo.sgml
index 0d6bebe..2a9c45a 100644
--- a/doc/src/sgml/sslinfo.sgml
+++ b/doc/src/sgml/sslinfo.sgml
@@ -22,7 +22,7 @@
 
  <para>
   This extension won't build at all unless the installation was
-  configured with <literal>--with-openssl</literal>.
+  configured with <literal>--with-ssl=openssl</literal>.
  </para>
```

2021-11-13 10:37 UTC, koizumistr commented on doc/src/sgml/sslinfo.sgml
>       Returns the name of the protocol used for the SSL connection (e.g., TLSv1.0,
確認ありがとうございます。対応しました。

2021-11-14 13:51 UTC, KenichiroTanaka approved these changes
早速の対応ありがとうございました。

2021-11-14 13:52 UTC, merged