update ref/pgupgrade for 14.0
pgsql-jp/jpug-doc pull request #2071
Opened 2021-11-09 14:51 UTC by koizumistr

ref/pgupgrade.sgmlの14.0対応です。

2021-11-21 08:06 UTC, tatsuo-ishii requested changes
一通り確認しました。

2021-11-21 08:06 UTC, tatsuo-ishii commented on doc/src/sgml/ref/pgupgrade.sgml
> +古いクラスタがこれらを使用していたのであれば、新しいサーバのバイナリに合った共有オブジェクトファイルを新しいクラスタにインストールしなければなりません。
"usually via operating system"が訳されていないようです。

2021-11-23 00:47 UTC, koizumistr commented
確認ありがとうございます。対応しました。

2021-12-02 07:24 UTC, tatsuo-ishii approved these changes
確認しました。対応有り難うございます。

2021-12-02 07:24 UTC, merged