update intarray for 14.0
pgsql-jp/jpug-doc pull request #2076
Opened 2021-11-13 12:35 UTC by koizumistr

intarray.sgml の１４．０対応です。

2021-11-26 14:15 UTC, KenichiroTanaka requested changes
1点気づいたところがあります。どうでしょうか。

2021-11-26 14:15 UTC, KenichiroTanaka commented on doc/src/sgml/intarray.sgml
> +また、デフォルトではないGIN演算子クラス<literal>gin__int_ops</literal>も存在し、これらの演算子と<literal>&lt;@</literal>をサポートします。
>これらの演算子と<literal>&lt;@</literal>をサポートします。
as well as なので、並列ではなく、

また、デフォルトではないGIN演算子クラス<literal>gin__int_ops</literal>も存在し、
<literal>&lt;@</literal>と同様にこれらの演算子をサポートしています。

などの訳とするのはどうでしょうか。

2021-11-26 14:50 UTC, koizumistr commented on doc/src/sgml/intarray.sgml
> +また、デフォルトではないGIN演算子クラス<literal>gin__int_ops</literal>も存在し、これらの演算子と<literal>&lt;@</literal>をサポートします。
確認ありがとうございます。対応しました。

2021-12-03 14:47 UTC, KenichiroTanaka approved these changes
対応ありがとうございました。

2021-12-03 14:47 UTC, merged