update ref/create_view and declare for 14.0
pgsql-jp/jpug-doc pull request #2080
Opened 2021-11-14 07:12 UTC by koizumistr

以下のファイルの１４．０対応です。

- ref/create_view.sgml
- ref/declare.sgml

2021-11-14 07:20 UTC, koizumistr commented
declareでは「カーソルのsensitivity」という概念が出てきて訳に苦労しています。（元は「センシティブカーソル」だけでした。これはそれなりに使われている言葉のようなので、まあいいかなと思えるのですが、なら「インセンシティブカーソル（=センシティブとは逆のカーソル）」ってこれで訳になっているのか、、、）

改めて調べると「センシティブカーソル」もそれほど多くないですが、それよりさらに少ないものの「インセンシティブカーソル」と言っている例はあるみたいですね（DB2で？）。カタカナにしても良かったかもしれません。データベースの経験が豊富な皆さんの助言をお願いします。

2021-12-02 14:02 UTC, tatsuo-ishii requested changes
一通り確認しました。

2021-12-02 14:02 UTC, tatsuo-ishii commented on doc/src/sgml/ref/declare.sgml
> +<productname>PostgreSQL</productname>は、これらの文をその他のデータを変更する文すべてと同様に扱います。その他の文ではinsensitiveカーソルでは変更は可視ではありません。
これだと、「これらの文」と「その他の文」で扱いが異なるように取られるかもしれないので、
「これらの文をその他のデータを変更する文すべてと同様に扱い、insensitiveカーソルでは変更は可視ではありません。」ではどうでしょう？

2021-12-05 06:16 UTC, koizumistr commented
確認ありがとうございます。対応しました。

2021-12-05 07:17 UTC, tatsuo-ishii approved these changes
対応ありがとうございます。確認しました。

2021-12-05 07:17 UTC, merged