update ref/pg_basebackup.sgml for 14.0
pgsql-jp/jpug-doc pull request #2094
Opened 2021-11-25 08:36 UTC by kitayama

2021-12-04 09:55 UTC, tatsuo-ishii approved these changes
一通り確認しました。

2021-12-04 14:23 UTC, KenichiroTanaka requested changes
細かいですが2点気づいたので修正をお願いできないでしょうか。

2021-12-04 14:23 UTC, KenichiroTanaka commented on doc/src/sgml/ref/pg_basebackup.sgml
> +
細かいですが原文には無い空行ができてしまっていますので削除をお願いできないでしょうか。

2021-12-04 14:23 UTC, KenichiroTanaka commented on doc/src/sgml/ref/pg_basebackup.sgml
> +            (これを変更するには<option>&#45;-tablespace-mapping</option>を参照してください。)
細かいですが、他の行と異なり先頭に空白が入っているため、合わせていただいてもいいでしょうか。

2021-12-07 05:06 UTC, kitayama commented
確認ありがとうございます。指摘事項に対応しました。

2021-12-08 10:53 UTC, tatsuo-ishii approved these changes
確認しました。

2021-12-08 15:52 UTC, KenichiroTanaka approved these changes
対応ありがとうございました。

2021-12-08 15:52 UTC, merged