update ref/copy for 14.0
pgsql-jp/jpug-doc pull request #2098
Opened 2021-11-27 05:27 UTC by koizumistr

ref/copy.sgml の14.0対応です。

2021-12-04 10:26 UTC, tatsuo-ishii requested changes
一通り確認しました。

2021-12-04 10:26 UTC, tatsuo-ishii commented on doc/src/sgml/ref/copy.sgml
> +       <entry><literal>\x</literal><replaceable>数字</replaceable></entry>
行頭に余計なスペースが入っています。

2021-12-05 03:11 UTC, koizumistr commented on doc/src/sgml/ref/copy.sgml
> +       <entry><literal>\x</literal><replaceable>数字</replaceable></entry>
一つ上のやり方（旧929、新933行目）を真似しているのですが、確かに混乱の元ですね。この表内では行頭からいきなり書き始めるのが多数派なので一つ上も合わせてやってしまおうかな、、、

2021-12-05 06:01 UTC, koizumistr commented
確認ありがとうございます。対応しました。

2021-12-08 10:52 UTC, tatsuo-ishii approved these changes
確認しました。
対応ありがとうございます。

2021-12-08 10:52 UTC, merged