update ref/initdb for 14.0
pgsql-jp/jpug-doc pull request #2101
Opened 2021-11-29 08:03 UTC by kitayama

2021-12-05 05:11 UTC, tatsuo-ishii requested changes
一通り確認しました。

2021-12-05 05:11 UTC, tatsuo-ishii commented on doc/src/sgml/ref/initdb.sgml
> +デフォルトでは<command>initdb</command>は出力の最後にクラスタを起動する手順を書きます。
ここでの"write..."は端末に表示するという意味なので、「手順を書きます」は「手順を表示します」などの方が適切と思います。

2021-12-07 05:38 UTC, kitayama commented
レビューありがとうございます。指摘事項に対応しました。

2021-12-08 10:56 UTC, tatsuo-ishii approved these changes
確認しました。

2021-12-08 10:56 UTC, merged