update backup for 14.0
pgsql-jp/jpug-doc pull request #2102
Opened 2021-11-30 06:21 UTC by kitayama

2021-12-05 05:27 UTC, tatsuo-ishii approved these changes
一通り確認しました。

2021-12-05 05:27 UTC, tatsuo-ishii commented on doc/src/sgml/backup.sgml
> +これらのファイルは、バックアップの動作にきわめて重要であり、返り値の内容から変更なしに書き込む必要があるため、バイナリモードでファイルを開く必要があります。
前からですが、ここは"byte for byte", "may"を訳出しておきたいところです。以下ではどうでしょう？

これらのファイルはバックアップが動作するために極めて重要であり、1バイトも変更なしに書き込まれる必要があるため、バイナリモードで開かれる必要があるかもしれません。

2021-12-05 05:29 UTC, tatsuo-ishii requested changes
間違ってapproveしてしまいました。

2021-12-07 06:51 UTC, kitayama commented
レビューありがとうございます。提案いただいた訳を採用させていただきました。よろしくお願いします。

2021-12-08 10:57 UTC, tatsuo-ishii approved these changes
確認しました。

2021-12-08 10:57 UTC, merged