appendix-obsolete*の14.0対応です。
pgsql-jp/jpug-doc pull request #2104
Opened 2021-12-01 05:01 UTC by noborus

同じような書き方なので、一つのPRで出してます。

2021-12-12 03:17 UTC, koizumistr requested changes
確認しました。

2021-12-12 03:17 UTC, koizumistr commented on doc/src/sgml/appendix-obsolete-default-roles.sgml
> +しかし、これらのロールは実際には変更できず、初期化時にシステムの一部としてインストールされるので、<quote>事前定義ロール</quote>という用語を使用するのが適切です。
とっても細かいですが、 より適切 と more を訳したほうがいいかなと思いました。

2021-12-12 03:17 UTC, koizumistr commented on doc/src/sgml/appendix-obsolete-recovery-config.sgml
> +PostgreSQL 12以下では、<link linkend="continuous-archiving">アーカイブリカバリ、ストリーミングレプリケーション、およびPITR</link>は<link linkend="runtime-config-replication-standby">通常のサーバ設定パラメータ</link>を使用して設定されていました。
この文も「12とそれ以上の今の動作」を述べているのではないでしょうか。

2021-12-13 01:47 UTC, noborus commented on doc/src/sgml/appendix-obsolete-recovery-config.sgml
> +PostgreSQL 12以下では、<link linkend="continuous-archiving">アーカイブリカバリ、ストリーミングレプリケーション、およびPITR</link>は<link linkend="runtime-config-replication-standby">通常のサーバ設定パラメータ</link>を使用して設定されていました。
すみません。致命的なミスでした。修正します。

2021-12-16 05:12 UTC, koizumistr approved these changes
確認しました。対応ありがとうございます。

2021-12-25 06:59 UTC, tatsuo-ishii approved these changes
一通り確認しました。

2021-12-25 07:00 UTC, merged