triger.sgmlのPostgreSQL14.0対応です。
pgsql-jp/jpug-doc pull request #2110
Opened 2021-12-09 10:41 UTC by TsukaPon03t

2021-12-09 10:50 UTC, koizumistr requested changes

2021-12-09 10:50 UTC, koizumistr commented on doc/src/sgml/trigger.sgml
> +トリガ制約として定義することにより、トリガ実行を文の終わりではなく、トランザクションの終わりまで保留することができます。
＜firstterm＞タグ（に限りませんが）は原文のまま維持してください。あと＜literal＞AFTER＜/literal＞が抜けています。

2021-12-09 12:10 UTC, koizumistr commented
ごめんなさい、書き方が良くなかったですね。タグの中身をそのままにしてほしかったのではなくて、原文にあるタグそのものを生かしてほしかった、というのが言いたかったことです、ですので

＜firstterm＞制約トリガ＜/firstterm＞

としてほしいです。多分このままコピーするとアウトです。
（コメントにタグは書けませんので＜とか全角にしてますから）

2021-12-09 12:13 UTC, koizumistr commented on doc/src/sgml/trigger.sgml
> +すべての場合において、トリガはトリガとした文と同じトランザクションの一部として実行されるため、文またはトリガのいずれかがエラーを引き起こした場合、両方の結果がロールバックされます。
トリガはトリガとした文と同じ

というところで引っ掛かってますが、今は良い案も出ません（多分お酒のせい）

2021-12-10 01:11 UTC, TsukaPon03t commented on doc/src/sgml/trigger.sgml
> +すべての場合において、トリガはトリガとした文と同じトランザクションの一部として実行されるため、文またはトリガのいずれかがエラーを引き起こした場合、両方の結果がロールバックされます。
ご指摘ありがとうございます。私もそこは引っかかっております…。
一応下記のような形で`trigered`の所を意訳を考えてみましたがいかがでしょう…（少しマシになった程度ですが…）
「トリガはトリガを定義した文と同じトランザクションの一部として実行されるため」

ここの約がしっくりきたら、タグの部分含めて改修してプルしたいと思います。

2021-12-12 00:57 UTC, noborus reviewed
`<firstterm>constraint trigger</firstterm>` → `<firstterm>制約トリガ</firstterm>` の件があるので、ラベルを指摘事項ありにしておきます。

2021-12-12 00:57 UTC, noborus commented on doc/src/sgml/trigger.sgml
> +すべての場合において、トリガはトリガとした文と同じトランザクションの一部として実行されるため、文またはトリガのいずれかがエラーを引き起こした場合、両方の結果がロールバックされます。
トリガを定義した文だと`CREATE TRIGGER` の意味のように読めてしまうので、
わかりやすくするなら、
「トリガはトリガが引き金となった文と同じトランザクションの一部として実行されるため」
でどうでしょうか？

2021-12-13 09:28 UTC, noborus approved these changes
確認しました

2021-12-19 23:16 UTC, KenichiroTanaka approved these changes
一通り確認しました。
@koizumistr さん
change requestになってますのでご確認いただけたらApprveをお願いします。

2022-01-09 04:14 UTC, noborus commented
@koizumistr さんが通知見逃しているかもですが、マージしちゃいます。

2022-01-09 04:15 UTC, merged