update ref/*_index.sgml for 14.0
pgsql-jp/jpug-doc pull request #2112
Opened 2021-12-09 11:58 UTC by koizumistr

以下のファイルの１４．０対応です。

- ref/alter_index.sgml
- ref/create_index.sgml
- ref/drop_index.sgml

2021-12-13 01:51 UTC, noborus approved these changes
確認しました。

2021-12-29 07:05 UTC, KenichiroTanaka requested changes
レビューが遅くなりすみません。いくつか気づくところがありましたので確認をお願いします。

2022-01-08 23:51 UTC, koizumistr commented
確認ありがとうございます。対応しました。
対応が遅くなってすみません。

2022-01-11 11:36 UTC, KenichiroTanaka approved these changes
対応ありがとうございました。

2022-01-11 11:36 UTC, KenichiroTanaka commented
対応ありがとうございます。一通り確認しました。

2022-01-11 11:36 UTC, merged