update ref/reindex for 14.0
pgsql-jp/jpug-doc pull request #2116
Opened 2021-12-18 23:34 UTC by koizumistr

ref/reindex.sgml の14.0対応です。

2021-12-25 07:19 UTC, tatsuo-ishii requested changes
一通り確認しました。

2021-12-25 07:19 UTC, tatsuo-ishii commented on doc/src/sgml/ref/reindex.sgml
>  したがって、読み込みがブロックされることはありませんが、コストが高いシーケンシャルスキャンの使用を強制されることになります。
"might"は訳出しなくて良いでしょうか？

2022-01-08 23:57 UTC, koizumistr commented
確認ありがとうございます。対応しました。
対応が遅くなってすみません。

2022-01-10 04:22 UTC, tatsuo-ishii approved these changes
確認しました。対応ありがとうございます。

2022-01-10 04:22 UTC, merged