high-availability.sgmlのPostgreSQL 14.0対応です。
pgsql-jp/jpug-doc pull request #2117
Opened 2021-12-25 14:04 UTC by tatsuo-ishii

2022-01-06 07:43 UTC, noborus commented on doc/src/sgml/high-availability.sgml
> +スタンバイのクラスタデータディレクトリ内に<link linkend="file-standby-signal"><filename>standby.signal</filename></link><indexterm><primary>standby.signal</primary></indexterm>ファイルを作成し、<varname>standby_mode</varname>を有効に
少し前からのようですが、
> <varname>standby_mode</varname>を有効にしてください。

に該当する箇所は原文には無くなっているようです。

2022-01-06 07:43 UTC, noborus commented on doc/src/sgml/high-availability.sgml
>  よりマスターサーバに近いスタンバイサーバは上流サーバと呼ばれるのに対し、より遠いスタンバイサーバは下流サーバと呼ばれます。
> よりマスターサーバに近い

ここもプライマリに変更が必要です。

2022-01-06 07:43 UTC, noborus commented on doc/src/sgml/high-availability.sgml
> +トリガベースのレプリケーションの構成では、典型的にはデータを変更する問い合わせを指定されたプライマリサーバに送り込みます。
「典型的」だとちょっと違和感がある気がします。「通常」の方が良いように思います。

2022-01-06 08:19 UTC, tatsuo-ishii reviewed
レビューありがとうございます。

2022-01-06 08:19 UTC, tatsuo-ishii commented on doc/src/sgml/high-availability.sgml
> +トリガベースのレプリケーションの構成では、典型的にはデータを変更する問い合わせを指定されたプライマリサーバに送り込みます。
はい、そうですね。

2022-01-06 08:19 UTC, tatsuo-ishii commented on doc/src/sgml/high-availability.sgml
> +スタンバイのクラスタデータディレクトリ内に<link linkend="file-standby-signal"><filename>standby.signal</filename></link><indexterm><primary>standby.signal</primary></indexterm>ファイルを作成し、<varname>standby_mode</varname>を有効に
おお、そうですね。

2022-01-06 08:19 UTC, tatsuo-ishii commented on doc/src/sgml/high-availability.sgml
>  よりマスターサーバに近いスタンバイサーバは上流サーバと呼ばれるのに対し、より遠いスタンバイサーバは下流サーバと呼ばれます。
修正漏れでした。

2022-01-09 04:15 UTC, noborus commented
修正ありがとうございます。確認しました。

2022-01-09 04:16 UTC, noborus approved these changes

2022-01-12 23:05 UTC, noborus commented on doc/src/sgml/high-availability.sgml
>  <!--
13の方の修正漏れのPRの方に入れましたが、
https://github.com/pgsql-jp/jpug-doc/pull/2122/files#diff-572bca5b159efd178a225b08229c874c147a35f8ccffb1252e41e1f9ae49e94bL1501-L1502

14.0の方も以下の文に該当する訳が抜けてました。

```
<xref linkend="guc-max-slot-wal-keep-size"/> limits the size of WAL files
    retained by replication slots.
```

2022-01-13 11:01 UTC, tatsuo-ishii commented on doc/src/sgml/high-availability.sgml
>  <!--
ご指摘ありがとうございます。対応します。

2022-01-14 00:16 UTC, noborus reviewed
ありがとうございます。確認しました。

2022-01-26 22:34 UTC, KenichiroTanaka requested changes
一通り確認しました。
１箇所気になるところがありましたので確認いただけないでしょうか。

2022-01-30 00:31 UTC, tatsuo-ishii reviewed
田中さんの指摘に対応しました。

2022-01-30 00:31 UTC, tatsuo-ishii commented on doc/src/sgml/high-availability.sgml
> +その理由は、各サーバが独立して稼動しているため、および、実際のデータ変更ではなくSQL問い合わせが送信されるからです。
ご指摘ありがとうございます。
「これが許容できない場合は、ミドルウェアかアプリケーションで単一のソースからそのような値を確定し、その結果を書き込み問い合わせで使用しなければなりません。」としました。

2022-01-31 11:41 UTC, KenichiroTanaka approved these changes
対応ありがとうございました。

2022-01-31 11:41 UTC, KenichiroTanaka commented
一通り確認しましたのでマージします。

2022-01-31 11:41 UTC, merged