update call etc. for 14.0
pgsql-jp/jpug-doc pull request #2140
Opened 2022-01-15 23:41 UTC by koizumistr

以下のファイルの１４．０対応です。

- ref/alter_collation.sgml
- ref/call.sgml

2022-01-20 05:50 UTC, tatsuo-ishii requested changes
一通り確認しました。

2022-01-20 05:50 UTC, tatsuo-ishii commented on doc/src/sgml/ref/call.sgml
> +引数は、<literal><replaceable class="parameter">name</replaceable> =&gt; <replaceable class="parameter">value</replaceable></literal>という文法を使ってパラメータ名を含むことができます。
ここではsyntaxの訳としては、「文法」よりも「構文」の方がより適しているような気がします。まあ、好みの範囲のような気もしますが...

2022-01-21 23:16 UTC, koizumistr commented
対応しました。読み直したら私もそんな気がしましたので。

2022-02-10 06:43 UTC, tatsuo-ishii approved these changes
確認しました。

2022-02-10 06:43 UTC, merged