update install-windows for 14.0
pgsql-jp/jpug-doc pull request #2141
Opened 2022-01-16 00:04 UTC by koizumistr

install-windows.sgml の14.0対応です。

2022-01-16 00:55 UTC, tatsuo-ishii approved these changes
一通り確認しました。

2022-01-19 22:11 UTC, KenichiroTanaka requested changes
一通り確認しました。
1箇所だけ確認をお願いします。

2022-01-19 22:11 UTC, KenichiroTanaka commented on doc/src/sgml/install-windows.sgml
> +ほとんどのユーザには、<ulink url="https://www.postgresql.org/download/"></ulink>の<productname>PostgreSQL</productname>ウェブサイトからグラフィカルインストーラパッケージとして入手可能なWindows用のバイナリ配布物をダウンロードすることを推奨します。
リンク先はPostgreSQLサイト内ですので、
```
ほとんどのユーザには、<ulink url="https://www.postgresql.org/download/"></ulink>の<productname>PostgreSQL</productname>ウェブサイトから
```
→
```
ほとんどのユーザには、<productname>PostgreSQL</productname>ウェブサイトの<ulink url="https://www.postgresql.org/download/"></ulink>から
```
とするのはどうでしょうか。

2022-01-21 23:20 UTC, koizumistr commented
確認ありがとうございます。対応しました。

2022-01-26 21:39 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。
確認しました。

2022-01-26 21:39 UTC, merged