client-auth.sgmlのPostgreSQL 14.0対応です。
pgsql-jp/jpug-doc pull request #2144
Opened 2022-01-16 10:18 UTC by tatsuo-ishii

2022-02-19 13:04 UTC, KenichiroTanaka requested changes
レビューが遅くなりすみません。少し気づいたところがあるので見ていただけないでしょうか。

2022-02-20 09:06 UTC, tatsuo-ishii reviewed
レビューありがとうございます。

2022-02-20 09:06 UTC, tatsuo-ishii commented on doc/src/sgml/client-auth.sgml
> +このオプションは1つあるいは2つの値を持つことができます。
失礼しました。"one or two"と読み違えていました。

2022-02-20 09:06 UTC, tatsuo-ishii commented on doc/src/sgml/client-auth.sgml
> +このオプションを使って<literal>DN</literal>に対して正規表現を使って比較を行う際には注意が必要です。
失礼しました。対応します。

2022-02-20 10:40 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。

2022-02-20 10:41 UTC, merged