update arch-dev for 14.0
pgsql-jp/jpug-doc pull request #2145
Opened 2022-01-19 05:36 UTC by koizumistr

arch-dev.sgml の14.0対応です。

2022-02-13 10:35 UTC, tatsuo-ishii requested changes
一通り確認しました。

2022-02-13 10:35 UTC, tatsuo-ishii commented on doc/src/sgml/arch-dev.sgml
> +バックエンドが問い合わせを受け取った時点からクライアントに結果を返す時点の間に引き起こる操作の一般的な流れを理解してもらうのが目的です。
"This chapter"が訳出されていないようです。

2022-02-13 10:37 UTC, tatsuo-ishii requested changes
指摘事項が漏れていました。

2022-02-13 10:37 UTC, tatsuo-ishii commented on doc/src/sgml/arch-dev.sgml
> +エクゼキュータ機構は4つの基本的なSQL型すべてを検証するために用いられます。
「SQL型」だとそのようなデータ型あるような誤解を招くかもしれないので、「SQL問い合わせの種類」くらいではどうでしょう？

2022-02-25 23:53 UTC, koizumistr commented
確認ありがとうございます。対応しました。

2022-02-26 01:46 UTC, tatsuo-ishii approved these changes
確認しました。対応ありがとうございます。

2022-02-26 01:47 UTC, merged