update ref/select for 14.0
pgsql-jp/jpug-doc pull request #2147
Opened 2022-01-24 12:18 UTC by koizumistr

ref/select.sgml の14.0対応です。

2022-02-13 10:51 UTC, tatsuo-ishii requested changes
一通り確認しました。

2022-02-13 10:51 UTC, tatsuo-ishii commented on doc/src/sgml/ref/select.sgml
> +<literal>SEARCH</literal>句を指定すると、再帰問い合わせの結果を幅優先順か深さ優先順で並べるのに使える<firstterm>検索シーケンス列</firstterm>を計算します。
"optional"が訳出されていないようです。

2022-02-13 10:51 UTC, tatsuo-ishii commented on doc/src/sgml/ref/select.sgml
> +<literal>CYCLE</literal>句は、再帰問い合わせで循環を検出するのに使われます。
"optional"が訳出されていないようです。

2022-02-13 10:51 UTC, tatsuo-ishii commented on doc/src/sgml/ref/select.sgml
> +関数呼び出しに<command>WITH ORDINALITY</command>句を追加した時は、<type>bigint</type>型の追加の列が関数の結果列に追加されます。
"optional"が訳出されていないようです。

2022-02-13 10:51 UTC, tatsuo-ishii commented on doc/src/sgml/ref/select.sgml
> +<literal>DISTINCT</literal>句を指定すると処理の前に重複するセットを削除します。<literal>UNION ALL</literal>を<literal>UNION DISTINCT</literal>に変換は<emphasis>しません</emphasis>。
"optional"が訳出されていないようです。

2022-03-05 04:24 UTC, koizumistr commented
確認ありがとうございます。対応しました。

（select.sgml内の）既存部分に合わせたつもりだったのですが、
- 既存部分でも結構バラバラ
- そもそも「合わせる」というのが自分の訳の中でも初志貫徹できてない

ということで、今回（それなりに）合わせる方向で既存部分にも手を入れてます。

2022-03-24 06:12 UTC, tatsuo-ishii commented
遅くなり申し訳ありません。対応ありがとうございます。確認しました。

2022-03-24 06:12 UTC, tatsuo-ishii approved these changes
確認しました。ありがとうございます。

2022-03-24 06:13 UTC, merged