pgsurgery.sgmlのPostgreSQL 14.0対応です。
pgsql-jp/jpug-doc pull request #2150
Opened 2022-01-30 10:54 UTC by tatsuo-ishii

新規ファイルです。

2022-02-19 13:31 UTC, KenichiroTanaka requested changes
細かいですが１箇所気づきましたので確認いただけないでしょうか。

2022-02-19 13:31 UTC, KenichiroTanaka commented on doc/src/sgml/pgsurgery.sgml
> +この関数はアクセスする方法がないタプルを強制的に削除するために使用することを意図しています。
細かいですが
 For example:
も訳出すべきでしょうか。

2022-02-20 09:01 UTC, tatsuo-ishii reviewed
レビューありがとうございます。

2022-02-20 09:01 UTC, tatsuo-ishii commented on doc/src/sgml/pgsurgery.sgml
> +この関数はアクセスする方法がないタプルを強制的に削除するために使用することを意図しています。
約抜け失礼しました。対応します。

2022-02-20 10:43 UTC, KenichiroTanaka approved these changes
対応ありがとうございました。

2022-02-20 10:43 UTC, merged