update ref/drop_procedure for 14.0
pgsql-jp/jpug-doc pull request #2156
Opened 2022-02-10 06:12 UTC by kitayama

2022-02-11 00:27 UTC, KenichiroTanaka requested changes

2022-02-11 00:27 UTC, KenichiroTanaka commented on doc/src/sgml/ref/drop_procedure.sgml
> +ここで説明した検索規則は、<コマンド>ALTER PROCEDURE</command>や<コマンド>COMMENT ON PROCEDURE</command>など、既存のプロシージャーに作用する他のコマンドでも使用されます。
タグの中が翻訳されてしまっているようです。
<コマンド>→<command>

2022-02-11 00:27 UTC, KenichiroTanaka commented
取り急ぎコンパイルが通っていませんので修正をお願いします。

2022-02-14 00:25 UTC, kitayama commented on doc/src/sgml/ref/drop_procedure.sgml
> +ここで説明した検索規則は、<コマンド>ALTER PROCEDURE</command>や<コマンド>COMMENT ON PROCEDURE</command>など、既存のプロシージャーに作用する他のコマンドでも使用されます。
すみません、修正しました。

2022-02-14 00:27 UTC, kitayama commented on doc/src/sgml/ref/drop_procedure.sgml
> +これが行なわれると、プロシージャの<literal>OUT</literal>引数の型はコマンドに対して<emphasis>後に</emphasis>検証されます。
レビューありがとうございます。指摘いただいた内容を反映しました。

2022-02-18 11:41 UTC, KenichiroTanaka approved these changes
対応ありがとうございます

2022-02-19 13:55 UTC, merged