runtime.sgmlのPostgreSQL 14.0対応です。
pgsql-jp/jpug-doc pull request #2157
Opened 2022-02-10 08:33 UTC by tatsuo-ishii

2022-03-24 01:29 UTC, noborus reviewed
diffで表示されている以外のところで、修正漏れがあるようなので修正をお願いします。

83行〜 Pre-packaged versions of 〜はマージ時ミスでダブってしまっているようです。
　　　削除をお願いします。
2051行〜
```
 カーネルがメモリオーバーコミットを実装する方法のため、カーネルは、
<productname>PostgreSQL</productname>や他のプロセスのメモリ要求がシステムの
仮想メモリを枯渇させた場合、<productname>PostgreSQL</productname> postmaster 
（マスタサーバプロセス）を終了させる可能性があります。
```
「スーパバイザサーバプロセス」への変更漏れです。
3898行〜
```
このサポートには<acronym>GSSAPI</acronym>の実装（MIT krb5など）が
```
原文では「MIT Kerberos」に変わっています。

2022-03-24 06:09 UTC, tatsuo-ishii commented
レビューありがとうございます。対応します。

2022-03-24 07:16 UTC, noborus commented
修正ありがとうございます。確認しました。

2022-03-24 23:08 UTC, KenichiroTanaka requested changes
レビューが遅くなりすみません。いくつか気づくことがあったため確認をお願いしてもいいでしょうか。

2022-03-25 22:19 UTC, tatsuo-ishii commented on doc/src/sgml/runtime.sgml
>  必要なhuge pages数を見積もるには、huge pagesを有効にせずに<productname>PostgreSQL</productname>を起動し、<filename>/proc</filename>ファイルシステムを使用してpostmasterの無名共有セグメントサイズとシステムのhuge pageサイズの値をチェックします。
対応します。

2022-03-25 22:20 UTC, tatsuo-ishii commented on doc/src/sgml/runtime.sgml
> +<literal>2MB</literal>のhuge pagesを想定すると、<literal>6490428</literal> / <literal>2048</literal>はおおよそ<literal>3169.154</literal>となり、この例では<literal>3170</literal>のhuge pagesが必要となります。
確かに。いただきます。

2022-03-25 22:22 UTC, tatsuo-ishii commented on doc/src/sgml/runtime.sgml
> +<literal>2MB</literal>のhuge pagesを想定すると、<literal>6490428</literal> / <literal>2048</literal>はおおよそ<literal>3169.154</literal>となり、この例では<literal>3170</literal>のhuge pagesが必要となります。
上記と同じところですね？

2022-03-25 22:54 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。
すみません、何か１箇所重複してコメントされていました。
いただいている内容で問題ありません。

2022-03-25 22:55 UTC, merged