keywords.sgmlのPostgreSQL 14.0対応です。
pgsql-jp/jpug-doc pull request #2161
Opened 2022-02-13 11:17 UTC by tatsuo-ishii

2022-03-24 01:44 UTC, noborus approved these changes
確認しました

2022-03-24 13:09 UTC, KenichiroTanaka requested changes
1点気づくところがありましたのでご確認をお願いします。

2022-03-24 13:09 UTC, KenichiroTanaka commented on doc/src/sgml/keywords.sgml
> +列名が空白のエントリは、<productname>PostgreSQL</productname>が通常の識別子として扱う単語であることを示します。
細かいですが、「列名が空白のエントリは」は「列が空白のエントリは」では無いかと思います。
※私も一瞬 column namesと見えました。

2022-03-25 22:15 UTC, tatsuo-ishii commented on doc/src/sgml/keywords.sgml
> +列名が空白のエントリは、<productname>PostgreSQL</productname>が通常の識別子として扱う単語であることを示します。
おお、ありがとうございます。対応しました。

2022-03-25 22:55 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。

2022-03-25 22:55 UTC, merged