extend.sgmlの14.0対応です
pgsql-jp/jpug-doc pull request #2174
Opened 2022-03-14 08:56 UTC by noborus

2022-04-01 11:36 UTC, KenichiroTanaka requested changes
1点気づくところがありましたので確認をお願いします。

2022-04-01 11:36 UTC, KenichiroTanaka commented on doc/src/sgml/extend.sgml
> +範囲型を選択する方法はないので、<type>anycompatiblerange</type>および/または<type>anycompatiblemultirange</type>を使用するには、その型で宣言されたすべての引数が実際の範囲型および/または多重範囲型を持ち、その型の派生型が選択された共通型と一致する必要があります。
knowing only its subtype,が訳出されていないように思います。
原文も変更がないため13の頃に記載があった「その派生元型だけ分かっている範囲型を〜」とするのはどうでしょうか。

2022-04-06 01:09 UTC, noborus commented
ご指摘ありがとうございます。
以前の訳を反映させて、他も少し修正しました。

2022-04-09 10:46 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。

2022-04-09 10:46 UTC, merged