release-14.sgml を翻訳。
pgsql-jp/jpug-doc pull request #2178
Opened 2022-03-27 12:42 UTC by harukat

2022-04-10 08:51 UTC, tatsuo-ishii requested changes
一通り確認しました。

2022-04-10 08:51 UTC, tatsuo-ishii commented on doc/src/sgml/release-14.sgml
> +<link linkend="functions-string"><function>substring()</function></link>の新たな正規表現の構文を追加しました。
「新たな」というと、新規に発案したような印象を受けますが、実際にはより最新のSQL標準の構文のことを言っているので、「より最新の」くらいが適切と思います。

2022-04-14 13:32 UTC, harukat commented on doc/src/sgml/release-14.sgml
> +ロジカルレプリケーションを使っているとき、コマンド完了の際に<acronym>WAL</acronym>の無効化メッセージを生成するようにしました。
ご指摘に懸念に対応するため「WALに無効化メッセージを生成する・・」としましたがいかがでしょう（「追加」と「生成」はほぼ同じことなので）。

2022-04-14 13:33 UTC, harukat commented on doc/src/sgml/release-14.sgml
> +ロジカルレプリケーションが無効のときには、<acronym>WAL</acronym>の無効化メッセージはトランザクション完了時に生成されます。
「WALにおける無効化メッセージ」としました。

2022-04-15 13:00 UTC, tatsuo-ishii commented on doc/src/sgml/release-14.sgml
> +ロジカルレプリケーションを使っているとき、コマンド完了の際に<acronym>WAL</acronym>の無効化メッセージを生成するようにしました。
「WALに無効化メッセージを生成する」は日本語としてちょっと不思議ですね。「...に追加」という表現はありますが、「...に生成」という表現はないので。
「無効化メッセージのWALを生成する」ではどうでしょう？あるいは言葉を補って「キャッシュ無効化メッセージのWALを生成する」の方がわかりやすいかもしれません。

2022-04-20 03:47 UTC, KenichiroTanaka requested changes
大きなファイルの対応ありがとうございました。
一通り確認しました。
いくつか気づくところがありましたのでご確認をお願いします。

2022-04-23 05:58 UTC, koizumistr reviewed
まだ途中ですが、気づいたものを。

2022-04-23 05:58 UTC, koizumistr commented on doc/src/sgml/release-14.sgml
> +配列のみならず任意のデータ型に有益な表記法である添え字を適用できるようになりました。
ここは
添字による表記法が有益であるようなデータ型に対してはすべて、添字が適用できるようになった、
と主張しているのだと思います。

元のものだと添え字による表記法は（例えば、整数とか浮動小数点数とかも含めて）「すべてのデータ型に対して有益」と読めてしまうかと。

2022-04-23 05:58 UTC, koizumistr commented on doc/src/sgml/release-14.sgml
> +データベースがトランザクションIDの周回状態に近づき始めた場合、<command>VACUUM</command>が自動的により積極的になり、また、不要なクリーンアップを省略するようになりました。
inessentialに対して「不要」としているようですが、ちょっと強すぎるような気がします。
不必要（必要ではない）、なくてもすむ、という意味であり、「不必要」=「不要」ではないと思いますが、個人的な感覚かもですので他の人の意見も聞きたいです。

2022-04-23 05:58 UTC, koizumistr commented on doc/src/sgml/release-14.sgml
> +<productname>PostgreSQL</productname> 14の上記の項目とその他の機能は次節でより詳しく説明されます。
原文にはnewがありますけど、訳していないのは何か意図がありますか。

2022-04-24 05:12 UTC, harukat commented on doc/src/sgml/release-14.sgml
> +<productname>PostgreSQL</productname> 14の上記の項目とその他の機能は次節でより詳しく説明されます。
「新機能」とします。ここは release-13.sgml からバージョン番号以外を変えていなくて、以前の見落としがそのまま残っていました。

2022-04-24 13:58 UTC, KenichiroTanaka approved these changes
対応ありがとうございました。私の指摘箇所に関しては問題ありません。

2022-05-08 22:21 UTC, tatsuo-ishii approved these changes
確認しました。

2022-05-08 22:21 UTC, merged