update wal.sgml for 14.0
pgsql-jp/jpug-doc pull request #2181
Opened 2022-04-02 04:12 UTC by kitayama

13.1 と 14.0 の差分訳出(新規追加)と、既存部分の変更(訳語の統一など)をおこないました。

2022-04-18 06:41 UTC, tatsuo-ishii requested changes
一通り確認しました。

2022-04-18 06:41 UTC, tatsuo-ishii commented on doc/src/sgml/wal.sgml
> +本章では、効率的かつ信頼できる操作を得るためにログ先行書き込みがどのように使用されているかについて説明します。
operationを「操作」と訳していますが、前の「運用」の方が良かったと思います。

2022-04-18 06:41 UTC, tatsuo-ishii commented on doc/src/sgml/wal.sgml
> +しかし、そのようなデータ構造が持続する場所は、WALレコードはクラッシュリカバリ時に正確に最新の変更を行えるようWALレコードが書き出され、それらのWALレコードは上記のように保護されます。
前からですが、persistentの訳としては「持続」より「永続」の方が良いかと（お約束のようなもの）
「そのようなデータ構造が持続する場所は」→「そのようなデータ構造が永続する場所では」

> WALレコードはクラッシュリカバリ時に正確に最新の変更を行えるようWALレコードが書き出され、

クラッシュリカバリ時に直近の更新が正確に再構築されるようにWALレコードが書き出され、

2022-04-18 06:41 UTC, tatsuo-ishii commented on doc/src/sgml/wal.sgml
> +データページのみがチェックサムによって保護されますが、内部データ構造と一時ファイルは保護されません。
「保護されますが」の「が」は不要なのでは？

2022-04-18 06:41 UTC, tatsuo-ishii commented on doc/src/sgml/wal.sgml
> +例えば、銀行では、ATMの現金支払を記録するトランザクションで非同期コミットを使用してはいけません。
would notなので、「使用してはいけません」ではなくて「決して使用しないでしょう」ではないでしょうか。

2022-04-20 05:17 UTC, kitayama commented on doc/src/sgml/wal.sgml
> +本章では、効率的かつ信頼できる操作を得るためにログ先行書き込みがどのように使用されているかについて説明します。
ご確認ありがとうございます。元の「運用」に戻しました。
「運用」という言葉の意味が広く違う意味にも取られるため、内部動作の説明の観点で「操作」と判断しましたが、御指摘を受けて考え直し前の「運用」に戻しました。どちらかというとまだ「稼働」のほうが「操作」より本来の意味に近いようにも思います。

2022-04-20 05:19 UTC, kitayama commented on doc/src/sgml/wal.sgml
> +しかし、そのようなデータ構造が持続する場所は、WALレコードはクラッシュリカバリ時に正確に最新の変更を行えるようWALレコードが書き出され、それらのWALレコードは上記のように保護されます。
前者は、他の箇所の訳も確認し、persistentの訳は「永続」に変更しました。「恒久的な」の訳も少しありました。
後者は、いただいた案を反映させていただきました。

2022-04-20 05:19 UTC, kitayama commented on doc/src/sgml/wal.sgml
> +データページのみがチェックサムによって保護されますが、内部データ構造と一時ファイルは保護されません。
文を繋げずに、二つの文にして、主語を入れ替えました。

2022-04-20 05:27 UTC, kitayama commented on doc/src/sgml/wal.sgml
> +例えば、銀行では、ATMの現金支払を記録するトランザクションで非同期コミットを使用してはいけません。
訳をあらためて検討していませんでした。ご指摘の通りこの would は推測ですので、いただいた案を反映しました。

2022-04-21 15:49 UTC, koizumistr reviewed
確認しました。

2022-04-21 15:49 UTC, koizumistr commented on doc/src/sgml/wal.sgml
> +しかし、そのようなデータ構造が永続する場所は、クラッシュリカバリ時に直近の更新が正確に再構築されるようにWALレコードが書き出され、それらのWALレコードは上記のように保護されます。
場所は、〜レコードは となって保護されるのが何だか迷うので、

永続する場所では

でいかがでしょう。

2022-04-25 07:00 UTC, kitayama commented on doc/src/sgml/wal.sgml
> +しかし、そのようなデータ構造が永続する場所は、クラッシュリカバリ時に直近の更新が正確に再構築されるようにWALレコードが書き出され、それらのWALレコードは上記のように保護されます。
レビューありがとうございます。最初意味を取り違えて一番最後の「それらのWALレコードは」を削除して文をつなげる対応をしてしまいましたが、最初のところの指摘であることに気付き、御指摘いただいた内容を反映しました。

2022-05-01 11:26 UTC, koizumistr approved these changes
確認しました。対応ありがとうございます。

2022-05-15 08:26 UTC, tatsuo-ishii approved these changes
確認しました。

2022-05-15 08:26 UTC, merged