update gist for 14.0
pgsql-jp/jpug-doc pull request #2199
Opened 2022-05-03 14:23 UTC by koizumistr

gist.sgml の14.0対応です。

2022-05-15 09:15 UTC, tatsuo-ishii requested changes
一通り確認しました。

2022-05-15 09:15 UTC, tatsuo-ishii commented on doc/src/sgml/gist.sgml
> +Datumはインデックス付けされる値2つで、インデックスに格納される形式です。すなわち、<function>compress</function>メソッドにより返される形式です。
"The full API is defined in..."以下が訳されていないようです。

2022-05-15 09:15 UTC, tatsuo-ishii commented on doc/src/sgml/gist.sgml
> +デフォルトでは、インデックスのサイズが<xref linkend="guc-effective-cache-size"/>に達した時にGiSTインデックス構築はバッファ処理法に切り替わります。
"If sorting is not possible"が訳出されていないようです。

2022-05-15 09:15 UTC, tatsuo-ishii commented on doc/src/sgml/gist.sgml
> +バッファ処理はCREATE INDEXコマンドの<literal>buffering</literal>パラメータによって、手作業で有効または無効にできます。
"forced or prevented"なので、どちらかというと「手動で強制あるいは無効にできます」でしょうか。

2022-05-20 23:22 UTC, koizumistr commented on doc/src/sgml/gist.sgml
> +Datumはインデックス付けされる値2つで、インデックスに格納される形式です。すなわち、<function>compress</function>メソッドにより返される形式です。
1514行に「完全なAPIは、、、」としてあるはずですが、、、

2022-05-20 23:23 UTC, koizumistr commented
確認ありがとうございます。
The full API 以外の部分は対応しました。

2022-05-21 00:09 UTC, tatsuo-ishii commented on doc/src/sgml/gist.sgml
> +Datumはインデックス付けされる値2つで、インデックスに格納される形式です。すなわち、<function>compress</function>メソッドにより返される形式です。
おっと、失礼しました。

2022-05-21 00:10 UTC, tatsuo-ishii approved these changes
確認しました。対応ありがとうございます。

2022-05-21 00:10 UTC, merged