update btree and charset for v14
pgsql-jp/jpug-doc pull request #2201
Opened 2022-05-12 07:02 UTC by thoshiai

btree.sgmlとcharset.sgmlのPostgreSQL14.0対応バージョンを翻訳しました。

2022-05-21 12:16 UTC, koizumistr reviewed
確認しました。

2022-05-21 12:16 UTC, koizumistr commented on doc/src/sgml/btree.sgml
> +これは、 一定の <emphasis>定量的な</emphasis>テーブルレベルの閾値が超えられたとき（<xref linkend="autovacuum"/>参照）に起動されるautovacuumワーカーによって実行された<quote>トップダウン</quote>インデックスのクリーンアップと対照的です。
「一定の」の前後に余分な空白が入っているようです。

2022-05-21 12:16 UTC, koizumistr commented on doc/src/sgml/btree.sgml
> +これは、インデックスがカバーするカラムを論理的に変更することが滅多にない<command>UPDATE</command>からの有意なバージョンチャーンに依存するB-Treeインデックスで予想されます。
or neverが訳されていないようです。

2022-05-21 12:16 UTC, koizumistr commented on doc/src/sgml/btree.sgml
> +リーフページは、余分なバージョンチャーンの重複を一時的に<quote>吸収</quote>することができます。
This allows なので、「これにより」がどこかに必要かと。

2022-06-05 07:30 UTC, thoshiai commented on doc/src/sgml/btree.sgml
> +インデックスに対して、各タプルは独自のインデックスエントリを必要とする独立したオブジェクトです。<quote>バージョンチャーン</quote>タプルは蓄積し、クエリ待ち時間とスループットに悪影響を与える可能性があります。
ありがとうございます。改行を入れました。

2022-06-05 07:30 UTC, thoshiai commented on doc/src/sgml/btree.sgml
> +ボトムアップインデックス削除パスは、論理行とバージョンを含む<emphasis>定量的な</emphasis>特徴に基づいた単一のリーフページ内の疑わしいごみタプルを対象としています。
定性的な、に修正しました。

2022-06-05 07:31 UTC, thoshiai commented on doc/src/sgml/btree.sgml
> +これは、 一定の <emphasis>定量的な</emphasis>テーブルレベルの閾値が超えられたとき（<xref linkend="autovacuum"/>参照）に起動されるautovacuumワーカーによって実行された<quote>トップダウン</quote>インデックスのクリーンアップと対照的です。
失礼しました、余計な余白を削除しました。

2022-06-05 07:32 UTC, thoshiai commented on doc/src/sgml/btree.sgml
> +これは、インデックスがカバーするカラムを論理的に変更することが滅多にない<command>UPDATE</command>からの有意なバージョンチャーンに依存するB-Treeインデックスで予想されます。
滅多にまたは決してない
といった記述に修正しました。

2022-06-05 07:32 UTC, thoshiai commented on doc/src/sgml/btree.sgml
> +リーフページは、余分なバージョンチャーンの重複を一時的に<quote>吸収</quote>することができます。
これにより、を冒頭に追加しました

2022-06-05 13:55 UTC, koizumistr approved these changes
対応ありがとうございます。確認しました。

2022-06-15 06:23 UTC, tatsuo-ishii requested changes
一通り確認しました。

2022-06-15 06:23 UTC, tatsuo-ishii commented on doc/src/sgml/btree.sgml
> +単純削除は、最近のインデックススキャンでは影響があるアイテムに<literal>LP_DEAD</literal>ビットをセットする際に、ついでに実行できる機会の場合のみに実行されます。
"is opportunistic in the sense"が訳出されていないようです。訳すとしたら、以下のような感じでしょうか。

単純削除は、最近のインデックススキャンでは影響があるアイテムに<literal>LP_DEAD</literal>ビットをセットする際に、ついでに実行できる機会の場合のみに実行されるという意味で、機会主義と言えます。

2022-06-15 06:23 UTC, tatsuo-ishii commented on doc/src/sgml/btree.sgml
> +論理行ごとのバージョン数の平均と最も悪いケースは、対象とされた増分削除パスによって低く維持することができます。
"purely"が訳出されてないようです。

2022-06-15 06:23 UTC, tatsuo-ishii commented on doc/src/sgml/btree.sgml
> +そのような場合でも、<command>VACUUM</command>操作（通常、自動バキュームワーカプロセスで実行します）による、徹底的な<quote>一掃</quote>が、テーブルとその各インデックスの<emphasis>集合的な</emphasis>クリーンアップの一部として最終的に要求されます。
"collective"を「集団的」と訳されていますが、ここは「共通の」という意味ではないでしょうか？

2022-06-15 06:23 UTC, tatsuo-ishii commented on doc/src/sgml/btree.sgml
> +テーブルと全てのインデックスの合計によって共通する控えめな切り捨て点より前に、不要になる<quote>浮いているゴミ</quote>インデックスタプルの維持を許可することはできません。
"conservative"はここでは「保守的な」という意味だと思います。

2022-07-17 20:55 UTC, thoshiai commented
レビューありがとうございます、遅くなりましたが、isii さんのコメント修正しました。

2022-07-18 02:03 UTC, tatsuo-ishii approved these changes
確認しました。対応ありがとうございます、

2022-07-18 02:03 UTC, merged