update spgist for 14.0
pgsql-jp/jpug-doc pull request #2206
Opened 2022-05-23 12:04 UTC by koizumistr

spgist.sgml の14.0対応です。

2022-05-30 23:10 UTC, KenichiroTanaka requested changes
一通り確認しました。1箇所だけ気づくところがありましたのでご確認をお願いします。

2022-05-30 23:49 UTC, tatsuo-ishii commented on doc/src/sgml/spgist.sgml
> +<acronym>SP-GiST</acronym>のツリーのリーフタプルは、インデックスの付けられた列の損失のある表現を含むこともできますが、通常はインデックスの付けられた列と同じデータ型の値を含んでいます。
それはどうでしょう？lossyを「非可逆」と訳すのは、"lossy compression"のように、何か処理を加えた後戻す際に、完全には元に戻らないようなケースでは適切と思いますが、このケースでは、何かを元に戻そうとしているわけではないのでlossyを「非可逆」と訳すのは違和感があります。

2022-05-31 14:15 UTC, KenichiroTanaka approved these changes

2022-05-31 14:15 UTC, KenichiroTanaka commented on doc/src/sgml/spgist.sgml
> +<acronym>SP-GiST</acronym>のツリーのリーフタプルは、インデックスの付けられた列の損失のある表現を含むこともできますが、通常はインデックスの付けられた列と同じデータ型の値を含んでいます。
私の「非可逆」の根拠は他との統一ですので、他の方も適切ではないのであれば、押す根拠がなくなります。
確かに可逆、非可逆は圧縮技術の表現で、インデックスの中で何かを変換したり、元に戻すという
話ではありませんので。上記の指摘は取り下げとさせてもらおうかと思います。

2022-06-02 22:36 UTC, KenichiroTanaka commented
本PRについてはlossyの話題は決着かと思いますのでマージします。

2022-06-02 22:36 UTC, merged

2022-06-03 05:25 UTC, koizumistr commented
上記の議論はこの項目のcloseで終わらせるにはもったいないと思いましたので、#2213としてissueにしておきました。