update ecpg for 14.0
pgsql-jp/jpug-doc pull request #2216
Opened 2022-06-12 14:32 UTC by koizumistr

ecpg.sgml の14.0対応です。

2022-06-16 01:06 UTC, KenichiroTanaka approved these changes
一通り確認しました。
特に気づくところはありませんでした。

2022-06-28 05:48 UTC, tatsuo-ishii requested changes
一通り確認しました。

2022-06-28 05:48 UTC, tatsuo-ishii commented on doc/src/sgml/ecpg.sgml
> +接続対象を直接(すなわち、文字列リテラルとしてでも、変数参照でもない形で)指定した場合、対象の要素は通常のSQLとして解析されて渡されます。これは、例えば、<replaceable>hostname</replaceable>はドットで区切られた一つ以上のSQL識別子のようでなければならなず、識別子が二重引用符で括られていなければ大文字小文字は変換されるということを意味します。
case-foldedは、ここでは「大文字小文字の違いが無視される」ということを言っているのではないでしょうか。

2022-07-08 13:54 UTC, koizumistr commented
確認ありがとうございます。対応しました。

「他のところを真似したはず」と思ったのですが、「他のところ」が見当たらないですね、、、、

2022-07-09 00:58 UTC, tatsuo-ishii approved these changes
確認しました。対応ありがとうございました。

2022-07-09 00:58 UTC, merged