queries.sgmlの14.0対応です
pgsql-jp/jpug-doc pull request #2217
Opened 2022-06-13 02:15 UTC by noborus

2022-06-16 04:40 UTC, KenichiroTanaka requested changes
一通り確認しました。
一部気づくところがありましたので見てもらってもいいでしょうか。

2022-06-16 04:40 UTC, KenichiroTanaka commented on doc/src/sgml/queries.sgml
> +<literal>AS</literal>キーワードは省略することができますが、目的のカラム名が<productname>PostgreSQL</productname>キーワードと一致する場合は、あいまいさを避けるために<literal>AS</literal>と記述するか、カラム名を二重引用符で括る必要があります。
細かいですが、原文が
keyword is optional
から
key word is usually optional
となっているので、usuallyは訳出した方が良いように思います。

2022-06-16 04:40 UTC, KenichiroTanaka commented on doc/src/sgml/queries.sgml
> +例えば、<literal>FROM</literal>はそのようなキーワードの1つなので、次のようには機能しません。
下に記載されているのはうまく動かないSQLですので、「次のようには機能しません。」だと分かりにくく感じました（↓のように動くの？動かないの？がパッと分かりませんでした）。
「以下は動きません。」もしくはもう少し意訳して「次のSQLは動きません。」
くらいの訳でどうでしょうか。

2022-06-16 04:40 UTC, KenichiroTanaka commented on doc/src/sgml/queries.sgml
> +例えば、<literal>FROM</literal>はそのようなキーワードの1つなので、次のようには機能しません。
下に記載されているのはうまく動かないSQLですので、「次のようには機能しません。」だと分かりにくく感じました（↓のように動くの？動かないの？がパッと分かりませんでした）。
「以下は動作しません。」もしくはもう少し意訳して「次のSQLは動作しません。」
くらいの訳でどうでしょうか。

2022-06-16 04:40 UTC, KenichiroTanaka commented on doc/src/sgml/queries.sgml
> +1つのフィールドだけを追跡する必要がある場合は、<literal>ROW()</literal>構文を省略します。
in the common case
が訳出されていないようです。

2022-06-16 04:40 UTC, KenichiroTanaka commented on doc/src/sgml/queries.sgml
> +1つのフィールドだけを追跡する必要がある場合は、<literal>ROW()</literal>構文を省略します。
in the common case
が訳出されていないようです。

2022-06-24 06:32 UTC, noborus commented on doc/src/sgml/queries.sgml
> +<literal>AS</literal>キーワードは省略することができますが、目的のカラム名が<productname>PostgreSQL</productname>キーワードと一致する場合は、あいまいさを避けるために<literal>AS</literal>と記述するか、カラム名を二重引用符で括る必要があります。
修正します

2022-06-24 06:33 UTC, noborus commented on doc/src/sgml/queries.sgml
> +例えば、<literal>FROM</literal>はそのようなキーワードの1つなので、次のようには機能しません。
「以下は動きません」に修正します。SQLを意訳で入れるとチェック時に整合が取れてないように見えるので。

2022-06-24 06:34 UTC, noborus commented on doc/src/sgml/queries.sgml
> +1つのフィールドだけを追跡する必要がある場合は、<literal>ROW()</literal>構文を省略します。
修正します。

2022-06-25 02:50 UTC, koizumistr reviewed
確認しました。

2022-06-25 02:50 UTC, koizumistr commented on doc/src/sgml/queries.sgml
> +追跡する必要があるフィールドが１つだけであるを一般的な場合では、<literal>ROW()</literal>構文を削除します。
であるを -> である

2022-06-25 02:50 UTC, koizumistr commented on doc/src/sgml/queries.sgml
> +再帰問合せを使用してツリーの巡回順を計算する場合、深さ優先または幅優先のいずれかの順序で結果を順序付ける必要がある場合があります。
titleのところでは「再帰的問い合わせ」になっています。どちらが良いというのはないのですが、揃えるべきかと。

2022-06-26 04:43 UTC, noborus commented
ありがとうございます。ご指摘の箇所修正しました。

2022-06-26 12:33 UTC, koizumistr reviewed
対応ありがとうございます。確認しました。

2022-06-28 13:11 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。

2022-06-28 13:12 UTC, merged