indexam.sgmlのPostgreSQL 14.0対応です。
pgsql-jp/jpug-doc pull request #2219
Opened 2022-06-16 08:25 UTC by tatsuo-ishii

include columnなどをどう訳すか悩んだのですが、「include列」としました。
"include"のうまい日本語訳があればよいのですが、思いつきませんでした。

2022-06-16 09:02 UTC, koizumistr commented
https://github.com/pgsql-jp/jpug-doc/pull/2212#discussion_r894974191 な議論もあるので「include列」で良い気がします。
「いやいや、あちらは大文字でSQL文の話をしていて、こちらは英語の地の文だよね」と言われてしまうとその通りなので、もちろんどなたかうまい訳を思いついてくれたら大歓迎です。

ただ、まあ、英語とSQL文がうまく地続きになっているから、こんな書き方ができている訳で、それを日本語でやろうとするといろいろ難しいよな、とも思います。

2022-06-16 22:52 UTC, KenichiroTanaka commented
「include列」で良いように思います。
カバリングインデックスを作る方法の一つですが、訳されると何のことか判別が難しくなると思いますし
↓を探しましたが適切な訳になりそうな日本語を見つけられませんでした。
https://pgsql-jp.github.io/current/html/indexes-index-only-scans.html

2022-06-20 23:13 UTC, KenichiroTanaka requested changes
一通り確認しました。
2点(2点目の指摘のついでに1点目は細かいですが聞いてみました)気づくところがありましたのでご確認いただけないでしょうか。

2022-06-20 23:13 UTC, KenichiroTanaka commented on doc/src/sgml/indexam.sgml
> +インデックスの生成、破棄、<literal>REINDEX</literal>時にインデックス全体に対する<literal>ACCESS EXCLUSIVE</literal>ロックが獲得されます。
instead with <literal>CONCURRENTLY
が訳出されていないようです。

2022-06-20 23:13 UTC, KenichiroTanaka commented on doc/src/sgml/indexam.sgml
> +<structname>OpFamilyMember</structname>構造体の依存性に関するフィールドに、<command>CREATE OPERATOR CLASS</command>の場合にはopclassにコアコードがハード依存性を設定します。<command>ALTER OPERATOR FAMILY ADD</command>ならばopfamilyにソフト依存性を設定します。
コアコードがハード依存性を「設定します」。のところですが、原文がinitialized  なので「初期化します」の方が自然かな、と思ったのですが、何か意図がありましたでしょうか。

2022-06-21 05:32 UTC, tatsuo-ishii commented on doc/src/sgml/indexam.sgml
> +インデックスの生成、破棄、<literal>REINDEX</literal>時にインデックス全体に対する<literal>ACCESS EXCLUSIVE</literal>ロックが獲得されます。
追加します。

2022-06-21 05:32 UTC, tatsuo-ishii commented on doc/src/sgml/indexam.sgml
> +<structname>OpFamilyMember</structname>構造体の依存性に関するフィールドに、<command>CREATE OPERATOR CLASS</command>の場合にはopclassにコアコードがハード依存性を設定します。<command>ALTER OPERATOR FAMILY ADD</command>ならばopfamilyにソフト依存性を設定します。
ちょっと悩んだのですが、「初期化」だと、後からさらになにか設定するようなイメージがあったので「設定します」にしたのですが、ちょっと意訳すぎだったかも知れません。素直に「初期化します」にします。

2022-06-21 12:38 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。
確認しました。

2022-06-21 12:38 UTC, KenichiroTanaka commented
一通り確認しましたのでマージします。

2022-06-21 12:38 UTC, merged