ddl.sgmlのPostgreSQL 14.0対応です。
pgsql-jp/jpug-doc pull request #2221
Opened 2022-06-18 06:20 UTC by tatsuo-ishii

2022-06-24 07:30 UTC, noborus commented on doc/src/sgml/ddl.sgml
> +たとえばテーブルの行が木構造のノードを表現するようにしたいのであれば、以下のように書くことができるでしょう。
> this is called    a \<firstterm\>self-referential\<\/firstterm\> foreign key. 
の文が抜けています。

木構造は、他の文章では、ツリー構造の方が多いようです。（spgist.sgmlのみ木構造）。

2022-06-24 07:30 UTC, noborus commented on doc/src/sgml/ddl.sgml
>  このような制約がなければ、そのパーティションに<literal>ACCESS EXCLUSIVE</literal>ロック、親テーブルに<literal>SHARE UPDATE EXCLUSIVE</literal>を保持したままで、パーティション制約を検証するためにテーブルを走査することになります。
前からですが、 \<literal\>CHECK\<\/literal\>がキーワードになっているので\<literal\>CHECK\<\/literal\>がなければ、にしておいて欲しいです。
「親テーブル〜」以下が現在は変更されて無くなっているようです。

2022-06-25 04:17 UTC, KenichiroTanaka requested changes
いくつか気づいたところがありましたのでご確認をお願いします。

2022-06-25 04:17 UTC, KenichiroTanaka commented on doc/src/sgml/ddl.sgml
> +これらのどちらも大量のパーティション数をもたらす結果になるので、自制することをお勧めします。
細かいですが、easilyも訳出した方が良いように思います。

2022-06-25 09:26 UTC, tatsuo-ishii reviewed
レビューありがとうございます。

2022-06-25 09:26 UTC, tatsuo-ishii commented on doc/src/sgml/ddl.sgml
> +時には外部キー制約の<quote>他のテーブル</quote>を同じテーブルにすることが有用です。
失礼しました。訳出します。

2022-06-25 09:26 UTC, tatsuo-ishii commented on doc/src/sgml/ddl.sgml
> +たとえばテーブルの行が木構造のノードを表現するようにしたいのであれば、以下のように書くことができるでしょう。
個人的には「木構造」が好みですが（わざわざカタカナにする必要もない）、多数派に合わせて「ツリー構造」にします。

2022-06-25 09:26 UTC, tatsuo-ishii commented on doc/src/sgml/ddl.sgml
> +テーブルあるいはビューの<command>TRUNCATE</command>を許可します。
はい、そうします。

2022-06-25 09:26 UTC, tatsuo-ishii commented on doc/src/sgml/ddl.sgml
対応します。

2022-06-25 09:26 UTC, tatsuo-ishii commented on doc/src/sgml/ddl.sgml
> +ですからコマンドは以下のようになるかも知れません。
そのようにします。

2022-06-25 09:26 UTC, tatsuo-ishii commented on doc/src/sgml/ddl.sgml
>  このような制約がなければ、そのパーティションに<literal>ACCESS EXCLUSIVE</literal>ロック、親テーブルに<literal>SHARE UPDATE EXCLUSIVE</literal>を保持したままで、パーティション制約を検証するためにテーブルを走査することになります。
修正します。

2022-06-25 09:26 UTC, tatsuo-ishii commented on doc/src/sgml/ddl.sgml
> +この制約は<command>ATTACH PARTITION</command>が終わった後に削除することを推奨します。
対応します。

2022-06-25 09:26 UTC, tatsuo-ishii commented on doc/src/sgml/ddl.sgml
> +<literal>DEFAULT</literal>パーティション自体がパーティションテーブルなら、個々のパーティションは、上で述べたようにアタッチ予定のテーブルと同じ方法で捜査されます。
失礼しました。修正します。

2022-06-25 09:26 UTC, tatsuo-ishii commented on doc/src/sgml/ddl.sgml
> +これらのどちらも大量のパーティション数をもたらす結果になるので、自制することをお勧めします。
「容易に」を追加します。

2022-06-28 13:14 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。

2022-06-28 13:15 UTC, merged