update plpgsql for 14.0
pgsql-jp/jpug-doc pull request #2222
Opened 2022-06-18 07:45 UTC by koizumistr

plpgsql.sgml の14.0対応です。

volatilityですが、「変動性」となっていたものを「揮発性」にしました。
「変動性」も悪くないのですが、他のところでは「揮発性」となっていたためです。

2022-06-28 13:39 UTC, KenichiroTanaka requested changes
一通り確認しました。
いくつか気づくところがありましたので確認をお願いします。

2022-06-28 13:39 UTC, KenichiroTanaka commented on doc/src/sgml/plpgsql.sgml
> +行または変数リストが用いられる時、それはコマンドの結果の構造と正確に一致しなければなりません。レコード変数が使用される時、自動的に結果の構造と一致するように自身を構築させます。
以前からのところですが、原文が「f a row variable or variable list」
なので「行または変数リストが」→「行変数または変数リストが」などが良いでしょうか。

2022-06-28 13:39 UTC, KenichiroTanaka commented on doc/src/sgml/plpgsql.sgml
> +最後の場所のみが<application>PL/pgSQL</application>の関数の変数参照の候補です。
「 Likewise  the third occurrence must be a function name, so it also will not be  substituted for.」
の訳出が漏れているようです。

2022-07-08 13:22 UTC, koizumistr commented
確認ありがとうございます。対応しました。

2022-07-11 00:07 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。
確認しました。

2022-07-11 00:07 UTC, KenichiroTanaka commented
一通り確認したのでマージします。

2022-07-11 00:07 UTC, merged