update for monitoring for 14.0
pgsql-jp/jpug-doc pull request #2223
Opened 2022-06-18 13:34 UTC by kitayama

2022-06-25 03:44 UTC, koizumistr reviewed
確認しました。

2022-06-25 03:44 UTC, koizumistr commented on doc/src/sgml/monitoring.sgml
> +バックエンドの直近のクエリ識別子です。
query/queriesは「問い合わせ」としていますので、「クエリ識別子」ではなく「問い合わせ識別子」となるのではないでしょうか。

（すみません、query identifier(s) で裏は取ってませんので、もしかしたら「query identifierの場合だけ特別」とかあるかもです。）

2022-06-25 03:44 UTC, koizumistr commented on doc/src/sgml/monitoring.sgml
> +このスロットのこの他のストリーミングカウンタは、<literal>logical_decoding_work_mem</literal>を調整するために使用できます。
この他のストリーミングカウンタ
-> 
このカウンタと他のストリーミングカウンタ

（上では似たような原文を「このカウンタと他のあふれカウンタ」としてます）

2022-06-25 03:44 UTC, koizumistr commented on doc/src/sgml/monitoring.sgml
> +WAL ファイルが<function>issue_xlog_fsync</function>要求によりディスクに同期された回数（<xref linkend="guc-fsync"/>が<literal>on</literal>かつ<xref linkend="guc-wal-sync-method"/>が<literal>fdatasync</literal>または<literal>fsync<
「WAL」と「ファイル」の間に空白があります。

2022-06-25 03:44 UTC, koizumistr commented on doc/src/sgml/monitoring.sgml
> -
原文の空行を消してしまっているようです。

2022-06-27 05:01 UTC, kitayama commented on doc/src/sgml/monitoring.sgml
> +バックエンドの直近のクエリ識別子です。
レビューありがとうございます。「問い合わせ識別子」で統一しました。残ったクエリは「パラレルクエリ」のみですので、こちらはそのままにしています。

2022-06-27 05:02 UTC, kitayama commented on doc/src/sgml/monitoring.sgml
> +このスロットのこの他のストリーミングカウンタは、<literal>logical_decoding_work_mem</literal>を調整するために使用できます。
御指摘いただいた通りに対応しました。

2022-06-27 05:02 UTC, kitayama commented on doc/src/sgml/monitoring.sgml
> +WAL ファイルが<function>issue_xlog_fsync</function>要求によりディスクに同期された回数（<xref linkend="guc-fsync"/>が<literal>on</literal>かつ<xref linkend="guc-wal-sync-method"/>が<literal>fdatasync</literal>または<literal>fsync<
修正しました。

2022-06-27 05:02 UTC, kitayama commented on doc/src/sgml/monitoring.sgml
> -
修正しました。

2022-07-01 12:13 UTC, KenichiroTanaka requested changes
２箇所気づくところがありましたのでご確認をお願いできますでしょうか。

2022-07-01 12:13 UTC, KenichiroTanaka commented on doc/src/sgml/monitoring.sgml
>       </tbody>
githubの機能のために少し遠い位置からの指摘になりますが、以下のdiffの箇所が訳出されていません。
※COPYが追記されています。
```
@@ -4984,6 +5432,7 @@ SELECT pg_stat_get_backend_pid(s.backendid) AS pid,
    which support progress reporting are <command>ANALYZE</command>,
    <command>CLUSTER</command>,
    <command>CREATE INDEX</command>, <command>VACUUM</command>,
+   <command>COPY</command>,
    and <xref linkend="protocol-replication-base-backup"/> (i.e., replication
    command that <xref linkend="app-pgbasebackup"/> issues to take
    a base backup).
```

2022-07-01 12:13 UTC, KenichiroTanaka commented on doc/src/sgml/monitoring.sgml
> +<command>COPY</command>が実行されているときはいつでも、<structname>pg_stat_progress_copy</structname>ビューには現在COPYコマンドを実行している各バックエンドごとの行が含まれます。
細かいですが2回目のCOPYのタグが抜けてしまっているため、追記をお願いできますでしょうか。

2022-07-01 21:17 UTC, noborus commented on doc/src/sgml/monitoring.sgml
> +<xref linkend="guc-maintenance-work-mem"/>が、発見された無効タプルの数量を格納するのに不十分な場合（または、自動バキュームの場合は<xref linkend="guc-autovacuum-work-mem" />が設定されている場合）は、バキューム実行ごとに複数回発生する可能性があります。
`<xref linkend="guc-autovacuum-work-mem" />` にスペースが一つ入ってますが、原文に合わせて`<xref linkend="guc-autovacuum-work-mem"/>`にしてもらえますでしょうか。

2022-07-03 04:40 UTC, kitayama commented on doc/src/sgml/monitoring.sgml
>       </tbody>
レビューありがとうございます。修正しました。

2022-07-03 04:41 UTC, kitayama commented on doc/src/sgml/monitoring.sgml
> +<command>COPY</command>が実行されているときはいつでも、<structname>pg_stat_progress_copy</structname>ビューには現在COPYコマンドを実行している各バックエンドごとの行が含まれます。
抜けていたタグを追加しました。

2022-07-03 04:41 UTC, kitayama commented on doc/src/sgml/monitoring.sgml
> +<xref linkend="guc-maintenance-work-mem"/>が、発見された無効タプルの数量を格納するのに不十分な場合（または、自動バキュームの場合は<xref linkend="guc-autovacuum-work-mem" />が設定されている場合）は、バキューム実行ごとに複数回発生する可能性があります。
レビューありがとうございます。余分なスペースを削除しました。

2022-07-08 13:36 UTC, koizumistr reviewed
対応ありがとうございます。確認しました。
が、クエリでまた新しいところを見つけてしまいました、、、

2022-07-12 07:25 UTC, kitayama commented on doc/src/sgml/monitoring.sgml
> +<command>SELECT</command>クエリからコピーする場合は<literal>0</literal>に設定されます。
「パラレルクエリ」以外に見逃していた「クエリ」の指摘ありがとうございます。「問い合わせ」に修正しました。

2022-07-13 22:38 UTC, KenichiroTanaka approved these changes
反応が遅くなり失礼しました。また、対応いただきありがとうございました。

2022-07-13 22:38 UTC, merged