logicaldecoding.sgml の14.0対応です
pgsql-jp/jpug-doc pull request #2230
Opened 2022-07-11 05:48 UTC by noborus

2022-07-16 05:30 UTC, koizumistr reviewed
確認しました。

2022-07-16 05:30 UTC, koizumistr commented on doc/src/sgml/logicaldecoding.sgml
> -
原文の空行を消してしまっているようです。

2022-07-16 05:30 UTC, koizumistr commented on doc/src/sgml/logicaldecoding.sgml
> +この機能を使用して分散2相コミットを構築する論理レプリケーションソリューションは、準備されたトランザクションが[user]カタログテーブルを排他的にロックした場合にデッドロックを発生する可能性があります。
このファイルの他のところでは「ロジカルレプリケーション」とやっているような、、、、
でも他のファイルも含めると「論理レプリケーション」が多数派？

2022-07-18 01:19 UTC, noborus commented on doc/src/sgml/logicaldecoding.sgml
> +
ここは原文で珍しく1行空いたところがあったので、それに従いました。本来はパラグラフを分けるべきところからもしれません。

2022-07-18 01:21 UTC, noborus commented on doc/src/sgml/logicaldecoding.sgml
> +<function>stream_stop_cb</function>コールバックは、継続中のトランザクションからストリームされた変更のブロックをクローズするときに呼び出されます。
他にも両方あって統一されてませんでした。修正します。

2022-07-18 01:22 UTC, noborus commented on doc/src/sgml/logicaldecoding.sgml
> +この機能を使用して分散2相コミットを構築する論理レプリケーションソリューションは、準備されたトランザクションが[user]カタログテーブルを排他的にロックした場合にデッドロックを発生する可能性があります。
#943 が、そのままになっていて両方ある状態でした。ここでは一旦ロジカルレプリケーションに統一します。

2022-07-19 14:22 UTC, koizumistr approved these changes
対応ありがとうございます。確認しました。

2022-07-19 14:22 UTC, koizumistr commented on doc/src/sgml/logicaldecoding.sgml
> +
あ、本当だ。了解です。

2022-07-26 07:39 UTC, tatsuo-ishii requested changes

2022-07-26 07:39 UTC, tatsuo-ishii commented on doc/src/sgml/logicaldecoding.sgml
> +1つのスロットからの変更を同時に消費できるのは1つの受信側だけです。
「at any give time」は「同時に」ではないような気がします。

1つのスロットからの変更をある時点で消費できるのは一つの受信側だけです。

ということではないでしょうか？

2022-07-26 08:42 UTC, noborus commented on doc/src/sgml/logicaldecoding.sgml
> +1つのスロットからの変更を同時に消費できるのは1つの受信側だけです。
ご指摘ありがとうございます。確かに変でした。
表現に悩んだのですが、以下でどうでしょうか？

「どの時点でも1つのスロットからの変更を消費できるのは1つの受信側だけです。」

2022-07-26 10:28 UTC, tatsuo-ishii commented on doc/src/sgml/logicaldecoding.sgml
> +1つのスロットからの変更を同時に消費できるのは1つの受信側だけです。
いいですね！

2022-07-26 10:43 UTC, noborus commented on doc/src/sgml/logicaldecoding.sgml
> +1つのスロットからの変更を同時に消費できるのは1つの受信側だけです。
ありがとうございます。修正しました。

2022-07-26 11:12 UTC, tatsuo-ishii approved these changes
確認しました。

2022-07-26 11:12 UTC, merged