libpq1の14.0対応です
pgsql-jp/jpug-doc pull request #2249
Opened 2022-07-21 02:51 UTC by noborus

2022-07-23 04:17 UTC, tatsuo-ishii requested changes
一通り確認しました。

2022-07-23 04:17 UTC, tatsuo-ishii commented on doc/src/sgml/libpq.sgml
> +<function>PQgetResult</function>は繰り返し呼び出されなければなりません。
この行と次の行ですが、これだとパイプラインが終了するまでPGRES_PIPELINE_SYNCが返ってくるように取れますが、実際はPGRES_PIPELINE_SYNCが返ってきたことをもって、パイプラインモードが終了するのだと思います。
次の行と合わせて以下のような意味だと思います。

<function>PQgetResult</function>は繰り返し呼び出されなければならず、現在のパイプラインが終了するまでこのステータスコードが返ります。
パイプラインが終了すると、<literal>PGRES_PIPELINE_SYNC</literal>が返り、通常の処理を再開できます。

2022-07-23 04:17 UTC, tatsuo-ishii commented on doc/src/sgml/libpq.sgml
> +各問い合わせが実行するのにクライアント/サーバのラウンドトリップ時間の何倍もかかる場合、パイプラインコマンドを使用するメリットは通常少なくなります。
問い合わせが実行するのにクライアント/サーバのラウンドトリップ時間の何倍もかかる場合

は、

問い合わせを実行する時間がライアント/サーバのラウンドトリップ時間の何倍もかかる場合

あたりの方が自然ではないかと。

2022-07-24 00:28 UTC, noborus commented on doc/src/sgml/libpq.sgml
> +<function>PQgetResult</function>は繰り返し呼び出されなければなりません。
ありがとうございます。わかってませんでした。修正します。

2022-07-24 00:29 UTC, noborus commented on doc/src/sgml/libpq.sgml
> +各問い合わせが実行するのにクライアント/サーバのラウンドトリップ時間の何倍もかかる場合、パイプラインコマンドを使用するメリットは通常少なくなります。
ありがとうございます。いただきます。

2022-07-29 13:46 UTC, tatsuo-ishii approved these changes
確認しました。対応ありがとうございます。

2022-08-03 23:38 UTC, KenichiroTanaka commented
一通り確認しましたのでマージします。

2022-08-03 23:38 UTC, merged