fdwhandler.sgmlの14.0対応です。
pgsql-jp/jpug-doc pull request #2252
Opened 2022-07-22 23:06 UTC by abejjj

fdwhandler.sgmlの14.0対応です。
申し訳ありませんが現在926行目まで（およそ３分の1程度）作業を終えておらず、残は追ってcommitしていきます。

2022-07-23 23:41 UTC, abejjj commented on doc/src/sgml/fdwhandler.sgml
>       use <function>ExecForeignInsert</function>.
ここがL945-L948と同文なのですが、削除しましょうか...?

2022-07-24 00:21 UTC, noborus commented on doc/src/sgml/fdwhandler.sgml
>       use <function>ExecForeignInsert</function>.
これは原文が重複しているので、とりあえずこのままで良いと思います。
ExecForeignBatchInsert と GetForeignModifyBatchSize それぞれの関数の注意を、両方セットされていないと使用されないということで、わざと両方に書いているのかも。

2022-07-24 16:29 UTC, abejjj commented on doc/src/sgml/fdwhandler.sgml
>       use <function>ExecForeignInsert</function>.
@noborus 
なるほど、ありがとうございます。
ではこのままに残しておきます。

2022-07-24 16:30 UTC, abejjj commented
ひとまず13verとの差分訳は完了しました。

2022-07-25 04:02 UTC, noborus commented on doc/src/sgml/fdwhandler.sgml
> +<function>ExecForeignBatchInsert</function>または<function>GetForeignModifyBatchSize</function>ポインタにNULLが設定された場合、外部テーブルには<function>ExecForeignInsert</function>を使って挿入を試みます。
NULLがliteralタグで囲まれている必要があります。` <literal>NULL</literal>`

2022-07-25 04:02 UTC, noborus commented on doc/src/sgml/fdwhandler.sgml
> +この関数は、ルーティングされたタプルを外部テーブル・パーティションに挿入するときにも呼び出されることに注意してください。
外部テーブル・パーティション は、他では「外部テーブルパーティション」としています。

2022-07-25 04:02 UTC, noborus commented on doc/src/sgml/fdwhandler.sgml
> +<function>ExecForeignBatchInsert</function>または<function>GetForeignModifyBatchSize</function>ポインタにNULLが設定された場合、外部テーブルには<function>ExecForeignInsert</function>を使って挿入を試みます。
NULLがliteralタグで囲まれている必要があります。 `<literal>NULL</literal>`

2022-07-25 15:22 UTC, abejjj commented on doc/src/sgml/fdwhandler.sgml
> +コアシステムは、テーブルの<structfield>tableoid</structfield>列、<literal>ctid</literal>または<literal>ctid<replaceable>N</replaceable></literal>にジャンク列名<literal>tableoid</literal>を使用し、
@noborus 
失礼しました、指摘いただいた次の文節も怪しかったので併せて修正しています。

2022-07-25 15:23 UTC, abejjj commented on doc/src/sgml/fdwhandler.sgml
> +<literal>slots</literal> and <literal>planSlots</literal>が複数のタプルを含むことと<literal>*numSlots</literal>がそれらの配列のタプルの数を指定すること以外は<function>ExecForeignInsert</function>とパラメータは同じです。
失礼しました、修正しました。

2022-07-25 15:23 UTC, abejjj commented on doc/src/sgml/fdwhandler.sgml
> +<function>ExecForeignBatchInsert</function>または<function>GetForeignModifyBatchSize</function>ポインタにNULLが設定された場合、外部テーブルには<function>ExecForeignInsert</function>を使って挿入を試みます。
失礼しました、修正しました。

2022-07-25 15:24 UTC, abejjj commented on doc/src/sgml/fdwhandler.sgml
> +この関数は、ルーティングされたタプルを外部テーブル・パーティションに挿入するときにも呼び出されることに注意してください。
修正しました、以後表記を合わせるようにします。

2022-07-25 15:24 UTC, abejjj commented on doc/src/sgml/fdwhandler.sgml
> +<function>ExecForeignBatchInsert</function>または<function>GetForeignModifyBatchSize</function>ポインタにNULLが設定された場合、外部テーブルには<function>ExecForeignInsert</function>を使って挿入を試みます。
こちらも同様に修正しました。

2022-07-26 01:23 UTC, noborus commented
修正ありがとうございます。確認しました。

2022-07-29 12:45 UTC, koizumistr reviewed
確認しました。

2022-07-29 12:45 UTC, koizumistr commented on doc/src/sgml/fdwhandler.sgml
> +（複数の列が必要な場合は、これを一回以上実行できます。）
1回より多いなので厳密には「2回以上」かと。

2022-07-29 12:45 UTC, koizumistr commented on doc/src/sgml/fdwhandler.sgml
> +コアシステムは、テーブルの<structfield>tableoid</structfield>列をジャンク列名<literal>tableoid</literal>に、<literal>ctid</literal>または<literal>ctid<replaceable>N</replaceable></literal>を<structfield>ctid</structfield>に使用し、
ここでは改行しないでほしいです。

2022-07-29 12:45 UTC, koizumistr commented on doc/src/sgml/fdwhandler.sgml
> +できる限りこれらの名前を再利用してください（プランナーは同一のジャンク列に対する重複したリクエストを結合します）。 もしこれらとは別の種類のジャンク列が必要なら、他のFDWとの衝突を避けるために拡張子名をプレフィックスとした名前を選ぶのが賢明かもしれません。
ここは「もし」の前で改行してほしいです。

2022-07-29 12:45 UTC, koizumistr commented on doc/src/sgml/fdwhandler.sgml
> +<structfield>vartype</structfield> = <type>RECORD</type>と記された行全体の<structname>Var</structname>である<literal>wholerow</literal>と、<structfield>vartype</structfield>を記された行全体の<structname>Var</structname>である
ここは前の行からの続きで
（コアシステムは AをA’に使用し、BをB’に使用し、）〜をwholerowに使用し、 〜をwholerowNに使用する。
ということではないでしょうか。

2022-07-29 12:45 UTC, koizumistr commented on doc/src/sgml/fdwhandler.sgml
> -
もともとあった空行を消してませんか。

2022-07-29 12:45 UTC, koizumistr commented on doc/src/sgml/fdwhandler.sgml
> +外部テーブルに一括で複数のタプルを一つ挿入します。
「一つ」は不要と思います。

2022-07-29 12:45 UTC, koizumistr commented on doc/src/sgml/fdwhandler.sgml
> +<literal>slot</literal>とは異なり、このタプルはクエリによって変更されたカラムの新しい値のみを含むので、<literal>planSlot</literal>にインデックスを付けるために外部テーブルの属性番号に依存しないようにしましょう。
クエリ -> 問い合わせ

前からのようですね。1025行のクエリも合わせて修正しておいてください。
あと、
カラム -> 列

2022-07-29 12:45 UTC, koizumistr commented on doc/src/sgml/fdwhandler.sgml
> +ただし、<structname>Var</structname>が<structfield>varno</structfield>フィールドを除いて同一である場合は、カラム名を共有することができるのでそうすべきです。
カラム名 -> 列名

2022-07-29 12:45 UTC, koizumistr commented on doc/src/sgml/fdwhandler.sgml
> +また、<literal>planSlot</literal>は通常、追加の<quote>junk</quote> カラムを含んでいます。
＜quote＞junk＜/quote＞ カラム -> ＜quote＞ジャンク＜/quote＞列

直後の文でも「ジャンク列」としているようですから。

2022-07-29 12:45 UTC, koizumistr commented on doc/src/sgml/fdwhandler.sgml
> +<literal>restart_seqs</literal>が<literal>true</literal> の場合、元の<command>TRUNCATE</command>コマンドが<literal>RESTART IDENTITY</literal>動作が要求され、それ以外の場合は<literal>CONTINUE IDENTITY</literal> 動作が要求されていたことになります
CONTINUE IDENTITY と 動作 の間の空白は不要かと。

2022-07-29 12:45 UTC, koizumistr commented on doc/src/sgml/fdwhandler.sgml
> +(これは以下で説明されるコールバック関数が決して呼ばれないことを意味します。呼ばれないことを意味するので、それらも提供される必要はありません)。
ありません）。 -> ありません。）

2022-07-31 14:30 UTC, abejjj commented
@koizumistr 
レビューありがとうございます。
指摘いただいた事項を修正しました。

クエリ -> 問い合わせ ですが、他にも残っているので一括で修正して良いでしょうか。
もし何かルールのようなものがあれば、ご教示いただけると幸いです。

2022-08-02 00:11 UTC, KenichiroTanaka requested changes
1箇所だけ気づくところがありましたので対応をお願いしてもいいでしょうか。

2022-08-05 04:25 UTC, koizumistr commented
@abejjj 
> クエリ -> 問い合わせ ですが、他にも残っているので一括で修正して良いでしょうか。

多分それは私の見落としなので一括で大丈夫でしょう。あ、「パラレルクエリ」は例外でカタカナにすることになっているようです。

> もし何かルールのようなものがあれば、ご教示いただけると幸いです。

https://github.com/pgsql-jp/taiyaku に対訳表があることはあります。が、対訳表を更新するより先に新しい言葉が出てくる感じなので、周りを見て、というのが「皆さんの普通」なのかなと思ってます。

2022-08-05 04:32 UTC, koizumistr reviewed
確認しました。対応ありがとうございます。

改行に関して改悪になってしまっているところがありますので、直してもらえれば。

2022-08-05 04:32 UTC, koizumistr commented on doc/src/sgml/fdwhandler.sgml
> +それを行うには、必要な追加の値を表す<structname>Var</structname>を作成し、それをジャンク列の名前とともに<function>add_row_identity_var</function>に渡します。（複数の列が必要な場合は、これを二回以上実行できます。）必要とするそれぞれの<structname>Var</structname>に個別のジャンク列名を選択する必要があり
改行に関しては、以前の通りでお願いします。

2022-08-12 01:50 UTC, noborus commented
修正点は明確なのでマージして別途修正でよいのでは？

修正は別の人がやっても構わないと思います。

2022-08-12 01:56 UTC, tatsuo-ishii commented
私もそう思います。

2022-08-12 04:45 UTC, KenichiroTanaka commented
そうですね。一度マージします。

2022-08-12 04:45 UTC, KenichiroTanaka approved these changes

2022-08-12 04:45 UTC, merged

2022-08-12 09:04 UTC, KenichiroTanaka commented
@abejjj さん
本件対応いただきありがとうございます。
追い込み時期になりましたので残りは私の方で対応させていただきます。