マージミスで入れる位置が間違っていた
pgsql-jp/jpug-doc pull request #2256
Opened 2022-07-26 12:41 UTC by noborus

2022-07-27 07:10 UTC, tatsuo-ishii requested changes
確認しました。

2022-07-27 07:10 UTC, tatsuo-ishii commented on doc/src/sgml/monitoring.sgml
> +パラメータ<xref linkend="guc-track-wal-io-timing"/>を有効にすると、WALの書き込み時間を監視できます。
上に合わせて、

<xref linkend="guc-track-wal-io-timing"/>パラメータは、WALの書き込み時間の監視をするかどうかの指定ができます。

などとしたほうが良いと思います。

2022-07-27 13:49 UTC, noborus commented on doc/src/sgml/monitoring.sgml
> +パラメータ<xref linkend="guc-track-wal-io-timing"/>を有効にすると、WALの書き込み時間を監視できます。
ありがとうございます。表記を統一するために見直しました。

2022-07-27 13:49 UTC, noborus commented
track_io_timing が回数となっているミスを見つけて修正しました。

2022-07-28 06:17 UTC, tatsuo-ishii approved these changes
確認しました。

2022-07-28 06:17 UTC, merged