タグが翻訳で原文と揃っていない箇所の修正３
pgsql-jp/jpug-doc pull request #2276
Opened 2022-08-14 00:02 UTC by noborus

2022-08-16 09:20 UTC, koizumistr reviewed
確認しました。

funcの方は数字付きのものにコメントしたのに、libpqは数字がない方にコメントしてしまったのは暑さのせいです。分かると思うので直しません。

2022-08-16 09:20 UTC, koizumistr commented on doc/src/sgml/func3.sgml
> +入力の最頻値、集約引数の値のうち<firstterm>最頻値</firstterm>（複数の同じ度数の結果があれば、任意に選んだ最初のもの）を計算します。
最頻値をfirsttermで囲むのはよいと思いますが、囲まない方の「最頻値」は説明調に訳すべきかと。

集約引数の＜firstterm＞最頻値＜/firstterm＞、最も頻出する値（複数の同じ度数の結果があれば、任意に選んだ最初のもの）を計算します。

あたりでしょうか。

2022-08-16 09:20 UTC, koizumistr commented on doc/src/sgml/func4.sgml
> +手続きに対して<literal>NULL</literal>を返します。
procedureはプロシージャのような、、、

2022-08-16 09:20 UTC, koizumistr commented on doc/src/sgml/json.sgml
> +<firstterm>包含演算子</firstterm>のテストは<type>jsonb</type>型の重要な機能です。これらのセットは<type>json</type>型には全くありません。
ついでに「。」の後で改行してしまっていい気がします。

2022-08-16 09:20 UTC, koizumistr commented on doc/src/sgml/libpq.sgml
> +この関数呼び出しが<symbol>CONNECTION_BAD</symbol>を返す場合、接続手続きは失敗しており、<function>CONNECTION_OK</function>を返す場合、接続が確立しています。
これ、原文に忠実ではありますが、原文がおかしくありませんか。
CONNECTION_OKはfunctionではなくsymbolなのではないかと。

2022-08-16 22:04 UTC, noborus commented on doc/src/sgml/func3.sgml
> +入力の最頻値、集約引数の値のうち<firstterm>最頻値</firstterm>（複数の同じ度数の結果があれば、任意に選んだ最初のもの）を計算します。
ありがとうございます。いただきます。

2022-08-16 22:06 UTC, noborus commented on doc/src/sgml/func4.sgml
> +手続きに対して<literal>NULL</literal>を返します。
そう思ったのですが、他が「手続き」としていたので、合わせました。
ちょっとわかりにくい気がしたので、他も含めてプロシージャに変更してみます。

2022-08-16 22:06 UTC, noborus commented on doc/src/sgml/json.sgml
> +<firstterm>包含演算子</firstterm>のテストは<type>jsonb</type>型の重要な機能です。これらのセットは<type>json</type>型には全くありません。
了解です。

2022-08-16 22:07 UTC, noborus commented on doc/src/sgml/libpq.sgml
> +この関数呼び出しが<symbol>CONNECTION_BAD</symbol>を返す場合、接続手続きは失敗しており、<function>CONNECTION_OK</function>を返す場合、接続が確立しています。
確かに。他はliteralを使用している箇所もあり、原文の問題がありそうなので、一旦元に戻しておきます。

2022-08-17 00:24 UTC, koizumistr commented
対応ありがとうございます。確認しました。


procedureを「手続き」とするのはそれはそれでありだと思うのですが、他のsgmlファイルで「手続き」が出てきているのは「手続き（型）言語」くらいっぽいのでfuncだけ「手続き」で行くというのは微妙な気がします。

2022-08-17 00:48 UTC, KenichiroTanaka commented
procedureをプロシージャにまとめて変換する方針に賛成です。本PRはマージします。

2022-08-17 00:52 UTC, KenichiroTanaka commented
入れ違いになりました。procedureの扱いはまだ方針が定まってないですかね。

2022-08-17 05:18 UTC, koizumistr commented
> procedureの扱いはまだ方針が定まってないですかね。

すみません。余計なことを書いて混乱させてしまったでしょうか。
> procedureをプロシージャにまとめて変換する

に反対したつもりはなくて、
（funcに特別な事情があるのでなければ）（このドキュメント内の）他の部分と合わせて（手続きではなく）プロシージャにすべきでは、
のつもりでした。

2022-08-17 22:38 UTC, KenichiroTanaka commented
詳しい説明ありがとうございました。上記承知しました。

2022-08-17 23:09 UTC, KenichiroTanaka approved these changes
一通り確認しました。

2022-08-18 00:05 UTC, KenichiroTanaka requested changes
一旦Approveしましたが、見直すと１箇所だけ気づくところがありましたので見ていただいてもいいでしょうか。

2022-08-18 07:43 UTC, noborus commented on doc/src/sgml/json.sgml
> +これらのセットは<type>json</type>型には全くありません。
ありがとうございます。これは意訳が入りすぎてたのかもしれません。

2022-08-18 07:44 UTC, noborus commented
コミットの方に書きましたが、ご指摘を受けて、さらに追加で修正しました。

no parallel set of を原文に近づけて翻訳。
値ではなくjsonbを指定するのでドキュメントに変更。
テストを検査に変更（func.sgmlで同様の関数を検査としているため）。

2022-08-19 12:57 UTC, KenichiroTanaka approved these changes
対応ありがとうございました。
テスト→検査への修正も問題ないと思います。

2022-08-19 12:58 UTC, KenichiroTanaka commented
複数名のレビュー済みですのでマージします。

2022-08-19 12:58 UTC, merged