テンプレートの更新
pgsql-jp/jpug-doc pull request #2297
Opened 2022-08-21 02:00 UTC by noborus

テンプレートを新しい形式にします。

2022-08-21 23:15 UTC, KenichiroTanaka requested changes
テンプレートの修正案ありがとうございます。
少し気づいた点がありますのでご意見をいただけないでしょうか。

2022-08-21 23:15 UTC, KenichiroTanaka commented on .github/ISSUE_TEMPLATE/bug_report.md
> +貢献者として記載する表記名を書いてください。
ありがとうございます。この記載があると、助かります。
ただ、毎回記載するのは大変ですので、
「各バージョンで最初の報告時のみ」という但し書きがあるとどうでしょうか。

```
各バージョンの翻訳ごと(概ね新バージョンが出てから1年)に最初の報告時は貢献者として記載する表記名を書いてください。
```

というようなイメージです。

2022-08-21 23:15 UTC, KenichiroTanaka commented on .github/ISSUE_TEMPLATE/feature_request.md
> +name: 機能リクエスト
これは、マニュアルとしてのほしい機能のことかと思います。
「PostgreSQLにこんな機能を追加してほしい」というISSUESが上がらないような表記の方が良いように思います。
```
マニュアルに追加してほしい機能のリクエスト
```
くらいの表記でどうでしょうか。

2022-08-22 03:38 UTC, koizumistr commented on .github/ISSUE_TEMPLATE/bug_report.md
> +貢献者として記載する表記名を書いてください。
マニュアルの該当ページにリンクを張って、具体例を提示してもいいかと思いました。

2022-08-22 11:03 UTC, noborus commented on .github/ISSUE_TEMPLATE/feature_request.md
> +name: 機能リクエスト
入れるのはここじゃない方が良いと思います。

2022-09-06 22:30 UTC, KenichiroTanaka commented
2298をマージしたのでこちらはクローズします。

2022-09-06 22:30 UTC, closed without merging