update release-14.sgml for 14.5
pgsql-jp/jpug-doc pull request #2303
Opened 2022-08-30 04:59 UTC by kitayama

release-14.sgml の 14.5 対応版です。表現の不統一があったり原文にないプラスアルファなどがありますが、一旦プルリクエストさせてください。

2022-09-08 13:44 UTC, KenichiroTanaka requested changes
14.5を見ましたので一度ここでChangeRequestします。
14.4を続いて見ていきます。

2022-09-08 13:44 UTC, KenichiroTanaka commented on doc/src/sgml/release-14.sgml
> +これに伴って、pg_stat_statements.maxの最大値が2147483647から1073741823に変更されました。
これに伴って〜以下原文にはないようです。

2022-09-08 13:44 UTC, KenichiroTanaka commented on doc/src/sgml/release-14.sgml
> +<filename>contrib/postgres_fdw</filename>が<type>regconfig</type>およびその他の<type>reg*</type>タイプの定数を適切なスキーマpg_catalog修飾で送信するようになりました。
pg_catalog　は何か誤って入った感じでしょうか。

2022-09-08 13:44 UTC, KenichiroTanaka commented on doc/src/sgml/release-14.sgml
> +これにより、シグナルが<function>posix_fallocate()</function>に割り込むときのバスエラー(SIGBUS)が回避されます。
ここも原文にはない情報が入ってきているようです。

2022-09-08 13:44 UTC, KenichiroTanaka commented on doc/src/sgml/release-14.sgml
> +オープンソースのUnix系OS<productname>illumos</productname>では<function>signalfd()</function>を使用しないようになりました。
ここも原文にはない情報が入っているようです。

2022-09-10 14:42 UTC, koizumistr reviewed
下から見ていますが、6000行目くらいで力尽きましたので、いったん終了です。

2022-09-10 14:42 UTC, koizumistr commented on doc/src/sgml/release-14.sgml
> +また、Africa/Accra、America/Atikokan、America/Blanc-Sablon、America/Creston、America/Curacao、America/Nassau、America/Port_of_Spain、Antarctica/DumontDUrville、Antarctica/Syowa の各ゾーンは、近くのより人口の多いゾーンに統合されました。
whose clocks have agreed with them since 1970 に対応する訳がないようです。

どうでもいいことですが、最後のは南極昭和基地ですよね。

2022-09-10 14:42 UTC, koizumistr commented on doc/src/sgml/release-14.sgml
> +これまでWindowsで利用していたマッピングテーブルは何年も前に生成され、更新も散発的にしか行われないため、エラーが含まれていたり、最近追加されたゾーンが存在していなかったりと問題がありました。
a number of errors なので 単なるエラーではなく「数多くの」エラーではないでしょうか。
忖度したのかもしれませんが。

2022-09-10 14:42 UTC, koizumistr commented on doc/src/sgml/release-14.sgml
> +これによりインストールされていないプログラムを検出できるようになりました。
such as custom test drivers. に対応する訳がないようです。

2022-09-10 14:42 UTC, koizumistr commented on doc/src/sgml/release-14.sgml
> +内部実装の関数<function>GetSharedSecurityLabel()</function>が、クリティカルなリレーションキャッシュエントリがまだ構築されていない新たに開始したセッションでも使用できるようになりました。
内部実装の関数 は原文にないですが意図的に補ったものでしょうか。

2022-09-10 14:42 UTC, koizumistr commented on doc/src/sgml/release-14.sgml
> +Wondws 64 では2GB以上のファイルを一度に読み込もうとするとすると失敗する可能性があるため、複数回に分けて読み込むようになりました。
なんかいろいろあるのですが、、、、

そのように大きな問い合わせテキストファイルは非常にまれですが、もし発生した場合、以前のコードは（一度に2GB以上の読み込みを拒否しますので）Windows 64［多分64ビット版Windowsってことですよね］では失敗していたでしょう。

2022-09-10 14:42 UTC, koizumistr commented on doc/src/sgml/release-14.sgml
> +<filename>contrib/pg_stat_statements</filename>が最大1GB単位で<quote>クエリテキスト</quote>ファイルを読み込むようになりました。
quote内ですが、「問い合わせテキスト」かと。

2022-09-10 14:42 UTC, koizumistr commented on doc/src/sgml/release-14.sgml
> +<application>pg_dump</application>が子のパーティションのいずれかをロックすれば、パーティションテーブル自体に対する重要なDDLを防ぐのに十分であるためこの見落としはたいていの場合は無害なものでしたが、関連するロックが保持されないため、子のないパーティションテーブルをダンプするときに問題が発生する可能性がありました。
子のパーティション
厳密にはleafですから孫とかひ孫とかの可能性もあるかと、、、

あと、できれば原文同様2つの文に分けてもらえると誤解しないので助かります。

2022-09-10 14:42 UTC, koizumistr commented on doc/src/sgml/release-14.sgml
> +<command>RETURN QUERY</command>は、<command>UPDATE RETURNING</command>のようにタプルを返すことができる 任意のクエリを受け入れるべきです。
「任意」の直前に余分な空白があります。

2022-09-10 14:42 UTC, koizumistr commented on doc/src/sgml/release-14.sgml
> +さらに、可変の<command>RETURN QUERY EXECUTE</command>では、クエリ型チェックがまったく適用されていませんでした。
variantなので「可変」ではなく「変異体」（ちょっと違うけど似たようなもの）ですよね。（変異体よりより適切な訳がありそうですが、、、）

2022-09-10 14:42 UTC, koizumistr commented on doc/src/sgml/release-14.sgml
> +認証処理で使われるHMACハッシュ計算におけるメモリリークが修正されました。
認証処理で使われる は原文にありません。
（「認証処理で使われる」のはその通りだと思いますが、、、）
意図的に補ったものでしょうか。

2022-09-10 14:42 UTC, koizumistr commented on doc/src/sgml/release-14.sgml
> +アサートを無効にした実運用むけビルドにおいては、このような場合、いくらか非効率的ですが間違ってはいないインデックスになります。
アサートを無効にした は原文にはありません。
（production buildではアサートは無効になるのはその通りだと思いますが、、、）
意図的に補ったものでしょうか。

2022-09-10 14:42 UTC, koizumistr commented on doc/src/sgml/release-14.sgml
> +B-tree のポスティングリスト分割に関する防御的な検査が追加されました。
細かいかもしれませんが
防御的 -> より防御的

2022-09-20 02:45 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +通常、PostgreSQL のテーブルスペースは、他のファイルシステム上のディレクトリへのシンボリックリンクですが、この変更により、データベースクラスタディレクトリ内の単なるディレクトリにすることができます。
PostgreSQLの後の空白を削除しました。

2022-09-20 02:45 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +CVE-2022-1552むけの修正により、<command>CREATE INDEX</command>が演算子クラスや その他のオブジェクトの検索を実行する際に、以前は呼び出しユーザのパーミッションを適用していたところで、テーブル所有者のパーミッションを適用するようになっていました。
空白を削除しました。

2022-09-20 02:46 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +本修正で問題を回避するように調整されました。
原文にはない文を削除しました。

2022-09-20 02:48 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +これにより、AIX での libc メモリリークが軽減され、あらゆる場所でパフォーマンスが向上する可能性があります。
英語の前後の空白が削除できていなくてすみません。空白を削除しました。

2022-09-20 02:49 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +これに伴って、pg_stat_statements.maxの最大値が2147483647から1073741823に変更されました。
該当文を削除しました。

2022-09-20 02:50 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +<filename>contrib/postgres_fdw</filename>が<type>regconfig</type>およびその他の<type>reg*</type>タイプの定数を適切なスキーマpg_catalog修飾で送信するようになりました。
削除しました。

2022-09-20 02:52 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +これにより、シグナルが<function>posix_fallocate()</function>に割り込むときのバスエラー(SIGBUS)が回避されます。
原文通りに修正しました。

2022-09-20 02:53 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +オープンソースのUnix系OS<productname>illumos</productname>では<function>signalfd()</function>を使用しないようになりました。
原文通りに修正しました。

2022-09-20 03:11 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +これまでWindowsで利用していたマッピングテーブルは何年も前に生成され、更新も散発的にしか行われないため、エラーが含まれていたり、最近追加されたゾーンが存在していなかったりと問題がありました。
「数多くの」エラーとしました。

2022-09-20 03:13 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +これによりインストールされていないプログラムを検出できるようになりました。
訳を追加しました。

2022-09-20 03:15 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +内部実装の関数<function>GetSharedSecurityLabel()</function>が、クリティカルなリレーションキャッシュエントリがまだ構築されていない新たに開始したセッションでも使用できるようになりました。
意図的に補ったものなので、原文通りとするために削除しました。

2022-09-20 03:18 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +Wondws 64 では2GB以上のファイルを一度に読み込もうとするとすると失敗する可能性があるため、複数回に分けて読み込むようになりました。
ほぼいただいた訳案で原文通りの訳に修正しました。

2022-09-20 03:19 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +<filename>contrib/pg_stat_statements</filename>が最大1GB単位で<quote>クエリテキスト</quote>ファイルを読み込むようになりました。
修正しました。

2022-09-20 03:23 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +<application>pg_dump</application>が子のパーティションのいずれかをロックすれば、パーティションテーブル自体に対する重要なDDLを防ぐのに十分であるためこの見落としはたいていの場合は無害なものでしたが、関連するロックが保持されないため、子のないパーティションテーブルをダンプするときに問題が発生する可能性がありました。
leaf partitionはリーフパーティションに変更しました。
また原文通りに2つの分に分けました。

2022-09-20 03:23 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +<command>RETURN QUERY</command>は、<command>UPDATE RETURNING</command>のようにタプルを返すことができる 任意のクエリを受け入れるべきです。
空白を削除しました。

2022-09-20 03:30 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +さらに、可変の<command>RETURN QUERY EXECUTE</command>では、クエリ型チェックがまったく適用されていませんでした。
variantは「変異体」だと生物学的な感じがしますので言語学的な「異形」に修正しました。

2022-09-20 03:30 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +認証処理で使われるHMACハッシュ計算におけるメモリリークが修正されました。
意図的に補った箇所を削除して原文通りとしました。

2022-09-20 03:31 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +アサートを無効にした実運用むけビルドにおいては、このような場合、いくらか非効率的ですが間違ってはいないインデックスになります。
意図的に補った箇所を削除して原文通りとしました。

2022-09-20 03:32 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +B-tree のポスティングリスト分割に関する防御的な検査が追加されました。
御指摘通りに追記修正しました。

2022-09-20 06:08 UTC, noborus commented on doc/src/sgml/release-14.sgml
> +(CVE-2021-23222)
これは、CVE-2021-23214のサーバ側脆弱性と組み合わせて可能となります。

でしょうか。

2022-09-20 06:08 UTC, noborus commented on doc/src/sgml/release-14.sgml
> +プランナで<literal>GROUPING</literal>関数で参照されている副問い合わせをプルアップする（上位の問い合わせに統合する）ときに、<quote>variable not found in subplan target list</quote>が生じる問題が修正されました。
`sub-<literal>SELECT</literal>` なので`副<literal>問い合わせ</literal>`または`副<literal>SELECT</literal>`にしてもらえると助かります（この後も何回か出てくる箇所も）。

2022-09-20 08:22 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +(CVE-2021-23222)
御指摘通り修正しました。

2022-09-20 08:23 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +プランナで<literal>GROUPING</literal>関数で参照されている副問い合わせをプルアップする（上位の問い合わせに統合する）ときに、<quote>variable not found in subplan target list</quote>が生じる問題が修正されました。
他の箇所を確認したところ、ご提示いただいた表現がなかったので、そのままの表現sub-<literal>SELECT</literal>で統一しました。

2022-09-22 06:26 UTC, noborus reviewed
前からですが、9682行の後ぐらいに
> A <option>-&#045tablespace</option>

となっている箇所があります。`&#045;`に直してもらえると助かります。

2022-09-22 06:26 UTC, noborus commented on doc/src/sgml/release-14.sgml
この後のChanges（変更点）が未翻訳です。

2022-09-22 06:51 UTC, kitayama commented on doc/src/sgml/release-14.sgml
>          Enhance logical decoding APIs to handle two-phase commits (Ajin
マッチ度を削除し、andも削除しました。

2022-09-22 06:51 UTC, kitayama commented on doc/src/sgml/release-14.sgml
レビューありがとうございます。どちらも修正しました。

2022-09-23 00:13 UTC, noborus commented on doc/src/sgml/release-14.sgml
>          Enhance logical decoding APIs to handle two-phase commits (Ajin
ありがとうございます。確認しました。

2022-09-23 01:25 UTC, noborus commented on doc/src/sgml/release-14.sgml
> +このバグにより、正しいデータに対しても<quote>invalid byte sequence for encoding "UTF8": 0xe5</quote>などの入力データが不正であるという偽性のエラーが生じる可能性がありました。
`<quote>` の部分は原文に無いようです。

2022-09-23 01:25 UTC, noborus commented on doc/src/sgml/release-14.sgml
> +短い説明はSHOW ALLのdescriptionなどに表示されるもので、以前は、拡張でここにNULLを指定していると表示処理がクラッシュしていました。
ここはちょっと原文に対して訳が合ってません。

2022-09-23 01:25 UTC, noborus commented on doc/src/sgml/release-14.sgml
> +以前のマイナーリリースで、サーバでのSSL秘密鍵のアクセス権チェック方式を<application>libpq</application>にも適用しましたが、所有者チェックまで同様に行うべきではありませんでした。
こっちに`application`タグは無いですが...これは原文側のミスのような気がするので、このままで良いかもしれません。

2022-09-23 01:25 UTC, noborus commented on doc/src/sgml/release-14.sgml
> +<command>ALTER TABLE</command>でテーブルのシステム列を変更しようとすると、間違ったエラーが発生する問題が修正されました。
`<command>ALTER TABLE</command>で`は原文にありません。

2022-09-23 01:25 UTC, noborus commented on doc/src/sgml/release-14.sgml
> -     </para>
細かいですが、たぶん`</para>`と改行の間にスペースを入れたため差分が発生しています。

2022-09-23 01:25 UTC, noborus commented on doc/src/sgml/release-14.sgml
> +   <title>バージョン14.3への移行</title>
間に空行が入っているのを訳の`</title>`の後にしてもらえると助かります。
```
<!--
   <title>Migration to Version 14.3</title>
-->
   <title>バージョン14.3への移行</title>

```

2022-09-23 02:16 UTC, KenichiroTanaka reviewed
途中ですが、斉藤さんも見ていただいているようなので取り急ぎSubmit reviewします。

2022-09-26 06:50 UTC, kitayama commented on doc/src/sgml/release-14.sgml
追記しました。

2022-09-26 06:50 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +14より前のバージョンは、2つ以上の<literal>.</literal>(ドット)を含むパターンにおけるスキーマとテーブル以外の全ての修飾名を黙って無視していました。
追記しました。

2022-09-26 06:50 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +同時に<command>DROP STATISTICS</command>で統計オブジェクトが削除された時に発生する<command>ALTER STATISTICS</command>でのNULLポインタ参照によるクラッシュが回避されました。
削除しました。

2022-09-26 06:50 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +<productname>PostgreSQL</productname>ビルド中に複数の<productname>OpenLDAP</productname>がインストールされている場合に、古い<application>libldap_r</application>ライブラリを誤って使用しないように<application>configure</application>が修正されました。
削除しました。

2022-09-26 06:50 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +最初から<type>ltree</type>をバージョン1.2 にアップグレードしている場合を除き、このようなインデックスに何らか操作が行われた場合、シグネチャ長が8バイトではなく28バイトと見做されて動作します。
修正しました。

2022-09-26 06:50 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +非決定的な等価関数に対してMemorizeプランノードが堅牢になりました。
修正しました。

2022-09-26 06:50 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +データ型の等価関数またはハッシュ関数が各呼び出しで一貫性に欠ける結果を返す場合に、Memorizeがクラッシュを起こす可能性がありました。
修正しました。

2022-09-26 06:50 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +Memorizeプランの誤ったコスト見積もりが修正されました。
修正しました。

2022-09-26 06:50 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +この誤りにより、それが最善でない場合でも Memorize が使われたり、Memorizeノードにおける巨大なハッシュ表の初期化のためにエグゼキュータの起動時間が非常に長くなったりしました。
修正しました。

2022-09-26 06:50 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +このバグにより、正しいデータに対しても<quote>invalid byte sequence for encoding "UTF8": 0xe5</quote>などの入力データが不正であるという偽性のエラーが生じる可能性がありました。
該当箇所を削除し、修正しました。

2022-09-26 06:50 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +以前のマイナーリリースで、サーバでのSSL秘密鍵のアクセス権チェック方式を<application>libpq</application>にも適用しましたが、所有者チェックまで同様に行うべきではありませんでした。
このままにしています。

2022-09-26 06:50 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +非同期リモートクエリをサポートするために最近追加されたコードは、このケースを処理できず、クラッシュや<quote>unrecognized node type ..</quote>などの認識されないノードタイプに関するエラーが引き起こされました。
削除しました。

2022-09-26 06:50 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +<command>ALTER TABLE</command>でテーブルのシステム列を変更しようとすると、間違ったエラーが発生する問題が修正されました。
削除しました。

2022-09-26 06:50 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> -     </para>
スペースを削除しました。

2022-09-26 06:51 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +<filename>contrib/pg_stat_statements</filename>が32ビットプラットフォームでの数ギガバイトのクエリテキストファイルの整数オーバフローの問題を回避するように修正されました。
修正しました。

2022-09-26 06:51 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +これからは、そのような場合にエラー<quote>could not find memoization table entry</quote>が出るようになります。
当初は有用な情報と思うのは残していました(弊社ブログでの有用と思われる改変)が、原文に無い情報は削除(原文に忠実に翻訳)する方針で進めているので、こちらも原文通りに削除、修正しました。

2022-09-26 06:51 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +キープアライブメッセージを定期的に送信することで修正されました。
追記しました。

2022-09-26 08:03 UTC, noborus approved these changes
修正ありがとうございます。確認しました。

2022-09-29 04:57 UTC, koizumistr reviewed
1000行くらいまで見たのでいったん提出。

2022-09-29 04:57 UTC, koizumistr commented on doc/src/sgml/release-14.sgml
> +スタンバイサーバでの<command>CREATE DATABASE</command>WALレコードのリプレイが修正されました。
ここはDATABASEとWALの間に空白を入れなくて大丈夫でしょうか。
DATABASEWAL となってしまいそうですが、、

2022-09-29 04:57 UTC, koizumistr commented on doc/src/sgml/release-14.sgml
> +しかしながら、32Kを超える列を持ったクエリによってアサート失敗またはクラッシュが発生する以前のコードが一部ありました。
クエリ -> 問い合わせ

2022-09-29 04:57 UTC, koizumistr commented on doc/src/sgml/release-14.sgml
> +ビューが作られて複合タイプの列がドロップされた場合、複合タイプを返す<literal>FROM</literal>の中の関数を使っているビューのダンプが修正されました。
複合タイプ -> 複合型

2022-09-29 04:57 UTC, koizumistr commented on doc/src/sgml/release-14.sgml
> +論理レプリケーションのパブリッシャーのスキーマを変更した後、サブスクライバでキャッシュされたスキーマデータ更新に失敗する障害が修正されました。
パブリッシャー は パブリッシャ （伸ばさない）では、と思ったのですが、何も確認せずに書いてます。多数派に合わせてもらえれば。

2022-09-29 04:57 UTC, koizumistr commented on doc/src/sgml/release-14.sgml
> +このために、手続き言語が<command>COMMIT</command>を発行したが（例えば遅延制約検査などで）エラーが起きてしまった場合に誤動作を招きます。
手続き言語が -> 手続き言語のプロシージャが
でしょうか。

2022-09-29 04:57 UTC, koizumistr commented on doc/src/sgml/release-14.sgml
> +この変更を透過的にするため、<function>SPI_start_transaction()</function>をno-op（何もしない動作）に再定義しました。
この変更をAPIの観点からある程度透過的に
あたりでしょうか。

2022-09-29 04:57 UTC, koizumistr commented on doc/src/sgml/release-14.sgml
> +クエリごとにロケールオブジェクトを作成して解放するのではなく、最初の接続時にプロセスごとにCロケールオブジェクトを割り当てます。
クエリ -> 問い合わせ

2022-09-29 04:57 UTC, koizumistr commented on doc/src/sgml/release-14.sgml
> +これにより、AIXでのlibcメモリリークが軽減され、あらゆる場所でパフォーマンスが向上する可能性があります。
このeverywhereは（AIXに限らない）あらゆるプラットフォームという意味ではないかと。

2022-09-29 06:40 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +これにより、AIXでのlibcメモリリークが軽減され、あらゆる場所でパフォーマンスが向上する可能性があります。
修正しました(たんなる場所ではないですね)。

2022-09-29 06:40 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +このために、手続き言語が<command>COMMIT</command>を発行したが（例えば遅延制約検査などで）エラーが起きてしまった場合に誤動作を招きます。
修正しました。

2022-09-29 06:40 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +論理レプリケーションのパブリッシャーのスキーマを変更した後、サブスクライバでキャッシュされたスキーマデータ更新に失敗する障害が修正されました。
ざっと他を見たところ「パブリッシャー」が多数だったのでそのままにします。

2022-09-29 06:40 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +ビューが作られて複合タイプの列がドロップされた場合、複合タイプを返す<literal>FROM</literal>の中の関数を使っているビューのダンプが修正されました。
修正しました。

2022-09-29 06:40 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +しかしながら、32Kを超える列を持ったクエリによってアサート失敗またはクラッシュが発生する以前のコードが一部ありました。
修正しました。

2022-09-29 06:41 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +スタンバイサーバでの<command>CREATE DATABASE</command>WALレコードのリプレイが修正されました。
間に「の」を入れて、後ろの「の」を削除しました(「の」が連続するので）。

2022-09-29 13:17 UTC, KenichiroTanaka requested changes
追加で１箇所気づいたのでコメントしました。見ていただいてもいいでしょうか。

2022-10-03 01:52 UTC, kitayama commented
田中さんの指摘事項を反映しました。

2022-10-03 03:50 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。

2022-10-03 03:59 UTC, KenichiroTanaka commented
@noborus さん
@koizumistr  さん
そろそろマージを考えていますが、レビューが途中だったりする箇所あるでしょうか？

2022-10-03 04:02 UTC, noborus commented
> @noborus さん @koizumistr さん そろそろマージを考えていますが、レビューが途中だったりする箇所あるでしょうか？

いえ、良いと思います。

2022-10-03 13:30 UTC, koizumistr commented on doc/src/sgml/release-14.sgml
> +
余分な空行が、、、

2022-10-03 13:32 UTC, koizumistr commented on doc/src/sgml/release-14.sgml
> +また、 checkpointerプロセスが既に終了している場合にループが終了しない可能性があるためpostmasterプロセスの終了を監視する必要があります。
checkpointerの前に余分なスペースがあるようです。

2022-10-03 13:34 UTC, koizumistr commented on doc/src/sgml/release-14.sgml
> +サポートされているプラットフォームで該当する唯一のものはCygwinで、 バックエンドプロセスのクラッシュが報告されました。
バックエンドプロセス の直前に余分なスペースがあるようです。

2022-10-03 13:34 UTC, koizumistr commented on doc/src/sgml/release-14.sgml
> +タイマ割り込みの見逃しに対して、より頑健になりました。
サーバがより頑健になりました。

2022-10-03 13:44 UTC, koizumistr commented on doc/src/sgml/release-14.sgml
> +マルチ範囲型データから範囲を抽出する際に、アライメントのパディングが正しく処理されるようになりました。
これ、たしかマルチではない方に揃えたのだと思います。

2022-10-03 13:46 UTC, koizumistr commented on doc/src/sgml/release-14.sgml
> +<type>anicompatible</type>で始まる名前の疑似データ型の多相パラメータを持つ関数や演算子が、実際には本当は一致しないはずの引数の集合に一致したとパーサが誤判断することがありました。
anicompatible -> anycompatible

2022-10-03 13:50 UTC, koizumistr commented on doc/src/sgml/release-14.sgml
> +その結果、xmin の限界値の前進が抑えられることで、バキュームのクリーンアップが遅れるなどの望ましくない影響がありました。
xminの直後に余分なスペースがあります。

2022-10-03 13:51 UTC, koizumistr commented on doc/src/sgml/release-14.sgml
> +認証方式が <literal>cert</literal>の場合、<literal>clientcert=verify-full</literal>が暗黙的に指定されますが、<structname>pg_hba_file_rules</structname>ビューは誤って<literal>clientcert=verify-ca</literal>と報告していました。
「認証方式が」の直後に余分なスペースがあります。

2022-10-03 13:54 UTC, koizumistr commented on doc/src/sgml/release-14.sgml
> +<application>psql</application>の <command>\password</command>コマンドで設定するパスワードは、接続元のユーザのものではなく、<literal>CURRENT_USER</literal>のものがデフォルトとなりました。
＜command＞\password＜/command＞の直前に余分なスペースがあります。

2022-10-04 01:08 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +
削除しました。

2022-10-04 01:08 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +また、 checkpointerプロセスが既に終了している場合にループが終了しない可能性があるためpostmasterプロセスの終了を監視する必要があります。
削除しました。

2022-10-04 01:09 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +サポートされているプラットフォームで該当する唯一のものはCygwinで、 バックエンドプロセスのクラッシュが報告されました。
削除しました。

2022-10-04 01:12 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +タイマ割り込みの見逃しに対して、より頑健になりました。
追記しました。

2022-10-04 01:12 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +マルチ範囲型データから範囲を抽出する際に、アライメントのパディングが正しく処理されるようになりました。
多重に変更しました。

2022-10-04 01:13 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +<type>anicompatible</type>で始まる名前の疑似データ型の多相パラメータを持つ関数や演算子が、実際には本当は一致しないはずの引数の集合に一致したとパーサが誤判断することがありました。
修正しました。

2022-10-04 01:13 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +その結果、xmin の限界値の前進が抑えられることで、バキュームのクリーンアップが遅れるなどの望ましくない影響がありました。
削除しました。

2022-10-04 01:13 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +認証方式が <literal>cert</literal>の場合、<literal>clientcert=verify-full</literal>が暗黙的に指定されますが、<structname>pg_hba_file_rules</structname>ビューは誤って<literal>clientcert=verify-ca</literal>と報告していました。
削除しました。

2022-10-04 01:14 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +<application>psql</application>の <command>\password</command>コマンドで設定するパスワードは、接続元のユーザのものではなく、<literal>CURRENT_USER</literal>のものがデフォルトとなりました。
削除しました。

2022-10-04 01:14 UTC, kitayama commented on doc/src/sgml/release-14.sgml
> +これは、<application>psql</application>の <command>\copy</command>コマンド、または<application>pg_recvlogical</application>で<option>-f -</option>を付けた場合に影響がありました。
削除しました。

2022-10-04 01:23 UTC, koizumistr commented
対応ありがとうございます。確認しました。

@KenichiroTanaka さん、小泉としては完了です。

2022-10-04 21:55 UTC, KenichiroTanaka commented
@noborus さん
@koizumistr さん
レビューありがとうございました。

@kitayama とても大きなファイルとレビューの確認はとても大変だったと思いますが、対応ありがとうございました。

ここでマージしたいと思います。

2022-10-04 21:56 UTC, merged