update psql-ref for 14.5
pgsql-jp/jpug-doc pull request #2306
Opened 2022-08-30 10:41 UTC by koizumistr

ref/psql-ref.sgml の１４．５対応です。

2022-09-02 22:41 UTC, KenichiroTanaka requested changes
少し気づくところがありましたので見ていただいてもいいでしょうか。

2022-09-02 22:41 UTC, KenichiroTanaka commented on doc/src/sgml/ref/psql-ref.sgml
> +ここでも、二重引用符で括られた文字列内のドットは特別な意味を失い、文字そのものにマッチすることになります。
```
A relation pattern that contains two dots (<literal>.</literal>)
   is interpreted as a database name followed by a schema name pattern followed
   by an object name pattern. 
```
の訳文が抜けているようです。

2022-09-02 22:41 UTC, KenichiroTanaka commented on doc/src/sgml/ref/psql-ref.sgml
> +拡張統計情報の各種の状態は、その統計の種類(例えば、Ndistinct)にちなんだ名前の列に表示されます。
細かいですが、doc/src/sgml/perform.sgmlにある変更点をレビューする中で「statistics」と「statistic」は使い分けられているように思いました。
https://github.com/pgsql-jp/jpug-doc/pull/2304/files

「その統計」→「その統計値」とするのはどうでしょうか。

2022-09-04 02:29 UTC, koizumistr commented on doc/src/sgml/ref/psql-ref.sgml
> +拡張統計情報の各種の状態は、その統計の種類(例えば、Ndistinct)にちなんだ名前の列に表示されます。
なんかとってもいい感じですね、採用します。

2022-09-04 02:32 UTC, koizumistr commented
確認ありがとうございます。対応しました。

2022-09-06 22:33 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。
マージします。

2022-09-06 22:33 UTC, merged