func.sgmlのPostgreSQL 14.5対応です。
pgsql-jp/jpug-doc pull request #2323
Opened 2022-09-05 23:28 UTC by tatsuo-ishii

2022-09-08 14:47 UTC, noborus reviewed
マッチ度の箇所で削除漏れがありました。

2022-09-08 14:47 UTC, noborus commented on doc/src/sgml/func1.sgml
>    </para>
マッチ度[70.747218] の箇所が削除漏れです。

2022-09-08 23:55 UTC, tatsuo-ishii commented
「マッチ度」コメントは翻訳の際には削除する、ということをどこかに書いておいたほうが良いような。

2022-09-12 00:19 UTC, KenichiroTanaka requested changes
1箇所気づくところがありましたのでご確認をよろしくお願いします。

2022-09-12 00:19 UTC, KenichiroTanaka commented on doc/src/sgml/func.sgml
>  7つのすべての幾何型、<type>point</type>と他のすべての幾何型との組み合わせ、そして次の型の組み合わせで利用できます。
変更になった以下の部分が変更されていないようです。
```
        Available for all geometric types except <type>polygon</type>,
        for all combinations
```

2022-09-12 04:38 UTC, tatsuo-ishii commented on doc/src/sgml/func.sgml
>  7つのすべての幾何型、<type>point</type>と他のすべての幾何型との組み合わせ、そして次の型の組み合わせで利用できます。
ご指摘ありがとうございます。修正します。

2022-09-12 08:36 UTC, KenichiroTanaka approved these changes
ご対応ありがとうございます。変更いただいた内容を確認しました。

2022-09-12 08:36 UTC, merged