split sentences in textsearch
pgsql-jp/jpug-doc pull request #2340
Opened 2022-09-09 12:40 UTC by koizumistr

textsearch.sgml で文末で改行するようにしました。

それ以外にも少しやってますので、その場所には直接コメントを書きます。

2022-09-09 12:41 UTC, koizumistr commented on doc/src/sgml/textsearch.sgml
> -テキスト検索という目的のため、各々の文書は前処理されて<type>tsvector</type>形式に変換しておかなければなりません。検索と順位付けはすべて<type>tsvector</type>表現の文書上で行われます。検索とランキングは文書の<type>tsvector</type>表現上で実行されます &mdash; オリジナル文書は、ユーザに表示のため選択された場合にのみ取り出される必
検索と順位付けは という文と 検索とランキングは という文が重複していましたので、前者を削除しました。

2022-09-09 12:42 UTC, koizumistr commented on doc/src/sgml/textsearch.sgml
> -テキスト検索パーサは、もとの文書テキストを分割して<firstterm>トークン</firstterm>に変換し、それぞれのトークンの型を識別子する役割を持っています。ここで、可能な型の集合は、パーサ自身が定義します。パーサは文書をまったく変更しないことに注意してください &mdash; それは、単に可能な単語の境界を識別するだけです。このような制限があるため、カスタム辞書を作るのに比べ、用途限
識別子 -> 識別

2022-09-09 12:44 UTC, koizumistr commented on doc/src/sgml/textsearch.sgml
> -この形式の<function>ts_rewrite</function>は、開始<replaceable>問い合わせ</replaceable>と、テキスト文字列で与えられるSQLの<replaceable>SELECT</replaceable>コマンドを受け取ります。<replaceable>SELECT</replaceable>は、<type>tsquery</type>型の2つの列を出
＜replaceable＞で囲まれたものは、直前の関数の引数のことを指しているはずですので、英語に戻しました/原文と同じ形にしました。

2022-09-14 23:04 UTC, KenichiroTanaka requested changes
前からのところで申し訳ないのですが1箇所気づいてしまいましたので修正をお願いしてしまってもいいでしょうか。文体のところです。

2022-09-15 10:44 UTC, koizumistr commented
確認ありがとうございます。「など。」で検索したらもう一ヶ所見つけてしまったので、そこも合わせて直しています。

2022-09-15 13:24 UTC, KenichiroTanaka approved these changes
他の箇所の修正もありがとうございます。
確認しました。

2022-09-15 13:24 UTC, merged