plpgsql.sgmlを再修正
pgsql-jp/jpug-doc pull request #2343
Opened 2022-09-12 00:51 UTC by noborus

余分な改行が含まれてしまうので、CDATAの終わり部分を元に戻す。
追加で以下を修正。
* typo
* タグ不足

2022-09-15 13:44 UTC, KenichiroTanaka requested changes
少し気づくところがありましたので見ていただいてもいいでしょうか。

2022-09-15 13:44 UTC, KenichiroTanaka commented on doc/src/sgml/plpgsql.sgml
> +各<replaceable>item</replaceable>は、指定された<replaceable>変数</replaceable>（これは受け取るために正しいデータ型でなければなりません）に代入される状態値を識別するキーワードです。
ここはタグがreplaceableなのでvariableのままがいいでしょうか。

2022-09-15 13:44 UTC, KenichiroTanaka commented on doc/src/sgml/plpgsql.sgml
> +        -- ここで"mviews"はマテリアライズドビューの1つのレコードを持ちます
以前からのところですがinformationも訳出した方がいいかもです。

「マテリアライズドビューについての情報のレコードを１つ持ちます」

などとするのはどうでしょうか。

2022-09-19 02:41 UTC, noborus commented on doc/src/sgml/plpgsql.sgml
> +各<replaceable>item</replaceable>は、指定された<replaceable>変数</replaceable>（これは受け取るために正しいデータ型でなければなりません）に代入される状態値を識別するキーワードです。
ありがとうございます。その通りです。

2022-09-19 02:41 UTC, noborus commented on doc/src/sgml/plpgsql.sgml
> +        -- ここで"mviews"はマテリアライズドビューの1つのレコードを持ちます
ありがとうございます。修正します。

2022-09-20 14:04 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。一通り確認しました。

2022-09-20 14:05 UTC, merged