config.sgmlのPostgreSQL 15.0対応です。
pgsql-jp/jpug-doc pull request #2422
Opened 2022-10-16 09:02 UTC by tatsuo-ishii

14.5との差分がないところにも「機械翻訳」のタグが入っているような気がします。

2022-10-16 09:22 UTC, tatsuo-ishii commented
> 14.5との差分がないところにも「機械翻訳」のタグが入っているような気がします。
気の所為でした。「Hot」が「hot」になっただけのところも機械翻訳されていただけでした。

2022-10-16 22:32 UTC, noborus commented
> > 14.5との差分がないところにも「機械翻訳」のタグが入っているような気がします。
> 
> 気の所為でした。「Hot」が「hot」になっただけのところも機械翻訳されていただけでした。

完全に一致して既存訳を置き換えているところは大丈夫だと思いますが、変更があるところは類似文が優先されるはずで、
これがうまくいかなかったようです。
機械翻訳では、TexTraに既存の訳を対訳集として登録しているので似た文は、ほとんど対訳集と同じ文が返される場合があります
（誤訳も学習したそのまま返される場合があります）。

2022-10-17 07:18 UTC, tatsuo-ishii commented
> 完全に一致して既存訳を置き換えているところは大丈夫だと思いますが、変更があるところは類似文が優先されるはずで、
これがうまくいかなかったようです。

ここが良くわからなかったのですが、もしかして、ある段落(<para>から</para>まで)の一部だけでも変更されていた場合は、その段落全体を機械翻訳で置き換えてしまうのでしょうか？たとえば、以下の段落ですが、変更があったのは最初の1行だけですが、2行目以降も機械翻訳に置き換えられてしまっているようです。これだと、機械翻訳が適切なのかどうかをチェックするのにかなり手間になります。既存訳の再利用であれば、変更箇所だけのチェックで済むのですが。

`
<!--
        The <xref linkend="guc-archive-command"/> is only invoked for
        completed WAL segments. Hence, if your server generates little WAL
        traffic (or has slack periods where it does so), there could be a
        long delay between the completion of a transaction and its safe
        recording in archive storage.  To limit how old unarchived
        data can be, you can set <varname>archive_timeout</varname> to force the
        server to switch to a new WAL segment file periodically.  When this
        parameter is greater than zero, the server will switch to a new
        segment file whenever this amount of time has elapsed since the last
        segment file switch, and there has been any database activity,
        including a single checkpoint (checkpoints are skipped if there is
        no database activity).  Note that archived files that are closed
        early due to a forced switch are still the same length as completely
        full files.  Therefore, it is unwise to use a very short
        <varname>archive_timeout</varname> &mdash; it will bloat your archive
        storage.  <varname>archive_timeout</varname> settings of a minute or so are
        usually reasonable.  You should consider using streaming replication,
        instead of archiving, if you want data to be copied off the primary
        server more quickly than that.
        If this value is specified without units, it is taken as seconds.
        This parameter can only be set in the
        <filename>postgresql.conf</filename> file or on the server command line.
-->
<xref linkend="guc-archive-command"/>は完了したWALセグメントに対してのみ呼び出されます。
従って、サーバのWAL転送量が少ししかない（あるいは処理が少ないなぎの期間がある）場合、トランザクションの完了とアーカイブ格納領域への安全な記録との間に長期にわたる遅延があることになります。
データが未アーカイブのままでいられる期間を制限するために、<varname>archive_timeout</varname>を設定して、強制的にサーバを新しいWALセグメントに定期的に切り替えるようにすることができます。
このパラメータが0より大きければ、サーバは前回のセグメントファイル切り替えから指定時間経過し、かつ単一のチェックポイントを含む何らかのデータベース操作が行われた場合、新しいセグメントファイルに切り替えます。
（データベースが活動していなければ、チェックポイントはスキップされます。）
強制切り替えにより早期にクローズされたアーカイブ済みファイルは、完全に完了したファイルと同じ大きさを持つことに注意してください。
そのため、非常に小さな<varname>archive_timeout</varname>を使用することは賢明ではなく、格納領域を膨張させてしまいます。
１分程度の<varname>archive_timeout</varname>設定が通常は妥当です。
もしそれより高速にデータをプライマリサーバからコピーをしてしまいたいのであれば、アーカイブするよりストリーミングレプリケーションの選択を検討すべきです。
この値が単位なしで指定された場合は、秒単位であるとみなします。
このパラメータは <filename>postgresql.conf</filename>ファイル、または、サーバのコマンドラインでのみで設定可能です。
       </para>
`

2022-10-17 08:21 UTC, noborus commented
> ここが良くわからなかったのですが、もしかして、ある段落(からまで)の一部だけでも変更されていた場合は、その段落全体を機械翻訳で置き換えてしまうのでしょうか？

いえ、ここは《マッチ度[84.711605]》で既存訳が残るべきところです。それがミスって残らなかったので機械翻訳に変わってます。

ミスの原因の一つとして、変更が一部あるために完全一致するのが以下の文のみで、ここを置き換えて、残りが放置された状態になった場合がありました。

> This parameter can only be set in the
>      <filename>postgresql.conf</filename> file or on the server command line.

これをリカバリするときに機械翻訳の方が入ってしまったようです。
一発で置き換え出来てたら良かったのですが、いろいろ問題があって、#2404や#2413で直していたのは、そのためです。

2022-10-17 08:40 UTC, tatsuo-ishii commented
> ミスの原因の一つとして、変更が一部あるために完全一致するのが以下の文のみで、ここを置き換えて、残りが放置された状態になった場合がありました。

そうなんですか？REL_14_5 と REL_15_0 でdiffを取ると、この段落では違っているのは最初の1行だけなのですが。
```
@@ -3588,7 +3637,7 @@ include_dir 'conf.d'
       </term>
       <listitem>
        <para>
-        The <xref linkend="guc-archive-command"/> is only invoked for
+        The <xref linkend="guc-archive-command"/> or <xref linkend="guc-archive-library"/> is only invoked for
         completed WAL segments. Hence, if your server generates little WAL
         traffic (or has slack periods where it does so), there could be a
         long delay between the completion of a transaction and its safe
```

2022-10-17 08:49 UTC, tatsuo-ishii commented
> あ、えっと既存の訳を使うか機械翻訳にするかは、１文毎ではなく、ブロック単位の判断で、そういう意味では一部変わると全部機械翻訳になる場合があります。

その場合は「マッチ度」が大きいので、既存訳が使われると思っていたのですが、使われなかった理由は何でしょうか？

2022-10-17 09:05 UTC, noborus commented
> > あ、えっと既存の訳を使うか機械翻訳にするかは、１文毎ではなく、ブロック単位の判断で、そういう意味では一部変わると全部機械翻訳になる場合があります。
> 
> その場合は「マッチ度」が大きいので、既存訳が使われると思っていたのですが、使われなかった理由は何でしょうか？

それが、上で書いた一部分に完全一致してしまって置き換えるミスが発生していたところです。
通常はブロック単位なのですが、完全一致の場合は上の部分を無視すれば、下の部分だけ完全一致するということで置き換えミスが起こってました。
config.sgmlに、この文だけのブロックがあったために起こりました。

> This parameter can only be set in the
> postgresql.conf file or on the server command line.

完全一致のときに完全にブロック単位の一致にするとブロックの切り出し方によって一致しなくなる場合が多いので（例えばprogramlistingを含むか＋空行を含むかとか）、
既存訳の取り出しの時にブロックで切り出して、置き換えるときにはファイル全体から探していたためです。

2022-10-17 10:21 UTC, KenichiroTanaka commented
@noborus さん
この辺りの動作についてオンラインで勉強会など実施できないでしょうか。
動作が複雑なので関係者で一度認識合わせができないかと思っています。

2022-10-17 23:22 UTC, noborus commented
> @noborus さん この辺りの動作についてオンラインで勉強会など実施できないでしょうか。 動作が複雑なので関係者で一度認識合わせができないかと思っています。

了解です。やりながらプログラムの方も変更しているので動作はまだまだ不安定ですが。

2022-10-25 22:29 UTC, noborus commented on doc/src/sgml/config0.sgml
>  《マッチ度[86.556360]》サーバが使う動的共有メモリの実装を指定します。可能な値は<literal>posix</literal> (<literal>shm_open</literal>で獲得するPOSIX共有メモリ)、<literal>sysv</literal>(<literal>shmget</literal>で獲得するSystem V共有メモリ)、<literal>window
《マッチ度[86.556360]》の方も消してもらえますでしょうか

2022-10-25 22:29 UTC, noborus commented on doc/src/sgml/config1.sgml
>        </listitem>
この後の1000行あたりに《マッチ度[80.587618]》が残っています。
`この設定はスーパーユーザのみ変更可能です。`から`スーパーユーザと、適切な<literal>SET</literal>権限を持つユーザのみがこの設定を変更することができます。`への変更があるようです。

2022-10-25 22:29 UTC, noborus commented on doc/src/sgml/config1.sgml
>  デフォルトは30秒です。
この後の3210行あたりに《マッチ度[85.945946]》が残っています。amount→numberの変更で、訳はそのままで良さそうです。

2022-10-25 22:29 UTC, noborus commented on doc/src/sgml/config2.sgml
>  デフォルトは<literal>0</literal>で、これは追加のトランザクションのログを取らないことを意味します。
このブロックの最後の部分も`スーパーユーザと、適切な<literal>SET</literal>権限を持つユーザのみがこの設定を変更することができます。`に変更されています。

2022-10-25 22:29 UTC, noborus commented on doc/src/sgml/config2.sgml
>  スーパーユーザのみがこの設定を変更することができます。
ここも`スーパーユーザと、適切な<literal>SET</literal>権限を持つユーザのみがこの設定を変更することができます。`に変わっています。

2022-10-25 22:29 UTC, noborus commented on doc/src/sgml/config2.sgml
>  スーパーユーザだけがセッション開始時にこのパラメータを変更でき、セッションが開始された後は変更できません。
ここも`スーパーユーザと、適切な<literal>SET</literal>権限を持つユーザのみ`に変わっています。

2022-10-26 05:49 UTC, tatsuo-ishii commented
斉藤さん
レビューありがとうございます。すべていただきました。

2022-10-26 12:44 UTC, KenichiroTanaka requested changes
途中ですが一度お送りします。

2022-10-26 12:44 UTC, KenichiroTanaka commented on doc/src/sgml/config1.sgml
> +
この空行は不要のように思います。

2022-10-26 12:49 UTC, KenichiroTanaka commented
@noborus さん

認識があっているか確認させてください。
git diff REL_14_5 REL_15_0 config.sgml 
ででてくる以下ですが
```
@@ -5892,6 +6013,29 @@ SELECT * FROM parent WHERE key = 2400;
       </listitem>
      </varlistentry>
 
+     <varlistentry id="guc-recursive-worktable-factor" xreflabel="recursive_worktable_factor">
+      <term><varname>recursive_worktable_factor</varname> (<type>floating point</type>)
+      <indexterm>
+       <primary><varname>recursive_worktable_factor</varname> configuration parameter</primary>
+      </indexterm>
+      </term>
+      <listitem>
+       <para>
+        Sets the planner's estimate of the average size of the working
+        table of a <link linkend="queries-with-recursive">recursive
+        query</link>, as a multiple of the estimated size of the initial
+        non-recursive term of the query.  This helps the planner choose
+        the most appropriate method for joining the working table to the
+        query's other tables.
+        The default value is <literal>10.0</literal>.  A smaller value
+        such as <literal>1.0</literal> can be helpful when the recursion
+        has low <quote>fan-out</quote> from one step to the next, as for
+        example in shortest-path queries.  Graph analytics queries may
+        benefit from larger-than-default values.
```
原文に追加があったところだと思いますが、本来は「機械翻訳」タグがつく認識です。
合っているでしょうか？現在訳が追加されているのですが、GITHUB上では表示されず、
訳を探すのに手間取っています。

2022-10-26 13:13 UTC, tatsuo-ishii commented on doc/src/sgml/config1.sgml
> +しかし、minimal WALにはPoint-in-Timeリカバリのための十分な情報が含まれていないので、<literal>replica</literal>以上を使って継続的アーカイブ(<xref linkend="guc-archive-mode"/>)とストリーミングバイナリレプリケーションを可能にしなければなりません。
はい、カタカナにします。

2022-10-26 13:17 UTC, tatsuo-ishii commented on doc/src/sgml/config1.sgml
> +永続リレーションを作成あるいは書き換えるトランザクションの差分に関する情報はログされません。
「ログする」とか「ログされません」があまり良くないのには同意しますが、動詞の"log"は素直に「記録する」と訳すのでも良いような気がします。ちなみにconfig.sgmlで「ログされ」でgrepすると、以下のものが出てきます。
```
永続リレーションを作成あるいは書き換えるトランザクションの差分に関する情報はログされません。
<literal>logical</literal>レベルでは、<literal>replica</literal>と同じ情報がログされるのに加え、ロジカルチェンジセットをWALから取り出すのに必要な情報が追加されます。
データチェックサムが有効であると、ヒントビットの更新は常にWALにログされ、この設定パラメータは無視されます。
このオプションと<xref linkend="guc-log-statement"/>を一緒に使用する時、<varname>log_statement</varname>によってログされるテキスト文は、実行時間のログには重複されません。
```
これらの「ログ」を「記録」に置き換えても良さそうに見えます。
```
永続リレーションを作成あるいは書き換えるトランザクションの差分に関する情報は記録されません。
<literal>logical</literal>レベルでは、<literal>replica</literal>と同じ情報が記録されるのに加え、ロジカルチェンジセットをWALから取り出すのに必要な情報が追加されます。
データチェックサムが有効であると、ヒントビットの更新は常にWALに記録され、この設定パラメータは無視されます。
このオプションと<xref linkend="guc-log-statement"/>を一緒に使用する時、<varname>log_statement</varname>によって記録されるテキスト文は、実行時間のログには重複されません。
```

2022-10-26 13:47 UTC, noborus commented
> 原文に追加があったところだと思いますが、本来は「機械翻訳」タグがつく認識です。 合っているでしょうか？現在訳が追加されているのですが、GITHUB上では表示されず、 訳を探すのに手間取っています。

いえ表示されますよ。config2.sgmlのdiffの最初の方です。
https://github.com/pgsql-jp/jpug-doc/pull/2422/files#diff-660760ee0e42c8b00d6914454efdc296a5c6caa5800b4dcaef64b7af76b801f0L114-L131

2022-10-26 13:55 UTC, noborus commented on doc/src/sgml/config3.sgml
> +指定された<xref linkend="guc-huge-page-size"/>に基づいて、主共有メモリー領域に必要な巨大ページの数を報告します。
機械翻訳からですがメモリーになってます（他はメモリ）。
（後で機械翻訳の用語登録をしようと思います）。

2022-10-28 04:35 UTC, koizumistr commented on doc/src/sgml/config1.sgml
> +永続リレーションを作成あるいは書き換えるトランザクションの差分に関する情報はログされません。
log = 「記録する」
に私も一票ということで。

2022-10-28 12:26 UTC, KenichiroTanaka commented
> > 原文に追加があったところだと思いますが、本来は「機械翻訳」タグがつく認識です。 合っているでしょうか？現在訳が追加されているのですが、GITHUB上では表示されず、 訳を探すのに手間取っています。
> 
> いえ表示されますよ。config2.sgmlのdiffの最初の方です。 https://github.com/pgsql-jp/jpug-doc/pull/2422/files#diff-660760ee0e42c8b00d6914454efdc296a5c6caa5800b4dcaef64b7af76b801f0L114-L131

あれ・・・すみません。見落としていたようです。

2022-11-05 02:51 UTC, KenichiroTanaka approved these changes

2022-11-06 00:26 UTC, noborus approved these changes
確認しました

2022-11-06 00:27 UTC, noborus commented
レビュー済みということでマージします。

2022-11-06 00:27 UTC, merged