monitoring.sgmの15.0対応の第1弾です
pgsql-jp/jpug-doc pull request #2430
Opened 2022-10-24 08:11 UTC by noborus

レビューしやすい単位でPRを分割して送る実験です。

monioring.sgmlの対応を全部終わらせてから送ろうとすると時間がかかり、レビューもまた時間がかかります。
分割することで、できそうなところから先行し、スキマ時間でもレビューできる単位にする試みです。

2022-11-01 23:20 UTC, KenichiroTanaka commented
PR分割の試みありがとうございます。
今回はmonitor.sgml多いですね。
いただいたPRですが、どう分割されたのか全貌が見えず・・
ファイルの分け方についてもう少し詳しく教えていただく事は可能でしょうか。

2022-11-02 02:13 UTC, noborus commented
ありがとうございます。
分割の基準はなくて、意図としては変更した部分のみをレビューの対象としてもらってマージすることで
https://pgsql-jp.github.io/current/html/
に既に入っている訳が改善されれば良い。
１つのファイルの最終のときに完了で良いかレビューをしていただくという意図です。

変更が多いファイルでは、レビューに時間がかかり、１つでも問題があると、そのファイル全体がマージされない状態になります。
問題がないといころはマージされてしまったほうが良いので、そこはファイル単位である必要はなく、マージしやすい単位にする
（この辺はコード修正と同じ考えだと思ってます）
とはいっても完了まで持っていくには、どこが終わっているかどうかを示す必要があるため、そこはファイル単位でおこなう
のが良いと思います。

2022-11-02 02:20 UTC, noborus commented
さらに、複数人が同時におこなう場合は、作業がかぶらないために範囲を決める必要がありますが、
一人でやる場合は難しいところは後回しにしてPRを送るようなやり方も可能だと思います。
場合によっては、その後担当を外れてもやった部分が無駄になりません。

2022-11-02 03:27 UTC, tatsuo-ishii commented
一つのファイルの中で、修正必要箇所の見落としがないことは、どうやって担保するのでしょうか？
たとえば一つのファイルの中で、「1000-2000行目までチェック、修正対応した結果のpull requestです」という形でpull requestされれば、少なくともレビューする方は、「1000-2000行目までは対応しているが、それ以外の行はまだ対応していない」という判断ができます。
しかし、そういう情報が提示されていないpull requestをいくつ投げられても、レビューする側はそのファイルの修正完了、という判断ができないです。それとも、その点はpull requestを投げる側を信用してください、という話なのでしょうか。
もう少し具体的なワークフローを提示していただけないでしょうか？

2022-11-02 03:35 UTC, tatsuo-ishii commented
ファイルの分割pull request/reviewという考え方自体は悪くないですが、ファイルの分割単位を客観的、かつ容易に判断できるようにすべきと思います。そしてその上で、分割単位それぞれについて、「分割nは終わっているが、分割n+1はまだ終わっていない」ということをわかりやすく判断できる情報がWikiなどに必要と思います。

2022-11-02 05:46 UTC, noborus commented
ありがとうございます。
> 一つのファイルの中で、修正必要箇所の見落としがないことは、どうやって担保するのでしょうか？ たとえば一つのファイルの中で、「1000-2000行目までチェック、修正対応した結果のpull requestです」という形でpull requestされれば、少なくともレビューする方は、「1000-2000行目までは対応しているが、それ以外の行はまだ対応していない」という判断ができます。 しかし、そういう情報が提示されていないpull requestをいくつ投げられても、レビューする側はそのファイルの修正完了、という判断ができないです。それとも、その点はpull requestを投げる側を信用してください、という話なのでしょうか。 もう少し具体的なワークフローを提示していただけないでしょうか？

そのファイルに対して最後のPRのときに宣言して、完了として出し、レビューもそのつもりで見てもらう想定です。
完了でないPRの場合は途中であることを宣言して、修正したところをレビューしてもらう意図で出します。
つまり、最後のPRがこれまでやってきた翻訳担当のPRと同じで、それ以外は間違いを見つけたときの修正PRと同じように考えてもらえば良いと思います。

> ファイルの分割pull request/reviewという考え方自体は悪くないですが、ファイルの分割単位を客観的、かつ容易に判断できるようにすべきと思います。そしてその上で、分割単位それぞれについて、「分割nは終わっているが、分割n+1はまだ終わっていない」ということをわかりやすく判断できる情報がWikiなどに必要と思います。

分割単位を決めてしまうとレビューしやすい単位になるとは限らず、前の部分との関連の見逃しも別の意味で発生すると思います。
今回のPRでは変更がないところも修正していますが、表の同じような表現で書かれている箇所が翻訳では揃っていませんでした。
ある意味では、今回はその部分を修正した修正PRです。
コードと同じように意味のある単位で修正を出してレビューした方が見やすくなります。

完了前のPRは他の修正のみのPRと同じで、改善されていれば良く、そのファイルの最終のときに、これまでと同じように完了して問題ないかレビューしてもらえば良い
という考えです。

2022-11-02 08:13 UTC, tatsuo-ishii commented
> そのファイルの最終のときに、これまでと同じように完了して問題ないかレビューしてもらえば良い

これが大変そうです。今回で言うと、REL_14_5 REL_15_0で差分が生じているところは、翻訳で修正が必要かどうかを判断しなければならないのですが、そのためには、今までのpull requestを全部調べ、英文で差分が出ているのに見過ごされているところがないかどうかを、「最後の」pull requestのレビューワーが調べなければなりません。

というわけで
> 一つのファイルの中で、修正必要箇所の見落としがないことは、どうやって担保するのでしょうか？

の話に戻ると、これを担保するためには最後のpull requestのレビューワーが頑張るしか無いように思います。そうすると、「最後の」レビューワーにみんな最後のレビューワーになりたがらないので、作業が終了しない、ということになりそうな気がします。

2022-11-02 10:03 UTC, koizumistr commented
@noborus さんは、「基本一人で最後まで頑張るのだけれど、一気に頑張るのはちょっとつらいので」という前提で、一方、 @tatsuo-ishii さんは、「みんなでやる時には」という前提になっているのかな、と思いました。

「基本一人で最後まで頑張る」前提であれば、「俺はここまで頑張った。でも限界」という時だけ、「頑張ったのはここからここまでなので残りはよろしく」みたいなことを伝えられれば十分とは思いますが、でも万が一に備えて必ず「頑張ったのはここからここまで」とやっておくのが良いのかな、とも、、、

2022-11-02 12:06 UTC, noborus commented
> > そのファイルの最終のときに、これまでと同じように完了して問題ないかレビューしてもらえば良い
> 
> これが大変そうです。今回で言うと、REL_14_5 と REL_15_0で差分が生じているところは、翻訳で修正が必要かどうかを判断しなければならないのですが、そのためには、今までのpull requestを全部調べ、英文で差分が出ているのに見過ごされているところがないかどうかを、「最後の」pull requestのレビューワーが調べなければなりません。
> 
> というわけで
> 
> > 一つのファイルの中で、修正必要箇所の見落としがないことは、どうやって担保するのでしょうか？
> 
> の話に戻ると、これを担保するためには最後のpull requestのレビューワーが頑張るしか無いように思います。そうすると、「最後の」レビューワーにみんななりたがらないので、作業が終了しない、ということになりそうな気がします。

これは元々１回ですべて完了していた場合にもやっておく必要がある問題で、マージ作業と後のチェックを散々やった経験から言わせてもらうと

* REL_14_5 と REL_15_0の差分
* doc_ja_14との差分
* REL_15_0との差分

までやらないと漏れが多く発生します。
１４までのgit mergeを使用していた方が気づかずに変更されている場合が多く、15では多くの場合で変更が必要な記述が入るので楽になったと思ってます。
翻訳のレビューとこの漏れのチェックを数千行の中で数百行の変更をやる場合は１回でやればどうしても見落としが発生しますが、
翻訳の内容のレビューが先に済んでいれば、最後は見落としに注力できるため、むしろ楽になります。

2022-11-02 13:18 UTC, tatsuo-ishii commented
> これは元々１回ですべて完了していた場合にもやっておく必要がある問題で

大きな違いは、

- 一回のpull requestで済ませていた場合には、pull requestでの変更と、英文のdiffを頭から見比べるだけで良かった
-  N回のpull requestになる場合には、その作業をN回やらなければならない

ということで、そこを気にしています。ですから「むしろ楽になる」とは思えません。Githubでも、1回めのpull requestからN回目までのpull requestの累積差分を一度に見る方法があれば、また別ですが。

2022-11-03 00:18 UTC, noborus commented
> > これは元々１回ですべて完了していた場合にもやっておく必要がある問題で
> 
> 大きな違いは、
> 
> * 一回のpull requestで済ませていた場合には、pull requestでの変更と、英文のdiffを頭から見比べるだけで良かった
>
> * N回のpull requestになる場合には、その作業をN回やらなければならない
> 
> ということで、そこを気にしています。ですから「むしろ楽になる」とは思えません。Githubでも、1回めのpull requestからN回目までのpull requestの累積差分を一度に見る方法があれば、また別ですが。

いえ、繰り返しになりますが、完了するためのチェック項目は変わらず、そのための見逃しを防ぐためにはgit diffを駆使しなければなりません。
一つのdiffを見るだけで良いように準備できたことは、これまで一度も無いんです。だから見逃しは発生していました。
対して、完了以外のpull requestは修正されている箇所だけをレビューすればよく、それ以外は気にする必要はありません。
なのでブラウザで見ただけで問題ないです。

１つのファイルにA,B,C,Dの変更があるように見えたとき、A,B,C,Dをレビューすれば終わりということではなく、A,B,C,D,その他を見る必要があります。
A,B,Cの翻訳がレビューされてマージされていれば、その内容はある程度信頼できると考えて、最終のpull requestはD,その他に注力すればよくなるので楽になると書きました。

2022-11-03 02:02 UTC, tatsuo-ishii commented
なるほど。
> 最終のpull requestはD,

pull requestを出す人は、「これが最終のpull requestである」ことを宣言する必要があるのですね。逆に言うと、最終であると宣言されていないpull requestは、修正箇所だけレビューすれば良いと。
ところで、Dのレビューする人は、「A,B,Cの翻訳がレビューされてマージされていれば、その内容はある程度信頼できると考え」であるとすると、A, B, Cの修正箇所がどこであるかを探しておかなければなりませんね。
そのためには、
> 1回めのpull requestからN回目までのpull requestの累積差分を一度に見る方法があれば、また別ですが。

これをなんとかしなければならないことは変わっていないと理解しました。

2022-11-03 02:16 UTC, tatsuo-ishii requested changes
確認しました。

2022-11-03 02:16 UTC, tatsuo-ishii commented on doc/src/sgml/monitoring.sgml
> +シーケンシャルスキャンとこのデータベース内のインデックススキャンによって返されたインデックスエントリから取り出された行数です。
"live"が訳出されていません。
index tupleにはlive rowもdead rowも含まれており、index scanはテーブルを見ることによってindex tupleがliveかdeadを判別しています。ですから、"live"を訳出しないとdead rowも含んでしまうことになり、原文の意味が損なわれると思います。

2022-11-03 02:16 UTC, tatsuo-ishii commented on doc/src/sgml/monitoring.sgml
> +データベース内のインデックススキャンで取り出された行数です。
"live"が訳出されていません。

2022-11-03 02:16 UTC, tatsuo-ishii commented on doc/src/sgml/monitoring.sgml
> +シーケンシャルスキャンによって取り出された行数です。
"live"が訳出されていません。

2022-11-03 02:16 UTC, tatsuo-ishii commented on doc/src/sgml/monitoring.sgml
> +インデックススキャンによって取り出された行数です。
"live"が訳出されていません。

2022-11-03 07:18 UTC, tatsuo-ishii commented
> 1回めのpull requestからN回目までのpull requestの累積差分を一度に見る方法があれば、また別ですが。

失礼しました。先の例で言えば、AからDまでの累積diffは無理ですが、AからCまでなら手元でgit操作すれば可能ですね。
AからCまではすでにdoc_ja_15ブランチにコミットされているという前提なので。

2022-11-03 20:43 UTC, noborus commented on doc/src/sgml/monitoring.sgml
> +シーケンシャルスキャンとこのデータベース内のインデックススキャンによって返されたインデックスエントリから取り出された行数です。
なるほど、ありがとうございます。
「有効な行数」とするのはどうでしょうか？

2022-11-05 00:00 UTC, tatsuo-ishii commented
> 「有効な行数」とするのはどうでしょうか？

私は良いと思います。

2022-11-05 01:38 UTC, noborus commented
> > 「有効な行数」とするのはどうでしょうか？
> 
> 私は良いと思います。

ありがとうございます！

2022-11-05 01:54 UTC, noborus commented
修正しました

2022-11-05 03:08 UTC, KenichiroTanaka commented
@noborus さん
@tatsuo-ishii さん
@koizumistr さん
乗り遅れました。私も当初は現在翻訳されている箇所がどこかを判断しなければならないためレビューが煩雑になると思いましたが、最終PRである旨を最後に宣言すれば、途中のPR対応は楽になりますね。
（つまり、翻訳者は１人でPRを分割した人がどこまでをPR出したか管理し、他の人は管理しない、
　ということですね。
　そして、ここがレビュワーの負荷を上げずに翻訳/レビューしやすくするポイントですね。）
分割PRの場合のレビューの進め方は
最終PR以外：翻訳のみをレビュー
最終PR：翻訳に加えて抜け漏れチェックを実施
という進め方になると理解しました。
進め方について異議はありません。

2022-11-07 22:50 UTC, KenichiroTanaka requested changes
1箇所気づくところがありましたのでご確認いただけないでしょうか。

2022-11-07 22:50 UTC, KenichiroTanaka commented on doc/src/sgml/monitoring.sgml
> +更新された行数です（<link linkend="storage-hot">HOT updated rows</link>更新された行数を含みます）。
update rowsが英文と日本語で２回出てきているように見えます。

```
<link linkend="storage-hot">HOT updated rows</link>更新された行数を含みます
```
↓
```
<link linkend="storage-hot">HOT updated rows</link>を含みます
```
などとするのはどうでしょうか。

2022-11-09 00:19 UTC, noborus commented on doc/src/sgml/monitoring.sgml
> +更新された行数です（<link linkend="storage-hot">HOT updated rows</link>更新された行数を含みます）。
ありがとうございます。確かに２重になってました。
「HOT更新された行数」で統一されていたようなので、`<link linkend="storage-hot">HOT更新された行数</link>`にします。

2022-11-09 03:08 UTC, tatsuo-ishii approved these changes
一通り確認しました。

2022-11-09 03:09 UTC, tatsuo-ishii approved these changes
確認しました。

2022-11-09 03:16 UTC, koizumistr reviewed
確認しました。指摘はないです。
（マージまで進めるつもりだったのですけど、私ではできないようなのでとりあえず「確認しました」宣言を。）

2022-11-12 07:27 UTC, tatsuo-ishii commented
田中さんのapproveがないとマージできないようですね。

2022-11-12 07:34 UTC, KenichiroTanaka approved these changes

2022-11-12 07:35 UTC, KenichiroTanaka commented
すみません、ブロックしていました。マージします。

2022-11-12 07:35 UTC, merged