func.sgmlのPostgreSQL 15.0対応です。
pgsql-jp/jpug-doc pull request #2440
Opened 2022-11-02 06:01 UTC by tatsuo-ishii

2022-11-06 09:40 UTC, koizumistr reviewed
確認したのは func1.sgml だけですが、とにかく送信してしまいます。

2022-11-06 09:40 UTC, koizumistr commented on doc/src/sgml/func1.sgml
> +また、<xref linkend="functions-matching"/>で説明するしたパターンマッチ演算子と、<xref linkend="textsearch"/>で説明するフルテキストサーチ用の演算子もあります。
フルテキストサーチ -> 全文検索

2022-11-06 09:40 UTC, koizumistr commented on doc/src/sgml/func1.sgml
> +最初の文字列が2番目の文字列で始まる場合にtrueを返します（<function>starts_with()</function>関数と同じです）。
「trueを返します」ではなく「真を返します」としているところの方が多いようです。

2022-11-06 09:40 UTC, koizumistr commented on doc/src/sgml/func1.sgml
> +<parameter>string</parameter>に対してPOSIX正規表現で最初の一致、あるいは<literal>g</literal>が指定された場合にはすべての一致の結果部分文字列を返します。<xref linkend="functions-posix-regexp"/>を参照してください。
（他のところと同じ感じで）

POSIX正規表現＜parameter＞pattern＜/parameter＞

2022-11-06 09:40 UTC, koizumistr commented on doc/src/sgml/func1.sgml
> +POSIX正規表現<parameter>pattern</parameter>の<parameter>N</parameter>番目のオカレンスに一致する<parameter>string</parameter>内の部分文字列を返します。一致しない場合は<literal>NULL</literal>を返します。
オカレンスに一致する -> 一致する

2022-11-06 09:40 UTC, koizumistr commented on doc/src/sgml/func1.sgml
> +<replaceable>flags</replaceable>パラメータは、関数の動作を変更する0個以上の単一文字フラグを含むオプションのテキスト文字列です。サポートされているフラグは<xref linkend="posix-embedded-options-table"/>で説明されています。
サポートされているフラグ の前に改行が欲しいです。

2022-11-06 09:40 UTC, koizumistr commented on doc/src/sgml/func1.sgml
> +構文<function>regexp_substr</function><replaceable>string</replaceable>,<replaceable>pattern</replaceable><optional>,<replaceable>start</replaceable><optional>,<replaceable>N</replaceable><optional>,<r
構文～の構文を持ちます。
となっていてしつこいかもです。（～が長いので気にならないかもしれませんが）

2022-11-06 09:40 UTC, koizumistr commented on doc/src/sgml/func1.sgml
> +<replaceable>subexpr</replaceable>が省略されているか0の場合、結果はカッコで囲まれた部分式に関係なく完全に一致します。
他の似たような文に対しては「完全」ではなく「全体」としていたような。

2022-11-08 05:40 UTC, noborus commented on doc/src/sgml/func1.sgml
> +POSIX正規表現<parameter>pattern</parameter>が<parameter>string</parameter>でマッチした回数を返します。<xref linkend="functions-posix-regexp"/>を参照してください。
機械翻訳がそうだったのですが、他のところで前から書かれている「`<parameter>string</parameter>`に対してPOSIX正規表現<parameter>pattern</parameter>がマッチ」の順の方がわかりやすくないでしょうか。

2022-11-08 05:40 UTC, noborus commented on doc/src/sgml/func3.sgml
> +<literal>twoints型を(a int,b int);として作成</literal>
元々翻訳対象にしていなかった箇所に機械翻訳が入ってしまったようです。これは必要ないと思います。

2022-11-08 05:40 UTC, noborus commented on doc/src/sgml/func4.sgml
> +指定プロセスIDのバックエンドのメモリコンテキストをログすることを要求します。
config.sgmlであった話と関連すると思いますが、ログを取るか記録するになるでしょうか？

2022-11-08 05:54 UTC, noborus commented on doc/src/sgml/func4.sgml
>  <parameter>type</parameter>パラメータは以下のどれかでなければなりません。
`'p'で<literal>PARAMETER</literal>が抜けています。

2022-11-08 05:55 UTC, noborus commented on doc/src/sgml/func4.sgml
>  <xref linkend="sql-altercollation"/>も参照してください。
`<xref linkend="sql-alterdatabase"/>`です。

2022-11-08 06:00 UTC, noborus commented on doc/src/sgml/func4.sgml
> +WALアーカイブステータスディレクトリ（<filename>pg_wal/archive_status</filename>）内の各ファイルについて、名前、サイズ、最終更新時刻（mtime）を返します。
> `where <parameter>slot_name</parameter> is the name of the
        replication slot provided as input of the function.`
の部分が抜けています。

2022-11-09 03:41 UTC, tatsuo-ishii reviewed
レビューありがとうございます。

2022-11-09 03:41 UTC, tatsuo-ishii commented on doc/src/sgml/func1.sgml
>  そのいくつかは、<xref linkend="functions-string-sql"/>で列挙した標準<acronym>SQL</acronym>の文字列関数を実装するため、内部的に使用されます。
見逃していました。

2022-11-09 03:41 UTC, tatsuo-ishii commented on doc/src/sgml/func1.sgml
> +また、<xref linkend="functions-matching"/>で説明するしたパターンマッチ演算子と、<xref linkend="textsearch"/>で説明するフルテキストサーチ用の演算子もあります。
修正します。

2022-11-09 03:41 UTC, tatsuo-ishii commented on doc/src/sgml/func1.sgml
> +最初の文字列が2番目の文字列で始まる場合にtrueを返します（<function>starts_with()</function>関数と同じです）。
そうですね。対応します。

2022-11-09 03:41 UTC, tatsuo-ishii commented on doc/src/sgml/func1.sgml
> +POSIX正規表現<parameter>pattern</parameter>が<parameter>string</parameter>でマッチした回数を返します。<xref linkend="functions-posix-regexp"/>を参照してください。
そうですね。

2022-11-09 03:41 UTC, tatsuo-ishii commented on doc/src/sgml/func1.sgml
> +<parameter>string</parameter>に対してPOSIX正規表現で最初の一致、あるいは<literal>g</literal>が指定された場合にはすべての一致の結果部分文字列を返します。<xref linkend="functions-posix-regexp"/>を参照してください。
修正します。

2022-11-09 03:41 UTC, tatsuo-ishii commented on doc/src/sgml/func1.sgml
> +POSIX正規表現<parameter>pattern</parameter>の<parameter>N</parameter>番目のオカレンスに一致する<parameter>string</parameter>内の部分文字列を返します。一致しない場合は<literal>NULL</literal>を返します。
いただきます。

2022-11-09 03:41 UTC, tatsuo-ishii commented on doc/src/sgml/func1.sgml
> +<replaceable>flags</replaceable>パラメータは、関数の動作を変更する0個以上の単一文字フラグを含むオプションのテキスト文字列です。サポートされているフラグは<xref linkend="posix-embedded-options-table"/>で説明されています。
そうですね。

2022-11-09 03:41 UTC, tatsuo-ishii commented on doc/src/sgml/func1.sgml
> +構文<function>regexp_substr</function><replaceable>string</replaceable>,<replaceable>pattern</replaceable><optional>,<replaceable>start</replaceable><optional>,<replaceable>N</replaceable><optional>,<r
最初の「構文」を削除、後の「構文」を「の構文となっています」にしました。

2022-11-09 03:41 UTC, tatsuo-ishii commented on doc/src/sgml/func1.sgml
> +<replaceable>subexpr</replaceable>が省略されているか0の場合、結果はカッコで囲まれた部分式に関係なく完全に一致します。
「全体」にしました。

2022-11-09 03:41 UTC, tatsuo-ishii commented on doc/src/sgml/func3.sgml
> +<literal>twoints型を(a int,b int);として作成</literal>
おっと。こういうこともあるのですね。

2022-11-09 03:41 UTC, tatsuo-ishii commented on doc/src/sgml/func4.sgml
>  <xref linkend="sql-altercollation"/>も参照してください。
修正します。

2022-11-09 03:41 UTC, tatsuo-ishii commented on doc/src/sgml/func4.sgml
> +WALアーカイブステータスディレクトリ（<filename>pg_wal/archive_status</filename>）内の各ファイルについて、名前、サイズ、最終更新時刻（mtime）を返します。
対応します。

2022-11-09 03:43 UTC, tatsuo-ishii commented on doc/src/sgml/func4.sgml
> +指定プロセスIDのバックエンドのメモリコンテキストをログすることを要求します。
2箇所あったので、両方共「記録する」にしました。

2022-11-09 03:45 UTC, tatsuo-ishii commented on doc/src/sgml/func4.sgml
>  <parameter>type</parameter>パラメータは以下のどれかでなければなりません。
追加します。

2022-11-09 21:17 UTC, noborus commented on doc/src/sgml/func1.sgml
>  <replaceable>pattern</replaceable>にマッチしない場合は、<replaceable>source</replaceable>文字列がそのまま返されます。
`<optional>, <replaceable>start</replaceable> <optional>, <replaceable>N</replaceable></optional></optional> <optional>` が原文に追加されていますが、反映されていません。

2022-11-09 21:17 UTC, noborus commented on doc/src/sgml/func4.sgml
>  これが<structname>pg_collation</structname>.<structfield>collversion</structfield>と異なると、その照合順序に依存しているオブジェクトは再構築の必要があるかも知れません。
すみません指摘漏れました。
`<structname>pg_database</structname>.<structfield>datcollversion</structfield>`もです。

2022-11-09 21:17 UTC, noborus commented on doc/src/sgml/func2.sgml
> +<parameter>語彙素</parameter>内の文字列は、それ以上の処理を行わずに、そのまま語彙素として扱われます。
`<parameter>lexemes</parameter>` パラメータの方なのでlexemesのままではないでしょうか。

2022-11-10 11:04 UTC, tatsuo-ishii commented on doc/src/sgml/func1.sgml
>  マッチすると、マッチ部分文字列を<replaceable>replacement</replaceable>文字列で置換した<replaceable>source</replaceable>文字列が返されます。
追加します。

2022-11-10 11:23 UTC, tatsuo-ishii commented on doc/src/sgml/func2.sgml
> +<parameter>語彙素</parameter>内の文字列は、それ以上の処理を行わずに、そのまま語彙素として扱われます。
おっと、そうでした。

2022-11-10 11:44 UTC, tatsuo-ishii commented on doc/src/sgml/func4.sgml
>  これが<structname>pg_collation</structname>.<structfield>collversion</structfield>と異なると、その照合順序に依存しているオブジェクトは再構築の必要があるかも知れません。
指摘ありがとうございます。

2022-11-19 23:11 UTC, noborus approved these changes
修正ありがとうございます。確認しました。

2022-11-23 04:54 UTC, KenichiroTanaka commented
お待たせしていてすみません。まとまったレビュー時間が取れ次第対応します。
今週、来週中には時間が取れると思います。

2022-11-29 13:31 UTC, KenichiroTanaka requested changes
大変遅くなりましたが、２箇所気づくところがありましたので確認をお願いできますでしょうか。

2022-11-29 13:31 UTC, KenichiroTanaka commented on doc/src/sgml/func4.sgml
> +オプションで2番目の<type>boolean</type>型パラメータがあります。
「2番目の」は削除されたようです。

2022-11-30 01:35 UTC, tatsuo-ishii commented
レビューありがとうございます。対応しました。

2022-12-01 09:53 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。

2022-12-01 09:55 UTC, KenichiroTanaka commented
複数名のチェックも通りましたのでこの辺りでマージします。

2022-12-01 09:55 UTC, merged