update pg_recvlogical for 15.0
pgsql-jp/jpug-doc pull request #2470
Opened 2022-11-13 08:20 UTC by koizumistr

ref/pg_recvlogical.sgmlの15.0対応です。

prepared transactionは「プリペアドトランザクション」としましたが、最初に機械翻訳が提示してきた「準備されたトランザクション」の方が良かったでしょうか。

2022-11-23 06:16 UTC, KenichiroTanaka commented
プリペアドトランザクションだと思っていましたが、現時点では混在していて準備されたトランザクションの方が多数ですね。どちらかに統一したいです。

2022-11-23 07:14 UTC, KenichiroTanaka requested changes
discussionで方針がたち次第マージします。

2022-11-24 01:48 UTC, koizumistr commented
#2490 ですね。

2022-12-01 10:00 UTC, KenichiroTanaka approved these changes

2022-12-01 10:01 UTC, merged