uuid-ossp.sgmlの15.0対応です
pgsql-jp/jpug-doc pull request #2471
Opened 2022-11-13 23:19 UTC by noborus

2022-11-14 04:53 UTC, koizumistr commented on doc/src/sgml/uuid-ossp.sgml
>  Linux、OS X、その他のプラットフォームでは、適切な関数が<filename>libuuid</filename>ライブラリで提供されており、(現在のLinuxでは<literal>util-linux-ng</literal>の一部と考えられていますが)そのライブラリは<literal>e2fsprogs</literal>プロジェクトに由来します。
他にもあったNetBSD削除ですね。その理由は気になるところですが、指摘はそこではなくて、
次の行に OS X という表記が残ってしまっています。 macOS への修正が必要かと。
（最近よく名前を変えるAppleが悪い？;-p）

2022-11-14 07:01 UTC, noborus commented on doc/src/sgml/uuid-ossp.sgml
>  Linux、OS X、その他のプラットフォームでは、適切な関数が<filename>libuuid</filename>ライブラリで提供されており、(現在のLinuxでは<literal>util-linux-ng</literal>の一部と考えられていますが)そのライブラリは<literal>e2fsprogs</literal>プロジェクトに由来します。
見逃してました。修正します。

2022-11-14 12:23 UTC, koizumistr approved these changes
対応ありがとうございます。確認しました。

2022-11-23 07:21 UTC, KenichiroTanaka requested changes
1箇所よく分かってないところがありますが、気づいたので確認をお願いします。

2022-11-23 07:21 UTC, KenichiroTanaka commented on doc/src/sgml/uuid-ossp.sgml
> +   at <ulink\ url="http://www.ossp.org/pkg/lib/uuid/"></ulink>, it is not well
ulinkの後にバックスラッシュが入っていますが、これって必要だったでしょうか？
私には原文には無いように見えていまして。

2022-11-23 08:14 UTC, noborus commented on doc/src/sgml/uuid-ossp.sgml
> +   at <ulink\ url="http://www.ossp.org/pkg/lib/uuid/"></ulink>, it is not well
すみません。気づかずに入ってました。

2022-11-29 13:33 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。

2022-11-29 13:33 UTC, merged