catalogs.sgmlのPostgreSQL 15.0対応です(パート2)
pgsql-jp/jpug-doc pull request #2475
Opened 2022-11-16 11:27 UTC by tatsuo-ishii

catalogs2.sgml部分のみの作業です。

2022-12-04 21:58 UTC, KenichiroTanaka requested changes
遅くなりました。
いくつか気づくところがありましたのでご確認をお願いします。

2022-12-04 21:58 UTC, KenichiroTanaka commented on doc/src/sgml/catalogs2.sgml
> +大部分のシステムカタログとは異なり、<structname>pg_parameter_acl</structname>は、すべてのクラスタのデータベース間で共有されます。
all databases of a clusterのallはdatabaseにかかるので
「すべてのクラスタのデータベース間で共有されます」
は
「クラスタのすべてのデータベース間で共有されます」
が良いように思います。

2022-12-04 21:58 UTC, KenichiroTanaka commented on doc/src/sgml/catalogs2.sgml
> +特権が付与される設定パラメーターの名前。
「特権」だとSUPERUSERですのでここは「権限」くらいが良いように思います（少し自信がありません）。

2022-12-04 21:58 UTC, KenichiroTanaka commented on doc/src/sgml/catalogs2.sgml
> +真の場合、統計情報には指定されたリレーションの値だけではなく、継承関係の子テーブルが含まれます。
diffは以下の通りでinheritanceを削除し＋αの変更のようです。
```
-       If true, the stats include inheritance child columns, not just the
+       If true, the stats include values from child tables, not just the
        values in the specified relation
```
「統計情報は指定されたリレーションの値だけでなく、子テーブルの値も含まれます」
くらいの訳でどうでしょうか。

2022-12-04 21:58 UTC, KenichiroTanaka commented on doc/src/sgml/catalogs2.sgml
> +真の場合、統計情報には指定されたリレーションの値だけではなく、小テーブルからの値も含まれます。
小テーブル→子テーブル
かと思います。

2022-12-04 21:58 UTC, KenichiroTanaka commented on doc/src/sgml/catalogs2.sgml
> +       <literal>p</literal> = 一時的に有効化、
「pending enablement」なので「一時的に有効化」は「有効化待ち」くらいの訳でどうでしょうか。
（設定はされたもののpg_reload_confされるのを待っている状態をイメージしています）

2022-12-05 01:06 UTC, tatsuo-ishii reviewed
レビューありがとうございました。

2022-12-05 01:06 UTC, tatsuo-ishii commented on doc/src/sgml/catalogs2.sgml
> +       <literal>p</literal> = 一時的に有効化、
subtwophasestateは、論理レプリケーションの中で使われるデータのようです。2相コミットが進行中のデータベースを論理レプリケーションする際に、最初の同期が完了するまでは、あたかも2相コミットが無効であるかのようにするのが"p" (pending enablement)のようですね。そうすると、「一時的に有効化」よりも「有効化待ち」の方が適切だと思います。ご指摘ありがとうございました。

2022-12-08 02:35 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。

2022-12-08 02:35 UTC, merged

2022-12-08 02:35 UTC, KenichiroTanaka commented
マージします。