monitoring.sgmlの15.0対応の第2弾です
pgsql-jp/jpug-doc pull request #2476
Opened 2022-11-16 22:01 UTC by noborus

2022-12-04 22:31 UTC, KenichiroTanaka requested changes
いくつか気づくところがありましたのでご確認をお願いします。

2022-12-04 22:31 UTC, KenichiroTanaka commented on doc/src/sgml/monitoring.sgml
>  またこれは、各テーブル内の総行数、および、各テーブルでのバキュームやアナライズの実施情報を追跡します。
細かいですが、
「追跡します。」
の箇所について、
原文は「are also counted」ですので「数えます」
が良いように思います（v14ではIt also tracksでしたので、これが残っているものと思います）。

2022-12-04 22:31 UTC, KenichiroTanaka commented on doc/src/sgml/monitoring.sgml
>  また、ユーザ定義関数の呼ばれた回数、それぞれの消費した総時間を数えます。
If enabledの訳が抜けているようです。
track_functionsがデフォルトでoffなのでこれがtrueの場合は、という文脈かと思います。

「また、ユーザ定義関数の呼ばれた回数、それぞれの消費した総時間を数えます。」
は
「有効とされている場合は、ユーザ定義関数の呼ばれた回数、それぞれの消費した総時間を数えます。」
くらいの訳でどうでしょうか。

2022-12-04 22:31 UTC, KenichiroTanaka commented on doc/src/sgml/monitoring.sgml
> +この累積統計を使用して、収集されるデータを監視する場合、この情報は即座に更新されないことを認識することが重要です。
「この累積統計を使用して、収集されるデータを監視する場合」の箇所ですが原文が少し変わっているようです。
```
When using the statistics to monitor collected data,
→
When using the cumulative statistics views and functions to monitor collected data
```
「収集したデータを監視するために累積統計ビューやファンクションを使用する場合」
あたりの訳ではどうでしょうか。

2022-12-08 23:31 UTC, noborus commented on doc/src/sgml/monitoring.sgml
>  またこれは、各テーブル内の総行数、および、各テーブルでのバキュームやアナライズの実施情報を追跡します。
ありがとうございます。修正します。

2022-12-08 23:31 UTC, noborus commented on doc/src/sgml/monitoring.sgml
>  また、ユーザ定義関数の呼ばれた回数、それぞれの消費した総時間を数えます。
ありがとうございます。いただきます。

2022-12-08 23:31 UTC, noborus commented on doc/src/sgml/monitoring.sgml
> +この累積統計を使用して、収集されるデータを監視する場合、この情報は即座に更新されないことを認識することが重要です。
ありがとうございます。いただきます。

2022-12-08 23:35 UTC, noborus commented
時間が掛かってしまったため、monitoring.sgmlを最後までやりました。

2022-12-08 23:52 UTC, noborus commented
すみません。致命的なミスをしてしまっているのでやり直します。

2022-12-08 23:52 UTC, closed without merging