update json for 15.0
pgsql-jp/jpug-doc pull request #2483
Opened 2022-11-17 12:07 UTC by koizumistr

json.sgmlの15.0対応です。

2022-11-28 05:06 UTC, noborus approved these changes
確認しました。
良いと思いますが、Perlの方も合わせても良いかもしれません。

2022-12-09 15:17 UTC, KenichiroTanaka requested changes
内容として誤りではないですが、より分かりやすいと思いますので少し修正をお願いできないでしょうか。

2022-12-09 15:17 UTC, KenichiroTanaka commented on doc/src/sgml/json.sgml
> +この拡張を使うと、<type>jsonb</type>の値はPythonの辞書型、リスト、スカラの適切なものにマップされます。
確かにperlは以下のようになっていますね。
「この拡張を使うと<type>jsonb</type>の値は適したPerlの配列、ハッシュ、スカラにマップされます。」
個人的にはjsonの方が「適切な」→「マップ」の語順が近いために分かりやすいように思います。

折角ですので修正をお願いしてもいいでしょうか。

2022-12-22 12:43 UTC, koizumistr commented
確認ありがとうございます。対応しました。

諸般の事情により対応がものすごく遅くなりましてすみません。

2022-12-31 13:08 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。確認しました。

2022-12-31 13:08 UTC, merged