system-views.sgmlのPostgreSQL 15.0対応です。
pgsql-jp/jpug-doc pull request #2487
Opened 2022-11-23 03:34 UTC by tatsuo-ishii

2022-12-17 01:00 UTC, noborus reviewed
確認しました。
スーパーユーザの統一は今回後で変更しようと思っているので、指摘外にしてます。

2022-12-17 12:48 UTC, KenichiroTanaka requested changes
途中までですが気づいたところがありますのでここで一度reviewをサブミットします。

2022-12-17 12:48 UTC, KenichiroTanaka commented on doc/src/sgml/system-views.sgml
>         If the prepared statement does not provide a result (e.g., a DML
githubの表示上見えませんが
以下の２行はcatalogsにあった頃の名残利ですので不要かと思います。
```
2629 <!-- split-catalogs3-end -->
2630 <!-- split-catalogs4-start -->
```

2022-12-18 08:52 UTC, KenichiroTanaka commented
ひととおり確認しました。上記以外には気づくところはありませんでした。

2022-12-19 10:06 UTC, tatsuo-ishii reviewed
レビューありがとうございます。

2022-12-19 10:06 UTC, tatsuo-ishii commented on doc/src/sgml/system-views.sgml
そうですね。翻訳しておきます。

2022-12-19 11:32 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。

2022-12-20 06:16 UTC, noborus commented on doc/src/sgml/system-views.sgml
> +     <entry>shared memory allocations</entry>
ちょっとインデントが変わってしまったようです。

2022-12-21 00:56 UTC, tatsuo-ishii commented on doc/src/sgml/system-views.sgml
> +     <entry>shared memory allocations</entry>
修正します。

2022-12-31 13:09 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。

2022-12-31 13:09 UTC, merged