update indices for 15.0
pgsql-jp/jpug-doc pull request #2497
Opened 2022-11-30 06:57 UTC by kitayama

2022-12-13 00:07 UTC, tatsuo-ishii requested changes
確認しました。

2022-12-13 00:07 UTC, tatsuo-ishii commented on doc/src/sgml/indices.sgml
> +インデックスはまた、<link linkend="storage-hot">ヒープのみのタプル</link>の作成を防ぐこともできます。
ここはインデックスがある場合の否定的な効果について述べているので、「こともできます」という肯定的に受け取れる表現ではなく、「作成を防いでしまいます」のような否定的な表現の方が良いと思います。

2022-12-13 00:07 UTC, tatsuo-ishii commented on doc/src/sgml/indices.sgml
> +派生した式が、行挿入と<link linkend="storage-hot">非HOT更新</link>の度に実行されなければなりませんので、インデックス式は相対的に見て維持が高価です。
以前からですが、"computed"の訳としては、「実行される」よりも「計算される」とか「評価される」あたりの方が適切だと思います。

2022-12-19 12:20 UTC, KenichiroTanaka commented on doc/src/sgml/indices.sgml
> +派生した式が、行挿入と<link linkend="storage-hot">非HOT更新</link>の度に実行されなければなりませんので、インデックス式は相対的に見て維持が高価です。
すぐ下のrecomputedが「再計算」ですので「計算される」に１票です。

2022-12-19 12:21 UTC, KenichiroTanaka commented
ひととおり確認しました。引き続き石井さんからのご指摘の対応をよろしくお願いします。

2022-12-26 02:16 UTC, kitayama commented on doc/src/sgml/indices.sgml
> +インデックスはまた、<link linkend="storage-hot">ヒープのみのタプル</link>の作成を防ぐこともできます。
遅くなりました。いただいた表現で修正しました。

2022-12-26 02:16 UTC, kitayama commented on doc/src/sgml/indices.sgml
> +派生した式が、行挿入と<link linkend="storage-hot">非HOT更新</link>の度に実行されなければなりませんので、インデックス式は相対的に見て維持が高価です。
他の箇所も確認して「計算される」に変更しました。

2022-12-27 06:21 UTC, tatsuo-ishii approved these changes
確認しました。対応ありがとうございます。

2022-12-27 06:22 UTC, merged