pg_dump.sgmlの15.0対応です
pgsql-jp/jpug-doc pull request #2507
Opened 2022-12-17 01:33 UTC by noborus

2022-12-20 12:43 UTC, KenichiroTanaka requested changes
2箇所気づくところがありましたのでご確認をお願いします。

2022-12-20 12:43 UTC, KenichiroTanaka commented on doc/src/sgml/ref/pg_dump.sgml
> +並行ダンプの性能のため、データベースサーバは同期スナップショットをサポートする必要があります。
「並行ダンプの性能のため」の原文は「To perform a parallel dump」ですが、
performは「実行する」（性能の意は無い）かと思いますので、「並行ダンプを実行するために」
くらいが良いかと思います。

2022-12-20 12:43 UTC, KenichiroTanaka commented on doc/src/sgml/ref/pg_dump.sgml
>  スタンバイサーバからダンプを行う場合、ログを取らないテーブル内のデータは常に除外されます。
「テーブル内のデータは」の箇所でsequencesの訳出が漏れているようです。

2022-12-21 08:23 UTC, noborus commented on doc/src/sgml/ref/pg_dump.sgml
> +並行ダンプの性能のため、データベースサーバは同期スナップショットをサポートする必要があります。
ありがとうございます。なんか勘違いしてたようです。

2022-12-21 08:26 UTC, noborus commented on doc/src/sgml/ref/pg_dump.sgml
>  スタンバイサーバからダンプを行う場合、ログを取らないテーブル内のデータは常に除外されます。
修正します。

2022-12-21 23:39 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。マージします。

2022-12-21 23:39 UTC, merged