mvcc.sgmlのPostgreSQL 15.0対応です。
pgsql-jp/jpug-doc pull request #2513
Opened 2022-12-24 12:03 UTC by tatsuo-ishii

2023-01-01 23:36 UTC, noborus commented on doc/src/sgml/mvcc.sgml
> +<command>UPDATE</command>、<command>DELETE</command>、<command>SELECT FOR UPDATE</command>、および<command>SELECT FOR SHARE</command>コマンドでは、<command>SELECT</command>と同じように対象行を検索します。
`<command>MERGE</command>`が追加されています。

2023-01-01 23:36 UTC, noborus commented on doc/src/sgml/mvcc.sgml
> +   <indexterm>
すみません。indextermは英語、日本語、英語、日本語のように１項目ごとに翻訳を書くようにお願いします。
indextermが増減したときに対応できるようにindextermは直前のindextermに対して日本語訳をぶら下げるようマージのツールでやっています。

2023-01-02 01:11 UTC, KenichiroTanaka requested changes
細かいですが１箇所気づくところがありましたので確認をお願いします。

2023-01-02 10:03 UTC, tatsuo-ishii reviewed
レビューありがとうございます。

2023-01-02 10:03 UTC, tatsuo-ishii commented on doc/src/sgml/mvcc.sgml
>  このようなエラーのメッセージ・テキストは正確な状況によって異なりますが、常にSQLSTATEコード<literal>40001</literal>(<literal>serialization_failure</literal>)があります。
田中さんのご指摘どおりの意図と思います。訳文ですが、

`このようなエラーのメッセージ・テキストは細かい状況によって異なりますが、常にSQLSTATEコードは<literal>40001</literal>(<literal>serialization_failure</literal>)となります。`

としてみました。

ところで、「反復可能読み取り分離レベル」という訳は他にはなく、すべて「リピータブルリード」になっているようなので、そちらに合わせました。

2023-01-03 00:08 UTC, noborus commented on doc/src/sgml/mvcc.sgml
> +   <indexterm>
ありがとうございます。確認しました。

2023-01-03 00:19 UTC, noborus approved these changes

2023-01-04 11:40 UTC, KenichiroTanaka commented
ご対応ありがとうございます。
いただいている訳文の方が良いように思います。
また、「リピータブルリード」に賛成です。

本PRはこの辺りでマージします。

2023-01-04 11:40 UTC, KenichiroTanaka approved these changes

2023-01-04 11:40 UTC, merged