datatype.sgmlのv15対応です
pgsql-jp/jpug-doc pull request #2517
Opened 2023-01-02 02:15 UTC by KenichiroTanaka

2023-01-02 10:32 UTC, tatsuo-ishii requested changes
一通り確認しました。

2023-01-02 10:32 UTC, tatsuo-ishii commented on doc/src/sgml/datatype.sgml
> +これらは一般的な使用を目的としたものではなく、内部的なシステムカタログで使用することを意図しています。
<emphasys>はなくなったものの、"only"はまだ残っているので、onlyを訳出したほうが良くないでしょうか？

2023-01-03 01:12 UTC, KenichiroTanaka commented on doc/src/sgml/datatype.sgml
> +これらは一般的な使用を目的としたものではなく、内部的なシステムカタログで使用することを意図しています。
レビューありがとうございます。
ご指摘の通り、onlyは訳出漏れです。修正します。

2023-01-03 22:58 UTC, noborus reviewed
確認しました。

2023-01-03 22:58 UTC, noborus commented on doc/src/sgml/datatype.sgml
>  この範囲外のスケールを使用すると、他のデータベースシステムに移植できない可能性があります。
上記２つだけ「スケール」になってますが、他は「位取り」で統一されているので、ここも「位取り」で良いと思います。

2023-01-04 11:34 UTC, KenichiroTanaka commented on doc/src/sgml/datatype.sgml
>  この範囲外のスケールを使用すると、他のデータベースシステムに移植できない可能性があります。
ありがとうございます。ご指摘の通りです。修正します。

2023-01-10 06:17 UTC, tatsuo-ishii approved these changes
確認しました。

2023-01-10 06:17 UTC, merged