Update amcheck for 15.0
pgsql-jp/jpug-doc pull request #2520
Opened 2023-01-04 06:49 UTC by kitayama

差分対応と、typo修正、他の箇所との訳語の統一、分かりやすい訳語への変更をしました。

2023-01-08 11:57 UTC, noborus approved these changes
確認しました。変更点も良いと思います。

2023-01-12 07:42 UTC, KenichiroTanaka requested changes
1箇所だけ気になったところがあるので見ていただいてもいいでしょうか。

2023-01-12 07:42 UTC, KenichiroTanaka commented on doc/src/sgml/amcheck.sgml
> +破損タプルのオフセット。
原文がOffsetNumber（Offsetではなく）なので「オフセット番号」くらいの方が良いように思いますがどうでしょうか。

2023-01-16 06:37 UTC, kitayama commented on doc/src/sgml/amcheck.sgml
> +破損タプルのオフセット。
tablesample-method.sgml で offset number を単に「オフセット」と訳していたので番号をわざわざ付けなくてもよいかなと思って「オフセット」と訳していましたが、他の ～Number を見ると明示的に「～番号」となっている(LSN, のでおっしゃる通り「オフセット番号」がよいと思いますので修正します。

2023-01-16 22:41 UTC, KenichiroTanaka commented on doc/src/sgml/amcheck.sgml
> +破損タプルのオフセット。
対応ありがとうございます。
tablesample-method.sgml側も修正した方が良いので
https://github.com/pgsql-jp/jpug-doc/pull/2531
を出しておきました。

2023-01-16 22:42 UTC, KenichiroTanaka approved these changes

2023-01-16 22:42 UTC, merged