update maintenance for 15.0
pgsql-jp/jpug-doc pull request #2523
Opened 2023-01-07 08:41 UTC by koizumistr

maintenance.sgml の15.0対応です。

2023-01-09 22:58 UTC, noborus commented on doc/src/sgml/maintenance.sgml
> +適切な期間を経過した後に、新しいログファイルが開始され、古いログファイルが削除されるように、ログファイルを<emphasis>回転</emphasis>する必要があります。
前からでしたが、ログのときは「ローテーション」で良いように思います。

2023-01-18 23:57 UTC, KenichiroTanaka commented on doc/src/sgml/maintenance.sgml
> +適切な期間を経過した後に、新しいログファイルが開始され、古いログファイルが削除されるように、ログファイルを<emphasis>回転</emphasis>する必要があります。
そうですね。同ファイルに他にも複数箇所ありますのでまとめてお願いしてもいいでしょうか。

2023-01-18 23:58 UTC, KenichiroTanaka requested changes
ひととおり確認しました。「回転」のところだけ対応の検討をお願いします。

2023-01-19 07:13 UTC, KenichiroTanaka commented
回転をローテーションに変更する他のファイルは以下でPRしました。
https://github.com/pgsql-jp/jpug-doc/pull/2523

2023-01-22 06:06 UTC, koizumistr commented
確認ありがとうございます。対応しました。

2023-01-25 22:38 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。

2023-01-25 22:38 UTC, merged