high-availability.sgmlの15.0対応です
pgsql-jp/jpug-doc pull request #2525
Opened 2023-01-09 04:27 UTC by noborus

#2501 の対応も含みました。

2023-01-15 05:44 UTC, tatsuo-ishii requested changes
一通り確認しました。

2023-01-15 05:44 UTC, tatsuo-ishii commented on doc/src/sgml/high-availability.sgml
> +ホットスタンバイがどの様に配置されていても、ホットスタンバイフィードバックは上流に伝播します。
以前からですが、"cascaded"が訳出されていないので、訳したほうが良いと思います。
「ホットスタンバイがどのようにカスケード配置されていても」ではどうでしょう？

2023-01-15 05:44 UTC, tatsuo-ishii commented on doc/src/sgml/high-availability.sgml
> +<varname>archive_command</varname>や<varname>archive_library</varname>では、異なる内容で既存のファイルを上書きしないように注意する必要がありますが、まったく同じファイルが2回アーカイブされた場合は成功を返します。
"it must  be careful to"は"but return success..."にもかかっているのではないでしょうか？なので、訳としては、
「...異なる内容で既存のファイルを上書きしないように、ただしまったく同じファイルが2回アーカイブされた場合は成功を返すように注意する必要があります」あたりではどうでしょう？

2023-01-15 05:44 UTC, tatsuo-ishii commented on doc/src/sgml/high-availability.sgml
> +ホットスタンバイという単語は、サーバがアーカイブリカバリを実行している最中にサーバに接続し読み取り専用の問い合わせを実行することができる機能を説明するために使われます。
"or standby mode"が訳出されていません。

2023-01-15 05:44 UTC, tatsuo-ishii commented on doc/src/sgml/high-availability.sgml
> +
空白行が入っています。

2023-01-15 05:44 UTC, tatsuo-ishii commented on doc/src/sgml/high-availability.sgml
> +<function>pg_cancel_backend()</function>と<function>pg_terminate_backend()</function>は利用者のバックエンドでは実行できますが、リカバリを実行する起動プロセスでは実行できません。
「利用者のバックエンド」ですが、これは利用者のセッションを担当するバックエンドプロセスという意味なので、そのことがわかるように、
「ユーザを扱うバックエンド」あたりではどうでしょう？

2023-01-15 23:04 UTC, noborus commented on doc/src/sgml/high-availability.sgml
> +ホットスタンバイがどの様に配置されていても、ホットスタンバイフィードバックは上流に伝播します。
ありがとうございます。頂きます。

2023-01-15 23:05 UTC, noborus commented on doc/src/sgml/high-availability.sgml
> +<varname>archive_command</varname>や<varname>archive_library</varname>では、異なる内容で既存のファイルを上書きしないように注意する必要がありますが、まったく同じファイルが2回アーカイブされた場合は成功を返します。
ありがとうございます。頂きます。

2023-01-15 23:05 UTC, noborus commented on doc/src/sgml/high-availability.sgml
> +ホットスタンバイという単語は、サーバがアーカイブリカバリを実行している最中にサーバに接続し読み取り専用の問い合わせを実行することができる機能を説明するために使われます。
修正します。

2023-01-15 23:07 UTC, noborus commented on doc/src/sgml/high-availability.sgml
> +
これは原文に `<itemizedlist>`の前に空行が入っているたため、入れるように修正しました。

2023-01-15 23:07 UTC, noborus commented on doc/src/sgml/high-availability.sgml
> +<function>pg_cancel_backend()</function>と<function>pg_terminate_backend()</function>は利用者のバックエンドでは実行できますが、リカバリを実行する起動プロセスでは実行できません。
ありがとうございます。頂きます。

2023-01-15 23:28 UTC, tatsuo-ishii approved these changes
確認しました。対応ありがとうございます。

2023-01-19 07:06 UTC, KenichiroTanaka approved these changes
ひととおり確認しました。

2023-01-19 07:06 UTC, merged