backup.sgmlのPostgreSQL 15.0対応です。
pgsql-jp/jpug-doc pull request #2529
Opened 2023-01-14 05:15 UTC by tatsuo-ishii

1453-1454行あたりで、原文の間違いでarchive_commandが繰り返されているのは訳からは削除しています。 なお、原文の間違いについては修正パッチを本家に投稿済みです。

2023-01-14 09:22 UTC, tatsuo-ishii commented
原文の修正パッチはREL_15_STABLEブランチにコミットされました。
https://git.postgresql.org/gitweb/?p=postgresql.git;a=commit;h=40015cf8ec7a0384a0320c11a31fdeebba4b8e15

2023-01-15 03:30 UTC, tatsuo-ishii commented
archive_command重複の件は、私より早くすでに斉藤さんがpgsql-docsで指摘されていたのですね。気が付かず申し訳ありませんでした。

2023-01-15 03:35 UTC, tatsuo-ishii reviewed
レビューありがとうございます。

2023-01-15 03:35 UTC, tatsuo-ishii commented on doc/src/sgml/backup.sgml
>  このコマンドは単純な<literal>cp</literal>でも構いませんし、また、複雑なシェルスクリプトを呼び出しても構いません。
おっと、そうでした。

2023-01-15 03:35 UTC, tatsuo-ishii commented on doc/src/sgml/backup.sgml
> +WAL保管を有効にするには、<xref linkend="guc-wal-level"/>設定パラメータを<literal>replica</literal>以上に、<xref linkend="guc-archive-mode"/>を<literal>on</literal>に設定し、<xref linkend="guc-archive-command"/>設定パラメータで使用するシェルコマン
そうします。

2023-01-15 03:35 UTC, tatsuo-ishii commented on doc/src/sgml/backup.sgml
> +アーカイブ用コマンドがシグナル（サーバのシャットダウンの一部として使用される<systemitem>SIGTERM</systemitem>以外）やシェルによる125以上の終了ステータスを持つエラー（command not foundなど）、あるいはアーカイブ関数が<literal>ERROR</literal>または<literal>FATAL</literal>を出力したことによって終了する
そうですね。

2023-01-15 23:14 UTC, noborus commented
> archive_command重複の件は、私より早くすでに斉藤さんがpgsql-docsで指摘されていたのですね。気が付かず申し訳ありませんでした。

いえいえ。まさかここにきて、同じタイミングでかぶると思いませんでいた :sweat_smile:

2023-01-24 05:05 UTC, noborus commented
確認しました。他のところでアーカイブ用コマンドがあるので、統一しても良いかと思いましたが、後でも良いのでよいことにします。

2023-01-24 05:10 UTC, noborus approved these changes

2023-01-26 14:15 UTC, KenichiroTanaka requested changes
いくつか気づいたところがありましたので確認をお願いします。

2023-01-26 14:15 UTC, KenichiroTanaka commented on doc/src/sgml/backup.sgml
> +実行権限を持つユーザ<function>pg_backup_start</function>としてサーバ（どのデータベースであってもかまいません）に接続します。ユーザはスーパーユーザか、またはこの関数に<literal>EXECUTE</literal>権限を与えられたユーザです。以下のコマンドを発行します。
「実行権限を持つユーザ<function>pg_backup_start</function>としてサーバ（どのデータベースであってもかまいません）に接続します。」の場合、pg_backup_startというユーザが存在するように読めてしまいます。

「<function>pg_backup_start</function>の実行権限を持つユーザとしてサーバ（どのデータベースであってもかまいません）に接続します。」
とするのはどうでしょうか。

2023-01-26 14:15 UTC, KenichiroTanaka commented on doc/src/sgml/backup.sgml
> +オンラインバックアップは、常にチェックポイントの先頭から開始されます。
少し自信がありませんが、
「Online backups are always started at the beginning of a checkpoint」は
「オンラインバックアップは、常にチェックポイントの先頭から開始されます。」ではなく
「オンラインバックアップは、常にチェックポイントから始まります。」という意図ではないでしょうか。

2023-01-27 04:59 UTC, tatsuo-ishii commented on doc/src/sgml/backup.sgml
> +このコマンドは単純な<literal>cp</literal>でも構いませんし、また、複雑なC関数を呼び出しても構いません。
いただきます。

2023-01-27 06:41 UTC, tatsuo-ishii reviewed
レビューありがとうございます。

2023-01-27 06:47 UTC, tatsuo-ishii commented on doc/src/sgml/backup.sgml
>  一時的にアーカイビングを停止したい場合、１つの方法は<varname>archive_command</varname>を空文字列（<literal>''</literal>）に設定することです。
ありがとうございます。いただきます。

2023-01-28 14:25 UTC, KenichiroTanaka commented on doc/src/sgml/backup.sgml
> +オンラインバックアップは、常にチェックポイントの先頭から開始されます。
なるほど。確かにそういう意図の方が辻褄が合います。当初案で良いと思います。

2023-01-28 14:25 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。

2023-01-28 14:26 UTC, merged