charset.sgmlのPostgreSQL 15.0対応です。
pgsql-jp/jpug-doc pull request #2543
Opened 2023-02-03 11:23 UTC by tatsuo-ishii

2023-02-07 12:56 UTC, KenichiroTanaka requested changes
1箇所気づくところがありましたので見ていただいてもいいでしょうか。

2023-02-07 12:56 UTC, KenichiroTanaka commented on doc/src/sgml/charset.sgml
>  これは<firstterm>collation</firstterm>というSQLオブジェクトを使用します。
collationは他では照合順序と訳されているのでここは合わせた方が良いように思います。

2023-02-16 05:20 UTC, tatsuo-ishii reviewed
レビューありがとうございます。

2023-02-16 05:20 UTC, tatsuo-ishii commented on doc/src/sgml/charset.sgml
>  これは<firstterm>collation</firstterm>というSQLオブジェクトを使用します。
そうですね。修正します。

2023-02-16 13:18 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。

2023-02-16 13:19 UTC, merged