update earthdistance for 15.0
pgsql-jp/jpug-doc pull request #2555
Opened 2023-02-11 02:32 UTC by koizumistr

earthdistance.sgml の15.0対応です。

reasonablyの訳もドサクサに紛れて変えています。

2023-02-23 09:09 UTC, tatsuo-ishii requested changes
確認しました。

2023-02-23 09:09 UTC, tatsuo-ishii commented on doc/src/sgml/earthdistance.sgml
> +地球中心からのx、y、z距離をあらわす3次元を使用した点（両隅が同じ）であるcubeとして、データは格納されます。
3 cordinatesを「3次元」と訳していますが、「3つの座標」の意味だと思います。

2023-02-28 13:18 UTC, koizumistr commented
確認ありがとうございます。確かに指摘の通りと思います。対応しました。

2023-03-05 01:00 UTC, tatsuo-ishii approved these changes
確認しました。対応ありがとうございます。

2023-03-05 01:00 UTC, merged