update *_database for 15.0
pgsql-jp/jpug-doc pull request #2560
Opened 2023-02-18 06:20 UTC by koizumistr

以下のファイルの15.0対応です。

- ref/alter_database.sgml
- ref/create_database.sgml
- ref/createdb.sgml

2023-03-05 22:47 UTC, KenichiroTanaka requested changes
1箇所だけ気になるところがありましたので見ていただけないでしょうか。

2023-03-05 22:47 UTC, KenichiroTanaka commented on doc/src/sgml/ref/create_database.sgml
> +この手法は、ターゲットデータベースが使用する各テーブル空間の先行書き込みログに小さいレコードを書き込みます。
今の表現はfor以下がlogにかかっていますが技術的にはrecordをにかかるように思います。
ですので、
「この手法は、ターゲットデーターベースが使用する各テーブル空間のための小さなレコードを先行書き込みログに書き込みます。」
とするのが良いように思うのですが、どうでしょうか。

@tatsuo-ishii さん
少し自信がありませんのでアドバイスいただけますと助かります。

2023-04-26 14:44 UTC, KenichiroTanaka commented
少なくとも
「この手法は、ターゲットデータベースが使用する各テーブル空間の先行書き込みログに小さいレコードを書き込みます。」については「各テーブル空間の先行書き込みログ」というものは存在しないので、NGかなと思います。

ひとまず先に提案しました

「この手法は、ターゲットデーターベースが使用する各テーブル空間のための小さなレコードを先行書き込みログに書き込みます。」

でマージするのはどうでしょうか。

2023-04-30 02:57 UTC, koizumistr commented
コメントありがとうございます。自分の訳を否定する根拠が、単純に英語からだけだと出てこなかったので、ためらっていたのですが、

> 「各テーブル空間の先行書き込みログ」というものは存在しない

ということであれば、心置きなく修正できます。

2023-05-01 02:57 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。
マージします。

2023-05-01 02:57 UTC, merged