postgres-fdw.sgmlのPostgreSQL 15.0対応です。
pgsql-jp/jpug-doc pull request #2565
Opened 2023-02-26 07:25 UTC by tatsuo-ishii

2023-03-06 13:18 UTC, KenichiroTanaka requested changes
1箇所だけ気づくところがありましたので確認をお願いします。

2023-03-06 13:18 UTC, KenichiroTanaka commented on doc/src/sgml/postgres-fdw.sgml
> +ローカルサーバ上のカスタム名（詳細は<xref linkend="guc-cluster-name"/>を参照）
「カスタム名」は「クラスタ名」かと思います。

2023-03-08 10:35 UTC, tatsuo-ishii reviewed
レビューありがとうございます。

2023-03-08 10:35 UTC, tatsuo-ishii commented on doc/src/sgml/postgres-fdw.sgml
> +ローカルサーバ上のカスタム名（詳細は<xref linkend="guc-cluster-name"/>を参照）
ご指摘ありがとうございます。

2023-03-08 13:21 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。
他に気づくところはありませんでしたのでマージします。

2023-03-08 13:22 UTC, merged