protocol.sgmlの15.0対応です
pgsql-jp/jpug-doc pull request #2569
Opened 2023-03-05 00:36 UTC by noborus

2023-03-17 07:57 UTC, tatsuo-ishii requested changes
一通り確認しました。

2023-03-17 07:57 UTC, tatsuo-ishii commented on doc/src/sgml/protocol.sgml
> +実行サイクル全体は、テキストの問い合わせ文字列からプリペアド文を生成する<firstterm>解析</firstterm>段階、プリペアド文と必要なパラメータ値によりポータルを作成する<firstterm>バインド</firstterm>段階、ポータルの問い合わせを実行する<firstterm>実行</firstterm>段階からなります。
前からですが、parse, bind, executeは翻訳しないほうが良いと思います。この文以降、ほとんどの翻訳箇所でParse, Bind, Executeは英文のままで「解析」「バインド」「実行」とは翻訳されていません。ここだけ日本語にするのは不自然かと思います。また、parseやexecuteはこの文書ではプロトコルの種類を表す意味で使われていますが、日本語にすると概念としての範囲が広過ぎて、この文書での文脈としては焦点がボケる気がします。

2023-03-17 07:57 UTC, tatsuo-ishii commented on doc/src/sgml/protocol.sgml
> +レプリケーションコマンドをテストするために、<literal>replication</literal>オプションを含む接続文字列を使用して、<application>psql</application>または他の<application>libpq</application>によるレプリケーション接続を作成できます。
"-using tool"が訳出されていません。

2023-03-17 07:57 UTC, tatsuo-ishii commented on doc/src/sgml/protocol.sgml
> +しかし、物理的レプリケーションのために<xref linkend="app-pgreceivewal"/>を使用し、論理的レプリケーションのため<xref linkend="app-pgrecvlogical"/>を使用すれば、もっと有用なことが多いです。
「論理的レプリケーションのため」→「論理的レプリケーションのために」

2023-03-17 07:57 UTC, tatsuo-ishii commented on doc/src/sgml/protocol.sgml
>  そうでなければ、<acronym>WAL</acronym>はストリーミングレプリケーションクライアントからの接続に応じてだけ予約されます。
upon connectionは、「接続時に」という意味ではないでしょうか？

2023-03-17 07:57 UTC, tatsuo-ishii commented on doc/src/sgml/protocol.sgml
>  バックアップが開始される前に、システムは自動的にバックアップモードになり、バックアップが完了するとシステムから削除されます。
前からですが、taken out of itを「削除されます」と訳すのは間違いで、「（バックアップモードから）復帰します」ということだと思います。

2023-03-17 07:57 UTC, tatsuo-ishii commented on doc/src/sgml/protocol.sgml
> +現在、このオプションはバックアップターゲットが<literal>サーバ</literal>の場合にのみ使用できます。
<literal>server</literal>を<literal>サーバ</literal>と訳してしまうのはここでは間違いだと思います。"server"はパラメータ名なので。

2023-03-17 07:57 UTC, tatsuo-ishii commented on doc/src/sgml/protocol.sgml
> +falseの場合、バックアップは待機も警告もせず、必要なログが利用できるようになったことの確認をクライアントに負わせます。
「必要なログが利用できるようになったことの確認をクライアントに負わせます。」は日本語として少し不自然な感じがするので、
「必要なログが利用できるようになったことの確認をクライアントに任せます」ではどうでしょう？

2023-03-17 07:57 UTC, tatsuo-ishii commented on doc/src/sgml/protocol.sgml
> +次に、各列について以下のメッセージ部分があります。（生成列を除く）
"included in  the publication"が訳出されていません。

2023-03-17 07:57 UTC, tatsuo-ishii commented on doc/src/sgml/protocol.sgml
> +プリペアドトランザクションの終了LSNです。
他の箇所では「準備されたトランザクション」と訳出しているようです。

2023-03-17 07:57 UTC, tatsuo-ishii commented on doc/src/sgml/protocol.sgml
> +準備されたLSNです。
ここで言っている"the prepare"は、"the prepared transaction"の意味だと思います。

2023-03-22 20:24 UTC, noborus commented on doc/src/sgml/protocol.sgml
> +実行サイクル全体は、テキストの問い合わせ文字列からプリペアド文を生成する<firstterm>解析</firstterm>段階、プリペアド文と必要なパラメータ値によりポータルを作成する<firstterm>バインド</firstterm>段階、ポータルの問い合わせを実行する<firstterm>実行</firstterm>段階からなります。
ありがとうございます。修正します。

2023-03-22 20:25 UTC, noborus commented on doc/src/sgml/protocol.sgml
> +しかし、物理的レプリケーションのために<xref linkend="app-pgreceivewal"/>を使用し、論理的レプリケーションのため<xref linkend="app-pgrecvlogical"/>を使用すれば、もっと有用なことが多いです。
修正します。

2023-03-22 20:26 UTC, noborus commented on doc/src/sgml/protocol.sgml
>  そうでなければ、<acronym>WAL</acronym>はストリーミングレプリケーションクライアントからの接続に応じてだけ予約されます。
修正します。

2023-03-22 20:31 UTC, noborus commented on doc/src/sgml/protocol.sgml
>  バックアップが開始される前に、システムは自動的にバックアップモードになり、バックアップが完了するとシステムから削除されます。
なるほど。put inとtaken out の組だと思うので、一旦それで書いてみます。

2023-03-22 20:31 UTC, noborus commented on doc/src/sgml/protocol.sgml
> +falseの場合、バックアップは待機も警告もせず、必要なログが利用できるようになったことの確認をクライアントに負わせます。
ありがとうございます。いただきます。

2023-03-22 20:32 UTC, noborus commented on doc/src/sgml/protocol.sgml
> +次に、各列について以下のメッセージ部分があります。（生成列を除く）
修正します。

2023-03-22 20:33 UTC, noborus commented on doc/src/sgml/protocol.sgml
> +プリペアドトランザクションの終了LSNです。
プリペアドで統一するように他を修正します。

https://github.com/pgsql-jp/jpug-doc/discussions/2490

2023-03-22 20:36 UTC, noborus commented on doc/src/sgml/protocol.sgml
> +準備されたLSNです。
どう書くべきか、まだわかってないのでプリペアドで書いてみます。

2023-03-23 07:57 UTC, tatsuo-ishii approved these changes
対応ありがとうございました。

2023-03-23 07:57 UTC, merged