update pgupgrade for 15.0
pgsql-jp/jpug-doc pull request #2577
Opened 2023-03-18 06:33 UTC by koizumistr

ref/pgupgrade.sgml の15.0対応です。

2023-03-27 02:49 UTC, noborus approved these changes
確認しました。指摘事項はありません。

2023-03-28 02:57 UTC, tatsuo-ishii requested changes
一通り確認しました。

2023-03-28 02:57 UTC, tatsuo-ishii commented on doc/src/sgml/ref/pgupgrade.sgml
> +このオプションで<command>pg_upgrade</command>は待たずに戻るようになります。これはより高速ですが、その直後のオペレーティングシステムのクラッシュによってデータディレクトリが壊れたままになる可能性があることを意味します。
今回subsequentの訳を「その後」から「直後」に変更されていますが、これは意図してのことでしょうか？
subsequentは、ある時点以降を指しており、特に「直後」という限定は無いようなきがします。

2023-04-13 22:49 UTC, KenichiroTanaka approved these changes
ひととおり確認しました。

2023-04-15 06:18 UTC, tatsuo-ishii approved these changes
確認しました。対応ありがとうございます。

2023-04-15 06:19 UTC, merged