update *_subscription for 15.0
pgsql-jp/jpug-doc pull request #2579
Opened 2023-03-19 06:03 UTC by koizumistr

以下のファイルの15.0対応です。

- ref/alter_subscription.sgml
- ref/create_subscription.sgml

2023-03-22 21:36 UTC, noborus commented on doc/src/sgml/ref/create_subscription.sgml
> +パブリッシャーデータベースへの接続を定義する接続文字列です。
`<application>libpq</application>`が抜けています。

2023-03-22 21:36 UTC, noborus commented on doc/src/sgml/ref/create_subscription.sgml
> +この句は、サブスクリプションのオプションのパラメーターを指定します。
パラメーター（他はパラメータ）は、すぐに置き換え予定ではないので、パラメータにしておいてもらうのが良いと思います。

2023-03-24 23:25 UTC, koizumistr commented
確認ありがとうございます。対応しました。

2023-03-27 21:53 UTC, noborus commented on doc/src/sgml/ref/create_subscription.sgml
> +(この設定は、<literal>create_slot</literal>、<literal>enabled</literal>、または<literal>copy_data</literal>を<literal>true</literal>にすることと組み合わせることはできません。)
`setting <literal>connect</literal> to <literal>false</literal> with` に該当する訳が抜けてます

2023-03-28 09:10 UTC, koizumistr commented
確認ありがとうございます。対応しました。

2023-03-28 21:07 UTC, noborus commented
ありがとうございます。確認しました。

2023-03-28 21:07 UTC, noborus approved these changes

2023-04-03 10:32 UTC, KenichiroTanaka requested changes
細かいですが1箇所見ていただけないでしょうか。

2023-04-03 10:32 UTC, KenichiroTanaka commented on doc/src/sgml/ref/alter_subscription.sgml
> +この句では、元は<xref linkend="sql-createsubscription"/>により設定された接続文字列を変更します。
```
-      This clause alters the connection property originally set by
+      This clause replaces the connection string originally set by
```
と、
細かいですが原文がalterからreplaceになっていますので、「設定された接続文字列を変更します。」は「設定された接続文字列を置き換えます。」とするのはどうでしょうか。

2023-04-05 23:33 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。

2023-04-05 23:33 UTC, merged