flushの訳をフラッシュに修正
pgsql-jp/jpug-doc pull request #2583
Opened 2023-03-22 20:55 UTC by noborus

#2574 の修正です。
一部まだ翻訳未完了のファイルは除いています。

2023-03-22 23:20 UTC, KenichiroTanaka requested changes
前からのところですが１箇所気づいたところがありましたので見ていただけないでしょうか。

2023-03-22 23:20 UTC, KenichiroTanaka commented on doc/src/sgml/config.sgml
> +<varname>wal_writer_flush_after</varname>が<literal>0</literal>に設定されている場合は、WALが書かれるたびにWALがフラッシュされます。
以前からのところですが、
「WALが書かれるたびにWALがフラッシュされます。」
のところは原文が
「WAL data is always flushed immediately.」
ですので、
・dataが訳出されていない
・immediatelyが訳出されていない
の２点が気になりました。
「WALデータが書かれるたびにWALが即時にフラッシュされます。」
くらいの訳とするのはどうでしょうか。

2023-03-22 23:20 UTC, KenichiroTanaka commented on doc/src/sgml/config1.sgml
> +<varname>wal_writer_flush_after</varname>が<literal>0</literal>に設定されている場合は、WALが書かれるたびにWALがフラッシュされます。
(誤って分割前の行にコメントしてしまいましたのでこちらにも同じコメントを記載します。)
以前からのところですが、
「WALが書かれるたびにWALがフラッシュされます。」
のところは原文が
「WAL data is always flushed immediately.」
ですので、
・dataが訳出されていない
・immediatelyが訳出されていない
の２点が気になりました。
「WALデータが書かれるたびにWALが即時にフラッシュされます。」
くらいの訳とするのはどうでしょうか。

2023-03-26 23:32 UTC, noborus commented on doc/src/sgml/config.sgml
> +<varname>wal_writer_flush_after</varname>が<literal>0</literal>に設定されている場合は、WALが書かれるたびにWALがフラッシュされます。
ありがとうございます。修正します。

2023-03-31 12:05 UTC, KenichiroTanaka approved these changes
すみません、その後反応が遅くなりました。
対応ありがとうございます。

2023-03-31 12:05 UTC, merged