Update for release-15
pgsql-jp/jpug-doc pull request #2588
Opened 2023-03-29 09:38 UTC by kitayama

遅くなりました。release-15 を一通り対応しました。文末の表現のゆれ(ぶれ)などがあるかと思いますが一度 pull request をしてレビューしていただくことを優先します。

2023-03-29 21:46 UTC, noborus reviewed
とりあえずtypoの指摘です

2023-03-29 21:46 UTC, noborus commented on doc/src/sgml/release-15.sgml
> +<link linkend="datatype-datetime"><type>inteval</type></link>型の入力が月より大きい単位の小数値を提供する場合、最も近い月に丸めます。
`<type>interval</type>`です

2023-03-29 21:46 UTC, noborus commented on doc/src/sgml/release-15.sgml
>  (Alikksandr Kalenik、Sergei Shoulbakov、Andrey Brodin)
`Aliaksandr Kalenik`です

2023-03-30 08:10 UTC, tatsuo-ishii requested changes
一通り確認しました。

2023-03-30 08:10 UTC, tatsuo-ishii commented on doc/src/sgml/release-15.sgml
> +出力が端末でない場合、<application>pg_upgrade</application>操作中のデフォルトステータス報告を無効にします。
「します。」→「しました。」

2023-03-30 08:10 UTC, tatsuo-ishii commented on doc/src/sgml/release-15.sgml
> +<application>pg_waldump</application>が複数のリソースマネージャに関する情報をダンプできます。
「できます。」→「できるようにしました。」

2023-03-30 08:10 UTC, tatsuo-ishii commented on doc/src/sgml/release-15.sgml
> +<type>"char"</type>の新しい<link linkend="catalog-pg-type"><structfield>pg_type.typcategory</structfield></link>値を作成します。
「します。」→「しました。」

2023-03-30 08:10 UTC, tatsuo-ishii commented on doc/src/sgml/release-15.sgml
> +Windowsでは、<literal>PGDLLIMPORT</literal>印を使用してサーバのすべてのグローバル変数をエクスポートします。
「します。」→「しました。」

2023-03-30 08:10 UTC, tatsuo-ishii commented on doc/src/sgml/release-15.sgml
> +<link linkend="pgcrypto"><application>pgcrypto</application></link>拡張モジュールのビルドにはOpenSSLが必要です。
「が必要です。」→「を必須としました。」

2023-03-30 08:10 UTC, tatsuo-ishii commented on doc/src/sgml/release-15.sgml
> +<application>Perl</application>バージョン5.8.3以降が必要です。
「必要です。」→「必要としました。」

2023-03-30 08:10 UTC, tatsuo-ishii commented on doc/src/sgml/release-15.sgml
> +<application>Python</application>バージョン3.2以降が必要です。
「必要です。」→「必要としました。」

2023-03-30 08:10 UTC, tatsuo-ishii commented on doc/src/sgml/release-15.sgml
> +<link linkend="sepgsql"><application>sepgsql</application></link>ログメッセージにpermissive/enforcing状態を示します。
「示します。」→「示すようにしました。」

2023-04-01 05:02 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +新しいデフォルトは、CVE-2018-1058のセキュリティリリース以降<xref linkend="ddl-schemas-patterns"/>で推奨している安全なスキーマ使用パターンの1つです。
レビューありがとうございます。追記しました。

2023-04-01 05:02 UTC, kitayama commented on doc/src/sgml/release-15.sgml
>  (Alikksandr Kalenik、Sergei Shoulbakov、Andrey Brodin)
修正しました。

2023-04-01 05:02 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +<link linkend="datatype-datetime"><type>inteval</type></link>型の入力が月より大きい単位の小数値を提供する場合、最も近い月に丸めます。
レビューありがとうございます。修正しました。

2023-04-01 05:02 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +クラスタをアップグレードするか、データベースダンプを復元すると、<literal>public</literal>の既存の所有者仕様が保持されます。
おっしゃる通り、仕様は変ですね。設定に変更しました。

2023-04-01 05:07 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +<link linkend="guc-hash-mem-multiplier"><varname>hash_mem_multiplier</varname></link>のデフォルトを2.0に増やします。
修正しました。

2023-04-01 05:07 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +上位ビットが設定されたバイトは、エンコーディングの問題を避けるために、バックスラッシュと3桁の八進数として出力されるようになりました。
修正しました。

2023-04-01 05:07 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +廃止予定のサーバパラメータ<varname>stats_temp_directory</varname>を削除しました。
修正しました。

2023-04-01 05:08 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +Windowsでは、<literal>PGDLLIMPORT</literal>印を使用してサーバのすべてのグローバル変数をエクスポートします。
修正しました。

2023-04-01 05:08 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +<link linkend="pgcrypto"><application>pgcrypto</application></link>拡張モジュールのビルドにはOpenSSLが必要です。
修正しました。

2023-04-01 05:08 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +<application>Perl</application>バージョン5.8.3以降が必要です。
修正しました。

2023-04-01 05:08 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +<application>Python</application>バージョン3.2以降が必要です。
修正しました。

2023-04-01 05:09 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +<link linkend="sepgsql"><application>sepgsql</application></link>ログメッセージにpermissive/enforcing状態を示します。
修正しました。

2023-04-03 23:31 UTC, kitayama commented
>私の指摘の大半が対応されていないようです。行番号で言うと、以下です。

ご指摘事項を正しく理解しておらず大変失礼いたしました。
至急、対応させていただきます。

2023-04-04 05:39 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +<link linkend="app-psql"><application>psql</application></link>の<option>&#45;-single-transaction</option>モードでエラーが検出された後、<varname>ON_ERROR_STOP</varname>が設定されている場合にのみ、最後の<command>COMMIT</command>コマンドを
対応しました。

2023-04-04 05:39 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +<link linkend="postgres-fdw">postgres_fdw</link>が送信する問い合わせで、不要な定数のキャストを行わないようにします。
対応しました。

2023-04-04 05:40 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +<link linkend="custom-scan">カスタムスキャンプロバイダ</link>が射影をサポートしているかどうかを示すことをできるようになりました。
対応しました。

2023-04-04 05:41 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +デフォルトでは、カスタムスキャンプロバイダは射影をサポートしていないと見なされます。
対応しました。

2023-04-04 05:45 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +各<link linkend="sql-createdatabase">データベース</link>の照合順序バージョンを記録し、チェックします。
対応しました。

2023-04-04 05:49 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +パーティション間での行移動を伴うパーティションテーブル更新における外部キーの動作が改善しました。
「動作が改善されました。」に修正しました。

2023-04-04 05:49 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +一度に16バイトを処理することで<acronym>UTF</acronym>-8テキストのエンコーディング妥当性検証を高速化します。
対応しました。

2023-04-04 05:54 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +ソートデータが<varname>work_mem</varname>に収まらなくなったら、以前より多くの出力ストリームを使用するバッチソートアルゴリズムに切り替えます。
「切り替えます。」→「切り替えるようにしました。」に変更しました。

2023-04-04 05:55 UTC, kitayama commented on doc/src/sgml/release-15.sgml
>  (Kyotaro Horiguchi, Andres Freund, Melanie Plageman)
「保存します。」→「保存するようにしました。」に変更しました。

2023-04-04 05:56 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +一時ファイルブロックI/Oに対する<link linkend="sql-explain"><command>EXPLAIN (BUFFERS)</command></link>出力を追加します。
対応しました。

2023-04-04 05:57 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +<link linkend="predefined-roles-table"><literal>pg_read_all_stats</literal></link>事前定義ロールのメンバがビュー<link linkend="view-pg-backend-memory-contexts"><structname>pg_backend_memory_contexts</structname></l
対応しました。

2023-04-04 05:57 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +Solarisでは、<link linkend="guc-dynamic-shared-memory-type"><varname>dynamic_shared_memory_type</varname></link>のデフォルト設定を<literal>sysv</literal>にします。
対応しました。

2023-04-04 05:59 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +ロード可能なモジュールによるアーカイブが可能になりました。
対応しました。

2023-04-04 05:59 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +<link linkend="view-pg-publication-tables"><structname>pg_publication_tables</structname></link>システムビューで重複するエントリを抑制します。
対応しました。

2023-04-04 06:02 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +ログを記録しない<link linkend="sql-createsequence">シーケンス</link>作成ができるようにしました。
対応しました。

2023-04-04 06:11 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +<link linkend="datatype-numeric"><type>数値</type></link>の位取りを負にしたり、より精度を大きくすることができます。
対応しました。

2023-04-04 06:11 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +絵文字のような最新のUnicode文字の表示幅情報を更新します。
対応しました。

2023-04-04 06:16 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +<link linkend="datatype-polygon"><type>ポリゴン</type></link>間の距離を計算する機能を追加します。
対応しました。

2023-04-04 06:16 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +クライアントから送信されるクエリキャンセルは、通常のクライアント接続と同じ<acronym>TCP</acronym>設定を使用するように変更します。
対応しました。

2023-04-04 06:17 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +<option>--single-transaction</option>モードでエラーが検出された後、<varname>ON_ERROR_STOP</varname>が設定されている場合にのみ、最後の<command>COMMIT</command>コマンドを<command>ROLLBACK</command>に変更します。
対応しました。

2023-04-04 06:18 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +<application>pg_upgrade</application>のログファイルと一時ファイルを<filename>pg_upgrade_output.d</filename>という新しいクラスタのサブディレクトリに保存します。
「保存します。」→「保存するようにしました。」に変更しました。

2023-04-04 06:19 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +<application>pg_waldump</application>が複数のリソースマネージャに関する情報をダンプできます。
対応しました。

2023-04-04 06:20 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +<type>"char"</type>の新しい<link linkend="catalog-pg-type"><structfield>pg_type.typcategory</structfield></link>値を作成します。
対応しました。

2023-04-04 09:11 UTC, kitayama commented
@tatsuo-ishii さん、
途中の「27 hidden conversations」の存在に気付かずに未対応となって申し訳ありませんでした。
ご指摘いただいた内容はすべて対応しました。また他に気付いた点も修正を入れています。
ご確認よろしくお願いします。

2023-04-06 00:09 UTC, tatsuo-ishii approved these changes
確認しました。対応ありがとうございます。

2023-04-07 08:11 UTC, noborus commented on doc/src/sgml/release-15.sgml
> +<productname>PostgreSQL</productname>15には、以下をはじめとする多数の新機能と拡張が含まれます。
英語と日本語の間のスペースは取るようにしていますが、英語と数字の場合は、もともとあったスペースをのままにしておいた方が良いように思います。
PostgreSQL15のように表示されるため、`<productname>PostgreSQL</productname> 15`にする。

2023-04-07 08:14 UTC, noborus commented on doc/src/sgml/release-15.sgml
> +<acronym>SQL</acronym><link linkend="sql-merge"><command>MERGE</command></link>コマンドがサポートされました。
ここも同様に原文だと改行が入っているためスペースが入りますが、日本語版だとSQLMERGEのように表示されるため、
`<acronym>SQL</acronym> <link linkend="sql-merge"><command>MERGE</command></link>`のようにスペースを入れるのが良いと思います。もしかしたら`SQLのMERGEコマンド`の方が自然かもしれません。

2023-04-07 08:15 UTC, noborus commented on doc/src/sgml/release-15.sgml
> +<productname>PostgreSQL</productname>15の上記の項目とその他の新機能は次節でより詳しく説明されます。
ここもスペースを追加。

2023-04-13 02:42 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +<productname>PostgreSQL</productname>15には、以下をはじめとする多数の新機能と拡張が含まれます。
レビューありがとうございます。上記の箇所も含めてPostgreSQL <バージョン番号>の箇所はすべてスペースを入れました。

2023-04-13 02:43 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +<acronym>SQL</acronym><link linkend="sql-merge"><command>MERGE</command></link>コマンドがサポートされました。
もう一か所も含めて、明示的に「SQLのMERGEコマンド」と間に「の」を入れるようにしました。

2023-04-13 02:43 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +<productname>PostgreSQL</productname>15の上記の項目とその他の新機能は次節でより詳しく説明されます。
対応しました。

2023-04-13 07:02 UTC, tatsuo-ishii commented
確認しました。マージします。

2023-04-13 07:02 UTC, merged