custom-rmgr.sgmlの15.0対応です
pgsql-jp/jpug-doc pull request #2589
Opened 2023-04-01 22:15 UTC by noborus

2023-04-03 12:46 UTC, koizumistr reviewed
中身がよく分かっていないまま指摘している、という自信があります(T_T)

2023-04-03 12:46 UTC, koizumistr commented on doc/src/sgml/custom-rmgr.sgml
>   新しい拡張を開発する際には、<parameter>rmid</parameter>に<literal>RM_EXPERIMENTAL_ID</literal>を使用してください。
行頭に余分な空白があるようです。

2023-04-03 12:46 UTC, koizumistr commented on doc/src/sgml/custom-rmgr.sgml
> + * があります。https://wiki.postgresql.org/wiki/CustomWALResourceManagersを参照して、
ここは
必要があります。（改行）
https://~
としてほしいような。（何か制限があるわけではないですよね）

2023-04-03 12:46 UTC, koizumistr commented on doc/src/sgml/custom-rmgr.sgml
> + * rm_identifyは、xl_info（rmidへの結果なし）に基づいて、名前のレコードを
結果なし -> 参照なし

2023-04-03 12:46 UTC, koizumistr commented on doc/src/sgml/custom-rmgr.sgml
> + * バキュームになります。その後、rm_descを呼び出して、可能であれば（最後のブロックなど）、
たとえば、XLOG_BTREE_VACUUMは"VACUUM"という名前になります。

ということかと。

2023-04-03 12:46 UTC, koizumistr commented on doc/src/sgml/custom-rmgr.sgml
> + * rm_nameの場合、対応するRmgrTableエントリは無効と見なされます。
-> rm_nameがNULLの場合、

2023-04-03 21:29 UTC, noborus commented on doc/src/sgml/custom-rmgr.sgml
>   新しい拡張を開発する際には、<parameter>rmid</parameter>に<literal>RM_EXPERIMENTAL_ID</literal>を使用してください。
修正します。

2023-04-03 21:32 UTC, noborus commented on doc/src/sgml/custom-rmgr.sgml
> + * があります。https://wiki.postgresql.org/wiki/CustomWALResourceManagersを参照して、
修正します。
URLの終わりはスペースを入れるようにしました。

2023-04-03 21:34 UTC, noborus commented on doc/src/sgml/custom-rmgr.sgml
> + * rm_identifyは、xl_info（rmidへの結果なし）に基づいて、名前のレコードを
ありがとうございます。このブロックは意味不明だったのでやり直しました。

2023-04-03 21:34 UTC, noborus commented on doc/src/sgml/custom-rmgr.sgml
> + * rm_nameの場合、対応するRmgrTableエントリは無効と見なされます。
ありがとうございます。修正しました。

2023-04-04 11:57 UTC, koizumistr commented
対応ありがとうございます。確認しました。

2023-04-07 06:48 UTC, tatsuo-ishii requested changes
一通り確認しました。

2023-04-07 06:48 UTC, tatsuo-ishii commented on doc/src/sgml/custom-rmgr.sgml
> + * リファレンスする必要があります。例の場合、XLOG_BTREE_バキュームは記名的
「リファレンスする」は「参照する」で良いと思います。

2023-04-07 08:04 UTC, noborus commented on doc/src/sgml/custom-rmgr.sgml
> + * リファレンスする必要があります。例の場合、XLOG_BTREE_バキュームは記名的
小泉さんのご指摘により、この部分はまるまる変更修正しています。
最新のコミットの方を見ていただけますでしょうか？

2023-04-15 06:22 UTC, tatsuo-ishii approved these changes
確認しました。

2023-04-15 06:22 UTC, merged