logical-replication.sgmlの15.0対応です
pgsql-jp/jpug-doc pull request #2590
Opened 2023-04-01 22:18 UTC by noborus

たたき台です。

2023-04-08 08:33 UTC, tatsuo-ishii requested changes
一通り確認しました。

2023-04-08 08:33 UTC, tatsuo-ishii commented on doc/src/sgml/logical-replication.sgml
> +   <title>式制限</title>
ここは
式の制限
あるいは
式における制限
としたした方がわかりやすいかと思います。

2023-04-08 08:33 UTC, tatsuo-ishii commented on doc/src/sgml/logical-replication.sgml
> +パーティション表の場合、パブリケーション・パラメータ<literal>publish_via_partition_root</literal>によって使用される列リストが決定されます。
パーテション表→パーテション化テーブル

2023-04-08 08:33 UTC, tatsuo-ishii commented on doc/src/sgml/logical-replication.sgml
>  レプリケートされる列数を減らすために、表<literal>t1</literal>に対して列リストが定義されます。
表→テーブル

2023-04-08 08:33 UTC, tatsuo-ishii commented on doc/src/sgml/logical-replication.sgml
> +パブリケーション<literal>パブリッシュ</literal>パラメータは、レプリケートされるDML操作にのみ影響します。
「パブリケーション」は「パブリケーションの」とした方がわかりやすいと思います。

2023-04-08 08:33 UTC, tatsuo-ishii commented on doc/src/sgml/logical-replication.sgml
> +つまり、スーパーユーザが全てのユーザにパブリッシャーやサブスクライバーに非一時テーブルを作成することを信用している場合にのみ、<literal>FOR ALL TABLES</literal>または<literal>FOR TABLES IN SCHEMA</literal>サブスクリプションを作成してください。
ここは「パブリッシャーやサブスクライバーに非一時テーブルを作成することを許可しているすべてのユーザを、スーパユーザが信用している場合にのみ、」という意味ではないでしょうか。

2023-04-09 09:31 UTC, noborus commented on doc/src/sgml/logical-replication.sgml
> +サブスクライバー上に同じテーブルを作成します。
上で「パブリッシャーで」としているのでサブスクライバー上の「上」を外す。

2023-04-09 09:31 UTC, noborus commented on doc/src/sgml/logical-replication.sgml
>  これは、パブリケーション<literal>pub2</literal>および<literal>pub3a</literal>が<literal>INSERT</literal>をレプリケートしないことを意味します。
レプリケートをレプリケーションに統一。複製となっているところもreplicateであればレプリケーションに統一。
以下同様。
table→テーブル
replicate→レプリケーション
published→パブリッシュされた

2023-04-09 09:31 UTC, noborus commented on doc/src/sgml/logical-replication.sgml
> +   <title>式制限</title>
ありがとうございます。「式の制限」にします。

2023-04-09 09:31 UTC, noborus commented on doc/src/sgml/logical-replication.sgml
この下の「Combining Multiple Row Filters」のタイトルが抜け、「複数行フィルタの統合」にする。

2023-04-09 09:31 UTC, noborus commented on doc/src/sgml/logical-replication.sgml
> +パーティション表の場合、パブリケーション・パラメータ<literal>publish_via_partition_root</literal>によって使用される列リストが決定されます。
修正します。

2023-04-09 09:31 UTC, noborus commented on doc/src/sgml/logical-replication.sgml
>    <sect2 id="logical-replication-col-list-combining">
この下の「Combining Multiple Column Lists」のタイトルが訳抜け、「複数列リストの統合」にする。

2023-04-09 09:31 UTC, noborus commented on doc/src/sgml/logical-replication.sgml
> -この場合、<xref linkend="sql-alterpublication"/>は成功しますが、後でパブリッシャのwalsenderが実行されるか、サブスクライバがエラーをスローする可能性があります。
walsender→WAL送信に修正。以下同様。

2023-04-09 09:31 UTC, noborus commented on doc/src/sgml/logical-replication.sgml
> -《機械翻訳》解決は、受信した変更と競合しないようにサブスクライバのデータまたは権限を変更するか、既存のデータと競合するトランザクションをスキップすることによって実行できます。
修正案： この問題を解決するには、データを変更するか、サブスクライバーに対する権限を変更して、既存の変更でコンフリクトしないようにするか、既存のトランザクションと競合するデータをスキップします。
コンフリクトよってエラーが発生した場合、レプリケーションは処理を続行せず、論理レプリケーションワーカーは次のようなメッセージをサブスクライバーのサーバーログに送信します。

2023-04-09 09:31 UTC, noborus commented on doc/src/sgml/logical-replication.sgml
> +パブリケーション<literal>パブリッシュ</literal>パラメータは、レプリケートされるDML操作にのみ影響します。
修正します。

2023-04-10 00:53 UTC, noborus commented on doc/src/sgml/logical-replication.sgml
>  就業者がトランザクションの適用処理中に、サブスクリプションの所有権がコンカレント・トランザクションによって変更された場合、現在のトランザクションの適用は古い所有者の権限で継続されます。
コンカレント・トランザクションを「同時実行しているトランザクション」に修正

2023-04-10 06:36 UTC, noborus commented on doc/src/sgml/logical-replication.sgml
>       </listitem>
「One of the publications has no row filter.」の箇所も訳抜け。ここは箇条書きなのでこれより下も合わせて変更。
* パブリケーションの 1 つに行フィルターがない。
* パブリケーションの1つが\<literal\>FOR ALL TABLES\</literal\>を使用して作成された。この句では行フィルタを使用できません。
* パブリケーションの1つが\<literal\>FOR TABLES IN SCHEMA\</literal\>を使用して作成され、テーブルは参照されたスキーマに属している。この句では行フィルタを使用できません。

2023-04-10 06:36 UTC, noborus commented on doc/src/sgml/logical-replication.sgml
>  <!--
この上のタイトルExamplesも訳抜け。

2023-04-10 06:54 UTC, noborus commented on doc/src/sgml/logical-replication.sgml
>  就業者がトランザクションの適用処理中に、サブスクリプションの所有権がコンカレント・トランザクションによって変更された場合、現在のトランザクションの適用は古い所有者の権限で継続されます。
翻訳の修正案：
サブスクライバーでは、サブスクリプション所有者の権限は、適用時にトランザクションごとに再チェックされます。
同時に並行しているトランザクションによってサブスクリプションの所有権が変更されたときにワーカーがトランザクションを適用している場合、現在のトランザクションの適用は古い所有者の権限で継続されます。

2023-04-10 06:56 UTC, noborus commented
ここまでのレビュー結果を反映しました。

2023-04-15 06:25 UTC, tatsuo-ishii approved these changes
確認しました。

2023-04-15 06:25 UTC, merged