スーパ→スーパーへ変更
pgsql-jp/jpug-doc pull request #2595
Opened 2023-04-04 02:59 UTC by noborus

2023-04-05 23:16 UTC, KenichiroTanaka requested changes
念のためご確認をお願いします

2023-04-05 23:16 UTC, KenichiroTanaka commented on doc/src/sgml/func1.sgml
> +<type>numeric</type>の場合、小数点以下を四捨五入します。
スーパ→スーパー以外の修正ですが、意図的なものでしょうか？

2023-04-05 23:16 UTC, KenichiroTanaka commented on doc/src/sgml/func4.sgml
> +        <entry>オブジェクトのサブID（例えば、列の列番号）</entry>
スーパ→スーパー以外の修正ですが、意図的なものでしょうか？

2023-04-06 01:01 UTC, noborus commented
> 念のためご確認をお願いします

コメントを書き忘れてました。
前の修正分でsplit.shの実行漏れがあったため、他の修正が含まれてます。

2023-04-06 12:08 UTC, KenichiroTanaka approved these changes
確かにsplitの実行漏れですね。対応ありがとうございます。

2023-04-06 12:08 UTC, merged