xreflabelの翻訳追加
pgsql-jp/jpug-doc pull request #2611
Opened 2023-05-04 08:16 UTC by noborus

関連 #2501 #2580

2023-05-04 15:46 UTC, KenichiroTanaka requested changes
1か所気づくところがありましたので確認をお願いします。

2023-05-04 15:46 UTC, KenichiroTanaka commented on doc/src/sgml/ref/insert.sgml
> +  <refsect2 id="sql-on-conflict" xreflabel="ON CONFLICT句">
翻訳いただいた行がコメント内に入ってしまっているようです(コメント内に入れるべき行が逆)。

2023-05-04 22:28 UTC, noborus commented on doc/src/sgml/ref/insert.sgml
> +  <refsect2 id="sql-on-conflict" xreflabel="ON CONFLICT句">
レビューありがとうございます。修正しました。

2023-05-05 12:22 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。マージします。

2023-05-05 12:22 UTC, merged