xfunc.sgmlの15.3対応です
pgsql-jp/jpug-doc pull request #2626
Opened 2023-05-25 08:18 UTC by noborus

2023-06-05 14:12 UTC, KenichiroTanaka requested changes
少し気になった点がありコメントしました。見ていただいてもいいでしょうか。

2023-06-05 14:12 UTC, KenichiroTanaka commented on doc/src/sgml/xfunc.sgml
>  （<acronym>SQL</acronym>関数では<command>COMMIT</command>、<command>SAVEPOINT</command>などのトランザクション制御コマンドおよび<literal>VACUUM</literal>などのユーティリティコマンドは使用することはできません。）
https://github.com/pgsql-jp/jpug-doc/pull/2625
などで「使用することができます」を「使用できます」に修正していますので、
「関数として定義することができます。」→「関数として定義できます。」
「含めることができます。」→「含められます。」（ここは元の「含めることができます」、でもいい気がしていますが。。）
「使用することはできません。」→「使用できません。」
とするのはどうでしょうか。

2023-06-10 14:50 UTC, koizumistr commented on doc/src/sgml/xfunc.sgml
>  （<acronym>SQL</acronym>関数では<command>COMMIT</command>、<command>SAVEPOINT</command>などのトランザクション制御コマンドおよび<literal>VACUUM</literal>などのユーティリティコマンドは使用することはできません。）
- 「含めることができます。」
- 「含められます。」

これはどちらも「正しい」と思いますので、あえて変える必要もないかな、と思います。「いや、周りと調子を合わせるのだ」と強く言われてしまうと、それもありかな、とは思いますが、、、

2023-06-29 04:43 UTC, noborus commented on doc/src/sgml/xfunc.sgml
>  （<acronym>SQL</acronym>関数では<command>COMMIT</command>、<command>SAVEPOINT</command>などのトランザクション制御コマンドおよび<literal>VACUUM</literal>などのユーティリティコマンドは使用することはできません。）
#2659 の方で修正しました。

2023-06-29 10:50 UTC, KenichiroTanaka commented on doc/src/sgml/xfunc.sgml
>  （<acronym>SQL</acronym>関数では<command>COMMIT</command>、<command>SAVEPOINT</command>などのトランザクション制御コマンドおよび<literal>VACUUM</literal>などのユーティリティコマンドは使用することはできません。）
ありがとうございます。先にこちらをマージします。

2023-06-29 10:50 UTC, KenichiroTanaka approved these changes

2023-06-29 10:50 UTC, merged