Update for release-15 (15.3)
pgsql-jp/jpug-doc pull request #2627
Opened 2023-05-30 08:34 UTC by kitayama

15.3のリリース情報を翻訳しました。とりあえず一通りざっと作業した状態です。

2023-05-30 10:20 UTC, noborus commented on doc/src/sgml/release-15.sgml
> +<function>array_position()</function>または<function>array_posisions()</function>に空配列が渡された場合に発生するクラッシュの可能性を回避しました。
> `<function>array_positions()</function>`が `<function>array_posisions()</function>`になってます。

2023-05-30 10:20 UTC, noborus commented on doc/src/sgml/release-15.sgml
> +<literal>READ COMMITED</literal>分離モードでは、行更新の効果を、最初に検出されたクエリよりも新しい行バージョンに再適用する必要がある場合があります。
`<literal>READ COMMITTED</literal>`が`<literal>READ COMMITED</literal>`になっています。

2023-05-30 10:20 UTC, noborus commented on doc/src/sgml/release-15.sgml
> +ブール型の列に対するパーティションプルーニングのロジックを修正しました。
ddl.sgmlではパーティション除去としているようです。

2023-05-30 10:20 UTC, noborus commented on doc/src/sgml/release-15.sgml
>  これは、<type>timestamptz</type>ディスプレイの一貫性を期待するアプリケーションにとって厄介な問題になる可能性があります。
ここでのdisplayも表示で良いと思います。

2023-05-31 01:31 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +<function>array_position()</function>または<function>array_posisions()</function>に空配列が渡された場合に発生するクラッシュの可能性を回避しました。
レビューありがとうございます。修正しました。

2023-05-31 01:32 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +<literal>READ COMMITED</literal>分離モードでは、行更新の効果を、最初に検出されたクエリよりも新しい行バージョンに再適用する必要がある場合があります。
修正しました。

2023-05-31 01:32 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +ブール型の列に対するパーティションプルーニングのロジックを修正しました。
修正しました。

2023-05-31 01:32 UTC, kitayama commented on doc/src/sgml/release-15.sgml
>  これは、<type>timestamptz</type>ディスプレイの一貫性を期待するアプリケーションにとって厄介な問題になる可能性があります。
displayが「ディスプレイ」になっている複数箇所を「表示」に変更しました。

2023-06-02 07:36 UTC, tatsuo-ishii requested changes
一通り確認しました。

2023-06-02 07:36 UTC, tatsuo-ishii commented on doc/src/sgml/release-15.sgml
> +<filename>contrib/amcheck</filename>では、エポックゼロより前にあるように見えるxidを適切に扱います。
「扱います」→「扱うようにしました」

2023-06-02 07:36 UTC, tatsuo-ishii commented on doc/src/sgml/release-15.sgml
> +このような場合にはFirstNormalFullTransactionIdを返すことで、合理的に正常に動作するようになります。
「合理的に正常に動作するようになります。」→「理にかなった妥当な動作をするようになります」くらいでどうでしょう？

2023-06-02 07:36 UTC, tatsuo-ishii commented on doc/src/sgml/release-15.sgml
> +このようなグラフをpg_trgmのGINやGiSTインデックス修飾に最適化しようとした結果、作業配列の末尾からアクセスすることになり、クラッシュする可能性がありました。
この場合、off the endは「〜を超えて」という意味ではないですかね。なので、
「作業配列の末尾を超えてアクセスすることになり」ということではないかと。

2023-06-02 07:36 UTC, tatsuo-ishii commented on doc/src/sgml/release-15.sgml
> +サーバメッセージを適切にゼロで終端されるように修正します。
「修正します。」→「修正しました。」

2023-06-02 07:36 UTC, tatsuo-ishii commented on doc/src/sgml/release-15.sgml
> +代入では、値をガベージキーとともに保存できますが、この問題を引き起こすのに十分な長さのキーは、フィールドに存在することはおそらく稀です。
代入では、値をでたらめなキーとともに保存してしまう可能性がありましたが、この問題を引き起こすのに十分な長さのキーが実際に使われることはおそらく稀です。

2023-06-02 07:36 UTC, tatsuo-ishii commented on doc/src/sgml/release-15.sgml
> +無関係なエラーコードを報告するのではなく、短い読み取りを正しくレポートし、必要なバイト数と実際に読み取られたバイト数を示します。
「短い読み取り」→「読み取りの不足」

2023-06-02 07:36 UTC, tatsuo-ishii commented on doc/src/sgml/release-15.sgml
> +サブクエリのプルアップにおいて、再帰呼び出しおよびループに対する防御機構を追加しました。
サブクエリ→副問合せ

2023-06-02 07:36 UTC, tatsuo-ishii commented on doc/src/sgml/release-15.sgml
> +不自然なクエリを使用すると、深い再帰が発生し、サブクエリを平坦化するために不合理な時間がかかる可能性があります。
クエリ→問い合わせ

2023-06-02 07:36 UTC, tatsuo-ishii commented on doc/src/sgml/release-15.sgml
> +これらのエラーは、Memoizeが有用なコンテキストでMemoizeが使用されなかったり、場合によっては間違ったクエリプランにつながる可能性がありました。
クエリプラン→問い合わせ計画

2023-06-02 07:36 UTC, tatsuo-ishii commented on doc/src/sgml/release-15.sgml
> +原則として、これらのエラーに到達することはありません。しかし、もしそうであれば、間違ったタイプのオブジェクトを報告していました。
「ありません。」の後に改行が必要。

2023-06-10 15:06 UTC, koizumistr commented on doc/src/sgml/release-15.sgml
> +この見落としは、無効として拒否されるべきクエリのエグゼキュータ失敗につながる可能性がありました。
クエリ→問い合わせ もお願いします。

2023-06-15 08:52 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +集合を返すSQL言語機能が行レベルセキュリティポリシーを持つテーブルを参照し、そのテーブルがコール元クエリにインライン化できる場合、キャッシュされたプランを別のロールで再利用する状況では、これらのRLSポリシーが適切に実施されないことがありました。
レビューありがとうございます。修正しました。

2023-06-15 08:52 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +<command>MERGE</command>によって更新または削除される行が、同時に存在するトランザクションによって更新されたばかりである場合に、誤動作が発生することがありました。
自然な文をありがとうございます。上記の文で修正しました。

2023-06-15 08:53 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +<command>ALTER TABLE ... ENABLE/DISABLE TRIGGER</command>は、パーティションテーブルの外部キー強制トリガーに適用されると失敗しました。
修正しました。

2023-06-15 08:53 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +この見落としは、無効として拒否されるべきクエリのエグゼキュータ失敗につながる可能性がありました。
修正しました。「クエリ」→「問い合わせ」は他の箇所も実施しました。

2023-06-15 08:55 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +Initプランをあるノードから別のノードに移動させる際に、プランノードの並列安全性マークを正しく更新します。
「あるノードから別のノードに移動させる際に、」とごそっと削除してよいものかどうかの判断にも困ったので、initplanをそのまま使うのではなく、「プランツリーやサブプランツリーの開始点」と意訳して、「プランツリーやサブプランツリーの開始点をあるノードから別のノードに移動させる際に、プランノードの並列安全性マークを正しく更新するようになりました。」としました。
前半が不要ならば「プランノードの並列安全性マークを正しく更新するようになりました。」だけ残します。

2023-06-15 08:55 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +無関係なエラーコードを報告するのではなく、短い読み取りを正しくレポートし、必要なバイト数と実際に読み取られたバイト数を示します。
修正しました。

2023-06-15 08:56 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +サブクエリのプルアップにおいて、再帰呼び出しおよびループに対する防御機構を追加しました。
「クエリ」を「問い合わせ」としているのにあわせて「副問い合わせ」で修正しました。

2023-06-15 08:56 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +不自然なクエリを使用すると、深い再帰が発生し、サブクエリを平坦化するために不合理な時間がかかる可能性があります。
他の箇所も含めて修正しました。

2023-06-15 08:57 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +これらのエラーは、Memoizeが有用なコンテキストでMemoizeが使用されなかったり、場合によっては間違ったクエリプランにつながる可能性がありました。
該当箇所を修正しました。他の箇所の「プラン」をすべて「計画」に変更しようとしましたが、それは見送りました。

2023-06-15 08:57 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +原則として、これらのエラーに到達することはありません。しかし、もしそうであれば、間違ったタイプのオブジェクトを報告していました。
改行を入れました。

2023-06-20 01:24 UTC, tatsuo-ishii requested changes
確認しました。

2023-06-20 01:24 UTC, tatsuo-ishii commented on doc/src/sgml/release-15.sgml
> +Initプランをあるノードから別のノードに移動させる際に、プランノードの並列安全性マークを正しく更新します。
initPlanは何かの開始点ではなく、それ自体が一つのプランノードです。ですから単に

initPlanを移動する際に、プランノードの並列安全性マークを正しく更新するようになりました

で良いと思います。ちなみに、initplans→initPlanにしているのは、"initPlan"が実際にソースコード中で使われている構造体メンバーの名前です。

2023-06-20 01:24 UTC, tatsuo-ishii commented on doc/src/sgml/release-15.sgml
> +そのような句内のサブプランは、他のいくつかの異常な場合と同様に、アサーション失敗または誤った回答を引き起こすことがありました。
この対応が抜けているようです。

2023-06-20 01:24 UTC, tatsuo-ishii commented on doc/src/sgml/release-15.sgml
> +ビューの最後に列が追加されたときに発生する特殊なクラッシュを修正しました。
この対応が抜けているようです。

2023-06-20 01:24 UTC, tatsuo-ishii commented on doc/src/sgml/release-15.sgml
> +このエラーは、取得された値が重要ではないため、通常、稼動ビルドでは無害のようですが、原則としてサーバクラッシュを引き起こす可能性があります。
この対応が抜けているようです。

2023-06-20 01:24 UTC, tatsuo-ishii commented on doc/src/sgml/release-15.sgml
> +<function>AllocSetRealloc()</function>のValgrindマーキングを修正しました。
この対応が抜けているようです。

2023-06-20 01:24 UTC, tatsuo-ishii commented on doc/src/sgml/release-15.sgml
> +<filename>contrib/amcheck</filename>では、エポックゼロより前にあるように見えるxidを適切に扱います。
この対応が抜けているようです。

2023-06-20 01:24 UTC, tatsuo-ishii commented on doc/src/sgml/release-15.sgml
> +このような場合にはFirstNormalFullTransactionIdを返すことで、合理的に正常に動作するようになります。
この対応が抜けているようです。

2023-06-20 01:24 UTC, tatsuo-ishii commented on doc/src/sgml/release-15.sgml
> +<type>ltree</type>列のGiSTインデックスの<literal>siglen</literal>オプションが指定されている場合は、4の倍数にする必要があります。
この対応が抜けているようです。

2023-06-20 01:24 UTC, tatsuo-ishii commented on doc/src/sgml/release-15.sgml
> +このようなグラフをpg_trgmのGINやGiSTインデックス修飾に最適化しようとした結果、作業配列の末尾からアクセスすることになり、クラッシュする可能性がありました。
この対応が抜けているようです。

2023-06-20 01:24 UTC, tatsuo-ishii commented on doc/src/sgml/release-15.sgml
> +サーバメッセージを適切にゼロで終端されるように修正します。
この対応が抜けているようです。

2023-06-20 01:24 UTC, tatsuo-ishii commented on doc/src/sgml/release-15.sgml
> +代入では、値をガベージキーとともに保存できますが、この問題を引き起こすのに十分な長さのキーは、フィールドに存在することはおそらく稀です。
この対応が抜けているようです。

2023-06-24 04:18 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +サブクエリに適用され検索条件句が、サブクエリ内のウィンドウ集約<quote>run condition</quote>に変換できるかどうかの誤ったテストを修正しました。
「副問い合わせで対応しました。

2023-06-24 04:31 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +そのような句内のサブプランは、他のいくつかの異常な場合と同様に、アサーション失敗または誤った回答を引き起こすことがありました。
申し訳ありません。前回Firefoxで確認した時に見落としていたようです。今回Chromeで確認出来ました。
「そのような句内のサブプランは」→「そのような句は」に変更しました。

2023-06-24 04:32 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +ビューの最後に列が追加されたときに発生する特殊なクラッシュを修正しました。
修正しました。

2023-06-24 04:32 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +このような参照は実際にはラテラル参照ですが、サブクエリが明示的に<literal>LATERAL</literal>でマークされれていない場合、サーバはクラッシュする可能性があります。
「副問い合わせ」で修正しました。

2023-06-24 04:33 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +このエラーは、取得された値が重要ではないため、通常、稼動ビルドでは無害のようですが、原則としてサーバクラッシュを引き起こす可能性があります。
修正しました。

2023-06-24 04:34 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +<function>AllocSetRealloc()</function>のValgrindマーキングを修正しました。
追記しました。

2023-06-24 04:34 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +<filename>contrib/amcheck</filename>では、エポックゼロより前にあるように見えるxidを適切に扱います。
修正しました。

2023-06-24 04:35 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +このような場合にはFirstNormalFullTransactionIdを返すことで、合理的に正常に動作するようになります。
修正しました。

2023-06-24 04:36 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +<type>ltree</type>列のGiSTインデックスの<literal>siglen</literal>オプションが指定されている場合は、4の倍数にする必要があります。
修正しました。

2023-06-24 04:37 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +このようなグラフをpg_trgmのGINやGiSTインデックス修飾に最適化しようとした結果、作業配列の末尾からアクセスすることになり、クラッシュする可能性がありました。
修正しました。

2023-06-24 04:38 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +また、メモリ終端を超えた読み取りが行われるために、クラッシュが発生する可能性もわずかにあります。
修正しました。

2023-06-24 04:38 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +サーバメッセージを適切にゼロで終端されるように修正します。
修正しました。

2023-06-24 04:40 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +代入では、値をガベージキーとともに保存できますが、この問題を引き起こすのに十分な長さのキーは、フィールドに存在することはおそらく稀です。
修正しました。

2023-06-24 04:57 UTC, kitayama commented
更新しましたが、label の Add re-review label で下記エラーが出ています。当方では対応しようがなさそうなのでコメントのみ記しておきます。

Error: Unhandled error: TypeError: Cannot read properties of undefined (reading 'removeLabel')

2023-06-24 09:00 UTC, tatsuo-ishii requested changes
確認しました。

2023-06-24 09:02 UTC, tatsuo-ishii approved these changes
すみません。確認しました。

2023-06-24 09:02 UTC, tatsuo-ishii commented on doc/src/sgml/release-15.sgml
> +initPlanを移動する際に、プランノードの並列安全性マークを正しく更新するようになりました。
すみません。この件は対応いただいていますね。

2023-06-25 03:19 UTC, noborus commented
> 更新しましたが、label の Add re-review label で下記エラーが出ています。当方では対応しようがなさそうなのでコメントのみ記しておきます。
> 
> Error: Unhandled error: TypeError: Cannot read properties of undefined (reading 'removeLabel')

すみません。修正しました。re-runでは失敗してしまうようなので、手動でラベルを付けました。以降は大丈夫だと思います。

2023-06-27 14:36 UTC, koizumistr reviewed
変更後の2000行まで見ました。

2023-06-27 14:36 UTC, koizumistr commented on doc/src/sgml/release-15.sgml
> +代わりに、親トリガのOIDによってそれらを見つけることにしました。
トリガー と トリガ が混在してしまうのは、ちょっと、、、、

2023-06-27 14:36 UTC, koizumistr commented on doc/src/sgml/release-15.sgml
> +initPlanを移動する際に、プランノードの並列安全性マークを正しく更新するようになりました。
from one node to another に対応する訳がないですが、自明だから？

2023-06-27 14:36 UTC, koizumistr commented on doc/src/sgml/release-15.sgml
> +そのような句は他のいくつかの異常な場合と同様に、アサーション失敗または誤った回答を引き起こすことがありました。
A SubPlan within に対応する訳がないようです。

2023-06-27 14:36 UTC, koizumistr commented on doc/src/sgml/release-15.sgml
> +呼び出しに副問い合わせが含まれる場合、ウィンドウ集約の逆遷移最適化を無効にします。
原文は sub-SELECTs です。（サブ/副SELECT ？）

2023-06-27 14:36 UTC, koizumistr commented on doc/src/sgml/release-15.sgml
> +この最適化では、集約の引数式が繰り返し可能な結果を持つ必要がありますが、副問い合わせには当てはまらない場合がありました。
上と同じ

2023-06-27 14:38 UTC, koizumistr commented on doc/src/sgml/release-15.sgml
> +また、<option>&#45;-load-via-partition-root</option>モードが使用されている場合、リストア前にターゲットテーブルを<command>TRUNCATE</command>試行しないように、<application>pg_restore</application>を修正しました。
ここも ＆＃45; 化は不要ではないでしょうか。

2023-06-28 13:07 UTC, koizumistr reviewed
（更新後の）2511行目まで見ました

2023-06-28 13:07 UTC, koizumistr commented on doc/src/sgml/release-15.sgml
> +改変されたサーバ、または信頼できない中間者は、GSSAPI(Kerberos)トランスポート暗号化のセットアップ中に、ゼロ終端されていないエラーメッセージを送信できます。
> 信頼できない
機械翻訳の「認証されていない」が原文に忠実だと思います。

認証されていないから信頼できない、ということなのかもしれませんが。

2023-06-29 05:18 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +Initプランをあるノードから別のノードに移動させる際に、プランノードの並列安全性マークを正しく更新します。
対応しました。

2023-06-29 05:22 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +集合を返すSQL言語関数が行レベルセキュリティポリシーを持つテーブルを参照し、そのテーブルがコール元問い合わせにインライン化できる場合、キャッシュされたプランを別のロールで再利用する状況では、これらのRLSポリシーが適切に実施されないことがありました。
「呼び出し元」に変更しました。

2023-06-29 05:25 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +<command>MERGE</command>コマンドさまざまなプランナ障害を修正しました。
修正しました。

2023-06-29 05:28 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +代わりに、親トリガのOIDによってそれらを見つけることにしました。
「トリガー」をすべて「トリガ」で統一しました。

2023-06-29 05:29 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +initPlanを移動する際に、プランノードの並列安全性マークを正しく更新するようになりました。
この箇所は石井さんからのレビューでシンプルな訳に変更しました。
https://github.com/pgsql-jp/jpug-doc/pull/2627#discussion_r1234591788

2023-06-29 05:31 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +そのような句は他のいくつかの異常な場合と同様に、アサーション失敗または誤った回答を引き起こすことがありました。
こちらも同様に石井さんのレビューでシンプルな訳に変更しました。
https://github.com/pgsql-jp/jpug-doc/pull/2627#discussion_r1213990017

2023-06-29 05:52 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +複合型ドメイン配列内フィールドを更新するときにクラッシュを防ぎました。
列の訳を加えました。

2023-06-29 05:55 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +既存のコードでは、スキャンキーが一致するかどうかを判断する際に、最後のレンジのみを効果的に考慮していたため、通常は必要以上にインデックスをスキャンしていました。
修正しました。

2023-06-29 05:56 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +コミットタイムスタンプに対するSLRUバッファ入出力の待機イベント名を修正します。
修正しました。

2023-06-29 06:04 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +ユーザは<option>&#45;-load-via-partition-root</option>オプションを指定することでこの問題を回避できますが、それなしでは成功する可能性が非常に低いので、<application>pg_dump</application>がそのようなテーブルにこのオプションを自動的に適用するように変更しました。
日本語側での &#45; は全て - に変更しました。

2023-06-29 06:04 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +また、<option>&#45;-load-via-partition-root</option>モードが使用されている場合、リストア前にターゲットテーブルを<command>TRUNCATE</command>試行しないように、<application>pg_restore</application>を修正しました。
日本語側での - は全て - に変更しました。

2023-06-29 06:08 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +これにより、pgbenchスクリプトがパイプライン内でSERIALIZABLEトランザクションを開始しようとしたときの失敗を回避します。
カタカナが多数派だったのでカタカナに変更しました。

2023-06-29 06:13 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +GNU互換の<application>strip</application>で静的ライブラリを削除する場合は、<option>&#45;-strip-unneeded</option>オプションを使用します。
「静的ライブラリを削除する」は strip コマンドの説明を借りて「静的ライブラリから不要な情報を除去する」に変更しました。&#45; は全て日本語の箇所では - に変更しました。

2023-06-29 06:15 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +以前は、<literal>make install-strip</literal>は<option>-x</option>オプションを使用していました。
「この場合には」を追記しました。

2023-06-29 06:16 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +改変されたサーバ、または信頼できない中間者は、GSSAPI(Kerberos)トランスポート暗号化のセットアップ中に、ゼロ終端されていないエラーメッセージを送信できます。
元の機械翻訳の「認証されていない」に戻しました。

2023-06-30 04:13 UTC, koizumistr commented on doc/src/sgml/release-15.sgml
> +そのような句は他のいくつかの異常な場合と同様に、アサーション失敗または誤った回答を引き起こすことがありました。
石井さんの指摘を読みましたが、
> 翻訳する必要はない

というのは「翻訳結果から省略して良い」という意味ではなくて、「SubPlanと（翻訳しないで）英語のままで良い」という意味ではないでしょうか。「そのような句内のSubPlan」と「そのような句」だと意味がまったく違ってしまうように思います。

2023-06-30 07:09 UTC, tatsuo-ishii commented on doc/src/sgml/release-15.sgml
> +そのような句は他のいくつかの異常な場合と同様に、アサーション失敗または誤った回答を引き起こすことがありました。
はい、

>「SubPlanと（翻訳しないで）英語のままで良い」という意味ではないでしょうか。

が言いたかったことです。

2023-07-03 04:27 UTC, koizumistr commented on doc/src/sgml/release-15.sgml
> +複合型ドメイン配列内フィールドを更新するときにクラッシュを防ぎました。
> 複合型列上のドメイン配列内のフィールド

とされているようですが、array-of-domain-over-composite-typeなので、「複合型のドメイン配列の列の中のフィールド」となるように思います。が、私も自分で書いていて何言っているのかよく分かっていません。だれか詳しい人助けて！

2023-07-03 05:29 UTC, koizumistr reviewed
最後まで確認しました。

前回の指摘でsub-SELECTに関するものが対応されていないようです。

2023-07-03 05:29 UTC, koizumistr commented on doc/src/sgml/release-15.sgml
> +2フェーズトランザクションに関するデータを更新する際に、適切なロックを取得することを怠っていたため、潜在的に他のプロセスが一貫性のないデータを見ることが可能でした。
2フェーズトランザクション -> 2相トランザクション

すみません。裏取れてません。

2023-07-03 05:29 UTC, koizumistr commented on doc/src/sgml/release-15.sgml
> +これは、セッションのテンポラリテーブルにパラレルワーカーからアクセスできないためです。
テンポラリテーブル -> 一時テーブル

だと思います。（だんだん裏取るのが面倒になってきてます）

2023-07-03 05:29 UTC, koizumistr commented on doc/src/sgml/release-15.sgml
> +テーブルを削除するためのロジックが破損しており、一時的テーブルの削除と通常のテーブルのWAL再生の削除の2つの場合で最初のファイル以外を削除できませんでした。
この行と次の行で「一時的テーブル」としていますが、次の段落では「一時テーブル」としているようです。

2023-07-03 05:29 UTC, koizumistr commented on doc/src/sgml/release-15.sgml
> +レプリケーションワーカーで外部テーブルのパーティションにレプリケーションの試みを防止しました。
（好みの問題かもですが）
外部テーブルのパーティションに -> 外部テーブルのパーティションへの

2023-07-03 05:29 UTC, koizumistr commented on doc/src/sgml/release-15.sgml
> +postmasterプロセスは、共有メモリが破損した場合にも存続してデータベース再起動をすることになっていたが、コードの一部でそれに対する注意が不十分でした。
なっていたが -> なっていましたが

2023-07-03 05:29 UTC, koizumistr commented on doc/src/sgml/release-15.sgml
> +<application>pg_basebackup</application>でクロスプラットフォームのテーブルスペースの再配置を許可します。
テーブルスペース -> テーブル空間

2023-07-03 05:29 UTC, koizumistr commented on doc/src/sgml/release-15.sgml
> +また、Europe/KievゾーンはEurope/Kyivに名前が変更されました。
これってもしかして、、、、、

単なる独り言です。

2023-07-03 05:29 UTC, koizumistr commented on doc/src/sgml/release-15.sgml
> -これらのすべての場合において、以前のゾーン・サスカチュワンは、依然としてパプアであるが、実際には、統合されたのものである。
サスカチュワン？パプア？？これがもしかしてAIの幻覚（ハルシネーション）ってものですか、、、

すみません、独り言です。

2023-07-03 07:40 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +呼び出しに副問い合わせが含まれる場合、ウィンドウ集約の逆遷移最適化を無効にします。
コメントをしたつもりでしたが出来ていなかったようですみません。
こちらのコメントは、単数形ではなく複数形であることを意味していますでしょうか、それとも訳語についてでしょうか。こちらの訳語は他の箇所を確認して、ref/create_domain.sgmlで「The empty scalar sub-SELECT」を「空でスカラーの副問い合わせ」となってたので、それに合わせました。意図を確認後、下の箇所と合わせて対応します。

2023-07-03 07:40 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +この最適化では、集約の引数式が繰り返し可能な結果を持つ必要がありますが、副問い合わせには当てはまらない場合がありました。
上で確認していますので、確認後上と同一の対応をする予定です。

2023-07-03 07:45 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +<command>MERGE</command>では<literal>DO NOTHING</literal>アクションを処理された行として数えないようにしました。
修正しました。

2023-07-03 07:48 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +場合によっては、保留中のインサートがすぐに外部データラッパー(FDW)にフラッシュされず、例えば<literal>BEFORE ROW</literal>のトリガで表示できるはずの行が表示されないなど、論理的な不整合が発生することがありました。
多数派の「外部データラッパ」にしました。

2023-07-03 07:49 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +<type>jsonpath</type>の存在チェックで未定義変数の使用を拒否しました。
「拒否するようにしました」に修正しました。

2023-07-03 07:53 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +テーブルから直接フェッチされたテキスト値を<type>jsonb</type>添字として使用すると、失敗する可能性がありました。
訳語として採用されている「添字」で統一しました。「添え字」はfunc.sgml, func2.sgml に見受けられました。

2023-07-03 07:54 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +非決定性な照合順序を持つ文字列のハッシュ作成におけるメモリーリークを修正しました。
長音を削除しました（「メモリ」に修正しました）。

2023-07-03 07:55 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +ホットスタンバイサーバで、プライマリ上でアクティブと知られているXIDを調べる処理f負荷を削減します。
余分なfを削除しました。

2023-07-03 07:55 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +レプリケーションスロットは、<varname>max_slot_wal_keep_size</varname>を超えたために無効になった後でも、システムカタログ内の無効なタプルのクリーンアップを妨げることができました。
修正しました。

2023-07-03 07:59 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +2フェーズトランザクションに関するデータを更新する際に、適切なロックを取得することを怠っていたため、潜在的に他のプロセスが一貫性のないデータを見ることが可能でした。
「2相」が多かったので「2相トランザクション」に修正しました。「二相」も少し見受けられました。

2023-07-03 08:04 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +これは、セッションのテンポラリテーブルにパラレルワーカーからアクセスできないためです。
訳語の「一時テーブル」に修正しました。

2023-07-03 08:05 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +テーブルを削除するためのロジックが破損しており、一時的テーブルの削除と通常のテーブルのWAL再生の削除の2つの場合で最初のファイル以外を削除できませんでした。
修正しました。

2023-07-03 08:06 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +レプリケーションワーカーで外部テーブルのパーティションにレプリケーションの試みを防止しました。
そのままだと意味が取れないのでいただいた案で修正しました。

2023-07-03 08:06 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +postmasterプロセスは、共有メモリが破損した場合にも存続してデータベース再起動をすることになっていたが、コードの一部でそれに対する注意が不十分でした。
修正しました。

2023-07-03 08:09 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +<application>pg_basebackup</application>でクロスプラットフォームのテーブルスペースの再配置を許可します。
「テーブル空間」に修正しました。

2023-07-03 08:10 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +また、Europe/KievゾーンはEurope/Kyivに名前が変更されました。
おそらくそうなんでしょうね。

2023-07-03 08:20 UTC, kitayama commented
> （今回の指摘とは別で、）前回の指摘でsub-SELECTに関するものが対応されていないようです。

こちらの「sub-SELECT」以外は対応しました。「sub-SELECT」については前回コメントを書いたつもりでしたがかけてなかったので今回記載しましたので、ご確認よろしくお願いします(後者の訳語だとは思いますが一応…)

https://github.com/pgsql-jp/jpug-doc/pull/2627#discussion_r1250407269

2023-07-05 04:24 UTC, tatsuo-ishii commented on doc/src/sgml/release-15.sgml
> +複合型ドメイン配列内フィールドを更新するときにクラッシュを防ぎました。
コミットメッセージに書いてあるバグレポートによれば、
複合型を作る
その複合型からドメイン型を作る
そのドメイン型の配列を列として持つテーブルを作る
そのテーブルにNULLを行として挿入
その行をupdate dcomptable set f1[1].cf2 = 5;としてアップデートするとクラッシュ
というわけで、array-of-domain-over-composite-type の訳は、
「複合型から作成した、ドメイン型の配列」となり、訳文全体としては、
「複合型から作成した、ドメイン型の配列内のフィールドを更新する時のクラッシュを防止しました。」
という感じでしょうか。

2023-07-06 04:10 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +複合型ドメイン配列内フィールドを更新するときにクラッシュを防ぎました。
石井さんの案で修正しました。

2023-07-06 04:13 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +そのような句は他のいくつかの異常な場合と同様に、アサーション失敗または誤った回答を引き起こすことがありました。
指摘事項を誤って解釈してすみませんでした。「そのような句内のSubPlan」に修正しました。

2023-07-06 04:14 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +initPlanを移動する際に、プランノードの並列安全性マークを正しく更新するようになりました。
こちらは現在の対応のままでOKと認識しました。

2023-07-06 04:20 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +呼び出しに副問い合わせが含まれる場合、ウィンドウ集約の逆遷移最適化を無効にします。
sub-SELECTsは複数形である指摘では無く訳語の指摘と解釈して「副問い合わせ」を「サブSELECT」に変更しました(sは付けていない/「複数の」とは言っていない)

2023-07-06 04:20 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +この最適化では、集約の引数式が繰り返し可能な結果を持つ必要がありますが、副問い合わせには当てはまらない場合がありました。
sub-SELECTの訳語を「副問い合わせ」から「サブSELECT」に変更しました。

2023-07-06 04:26 UTC, kitayama commented
・A Subplan within such a clause を「そのような句は」から「そのような句内のSubPlanは」に修正しました。
・「sub-SELECTs」と「sub-SELECT」の訳語を「サブSELECT」に変更しました。「SELECTs」の複数形は訳出していません(複数のとか、SELECTsとするかはしていない)
・「array-of-domain-over-composite-type」で石井さんに提案いただいた訳で更新しました。

https://github.com/pgsql-jp/jpug-doc/pull/2627#issuecomment-1617605497

2023-07-10 04:28 UTC, koizumistr commented on doc/src/sgml/release-15.sgml
> +呼び出しに副問い合わせが含まれる場合、ウィンドウ集約の逆遷移最適化を無効にします。
すみません。分かりにくかったですね。「SELECTはSELECTであって、問い合わせならqueryでは？」と考えて書いたものですので、今回の対応で私の指摘に応えたものになっています。
> 「The empty scalar sub-SELECT」を「空でスカラーの副問い合わせ」

は多分誤訳だと思います。が、ref以下だから犯人は私かも、、、

2023-07-13 07:27 UTC, tatsuo-ishii commented
一通り確認したのでマージします。北山さんをはじめ、みなさんお疲れ様でした！

2023-07-13 07:27 UTC, merged