update create_publication for 15.3
pgsql-jp/jpug-doc pull request #2637
Opened 2023-06-10 15:03 UTC by koizumistr

ref/create_publication.sgmlの15.3対応です。

2023-06-19 13:17 UTC, KenichiroTanaka requested changes
１箇所ご確認をお願いできないでしょう以下。

2023-06-19 13:17 UTC, KenichiroTanaka commented on doc/src/sgml/ref/create_publication.sgml
> +<command>マージ</command>コマンドに対しては、パブリケーションは挿入、更新、または削除された行ごとに<command>INSERT</command>、<command>UPDATE</command>、または<command>DELETE</command>をパブリッシュします。
「<command>マージ</command>コマンドに対しては」の箇所は他と同様に
「<command>MERGE</command>コマンドに対しては」が良いと思います。

2023-06-21 12:43 UTC, koizumistr commented
確認ありがとうございます。対応しました。

2023-06-22 22:37 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。
マージします。

2023-06-22 22:37 UTC, merged