update create_role for 15.3
pgsql-jp/jpug-doc pull request #2647
Opened 2023-06-21 12:40 UTC by koizumistr

ref/create_role.sgml の15.3対応です。

2023-06-21 12:46 UTC, koizumistr commented
ビルドはできているようですが、ラベル付けの方が失敗しているみたいです。（なので自分で付けました。）

2023-06-22 23:16 UTC, KenichiroTanaka requested changes
1箇所気づくところがありましたので見ていただいてもいいでしょうか。

2023-06-22 23:16 UTC, KenichiroTanaka commented on doc/src/sgml/ref/create_role.sgml
> +これらの句は、他のロールの作成、変更、削除、コメント付与、セキュリティラベルの変更、およびメンバーシップの付与または取消しをロールに許可するかどうかを決定します。
「メンバーシップ」は他では「メンバー資格」とされているようです。
また、
「These clauses determine whether a role will be permitted to
 create, alter, drop, comment on, change the security label for,
 and grant or revoke membership in other roles.」
の箇所ですが、in other rolesはCREATE,ALTER以下にかかるのではなく、membershipにかかるように思います。
ですので、
「これらの句は、ロールの作成、変更、削除、コメント付与、セキュリティラベルの変更、および他のロールにあるメンバー資格の付与または取消しをロールに許可するかどうかを決定します」
というような訳になるように思います。見ていただいてもいいでしょうか。

2023-06-26 12:52 UTC, koizumistr commented on doc/src/sgml/ref/create_role.sgml
> +これらの句は、他のロールの作成、変更、削除、コメント付与、セキュリティラベルの変更、およびメンバーシップの付与または取消しをロールに許可するかどうかを決定します。
確認ありがとうございます。メンバ資格は対応しました。（ー付ける付けないは議論中かと思いますが、検索した限り、メンバ資格しかありませんでしたので。）

role-creationで参照している先を見ると create, alter ... other roles.....grant or revoke membership in them. みたいな書き方になっており、them = other roles でしょうから、 ここでも

- create, 
- alter, 
- drop, 
- comment on, 
- change the security label for,
- grant or revoke membership in

が並列になっているのではないかと思いました。

ではなくて、もしかして長くて分かりにくいという指摘でしょうか。

2023-06-27 11:28 UTC, KenichiroTanaka commented on doc/src/sgml/ref/create_role.sgml
> +これらの句は、他のロールの作成、変更、削除、コメント付与、セキュリティラベルの変更、およびメンバーシップの付与または取消しをロールに許可するかどうかを決定します。
解説ありがとうございます。
すみません、私がトンチンカンなことを言っていました。
>が並列になっているのではないかと思いました。
create <other roles>,
alter <other roles>,
drop <other roles>,
comment on <other roles>,
change the security label for <other roles>,
grant or revoke membership in <other roles>
ってことですね。構造が見えていませんでした。
ここの指摘は無しでお願いします。

2023-06-27 11:28 UTC, KenichiroTanaka approved these changes

2023-06-27 11:28 UTC, merged