update create_table for 15.3
pgsql-jp/jpug-doc pull request #2654
Opened 2023-06-28 12:43 UTC by koizumistr

ref/create_table.sgml の15.3対応です。

2023-07-03 11:17 UTC, KenichiroTanaka requested changes
1箇所だけ気づくところがありましたので見ていただいてもいいでしょうか。

2023-07-03 11:17 UTC, KenichiroTanaka commented on doc/src/sgml/ref/create_table.sgml
> +<command>TRUNCATE</command>TRUNCATEのように通常はテーブルとそれを継承するすべての子テーブルに影響を及ぼす操作は、すべてのパーティションに対しても適用されますが、個別のパーティションに対して操作することも可能です。
「<command>TRUNCATE</command>TRUNCATE」の２つ目のTRUNCATEは不要かと思います。

2023-07-06 10:05 UTC, koizumistr commented
確認ありがとうございます。対応しました。

2023-07-11 10:42 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。

2023-07-11 10:42 UTC, merged