arch-dev.sgmlの15.3対応です
pgsql-jp/jpug-doc pull request #2658
Opened 2023-06-29 01:27 UTC by noborus

2023-07-05 23:20 UTC, KenichiroTanaka requested changes
2箇所気づくところがありましたので見ていただいてもいいでしょうか。

2023-07-05 23:20 UTC, KenichiroTanaka commented on doc/src/sgml/arch-dev.sgml
> +4つのSQL問い合わせの種類とは<command>SELECT</command>、<command>INSERT</command>、<command>UPDATE</command>、<command>DELETE</command>、そして<command>MERGE</command>です。
意訳部分なので発見しづらいですが、
「4つのSQL問い合わせの種類とは」→「５つのSQL問い合わせの種類とは」
ですね。

2023-07-05 23:20 UTC, KenichiroTanaka commented on doc/src/sgml/arch-dev.sgml
> +<command>MERGE</command>では、プランナは元のリレーションと対象のリレーションに結合し、<literal>WHEN</literal>句のいずれかで必要とされるすべての列の値と対象行のTIDを含みます。
「プランナは元のリレーションと対象のリレーションに結合し」のところは読みづらく感じました。
「プランナは元のリレーションと対象のリレーションを結合し」
もしくは
「プランナは元のリレーションを対象のリレーションに結合し」
とするのはどうでしょうか。
技術的には前者が良いように思います。

2023-07-06 05:54 UTC, noborus commented on doc/src/sgml/arch-dev.sgml
> +4つのSQL問い合わせの種類とは<command>SELECT</command>、<command>INSERT</command>、<command>UPDATE</command>、<command>DELETE</command>、そして<command>MERGE</command>です。
失礼しました。修正します。

2023-07-06 05:55 UTC, noborus commented on doc/src/sgml/arch-dev.sgml
> +<command>MERGE</command>では、プランナは元のリレーションと対象のリレーションに結合し、<literal>WHEN</literal>句のいずれかで必要とされるすべての列の値と対象行のTIDを含みます。
たしかに。ありがとうございます。修正します。

2023-07-11 10:44 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。

2023-07-11 10:44 UTC, merged