update parallel for 15.3
pgsql-jp/jpug-doc pull request #2663
Opened 2023-07-06 10:29 UTC by koizumistr

parallel.sgml の15.3対応です。

2023-07-08 03:03 UTC, noborus approved these changes
確認しました

2023-07-15 13:36 UTC, KenichiroTanaka requested changes
1箇所だけ、細かい気もしますが、少し気になりました。見ていただいてもいいでしょうか。

2023-07-15 13:36 UTC, KenichiroTanaka commented on doc/src/sgml/parallel.sgml
> +<emphasis>パラレルシーケンシャルスキャン</emphasis>では、テーブルのブロックは範囲に分割され、協調するプロセス間で共有されます。
間違いではありませんが、beforeなのに「後で」と訳されているところが気になりました。
機械翻訳の訳案がそのようになっているからなのですが、
「各ワーカープロセスは、ブロックの追加範囲を要求する前に、与えられたブロック範囲のスキャンを完了します」
（ついでにgivenも「与えられた」に変更しました）などとした方が原文のSとVが一致して良いように思います。

2023-07-21 11:53 UTC, koizumistr commented
確認ありがとうございます。対応しました。

2023-07-24 13:33 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。

2023-07-24 13:33 UTC, merged