第21章の文章表現を見直しました。
pgsql-jp/jpug-doc pull request #2664
Opened 2023-07-07 09:48 UTC by pato-taityo

・冗長表現の見直し（例：することができます⇒できます）
・（）を全角に統一した
・漢字の開きの見直し（例：下さい⇒ください）
・助詞の繰り返しの見直し
・送り仮名の見直し（例：行なわれます⇒行われます）
・稼動⇒稼働
・読点の統一（,⇒、）

2023-07-08 03:06 UTC, noborus commented on doc/src/sgml/client-auth.sgml
> +<productname>SSPI</productname>認証は、サーバ、クライアントが共に<productname>Windows</productname>上もしくは<productname>GSSAPI</productname>が利用可能な場合はWindowsではないプラットフォームで稼働しているときにのみ動作します。
稼働/稼動 の修正します？するなら稼働で統一にしても良いかもしれませんが...

2023-07-08 23:44 UTC, pato-taityo commented on doc/src/sgml/client-auth.sgml
> +<productname>SSPI</productname>認証は、サーバ、クライアントが共に<productname>Windows</productname>上もしくは<productname>GSSAPI</productname>が利用可能な場合はWindowsではないプラットフォームで稼働しているときにのみ動作します。
コメントをありがとうございました。コメントを受けて再考し、どちらに判断すべきか悩んでいます。これまでのポリシーや対応を踏まえ、どちらのほうが適切か、ご教示ください。

まず、当初変更した経緯について説明します。

校正ツールで「稼動」は間違えた表記であるとして、「稼働」への修正を提案されました。これを受けて修正しました。

ただ、コメントをいただいて、改めて辞書でも確認しました。すると、「稼動」と「稼働」は併記されており、いずれかが間違いとの記述はありませんでした。
・新明解国語辞典
・デジタル大辞泉

ネットの記事でこの2つの使い分けについて調べましたが、判断に使えるほど根拠があるものは見つかりませんでした。

ここまでを踏まえ、「稼動」と「稼働」は同じ意味ととらえて良いのでは、と考えました。

さらに、現在の翻訳での使い分けを確認しました。登場件数は以下のとおりです。
稼動：59件
稼働：72件
同じ sgml ファイル内でも両方登場しているケースが見られました。

まとめると、「稼動」と「稼働」は同じ意味と考えています。また、翻訳の中では混在しているようです。
このような場合、これまではどのような対応をしてきたのでしょうか？統一していくのか。それとも同じ意味なので許容するのか。

2023-07-15 14:00 UTC, KenichiroTanaka requested changes
対応ありがとうございます。
いくつかコメントしましたので見ていただいてもいいでしょうか。

2023-07-16 07:49 UTC, pato-taityo commented on doc/src/sgml/client-auth.sgml
> +2つ目のモードでは、それはsearch+bindモードを呼びだすもので、サーバは最初に<replaceable>ldapbinddn</replaceable>と<replaceable>ldapbindpasswd</replaceable>で指定された、
「呼び出す」に戻します。

https://www.bunka.go.jp/seisaku/bunkashingikai/kokugo/hokoku/pdf/92968501_01.pdf
こちらの資料では「呼び出す」という記載が使われていました。

また、修正した根拠のスタイルガイドを再度確認しました。
https://www.jtf.jp/pdf/jtf_style_guide.pdf
「〜だす」：「〜し始める」の意味の場合。
「〜出す」：「出す」の意味を含む場合。
どちらでも説明できそうですが、"call" の元の意味を考えると、「呼び出す」が良いのではと考えました。

2023-07-16 07:53 UTC, pato-taityo commented on doc/src/sgml/client-auth.sgml
> +複数のサーバを指定したい場合は、別のRADIUSオプションをカンマ区切りのリストとして指定して、各サーバの値を個別に指定することもできます。
コメントに従い、元のままにします。
原文とのチェックが甘かったです。ありがとうございました。

2023-07-16 08:02 UTC, pato-taityo commented on doc/src/sgml/client-auth.sgml
> +<literal>trust</literal>認証はユーザが1人のみのワークステーション上でローカル接続を行う場合には適切であると同時に非常に便利です。
ここは今もちょっと悩んでます。

元の文章の
「認証はユーザが1人のみのワークステーション上でローカル接続を行う場合は適切である」
だと「は」が2箇所に出て、文章の構成がちょっと分かり辛く感じました。

「は」を「に」に代えたかったのですが、
『ローカル接続を行う場合に適切であると同時に非常に便利です』
だと「に」が連続してしまい、これも分かり辛い気がしました。

ただ、修正したバージョンの「には」だとシチュエーションを限定した印象が出ます。
原文だとそこまで言っていないので、やりすぎな気がしています。

素直に元の文章に直そうかと思いますが、いかがでしょうか？

2023-07-17 23:02 UTC, KenichiroTanaka commented on doc/src/sgml/client-auth.sgml
> +<literal>trust</literal>認証はユーザが1人のみのワークステーション上でローカル接続を行う場合には適切であると同時に非常に便利です。
レスありがとうございます。
原文を読んでみると、「と同時に」の原文は　andかと思います。必ずしも「と同時に」とする必要もないため、
ご指摘の読みづらさはこちらを解消しても良いかと思います。
例えば、
```
<literal>trust</literal>認証はユーザが1人のみのワークステーション上でローカル接続を行う場合に適切で非常に便利です。
```
などとするのはどうでしょうか。

2023-07-18 22:45 UTC, pato-taityo commented on doc/src/sgml/client-auth.sgml
> +<literal>trust</literal>認証はユーザが1人のみのワークステーション上でローカル接続を行う場合には適切であると同時に非常に便利です。
ありがとうございます！
ご提案いただいた文章はすっきり読みやすかったので、そのまま採用させていただきました。

2023-07-24 12:56 UTC, pato-taityo commented on doc/src/sgml/client-auth.sgml
> +<productname>SSPI</productname>認証は、サーバ、クライアントが共に<productname>Windows</productname>上もしくは<productname>GSSAPI</productname>が利用可能な場合はWindowsではないプラットフォームで稼働しているときにのみ動作します。
ご意見・提案をありがとうございました。

反対意見が無ければ、これを機に稼動⇒稼働の変更でIssueを作成したいと思います。

今は皆さんが翻訳作業を進めている最中だと思いますので、翻訳対象外のファイルを直しつつ、翻訳作業の区切りがついたタイミングで一括変換しようかと考えています。

2023-07-24 13:36 UTC, KenichiroTanaka commented on doc/src/sgml/client-auth.sgml
> +<productname>SSPI</productname>認証は、サーバ、クライアントが共に<productname>Windows</productname>上もしくは<productname>GSSAPI</productname>が利用可能な場合はWindowsではないプラットフォームで稼働しているときにのみ動作します。
確認ありがとうございます。
では一括変換しちゃいましょう。
ISSUESをお願いしてしまってもいいでしょうか。

2023-07-24 13:38 UTC, KenichiroTanaka approved these changes
ひととおり確認しました。マージします。

2023-07-24 13:38 UTC, merged