update user-manag for 15.3
pgsql-jp/jpug-doc pull request #2667
Opened 2023-07-07 13:52 UTC by koizumistr

user-manag.sgml の15.3対応です。

「CREATEROLE権限を持つユーザは」で始まる最後の段落は（機械翻訳で基本的にはいいのではないかと思うのですが）よく分かってないです。

2023-07-17 22:48 UTC, KenichiroTanaka requested changes
1箇所だけ気づくところがありましたので見ていただいてもいいでしょうか。

2023-07-17 22:48 UTC, KenichiroTanaka commented on doc/src/sgml/user-manag.sgml
> +<literal>CREATEROLE</literal>権限を持つユーザは、(まだ)アクセス権が付与されていないロールに対しても、メンバ資格の付与または取り消しを行うことができるため、<literal>CREATEROLE</literal>ユーザは、<literal>pg_execute_server_program</literal>や<literal>pg_write_server_fi
「CREATEROLEは自分に付与されていない権限を付与、剥奪できる。実質、権限を取得できる状態と同じ」という趣旨かと思います。
accessが「アクセス権」となると少し分かりにくいようにも思います。
privilege  と同じ訳語になりますが
「<literal>CREATEROLE</literal>権限を持つユーザは、(まだ)権限が付与されていないロールに対しても、メンバ資格の付与または取り消しを行うことができるため、<literal>CREATEROLE</literal>ユーザは、<literal>pg_execute_server_program</literal>や<literal>pg_write_server_files</literal>などの高度な権限を持つロールを含む、システム内のすべての事前定義されたロールの機能への権限を取得できます。」
とするのはどうでしょうか。

2023-07-21 11:59 UTC, koizumistr commented
確認ありがとうございます。対応しました。

2023-07-24 13:39 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。
マージします。

2023-07-24 13:39 UTC, merged