monitoring.sgmlの15.3対応です
pgsql-jp/jpug-doc pull request #2671
Opened 2023-07-13 16:54 UTC by noborus

2023-07-18 13:32 UTC, KenichiroTanaka requested changes
2箇所気になるところがありましたので見ていただいてもいいでしょうか。

2023-07-18 13:32 UTC, KenichiroTanaka commented on doc/src/sgml/monitoring.sgml
> +現在トランザクションのテーブルまたはインデックスについて、キャッシュで検出されたブロック読み取り要求の数を返します（カーネル<function>read()</function>呼び出しはトリガされません）。
「呼び出しはトリガされません」の箇所ですが「トリガする」という表現はPostgreSQLでは分かりにくい（CREATE TRIGGERで作成されるオブジェクトとパッと見混同してしまう）と思いました。
「カーネル<function>read()</function>呼び出しを引き起こしません」
くらいの訳文でどうでしょうか。

2023-07-18 13:32 UTC, KenichiroTanaka commented on doc/src/sgml/monitoring.sgml
> +<function>pg_stat_reset()</function>を使用すると、自動バキュームがバキュームまたはANALYZEをトリガするタイミングを決定するために使用するカウンタもリセットされます。
ここも同様で
「自動バキュームがバキュームまたはANALYZEをトリガする」
は
「自動バキュームがバキュームまたはANALYZEを実行する」
くらいでどうでしょうか。

2023-07-19 05:06 UTC, noborus commented on doc/src/sgml/monitoring.sgml
> +現在トランザクションのテーブルまたはインデックスについて、キャッシュで検出されたブロック読み取り要求の数を返します（カーネル<function>read()</function>呼び出しはトリガされません）。
ありがとうございます。修正します。

2023-07-21 12:06 UTC, koizumistr reviewed
確認しました。

2023-07-21 12:06 UTC, koizumistr commented on doc/src/sgml/monitoring.sgml
> +これらのカウンタをリセットすると、自動バキュームが必要な作業を実行できなくなり、テーブルの膨張や期限切れのテーブル統計処理などの問題が発生する可能性があります。
statistics は統計処理ではなく統計情報と思います。なので、
期限切れのテーブル統計情報
かと。

2023-07-21 12:06 UTC, koizumistr commented on doc/src/sgml/monitoring.sgml
> +統計処理がリセットになった後にデータベース全体で<command>ANALYZE</command>を実行することをお勧めします。
こちらも
統計情報がリセットされた後に
となるかと。

2023-07-21 21:36 UTC, noborus commented on doc/src/sgml/monitoring.sgml
> +統計処理がリセットになった後にデータベース全体で<command>ANALYZE</command>を実行することをお勧めします。
ありがとうございます。修正しました。

2023-07-21 21:38 UTC, noborus commented on doc/src/sgml/monitoring.sgml
> +トランザクションはまた、ビューの<structname>pg_stat_xact_all_tables</structname>、<structname>pg_stat_xact_sys_tables</structname>、<structname>pg_stat_xact_user_tables</structname>、および<structname>pg_stat_xact_user_fu
さらにもう一箇所、統計処理になっていたのを修正しました。cumulative statistics にしたほうが良いのではないかと思いましたが...

2023-07-23 09:06 UTC, koizumistr commented
対応ありがとうございます。確認しました。

2023-08-03 23:25 UTC, KenichiroTanaka approved these changes
すみません、確認が遅くなりました。
対応ありがとうございます。
マージします。

2023-08-03 23:25 UTC, merged