Update release-15 for 15.4
pgsql-jp/jpug-doc pull request #2713
Opened 2023-08-23 07:47 UTC by kitayama

2023-08-23 13:35 UTC, noborus commented on doc/src/sgml/release-15.sgml
> +しかしながら、BRINインデックスを使用しているる場合は、インデックスを再作成することをお勧めします。
るが多いです。使用しているる

2023-08-23 13:35 UTC, noborus commented on doc/src/sgml/release-15.sgml
> +揮発性の結合条件を含むラテラル結合で、Memoize を使わないようにしました。
Memoizeの後に余分なスペースがあります。
「ラテラル結合」は、他の章に出てこないんですよね。ちょっと悩ましい。

2023-08-23 13:35 UTC, noborus commented on doc/src/sgml/release-15.sgml
> +揮発性のフィルタ条件を含むサブブランにMemoizeを適用すると、間違った結果につながる可能性があります。
サブブラン→サブプラン

2023-08-23 13:35 UTC, noborus commented on doc/src/sgml/release-15.sgml
> +セグメントは新しい空き容量に応じて適切な<quote>ビン</quote>に移動され、その後の検索で見つかるようになります。
`<quote>ビン</quote>` は`<quote>bin</quote>`で良いと思います。

2023-08-24 04:36 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +しかしながら、BRINインデックスを使用しているる場合は、インデックスを再作成することをお勧めします。
レビューありがとうございます。修正しました。

2023-08-24 04:36 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +揮発性の結合条件を含むラテラル結合で、Memoize を使わないようにしました。
余分なスペースを削除しました。

2023-08-24 04:37 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +揮発性のフィルタ条件を含むサブブランにMemoizeを適用すると、間違った結果につながる可能性があります。
修正しました(ぱっと見、分からない(^^;))

2023-08-24 04:37 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +セグメントは新しい空き容量に応じて適切な<quote>ビン</quote>に移動され、その後の検索で見つかるようになります。
修正しました。

2023-08-27 11:28 UTC, tatsuo-ishii commented on doc/src/sgml/release-15.sgml
> +揮発性の結合条件を含むラテラル結合で、Memoize を使わないようにしました。
「ラテラル結合」は他に訳しようがない気がします。

2023-08-27 12:38 UTC, tatsuo-ishii requested changes
一通り確認しました。

2023-08-27 12:38 UTC, tatsuo-ishii commented on doc/src/sgml/release-15.sgml
> +プランナでの一意性の証明に部分的なユニークインデックスを使用しないようにしました。
"partial unique index"の訳語で「部分的なユニークインデックス」というのはちょっと意味がわかりません。partial indexが大分類としてまずあり、partial unique indexは一部の分類という位置づけです。ですので、partial unique indexはpatial index = 「部分インデックス」の一部である、ということがわかる訳が良いです。
「11.8. 部分インデックス」の「例11.3」では、「一意な部分インデックス」と訳しています。私も「一意な部分インデックス」が良いと思います。

2023-08-27 12:38 UTC, tatsuo-ishii commented on doc/src/sgml/release-15.sgml
> +問題のインデックスがテーブルのスキャンに使用されない場合、テーブルから読み込まれた行の一意性の推定が保持されない可能性があるため、これは誤った計画を引き起こす可能性がありました。
the presumed uniqueness... might not holdですから、保持されないのは推定したところの一意性であり、推定ではないので、機械翻訳の方が適切と思います。

2023-08-27 12:38 UTC, tatsuo-ishii commented on doc/src/sgml/release-15.sgml
> +偽性の定数のJOIN句を伴う外部結合に対して誤った計画を作成しないようにしました。
pseudoconstantの訳は「疑似定数」くらいで良いと思います。

2023-08-27 12:38 UTC, tatsuo-ishii commented on doc/src/sgml/release-15.sgml
> +現在、プランナにはプッシュダウンされたリモート結合に偽性の定数のJOIN句を付加するサポートがないため、このような場合にはリモート結合の生成を無効にしました。
pseudoconstantの訳は「疑似定数」くらいで良いと思います。

2023-08-27 12:38 UTC, tatsuo-ishii commented on doc/src/sgml/release-15.sgml
> +複合型列のフィールドを更新しようとしたときに断続的に発生する障害を修正しました。
ここでのintermittentは、「時々」という意味ですね。

2023-08-27 12:38 UTC, tatsuo-ishii commented on doc/src/sgml/release-15.sgml
> +増分ソート実行プランノードが再スキャンされるときのクエリ存続期間のメモリリークを防止しました。
「クエリ存続期間のメモリリーク」
これは本来タプルの処理行ごとに解放されるべきメモリが、クエリが終わるまでメモリが解放されていなかった、という意味ですね。
「増分ソート実行プランノードが再スキャンされる際に、メモリがクエリ処理が終了するまで解放されないメモリリークを防止しました。」
くらいでどうでしょう。

2023-08-30 06:58 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +プランナでの一意性の証明に部分的なユニークインデックスを使用しないようにしました。
レビューありがとうございます。上記の内容で修正しました。

2023-08-30 06:59 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +BRINインデックスでの行のない空の範囲と全てがNULL範囲との混同と、全てがNULLの集計の誤ったマージを修正しました。
修正しました。

2023-08-30 06:59 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +問題のインデックスがテーブルのスキャンに使用されない場合、テーブルから読み込まれた行の一意性の推定が保持されない可能性があるため、これは誤った計画を引き起こす可能性がありました。
機械翻訳の表現に修正しました。

2023-08-30 06:59 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +偽性の定数のJOIN句を伴う外部結合に対して誤った計画を作成しないようにしました。
修正しました。

2023-08-30 06:59 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +現在、プランナにはプッシュダウンされたリモート結合に偽性の定数のJOIN句を付加するサポートがないため、このような場合にはリモート結合の生成を無効にしました。
修正しました。

2023-08-30 07:00 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +複合型列のフィールドを更新しようとしたときに断続的に発生する障害を修正しました。
修正しました。

2023-08-30 07:00 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +増分ソート実行プランノードが再スキャンされるときのクエリ存続期間のメモリリークを防止しました。
いただいた内容で修正しました。

2023-08-30 07:12 UTC, tatsuo-ishii approved these changes
対応ありがとうございます。確認しました。

2023-08-31 00:34 UTC, KenichiroTanaka requested changes
量が多いリリースノートの対応ありがとうございました。
２箇所、気づくところがありましたので見ていただいてもいいでしょうか。

2023-08-31 00:34 UTC, KenichiroTanaka commented on doc/src/sgml/release-15.sgml
> +このような場合は、例えば<literal>GROUP BY</literal>句や<literal>ON CONFLICT</literal>句から発生することがありました。
「このような場合は、例えば<literal>GROUP BY</literal>句や<literal>ON CONFLICT</literal>句から発生することがありました。」
何が発生するのかパッとわかりませんでした。
fromがうまく訳出できませんでしたが意訳して良いところだと思いますので、
「このようなケースは<literal>GROUP BY</literal>句や<literal>ON CONFLICT</literal>句で発生することがあります。」
というような訳でどうでしょうか。

2023-08-31 01:08 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +インデックスの<structname>pg_index</structname>エントリの更新は、他の列に対して古いデータを使用する可能性があります。
レビューありがとうございます。過去形に修正しました。

2023-08-31 01:09 UTC, kitayama commented on doc/src/sgml/release-15.sgml
> +このような場合は、例えば<literal>GROUP BY</literal>句や<literal>ON CONFLICT</literal>句から発生することがありました。
頂いた内容で修正しました。

2023-08-31 03:33 UTC, KenichiroTanaka approved these changes
早速の対応ありがとうございました。

2023-08-31 03:34 UTC, KenichiroTanaka commented
複数名のレビューが通っていますのでこの辺りでマージします。

2023-08-31 03:34 UTC, merged