システムカタログの表記揺れを修正
pgsql-jp/jpug-doc pull request #2720
Opened 2023-09-01 01:16 UTC by noborus

bool値の表記を修正。真 -> true。偽 -> false。
なるべくtrue/falseが最初に出るように修正。

表内の不要な「。」を省いた。原文の「.」に準じた。
項目の説明を体言止めに修正。説明の文になっている場合は通常の文。

1文字アルファベットの場合は`<literal>a</literal> = 説明`形式に統一。

0をゼロに統一。

日本語内では全角カッコを使用するように修正。

2023-09-01 01:23 UTC, noborus commented
> 1文字アルファベットの場合は`<literal>a</literal> = 説明`形式に統一。

書いている時は`literal`タグがありますが、HTMLにするとliteralが変換されて目立たなくなるため。

元： 読み出し専用ならr、aggfinalfnの後でaggtransfnを適用できなければs、その値に書き込むならw。

新： r = 読み出し専用の場合、 s = aggfinalfnの後でaggtransfnを適用できない場合、 w = その値に書き込む場合

2023-09-09 06:49 UTC, koizumistr reviewed
確認しました。全体を見ているわけではないので的はずれな指摘があるかもです。

2023-09-09 06:49 UTC, koizumistr commented on doc/src/sgml/catalogs0.sgml
> +演算子の目的。 <literal>s</literal> = 検索用、<literal>o</literal> = 順序付け用
＜literalの直前の空白は不要かと。（なにか意図があるなら無視してください。）

2023-09-09 06:49 UTC, koizumistr commented on doc/src/sgml/catalogs0.sgml
> +IDENTITY列では、<literal>a</literal> = GENERATED ALWAYS 、<literal>d</literal> = GENERATED BY DEFAULTになります。
ALWAYSの直後の空白は不要かと。（ここも何か意図が有るなら無視してください。ただし、揃えるのならDEFAULTの直後にも空白が入ることになるのかな、と。）

2023-09-09 06:49 UTC, koizumistr commented on doc/src/sgml/catalogs0.sgml
> +さもなければ <literal>s</literal> = storedです。
＜literalの直前の空白は不要かと。（なにか意図があるなら無視してください。）

2023-09-09 06:49 UTC, koizumistr commented on doc/src/sgml/catalogs0.sgml
> +ロールはスーパーユーザの権限を持ってる
持ってる → 持っている
次のに揃えるなら 所持 / 保持 とかでしょうか（そこまでやらなくてもいいかも）

2023-09-09 06:49 UTC, koizumistr commented on doc/src/sgml/catalogs0.sgml
> +trueの場合は、テーブルあるいはインデックスが子テーブルあるいはパーテーションに継承されている（または以前に継承されていた）。
元からですけど「パーティション」では

2023-09-09 06:49 UTC, koizumistr commented on doc/src/sgml/catalogs1.sgml
> +<literal>O</literal> = トリガは<quote>origin</quote>および<quote>local</quote> モードで発行、
元からですけど、モードの直前の空白は要らないかも

2023-09-09 06:49 UTC, koizumistr commented on doc/src/sgml/catalogs1.sgml
> +trueの場合は、前回このインデックスを元にテーブルはクラスタ化された。
ここは、全体のノリだと「。」が不要だったりしませんか。

2023-09-09 06:49 UTC, koizumistr commented on doc/src/sgml/catalogs1.sgml
> +<literal>true</literal>の場合は、パーティションが取り外し処理。そうでなければ<literal>false</literal>。
処理中
では。

2023-09-09 08:53 UTC, noborus commented on doc/src/sgml/catalogs0.sgml
> +演算子の目的。 <literal>s</literal> = 検索用、<literal>o</literal> = 順序付け用
ありがとうございます。一応意図的で、１文字literalは「前後」にスペースを入れた方が良いと思って修正してます。
統一されていない方を修正したいと思います。「。」と「、」の後も入れることにして o の前にスペースを入れるようにします。

2023-09-09 08:53 UTC, noborus commented on doc/src/sgml/catalogs0.sgml
> +IDENTITY列では、<literal>a</literal> = GENERATED ALWAYS 、<literal>d</literal> = GENERATED BY DEFAULTになります。
こっちは入れるのが間違いので削ります。

2023-09-09 08:56 UTC, noborus commented on doc/src/sgml/catalogs0.sgml
> +さもなければ <literal>s</literal> = storedです。
これはあった方が良いと思うので残します。
*「さもなければs = storedです。」
*「さもなければ s = storedです。」
前者が一瞬typoっぽく見えるという理由です。

2023-09-09 08:56 UTC, noborus commented on doc/src/sgml/catalogs0.sgml
> +ロールはスーパーユーザの権限を持ってる
修正します。

2023-09-09 08:58 UTC, noborus commented on doc/src/sgml/catalogs0.sgml
> +trueの場合は、テーブルあるいはインデックスが子テーブルあるいはパーテーションに継承されている（または以前に継承されていた）。
修正します。

2023-09-09 08:58 UTC, noborus commented on doc/src/sgml/catalogs1.sgml
> +<literal>O</literal> = トリガは<quote>origin</quote>および<quote>local</quote> モードで発行、
修正します。

2023-09-09 08:58 UTC, noborus commented on doc/src/sgml/catalogs1.sgml
> +trueの場合は、前回このインデックスを元にテーブルはクラスタ化された。
修正します。

2023-09-09 08:58 UTC, noborus commented on doc/src/sgml/catalogs1.sgml
> +<literal>true</literal>の場合は、パーティションが取り外し処理。そうでなければ<literal>false</literal>。
修正します。

2023-09-09 11:21 UTC, koizumistr commented on doc/src/sgml/catalogs0.sgml
> +さもなければ <literal>s</literal> = storedです。
上にある
> １文字literalは「前後」にスペースを入れた方が良い

原則の適用ですね。了解です。

2023-09-09 11:36 UTC, KenichiroTanaka requested changes
一通り確認しました。
2点確認をお願いできないでしょうか。

2023-09-10 08:05 UTC, noborus commented on doc/src/sgml/catalogs0.sgml
> +trueの場合は、<structfield>member</structfield>が<structfield>roleid</structfield>のメンバシップを他に与えることができる
日本語の語順の入れ替えというよりも、英語と同様に「値」「説明」の順にしたい（表の中では）という意図です。
それで、trueの場合は、〜の説明が誤解を生む説明になっているかというところなのですが、どうでしょうか？

2023-09-10 13:08 UTC, koizumistr commented
確認しました。対応ありがとうございます。
残りはTrue if Aの件ですね。

2023-09-11 02:07 UTC, koizumistr commented on doc/src/sgml/catalogs0.sgml
> +trueの場合は、<structfield>member</structfield>が<structfield>roleid</structfield>のメンバシップを他に与えることができる
true: memberがroleidのメンバシップを他に与えることができる場合

とかしたらいかがでしょう。日本語として微妙かな。
（散歩中の思い付きなので、軽い気持ちで聞き流してもらえれば）

2023-09-12 01:16 UTC, KenichiroTanaka commented on doc/src/sgml/catalogs0.sgml
> +trueの場合は、<structfield>member</structfield>が<structfield>roleid</structfield>のメンバシップを他に与えることができる
>trueの場合は、〜の説明が誤解を生む説明になっているかというところなのですが、どうでしょうか？
文章のロジックが異なってしまうのでNGではないかと思います（社内メンバにも聞いてみましたが同様の意見でした）。

どうしても日本語にしてしまうと結論が最後になるので、小泉さん案が良いように思いますが、
どうでしょうか。

2023-09-12 04:52 UTC, noborus commented on doc/src/sgml/catalogs0.sgml
> +trueの場合は、<structfield>member</structfield>が<structfield>roleid</structfield>のメンバシップを他に与えることができる
うーん。変更ではなく元から説明が削ってしまっているということだと思ってます。
https://pgsql-jp.github.io/current/html/catalog-pg-auth-members.html の表の中の
admin_option bool の説明なので、「trueの場合は、〜できる」で足りていると思ったのですが、戻しますかね。

2023-09-13 16:02 UTC, KenichiroTanaka commented on doc/src/sgml/catalogs0.sgml
> +trueの場合は、<structfield>member</structfield>が<structfield>roleid</structfield>のメンバシップを他に与えることができる
今回は良いとしても他の箇所で今後翻訳対応する人が似たような箇所でこの機微を理解して翻訳できる（もしくはレビュアが気づく）のも難しいのかなと思います。量が多いので大変申し訳ないのですが、戻していただくのが良いのかと思っています(もし、いただいている形にするのであれば、原文に手を入れる必要があると考えています。

2023-09-19 03:49 UTC, noborus commented
booleanの項目を修正しました。

2023-09-22 11:23 UTC, KenichiroTanaka approved these changes
量が多い依頼でしたが対応ありがとうございました。マージします。

2023-09-22 11:23 UTC, merged

2023-09-22 11:24 UTC, KenichiroTanaka commented
@noborus さん
これを16にバックポートする方法が分からないのですが、良い方法はありますでしょうか？

2023-09-22 15:14 UTC, noborus commented
基本的に `jpug-doc-tool replace -u catalogs.sgml` でいけるのですが、一部うまくいかない箇所の修正が必要になります。
出しておきます。