config.sgmlのPostgreSQL 16.0対応です。
pgsql-jp/jpug-doc pull request #2735
Opened 2023-09-29 02:25 UTC by tatsuo-ishii

2023-09-29 02:47 UTC, tatsuo-ishii commented
何がNG語になっているのかわかりません。ローカルでは make checkでエラーにならないのですが...

2023-09-29 03:01 UTC, noborus commented on doc/src/sgml/config3.sgml
> +この安全機構が起動すると、すべての有効なコストに基づく遅延はもはや適用されず、（インデックスのバキュームのような）必須ではない保守タスクは迂回されます。
。後にスペースが含まれています。
```suggestion
この安全機構が起動すると、すべての有効なコストに基づく遅延はもはや適用されず、（インデックスのバキュームのような）必須ではない保守タスクは迂回されます。
```

2023-09-29 03:05 UTC, noborus commented on doc/src/sgml/config3.sgml
> +この安全機構が起動すると、すべての有効なコストに基づく遅延はもはや適用されず、（インデックスのバキュームのような）必須ではない保守タスクは迂回されます。
check-ngの仕組みの中に入れてしましたが、引っかかって表示される箇所が「。」だけなので分かりづらいですね...

```
。\s\+$
```

2023-09-29 03:52 UTC, tatsuo-ishii commented on doc/src/sgml/config3.sgml
> +この安全機構が起動すると、すべての有効なコストに基づく遅延はもはや適用されず、（インデックスのバキュームのような）必須ではない保守タスクは迂回されます。
ありがとうございます。
ローカルのmake checkではエラーにならなかったのですが、プラットフォーム依存なのでしょうか？

2023-09-29 06:56 UTC, noborus commented on doc/src/sgml/config3.sgml
> +この安全機構が起動すると、すべての有効なコストに基づく遅延はもはや適用されず、（インデックスのバキュームのような）必須ではない保守タスクは迂回されます。
> ありがとうございます。 ローカルのmake checkではエラーにならなかったのですが、プラットフォーム依存なのでしょうか？

ああ、なるほど。 git grepの正規表現で行末を指定しているので差が出る可能性はあります。

```console
git grep "。\s\+$"
```

だとヒットしない環境があるかもしれません。

2023-09-30 04:36 UTC, tatsuo-ishii commented on doc/src/sgml/config3.sgml
> +この安全機構が起動すると、すべての有効なコストに基づく遅延はもはや適用されず、（インデックスのバキュームのような）必須ではない保守タスクは迂回されます。
doc/src/sgml/Makefileのmake check -> make check-ng にはそうしたチェックは入っていないようですが？

2023-10-01 01:10 UTC, noborus commented on doc/src/sgml/config3.sgml
> +この安全機構が起動すると、すべての有効なコストに基づく遅延はもはや適用されず、（インデックスのバキュームのような）必須ではない保守タスクは迂回されます。
```
@if git --no-pager grep -f .ng.list *sgml ref/*sgml; \
```

で.ng.listに`。\s\+$`が入っているので、同じ動きになると思ったのですが、
考えてみると、ここでも動きが変わる可能性がありますね。

後はローカルでgit-configの設定が入っていると変わりますね。
https://git-scm.com/docs/git-grep

`--basic-regexp`を入れるとヒットするようになるでしょうか？

```
git  grep --basic-regexp  -f .ng.list *sgml ref/*sgml
```

2023-10-01 02:25 UTC, tatsuo-ishii commented on doc/src/sgml/config3.sgml
> +この安全機構が起動すると、すべての有効なコストに基づく遅延はもはや適用されず、（インデックスのバキュームのような）必須ではない保守タスクは迂回されます。
--basic-regexpの有無で変化はないです。

2023-10-01 02:32 UTC, tatsuo-ishii commented on doc/src/sgml/config3.sgml
> +この安全機構が起動すると、すべての有効なコストに基づく遅延はもはや適用されず、（インデックスのバキュームのような）必須ではない保守タスクは迂回されます。
> git grep "。\s\+$"  config.sgml

と手で直接叩くと、OKでした。

2023-10-01 08:29 UTC, noborus commented on doc/src/sgml/config3.sgml
> +この安全機構が起動すると、すべての有効なコストに基づく遅延はもはや適用されず、（インデックスのバキュームのような）必須ではない保守タスクは迂回されます。
ありがとうございます。手元でも試しましたが、git grepのときに'+'を'\+'にしているのがまずいような気がします。
これを"。\s+$"にすると手元で引っかからなかったので、'\+"にしたのですが、
git grep -E "。\s+$"ならば引っかかったので、`-E`を必ず付けるのが動作が一定になるように思います。

なので .ng.listの「。\s\+$」を「。\s+$」に修正して、`git grep -E`に変更する。
grep -f ../../../.ng.list の場合も`grep -E -f ../../../.ng.list`で引っかかるようになると思います。
よければ、これで修正します。

2023-10-01 10:40 UTC, tatsuo-ishii commented on doc/src/sgml/config3.sgml
> +この安全機構が起動すると、すべての有効なコストに基づく遅延はもはや適用されず、（インデックスのバキュームのような）必須ではない保守タスクは迂回されます。
> なので .ng.listの。\s\+$を。\s+$に修正して、git grep -Eに変更する。

大正解のようです。これでうまくいきました！

2023-10-01 11:57 UTC, noborus commented on doc/src/sgml/config3.sgml
> +この安全機構が起動すると、すべての有効なコストに基づく遅延はもはや適用されず、（インデックスのバキュームのような）必須ではない保守タスクは迂回されます。
ありがとうございます。修正します。

2023-10-01 12:07 UTC, tatsuo-ishii commented on doc/src/sgml/config3.sgml
> +この安全機構が起動すると、すべての有効なコストに基づく遅延はもはや適用されず、（インデックスのバキュームのような）必須ではない保守タスクは迂回されます。
ありがとうございます。pull request #2736 はマージしました。

2023-10-03 13:24 UTC, KenichiroTanaka requested changes
まずはconfig0を確認しました。
いくつか気づくところがありましたのでみていただいてもいいでしょうか。

2023-10-03 13:24 UTC, KenichiroTanaka commented on doc/src/sgml/config0.sgml
>  このパラメータは、<filename>PostgreSQL.conf</filename>ファイルまたはサーバコマンドラインでのみ設定できます。
ファイル名が一部大文字になってしまっています。
PostgreSQL.conf→postgresql.conf

2023-10-03 13:24 UTC, KenichiroTanaka commented on doc/src/sgml/config0.sgml
>  この値がunitsなしで指定された場合、キロバイトとして取得されます。
他の箇所では
「この値が単位なしで指定された場合は、キロバイト単位であるとみなします」
と表現されているようです。

2023-10-03 13:24 UTC, KenichiroTanaka commented on doc/src/sgml/config0.sgml
> +このパラメータは、<option>バッファ_USAGE_LIMIT</option>オプションを渡すことによって、<xref linkend="sql-vacuum"/>および<xref linkend="sql-analyze"/>に対して上書きできます。
パラメータ名ですので
<option>バッファ_USAGE_LIMIT</option>
→
<option>BUFFER_USAGE_LIMIT</option>が良いかと思います。

2023-10-12 03:40 UTC, KenichiroTanaka requested changes
遅くなりましたがconfig1までチェックしました。
いくつか気づくところがありましたのでご確認をおお願いします。

2023-10-12 14:11 UTC, KenichiroTanaka requested changes
いくつか気づくところがありましたので見ていただいてもいいでしょうか。

2023-10-12 14:11 UTC, KenichiroTanaka commented on doc/src/sgml/config3.sgml
>  これにより、子プロセスは多かれ少なかれ優雅に終了することができます。
gracefullyですが「優雅に」だと分かりづらいように思います。
「上品に」くらいの訳でどうでしょうか（ちょっと自信がありません）。。

2023-10-12 14:11 UTC, KenichiroTanaka commented on doc/src/sgml/config3.sgml
>  このパラメータは<filename>PostgreSQL.conf</filename>ファイルまたはサーバコマンドラインでのみ設定できます。
ファイル名ですのでPostgreSQL.confはpostgresql.confが良いように思います。

2023-10-12 14:11 UTC, KenichiroTanaka commented on doc/src/sgml/config3.sgml
>  このパラメータは<filename>PostgreSQL.conf</filename>ファイルまたはサーバコマンドラインでのみ設定できます。
同上です。

2023-10-23 10:00 UTC, tatsuo-ishii commented on doc/src/sgml/config3.sgml
>  これにより、子プロセスは多かれ少なかれ優雅に終了することができます。
「礼儀正しく」としてみました。

2023-10-23 10:01 UTC, tatsuo-ishii commented on doc/src/sgml/config3.sgml
>  このパラメータは<filename>PostgreSQL.conf</filename>ファイルまたはサーバコマンドラインでのみ設定できます。
修正しました。

2023-10-23 10:02 UTC, tatsuo-ishii commented on doc/src/sgml/config3.sgml
>  このパラメータは<filename>PostgreSQL.conf</filename>ファイルまたはサーバコマンドラインでのみ設定できます。
修正しました。

2023-10-23 13:03 UTC, koizumistr reviewed
config0.sgml 見ました。

2023-10-23 13:03 UTC, koizumistr commented on doc/src/sgml/config0.sgml
>  デフォルト値は<literal>256キロバイト</literal>です。
ここも上と同じノリなら"256 kB"にすべきと思います。

2023-10-23 13:03 UTC, koizumistr commented on doc/src/sgml/config0.sgml
> +設定を高くすると、<command>バキューム</command>および<command>ANALYZE</command>の実行速度が速くなりますが、設定を高くしすぎると、他の多くの有用なページが共有バッファから削除されてしまう可能性があります。
バキューム -> VACUUM

2023-10-24 09:52 UTC, tatsuo-ishii reviewed
小泉さん、レビューありがとうございます。

2023-10-24 09:52 UTC, tatsuo-ishii commented on doc/src/sgml/config0.sgml
> +<command>VACUUM</command>コマンドおよび<command>ANALYZE</command>コマンドで使用される<glossterm linkend="glossary-buffer-access-strategy">バキュームアクセスストラテジ</glossterm>の大きさを指定します。
機械翻訳が謎の置き換えをしていました。修正します。

2023-10-24 09:52 UTC, tatsuo-ishii commented on doc/src/sgml/config0.sgml
> +それ以外の場合は、有効なサイズは<literal>128キロバイト</literal>から<literal>16ギガバイト</literal>までの範囲です。
どうでしょう？PostgreSQLでは、値の設定単位はユーザが自由に選択できるので、"16 GB"ではなくて、"16777216 kB"と設定することも可能です。ですから、「この大さであれば、好きな単位で設定してください」という意味を「128キロバイト」などとしました。
ただ、（いないとは思いますが）「128キロバイト」とまさにそのままカタカナで単位を書いてしまうユーザがいないとも限らないので、やはり"128 kB"などとしておきます。

2023-10-24 09:52 UTC, tatsuo-ishii commented on doc/src/sgml/config0.sgml
>  デフォルト値は<literal>256キロバイト</literal>です。
了解です。

2023-10-24 09:52 UTC, tatsuo-ishii commented on doc/src/sgml/config0.sgml
> +設定を高くすると、<command>バキューム</command>および<command>ANALYZE</command>の実行速度が速くなりますが、設定を高くしすぎると、他の多くの有用なページが共有バッファから削除されてしまう可能性があります。
修正します。

2023-10-29 13:36 UTC, koizumistr commented on doc/src/sgml/config0.sgml
> +それ以外の場合は、有効なサイズは<literal>128キロバイト</literal>から<literal>16ギガバイト</literal>までの範囲です。
> （いないとは思いますが）「128キロバイト」とまさにそのままカタカナで単位を書いてしまうユーザがいないとも限らないので

流石にそんな人は、、、と思いたいところですが、これを書いているうちにだんだん言い切る自信がなくなってきました。

> PostgreSQLでは、値の設定単位はユーザが自由に選択できるので、"16 GB"ではなくて、"16777216 kB"と設定することも可能です。

これは大事な良い情報だと思うのですが、ドキュメントのどこか他のところに書いてあったりするのでしょうか。（この件だけでなく一般的な話かと思いますので。）

2023-10-29 14:06 UTC, koizumistr reviewed
確認しました。

（config.sgmlは見なくていいはずですから）今回は一通り目を通したことになります。

2023-10-29 14:06 UTC, koizumistr commented on doc/src/sgml/config3.sgml
>  このオプションが<literal>オン</literal>に設定されている場合、代わりに<systemitem>SIGABRT</systemitem>が送信されます。
以前からの部分なのですが、＜literal＞on＜/literal＞と＜literal＞の中にあるonは訳さないでonのままでいい気がしました。
＜literal＞の中にあるonを「オン」と訳しているのはconfigだけのようです。

2023-10-30 01:59 UTC, tatsuo-ishii commented on doc/src/sgml/config0.sgml
> +それ以外の場合は、有効なサイズは<literal>128キロバイト</literal>から<literal>16ギガバイト</literal>までの範囲です。
「20.1.1. パラメータ名とその値 」に以下の記述があります。
「単位付きの数値: 数値型のパラメータによっては暗黙的な単位を持つことがあります。 メモリの量や時間について記述するからです。 単位はバイト、キロバイト、ブロック（通常8キロバイト）、ミリ秒、秒、分などです。 修飾無しの数値によるこれらの設定においては、 pg_settings.unit からデフォルト値が採用されます。 使い勝手を考えて、たとえば'120 ms'のように単位を明示的に指定することもできます。 この場合は、実際の単位に変換が行われます。 なお、この機能を使う場合は、引用符付きの文字列として値を指定しなければならないことに注意してください。 単位の名称は大文字小文字を区別します。 また、数値と単位の間に空白があっても構いません。 」

2023-10-31 04:59 UTC, tatsuo-ishii reviewed
レビューありがとうございます。

2023-10-31 04:59 UTC, tatsuo-ishii commented on doc/src/sgml/config0.sgml
> +このパラメータは、<symbol>TCP_USER_TIMEOUT</symbol>をサポートするシステム（Windowsは含ません）でのみ使用できます。他のシステムでは、0にする必要があります。
修正します。

2023-10-31 04:59 UTC, tatsuo-ishii commented on doc/src/sgml/config2.sgml
> +             <entry>トランザクションID（0がアサインされていない場合）。
そうですね。

2023-10-31 04:59 UTC, tatsuo-ishii commented on doc/src/sgml/config3.sgml
> +<command>VACUUM</command>が、古いXIDを持つページをフリーズするきっかけとするかどうかを決定する、カットオフ（トランザクションにおける）年代を指定します。
いただきます。

2023-10-31 04:59 UTC, tatsuo-ishii commented on doc/src/sgml/config3.sgml
> +に一時ファイルを削除します。
修正します。

2023-10-31 04:59 UTC, tatsuo-ishii commented on doc/src/sgml/config3.sgml
>  このオプションが<literal>オン</literal>に設定されている場合、代わりに<systemitem>SIGABRT</systemitem>が送信されます。
修正します。

2023-10-31 04:59 UTC, tatsuo-ishii commented on doc/src/sgml/config0.sgml
> +空き接続スロットの数が<xref linkend="guc-superuser-reserved-connections"/>よりも大きく、かつ<varname>superuser_reserved_connections</varname>と<varname>reserved_connections</varname>の合計よりも小さい場合は常に、新しい接続はスーパーユーザあるいは<liter
修正します。

2023-11-06 11:33 UTC, KenichiroTanaka approved these changes
対応ありがとうございました。

2023-11-06 13:07 UTC, koizumistr reviewed
確認しました。対応ありがとうございます。

2023-11-06 13:11 UTC, koizumistr commented
私の確認でマージに持って行ってもいいようにも思いますが、やり取りが長くて見落としがありそうな気がしたので、念のため「マージまち」で止めておきます。

2023-11-07 09:23 UTC, KenichiroTanaka commented
ざっと確認しましたが問題なさそうですのでここで一度マージします。

2023-11-07 09:23 UTC, merged