acronyms.sgmlの16.0対応です
pgsql-jp/jpug-doc pull request #2743
Opened 2023-10-23 21:22 UTC by noborus

2023-10-23 23:06 UTC, KenichiroTanaka requested changes
1箇所だけ見ていただいてもいいでしょうか。

2023-10-23 23:06 UTC, KenichiroTanaka commented on doc/src/sgml/acronyms.sgml
> +<glossterm linkend="glossary-log-sequence-number">ログシーケンス番号</glossterm>
glosstermですが、英語【訳】が基本のようです。
https://www.postgresql.jp/document/15/html/glossary.html
<glossterm linkend="glossary-log-sequence-number">Log Sequence Number【ログシーケンス番号】</glossterm>
としていただいてもいいでしょうか。
このページ統一できてないですね。
まとめてPR出しておきます。

2023-10-29 14:24 UTC, koizumistr commented on doc/src/sgml/acronyms.sgml
> +頻出値の頻度、つまり最頻値が現れる頻度
「頻出値の頻度」ではなく「最頻値の頻度」ではないでしょうか。
でもそう説明的に訳すとつまりの後と同じになってしまう、、、、、、、、

2023-11-06 11:37 UTC, KenichiroTanaka approved these changes
対応ありがとうございました。
小泉さんからの指摘部分は別途考えてコメントします。

2024-02-23 03:34 UTC, tatsuo-ishii commented on doc/src/sgml/acronyms.sgml
> +頻出値の頻度、つまり最頻値が現れる頻度
「最頻値の頻度」で良いのではないでしょうか。他に訳しようがないような。

2024-02-23 04:59 UTC, noborus commented on doc/src/sgml/acronyms.sgml
> +頻出値の頻度、つまり最頻値が現れる頻度
放っておいてすみません。

頭字語なので、略前の英語が必要でした。以下のようにします。

Most Common Frequency（最貧値の頻度）、つまり最頻値が現れる頻度

Most Common Value（最頻値）、特定のテーブル列で最も頻繁に現れる値の1つ

2024-03-03 01:33 UTC, koizumistr reviewed
結論が出ているようなのでマージまで進めます。

2024-03-03 01:33 UTC, merged