update for release-16
pgsql-jp/jpug-doc pull request #2753
Opened 2023-10-31 03:11 UTC by kitayama

ざっと一通り翻訳しました。見直しや手直しが望ましいとは思いますが、長い間持ってい(て飽き)たので pull request させてください。よろしくお願いします。

2023-11-02 12:02 UTC, tatsuo-ishii commented
「余計な改行が入っているようです。」のようなコメントをたくさんつけてしまいました。今更ですが、リリースノートの翻訳では、貢献者の名前を改行していから記載しているのですね。たとえば原文が、

> Remove xxx (Tom Lane)

であると、

> xxxを削除しました。
> (Tom Lane)

のように。このように貢献者の名前の前に改行を入れるのは何故なんでしたっけ？
少なくとも、PostgreSQL 10ではすでにそうなっているようですが。

2023-11-07 07:21 UTC, noborus commented on doc/src/sgml/release-16.sgml
> +<acronym>ICU</acronym>サポートビルドがデフォルトになりました。
ICUサポートビルドだと別の意味に取れるような気もするので、「ICUサポートのビルドがデフォルトになりました。」ではどうでしょうか？

2023-11-07 07:21 UTC, noborus commented on doc/src/sgml/release-16.sgml
> +<systemitem class="osname">Windows 10</systemitem>の新しいバージョンで<link linkend="guc-huge-pages">huge pages</link>を使用できるようにしました。
「Windows 10以降のバージョンで」だとまずいですかね...
この後の
「これにより、新しいバージョンの`<systemitem class="osname">Windows 10</systemitem>`でヒープページを有効にするために必要となる特別な処理が追加されます。」も
「これにより、`<systemitem class="osname">Windows 10</systemitem>`以降のバージョンでヒープページを有効にするために必要となる特別な処理が追加されます。」の方が自然だと思うのですが。

2023-12-07 12:14 UTC, KenichiroTanaka requested changes
2/3見ました。時間がかかってしまっているので一度Change Request出します。残りは追って確認します。

2023-12-10 12:40 UTC, KenichiroTanaka requested changes
一通り確認しました。残り２点見ていただいてもいいでしょうか。

2023-12-10 12:40 UTC, KenichiroTanaka commented on doc/src/sgml/release-16.sgml
> +<link linkend="auto-explain"><application>auto_explain</application></link>がパラメータ化された文に渡された値をログするようにしました。
細かいですが「ログする」という訳語はこれまで使ってこなかったと思います。
「ログへ記録するようになりました」
あたりの訳語でどうでしょうか。

2023-12-22 00:46 UTC, kitayama commented on doc/src/sgml/release-16.sgml
> +<productname>PostgreSQL</productname>16には、以下をはじめとする多数の新機能と拡張が含まれます。
対応しました。

2023-12-22 00:47 UTC, kitayama commented on doc/src/sgml/release-16.sgml
> +以前は、<application>pg_rewind</application>がタイムラインの切り替え後でチェックポイントが発行される前に実行された場合、<application>pg_rewind</application>はリワインドが不要であると誤って判断する可能性がありました。
巻き戻しに変更しました。

2023-12-22 00:48 UTC, kitayama commented on doc/src/sgml/release-16.sgml
> +<acronym>ICU</acronym>サポートビルドがデフォルトになりました。
頂いた案で修正しました。

2023-12-22 00:52 UTC, kitayama commented on doc/src/sgml/release-16.sgml
> +<systemitem class="osname">Windows 10</systemitem>の新しいバージョンで<link linkend="guc-huge-pages">huge pages</link>を使用できるようにしました。
修正しました。

2023-12-22 00:59 UTC, kitayama commented on doc/src/sgml/release-16.sgml
> +新しい<structname>pg_stat_io</structname>ビューを使用した<acronym>I/O</acronym>統計統計の監視ができるようになりました。
おお、これは何と。修正しました。

2023-12-22 01:02 UTC, kitayama commented on doc/src/sgml/release-16.sgml
> +親テーブル(パーティションテーブル)と子テーブル(パーティション)の列はすべて同じ生成状態を持つ必要がありますが、実際の生成式は異なっていても構いません。
いただいた内容で修正しました。

2023-12-22 01:17 UTC, kitayama commented on doc/src/sgml/release-16.sgml
> +<link linkend="sql-createtable"><command>CREATE TABLE</command></link>で<literal>STORAGE</literal>型を指定できるようにしました。
型だとデータ型のように見えますね。属性も意味としてはよいと思いますが意訳し過ぎとも思いますので、タイプに修正しました。

2023-12-22 01:18 UTC, kitayama commented on doc/src/sgml/release-16.sgml
> +全文検索結果の強調をおこなう(<link linkend="textsearch-functions-table"><function>ts_headline()</function></link>)関数での<literal>OR</literal>および<literal>NOT</literal>式に対する処理を改善しました。
「全文検索結果を強調する」に変更しました。

2023-12-22 01:23 UTC, kitayama commented on doc/src/sgml/release-16.sgml
> +出力をきれいに表示するための<link linkend="datatype-xml-creating"><function>XMLSERIALIZE()</function></link>関数の<literal>INDENT</literal>オプションを追加しました。
修正しました。

2023-12-22 01:23 UTC, kitayama commented on doc/src/sgml/release-16.sgml
> +この認証方式のバックエンドサポートは<productname>PostgresSQL</productname>9.1で削除されました。
修正しました。

2023-12-22 01:24 UTC, kitayama commented on doc/src/sgml/release-16.sgml
> +<link linkend="auto-explain"><application>auto_explain</application></link>がパラメータ化された文に渡された値をログするようにしました。
確かにそうですね。いただいた内容で修正しました。

2023-12-22 01:35 UTC, kitayama commented
> 「余計な改行が入っているようです。」のようなコメントをたくさんつけてしまいました。今更ですが、リリースノートの翻訳では、貢献者の名前を改行していから記載しているのですね。たとえば原文が、
> 
> > Remove xxx (Tom Lane)
> 
> であると、
> 
> > xxxを削除しました。
> > (Tom Lane)
> 
> のように。このように貢献者の名前の前に改行を入れるのは何故なんでしたっけ？ 少なくとも、PostgreSQL 10ではすでにそうなっているようですが。



> 「余計な改行が入っているようです。」のようなコメントをたくさんつけてしまいました。今更ですが、リリースノートの翻訳では、貢献者の名前を改行していから記載しているのですね。たとえば原文が、
> 
> > Remove xxx (Tom Lane)
> 
> であると、
> 
> > xxxを削除しました。
> > (Tom Lane)
> 
> のように。このように貢献者の名前の前に改行を入れるのは何故なんでしたっけ？ 少なくとも、PostgreSQL 10ではすでにそうなっているようですが。

理由はわからないですが、このように独立した行にあるほうがこの直前の文と分離されるので翻訳作業はしやすいです。

2023-12-22 11:39 UTC, KenichiroTanaka approved these changes
対応ありがとうございました。
私の指摘文は修正いただけていることを確認しました。

2023-12-26 22:40 UTC, tatsuo-ishii commented
私のコメントの件は、歴史的経緯でそうなっており、特に今更変えるメリットはなさそうなので、現状維持としましょう。
二人でレビューしたので、マージします。

2023-12-26 22:40 UTC, merged