update *_stat for 16.0
pgsql-jp/jpug-doc pull request #2754
Opened 2023-11-04 06:06 UTC by koizumistr

以下のファイルの16.0対応です。

- alter_statistics.sgml
- ref/create_statistics.sgml

2023-11-06 12:23 UTC, KenichiroTanaka requested changes
1箇所だけ、見ていただけないでしょうか。私だけの問題かもしれません。

2023-11-18 02:39 UTC, koizumistr commented on doc/src/sgml/ref/create_statistics.sgml
> +指定された場合、統計オブジェクトの名前は、同じスキーマ内のどの統計オブジェクトとも異なるものでなければなりません。
確かに指摘の通り、
> 最初は「スキーマが指定された場合、」と読んでしまった

となってしまう人が多く出るような気がします。

この文の直前では
> スキーマ名が指定された場合〜〜
> スキーマ名を指定しなければ、〜〜

とスキーマ名の指定の話が続いていますので、「『指定された場合』？二つ前の文に話が戻ったのかな？」となるような、、、

2023-11-18 02:41 UTC, koizumistr commented
確認ありがとうございます。対応しました。

2023-11-18 02:45 UTC, koizumistr commented on doc/src/sgml/ref/create_statistics.sgml
> +指定された場合、統計オブジェクトの名前は、同じスキーマ内のどの統計オブジェクトとも異なるものでなければなりません。
原文が
> If given, 

なので、もしかしたら原文が好ましくないのかもです。
ただし、原文は直後に
> If given, the name of the statistics object

となっているので、英語を普段から使っている人にとってはgivenされるのは"the name of the statistics object"に決まっているだろ！となるのかも知れません。その辺りの感覚は私には分かりませんが、、、

2023-11-18 23:09 UTC, KenichiroTanaka approved these changes
ご確認いただきありがとうございます。
確かに原文が分かりにくいかもですね。。ひとまず、本件はここでマージします。

2023-11-18 23:10 UTC, merged