update pg_* for 16.0
pgsql-jp/jpug-doc pull request #2763
Opened 2023-11-05 09:48 UTC by koizumistr

以下のファイルの 16.0 対応です。

- ref/pg_dumpall.sgml
- ref/pg_receivewal.sgml
- ref/pg_recvlogical.sgml
- ref/pg_rewind.sgml
- ref/pg_verifybackup.sgml

2023-11-13 12:26 UTC, KenichiroTanaka requested changes
細かいのですが1点だけ見ていただけないでしょうか。

2023-11-13 12:26 UTC, KenichiroTanaka commented on doc/src/sgml/ref/pg_recvlogical.sgml
> +<application>pg_recvlogical</application>は<systemitem>SIGINT</systemitem>または<systemitem>SIGTERM</systemitem>シグナルで終了されたとき、ステータス0で終了します。
細かいですが、ここまでterminatedは「停止されるまで」としてきたため、ここも同じようにすると1文で「終了する」が2回出てこなくて済みますが、どうでしょうか。

「<application>pg_recvlogical</application>は<systemitem>SIGINT</systemitem>または<systemitem>SIGTERM</systemitem>シグナルで終了されたとき、ステータス0で終了します。」
→
「<application>pg_recvlogical</application>は<systemitem>SIGINT</systemitem>または<systemitem>SIGTERM</systemitem>シグナルで停止されたとき、ステータス0で終了します。」

2023-11-13 14:32 UTC, koizumistr commented on doc/src/sgml/ref/pg_recvlogical.sgml
> +<application>pg_recvlogical</application>は<systemitem>SIGINT</systemitem>または<systemitem>SIGTERM</systemitem>シグナルで終了されたとき、ステータス0で終了します。
（上にある？）SIGINTとSIGTERMが出てくる表現に合わせるということですね。いただきます。

2023-11-16 10:11 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。

2023-11-16 10:11 UTC, merged