update *_publication for 16.0
pgsql-jp/jpug-doc pull request #2765
Opened 2023-11-07 12:42 UTC by koizumistr

以下のファイルの 16.0 対応です。

- ref/alter_publication.sgml
- ref/create_publication.sgml

2023-11-16 10:52 UTC, KenichiroTanaka commented on doc/src/sgml/ref/create_publication.sgml
> +パーティションテーブルが、<literal>publish_via_partition_root = true</literal>に設定されたサブスクライブされたパブリケーションによってパブリッシュされる場合、このパーティションテーブル(またはそのパーティション)の変更は、個々のパーティションのものではなく、このパーティションテーブルのIDとスキーマを使用してパブリッシュされます。
原文がそうなのですが「された・・・」が3回続くので少し分かりにくいと思いました。
一部を能動形に変えるのはどうでしょうか。
```
パーティションテーブルが、<literal>publish_via_partition_root = true</literal>に設定されたサブスクライブされたパブリケーションによってパブリッシュされる場合、
```
↓
```
<literal>publish_via_partition_root = true</literal>を設定しサブスクライブされたパブリケーションがパーティションテーブルをパブリッシュする場合、
```
ちょっと自信がありません。ご意見いただきたいです。

2023-12-17 00:57 UTC, tatsuo-ishii requested changes

2023-12-17 00:57 UTC, tatsuo-ishii commented on doc/src/sgml/ref/create_publication.sgml
> +パーティションテーブルが、<literal>publish_via_partition_root = true</literal>に設定されたサブスクライブされたパブリケーションによってパブリッシュされる場合、このパーティションテーブル(またはそのパーティション)の変更は、個々のパーティションのものではなく、このパーティションテーブルのIDとスキーマを使用してパブリッシュされます。
田中さんの変更案に賛成です。

2023-12-17 00:57 UTC, tatsuo-ishii commented on doc/src/sgml/ref/create_publication.sgml
> +サブスクリプションが複数のパブリケーションを組み合わせている場合があります。
ここは「複数」との対比を明確にするために、"a"を訳出して「ひとつのサブスクリプションが」としてはいかがでしょう。

2023-12-17 09:15 UTC, koizumistr commented
確認ありがとうございます。対応しました。

2023-12-17 22:29 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。

2023-12-26 22:37 UTC, tatsuo-ishii approved these changes
対応ありがとうございます。確認しました。

2023-12-26 22:38 UTC, tatsuo-ishii commented
二人で確認したので、マージします。

2023-12-26 22:38 UTC, merged