update for 16.0 - new part 10
pgsql-jp/jpug-doc pull request #2767
Opened 2023-11-12 14:10 UTC by koizumistr

以下のファイルの 16.0 対応です。

- contrib-spi.sgml
- fdwhandler.sgml
- json.sgml

2023-11-17 23:17 UTC, noborus commented on doc/src/sgml/fdwhandler.sgml
> +<productname>PostgreSQL</productname> 16以降、<structfield>fs_relids</structfield>には、この結合に関連する外部結合がある場合、そのレンジテーブルの添字が含まれます。
rangetable は他にはないですが、「range table」だと「範囲テーブル」としているようです。

2023-11-17 23:17 UTC, noborus commented on doc/src/sgml/json.sgml
> +SQL/JSONパス式の数値リテラルは、JavaScriptルールに従います。JavaScriptルールは、SQLやJSONの両方とはいくつかの細かい点で異なります。
間違いではないと思いますが、ちょっと違和感があって
「JavaScriptルールは、いくつかの細かい点でSQLやJSONの両方とも異なります。」
の方が自然に感じました。

2023-11-18 02:29 UTC, koizumistr commented
確認ありがとうございます。
「JavaScriptルールは」のところは指摘の通りと思いましたが、さらにもう一捻りしてみました。いかがでしょう。

2023-11-18 23:28 UTC, KenichiroTanaka requested changes
1箇所気づくところがありましたのでご確認をお願いします。

2023-11-18 23:28 UTC, KenichiroTanaka commented on doc/src/sgml/json.sgml
> +例えば、SQL/JSONパスでは<literal>.1</literal>や<literal>1_000_000</literal>が有効ですが、JSONでは無効です。
```
<literal>.1</literal>や<literal>1_000_000</literal>が有効です
```
の箇所は原文を見ると
```
<literal>.1</literal>や<literal>1.</literal>が有効です
```
なのかと思います。機械翻訳もなぜこんな間違い方をしたのか・・・。

2023-11-19 13:15 UTC, koizumistr commented
、、、、、、、、、、、、、、、、、、orz

確認ありがとうございます。対応しました。

2023-11-19 22:36 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。私の指摘箇所はOKです。

2023-11-20 00:52 UTC, noborus commented
> 確認ありがとうございます。 「JavaScriptルールは」のところは指摘の通りと思いましたが、さらにもう一捻りしてみました。いかがでしょう。

ありがとうございます。良くなったと思います。

2023-11-20 00:52 UTC, noborus commented
確認済みということでマージします。

2023-11-20 00:52 UTC, merged