update vacuum for 16.0
pgsql-jp/jpug-doc pull request #2785
Opened 2023-11-21 13:33 UTC by koizumistr

ref/vacuum.sgml の 16.0 対応です。

2023-12-17 22:59 UTC, KenichiroTanaka requested changes
少し気づくところがありましたので見ていただけますでしょうか

2023-12-17 22:59 UTC, KenichiroTanaka commented on doc/src/sgml/ref/vacuum.sgml
> +ただし、非常に数多くのテーブルを持つデータベースでは、これには時間がかかる可能性があり、最も古いフリーズされていないXIDを含むテーブルがバキュームされたテーブルの中にない限り、何も達成されません。
freezeは他では「凍結」としているようです。

2023-12-17 22:59 UTC, KenichiroTanaka commented on doc/src/sgml/ref/vacuum.sgml
> +設定を高くすると<command>VACUUM</command>の実行速度がより速くなりますが、設定が大きs過ぎると、とても多くの他の有用なページが共有バッファから追い出されてしまう可能性があります。
「大きs過ぎると」とsが混じっています。

2023-12-17 22:59 UTC, KenichiroTanaka commented on doc/src/sgml/ref/vacuum.sgml
> +<command>VACUUM</command>が、最も古いフリーズされていないXIDについて、データベース全体の統計情報を更新する以外に何もしないことを指定します。
同上です。

2023-12-18 08:32 UTC, koizumistr commented
確認ありがとうございます。対応しました。

2023-12-22 11:35 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。
確認しました。

2023-12-22 11:35 UTC, merged