update pg_waldump for 16.0
pgsql-jp/jpug-doc pull request #2786
Opened 2023-11-21 14:11 UTC by koizumistr

ref/pg_waldump.sgml の 16.0 対応です。

2023-12-17 23:15 UTC, KenichiroTanaka requested changes
いくつか気づくところがありましたので見ていただけますでしょうか

2023-12-17 23:15 UTC, KenichiroTanaka commented on doc/src/sgml/ref/pg_waldump.sgml
> +WALセグメントファイルを見つけ出すディレクトリ、あるいはログセグメントファイルが含まれる<literal>pg_wal</literal>サブディレクトリが含まれるディレクトリを指定します。
ログファイルをWALファイルに変更するところですので2つめの「あるいはログセグメントファイル」も
「あるいはWALセグメントファイル」が良いと思います。

2023-12-17 23:15 UTC, KenichiroTanaka commented on doc/src/sgml/ref/pg_waldump.sgml
> +デフォルトでは、最初に見つかったファイルの中で最初に見つかったWALログレコードから読み取りを始めます。
「WALログレコード」は「WALレコード」が良いかと思います。

2023-12-18 14:03 UTC, koizumistr commented
確認ありがとうございます。対応しました。

2023-12-22 11:36 UTC, KenichiroTanaka approved these changes
対応ありがとうございます

2023-12-22 11:36 UTC, merged