update rules for 16.0
pgsql-jp/jpug-doc pull request #2787
Opened 2023-11-21 14:33 UTC by koizumistr

rules.sgml の 16.0 対応です。

2023-12-22 11:52 UTC, KenichiroTanaka requested changes
1箇所だけ気づくところがありましたので見ていただけますでしょうか。

2023-12-22 11:52 UTC, KenichiroTanaka commented on doc/src/sgml/rules.sgml
> +ビューには他の種類の<literal>DO INSTEAD</literal>ルールもあり、基礎となるストレージがないにもかかわらず、ビューに対して<command>INSERT</command>、<command>UPDATE</command>、または<command>DELETE</command>コマンドを実行できるようにします。
細かいですが「基礎となるストレージ」のstoregeですが、443行目では「実際の記憶域はありません」と「記憶域」としていますので合わせて「基礎となる記憶域」とするのはどうでしょうか。

2023-12-23 13:18 UTC, koizumistr commented
確認ありがとうございます。対応しました。

2023-12-27 22:33 UTC, KenichiroTanaka approved these changes
対応ありがとうございます

2023-12-27 22:33 UTC, merged