update for 16.0 - new part 13
pgsql-jp/jpug-doc pull request #2794
Opened 2023-12-10 05:51 UTC by koizumistr

以下のファイルの 16.0 対応です。

-  ref/alter_database.sgml
-  ref/create_database.sgml
-  ref/createdb.sgml
-  ref/initdb.sgml

2023-12-29 09:56 UTC, tatsuo-ishii requested changes
一通り確認しました。

2023-12-29 09:56 UTC, tatsuo-ishii commented on doc/src/sgml/ref/alter_database.sgml
> +所有者を変更するには、新しい所有者ロールに対して<literal>SET ROLE</literal>ができなければなりません。また、そのロールは演算子クラスのスキーマにおいて<literal>CREATE</literal>権限を持たなければなりません。さらに、<literal>CREATEDB</literal>権限も持たなければなりません。
「そのロールは演算子クラスのスキーマにおいて...」は原文にないので不要かと。

2023-12-29 09:56 UTC, tatsuo-ishii commented on doc/src/sgml/ref/initdb.sgml
> +<command>initdb</command>は、データベースクラスタのデフォルトのロケールと文字セット符号化方式を初期化します。
"character set"は「文字セット」と訳しているんですね。てっきり「文字集合」だと思っていました。
（単なるコメントです）

2023-12-29 09:56 UTC, tatsuo-ishii commented on doc/src/sgml/ref/initdb.sgml
> +このオプションは複数のパラメータを設定するために1回以上指定できます。
"more than once"なので、「2回以上」ではないでしょうか。

2023-12-29 13:33 UTC, koizumistr commented on doc/src/sgml/ref/initdb.sgml
> +<command>initdb</command>は、データベースクラスタのデフォルトのロケールと文字セット符号化方式を初期化します。
となると、character setを「文字集合」と訳してしまっているところがあるのかと気になりました。
が、「文字集合」だと対応する英語は"character repertoire"（レパートリー、フランス語由来）のようです。いろいろ勉強になりました。
（もちろんこれもコメントです。）

2023-12-29 13:36 UTC, koizumistr commented
確認ありがとうございます。対応しました。

2023-12-29 14:19 UTC, tatsuo-ishii commented on doc/src/sgml/ref/initdb.sgml
> +<command>initdb</command>は、データベースクラスタのデフォルトのロケールと文字セット符号化方式を初期化します。
私の中では、"character set"の訳語は「文字集合」もしくは「文字セット」ですが (wikipediaでもそうなっています　、なるべくカタカナ英語を避けるという意味で「文字集合」が正解だと思っていました。しかし、このプロジェクトでは「文字セット」だとしているようなので、驚いた、という意味です。

> 「文字集合」だと対応する英語は"character repertoire"（レパートリー、フランス語由来）のようです。

(character) repertoireを「文字集合」と訳しているのは見たことがないのですが、出展を教えていただけますでしょうか？

2023-12-29 14:42 UTC, koizumistr commented on doc/src/sgml/ref/initdb.sgml
> +<command>initdb</command>は、データベースクラスタのデフォルトのロケールと文字セット符号化方式を初期化します。
information_schema.sgml では"character repertoire"を「文字集合」と訳しているようです。（さらに文字セットと訳し分けているっぽいです。）
「以下の用語のSQL標準での使われ方に注意してください。」の直後にあるので、SQL標準の訳がそうなっているのかな、と思ったのですが、それ以上の裏付けは取ってません。

2024-01-02 05:57 UTC, tatsuo-ishii commented on doc/src/sgml/ref/initdb.sgml
> +<command>initdb</command>は、データベースクラスタのデフォルトのロケールと文字セット符号化方式を初期化します。
SQL標準の公式日本語訳であるJIS規格では、"character set"、"repertorie”には、「文字集合」「レパートリー」の訳語を当てているようです。

https://kikakurui.com/x3/X3005-2-2015-01.html

JIS以外の資料としては、以下のようなものもあります。
ここでは、repertorieを、「レパートリー 」 or 「文字セット」と訳しているようです。

repertorieを「文字集合」、character setを「文字セット」と訳し分けるのは見かけないですね。

2024-01-03 01:16 UTC, KenichiroTanaka requested changes
いくつか気づくところがありましたので見ていただいてもいいでしょうか。

2024-01-13 12:15 UTC, koizumistr commented
確認ありがとうございます。対応しました。

2024-01-14 22:48 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。

2024-02-23 04:47 UTC, koizumistr commented on doc/src/sgml/ref/initdb.sgml
> +<command>initdb</command>は、データベースクラスタのデフォルトのロケールと文字セット符号化方式を初期化します。
ここの議論を #2830 にissueとしてあげました。これ以外の点は解決しているかと思いますので、change requestを進めてもらえますか。

2024-03-05 09:43 UTC, noborus commented
@tatsuo-ishii さんのChanges requestedが残ってますが、issue立ってますし、こちらはマージして良いと思います。

2024-03-05 11:00 UTC, KenichiroTanaka commented
そうですね。
```
ここの議論を https://github.com/pgsql-jp/jpug-doc/issues/2830 にissueとしてあげました。
```
と上がっていますのでこちらはマージします。

2024-03-05 11:00 UTC, merged