update nls for 16.0
pgsql-jp/jpug-doc pull request #2795
Opened 2023-12-14 11:32 UTC by koizumistr

nls.sgml の 16.0 対応です。

2024-01-03 01:24 UTC, KenichiroTanaka requested changes
１箇所だけ気づくところがありましたので見ていただいてもいいでしょうか。

2024-01-03 01:24 UTC, KenichiroTanaka commented on doc/src/sgml/nls.sgml
> +新規の言語が利用可能になったことを知らせるために、<filename>po/LINGUAS</filename>を編集し、言語（もしくは言語と国）コードを以下のように追加してください。
「code to the line that looks like」も「code next to languages already listed,like」に変わっているため、
「以下のように追加してください」の箇所は「既存の言語リストの後に以下のように」などの訳語とするのはどうでしょうか。

2024-01-13 12:08 UTC, koizumistr commented
確認ありがとうございます。対応しました。

2024-01-14 22:50 UTC, KenichiroTanaka approved these changes
対応ありがとうございました。

2024-01-14 22:50 UTC, merged