func.sgmlのPostgreSQL 16.0対応です。
pgsql-jp/jpug-doc pull request #2796
Opened 2023-12-15 06:56 UTC by tatsuo-ishii

2023-12-28 12:22 UTC, koizumistr reviewed
確認しました。

2023-12-28 12:22 UTC, koizumistr commented on doc/src/sgml/func1.sgml
> +エラー関数
誤差関数
というのだと思います。
https://ja.wikipedia.org/wiki/%E8%AA%A4%E5%B7%AE%E9%96%A2%E6%95%B0

2023-12-28 12:22 UTC, koizumistr commented on doc/src/sgml/func1.sgml
> +補完的なエラー関数（<literal>1-erf(x)</literal>、大きな入力における精度の損失なし）
上記のWikipediaによれば
相補誤差関数
というようです。

2023-12-28 12:22 UTC, koizumistr commented on doc/src/sgml/func3.sgml
> +他の一部のデータベースでは、このように動作します）。
）。 -> 。）

2023-12-28 13:40 UTC, koizumistr commented
（補足情報）
release-16.sgmlでも誤差関数、相補誤差関数としています。

2023-12-29 07:48 UTC, koizumistr commented
確認しました。対応ありがとうございます。

2024-01-03 03:03 UTC, KenichiroTanaka requested changes
いくつか気づくところがありましたので見ていただけないでしょうか。

2024-01-17 12:30 UTC, noborus commented on doc/src/sgml/func1.sgml
> +<parameter>bytesremoved</parameter>に現れるバイトのみを含む最長の文字列を<parameter>bytes</parameter>の最初と最後から取り除きます。
>  Removes the longest string containing only 〜

で始まるtrim系の説明が日本語訳だと統一されていないようなので、これを機に統一するのが良いと思います。

[元]から[対象文字]から取り除きます。
[対象文字]を[元]から取り除きます。

の順番と、

先頭/最初、末尾/最後、取り除きます/削除します、空白一文字がデフォルトです/デフォルトは空白文字
が統一されていた方が良いと思います。
どちらかに統一されていれば良いと思いますが、個人的には

「string/bytes」の先頭、末尾からcharactersに現れる文字のみを有する最長の文字列を取り除きます。

の書き方がわかりやすいと思いました。

2024-01-25 00:54 UTC, tatsuo-ishii commented on doc/src/sgml/func.sgml
> +(これは逆コンパイルされた再構成であり、コマンドのオリジナルテキストではありません。
修正します。

2024-01-25 00:54 UTC, tatsuo-ishii commented on doc/src/sgml/func.sgml
> +スナップショットにはトップレベルの尾トランザクションIDだけが含まれます。
おっと、修正します。

2024-01-25 00:56 UTC, tatsuo-ishii commented on doc/src/sgml/func.sgml
>  この関数は副トランザクションIDに対しては正しい答えを返さないことに注意してください。
修正します。"subxid"は翻訳の必要はないと思うので、そのままにしておきます。

2024-01-25 00:57 UTC, tatsuo-ishii commented on doc/src/sgml/func.sgml
>  リストには副トランザクションのトランザクションIDは含まれません。
了解です。

2024-01-25 13:15 UTC, KenichiroTanaka approved these changes
ご対応ありがとうございます。

2024-02-09 05:10 UTC, tatsuo-ishii commented on doc/src/sgml/func1.sgml
> +<parameter>bytesremoved</parameter>に現れるバイトのみを含む最長の文字列を<parameter>bytes</parameter>の最初と最後から取り除きます。
個人的には、「有する」より「現れる」の方がわかりやすいと思いました。また、「元」と「対象文字列」の順ですが、必ずしも統一しない方が良いケースがあるように思います。つまり、「元」が長い場合、それを文頭に持ってくると、頭の中でパースするのに負担がかかります。以上を踏まえ、修正前と修正後を示します。いかがでしょう？

```
---修正前---

btrim
<parameter>characters</parameter>（空白一文字がデフォルトです）に現れる文字のみを含む最長の文字列を<parameter>string</parameter>の最初と最後から取り除きます。
ltrim
<parameter>string</parameter>の最初から、<parameter>characters</parameter>（デフォルトは空白文字）で指定された文字だけを有する最長の文字列を削除します。
rtrim
<parameter>string</parameter>の末尾から、<parameter>characters</parameter>（デフォルトは空白文字）で指定された文字のみを有する最長の文字列を削除します。
trim
<parameter>characters</parameter>（空白一文字がデフォルトです）に現れる文字のみを含む最長の文字列を<parameter>string</parameter>の最初、最後、あるいは両方（<literal>BOTH</literal>がデフォルトです）から取り除きます。

---修正後---

btrim
<parameter>characters</parameter>（空白一文字がデフォルトです）に現れる文字のみを含む最長の文字列を<parameter>string</parameter>の最初と最後から取り除きます。
ltrim
<parameter>string</parameter>の最初から、<parameter>characters</parameter>（空白一文字がデフォルトです）で指定された文字のみを含む最長の文字列を取り除きます。
rtrim
<parameter>string</parameter>の末尾から、<parameter>characters</parameter>（空白一文字がデフォルトです）で指定された文字のみを含む最長の文字列を取り除きます。
trim
<parameter>characters</parameter>（空白一文字がデフォルトです）に現れる文字のみを含む最長の文字列を<parameter>string</parameter>の最初、最後、あるいは両方（<literal>BOTH</literal>がデフォルトです）から取り除きます。
```

2024-02-10 22:45 UTC, noborus commented on doc/src/sgml/func1.sgml
> +<parameter>bytesremoved</parameter>に現れるバイトのみを含む最長の文字列を<parameter>bytes</parameter>の最初と最後から取り除きます。
btrim,ltrim,rtrimは同じ順で良いと思いました。trimだけ書式が違うので変えても良いかなと思います。
考え直してみましたが、なるべく引数順が理解しやすいかと思いました。

最初 -> 先頭、最後 -> 末尾に統一。

（）の文からつながるように（空白一文字がデフォルトです）→（空白一文字がデフォルト）

## string

btrim(string, characters)
`<parameter>string</parameter>`から`<parameter>characters</parameter>`（空白一文字がデフォルト）に現れる文字のみを含む最長の文字列を先頭と末尾から取り除きます。
ltrim(string, characters)
`<parameter>string</parameter>`から`<parameter>characters</parameter>`（空白一文字がデフォルト）に現れる文字のみを含む最長の文字列を先頭から取り除きます。
rtrim(string, characters)
`<parameter>string</parameter>`から`<parameter>characters</parameter>`（空白一文字がデフォルト）に現れる文字のみを含む最長の文字列を末尾から取り除きます。

trim([ LEADING | TRAILING | BOTH ] characters from string)

`<parameter>string</parameter>`から`<parameter>characters</parameter>`（空白一文字がデフォルト）に現れる文字のみを含む最長の文字列を先頭、末尾、あるいはその両方（<literal>BOTH</literal>がデフォルト）から取り除きます。

or 

`<parameter>characters</parameter>`（空白一文字がデフォルト）に現れる文字のみを含む最長の文字列を`<parameter>string</parameter>`の先頭、末尾、あるいはその両方（<literal>BOTH</literal>がデフォルト）から取り除きます。

## bytes

btrim(bytes, bytesremoved)
`<parameter>bytes</parameter>`から`<parameter>bytesremoved</parameter>`に現れるバイトのみを含む最長の文字列を先頭と末尾から取り除きます。
ltrim(bytes, bytesremoved)
`<parameter>bytes</parameter>`から`<parameter>bytesremoved</parameter>`に現れるバイトのみを含む最長の文字列を先頭から取り除きます。
rtrim(bytes, bytesremoved)
`<parameter>bytes</parameter>`から`<parameter>bytesremoved</parameter>`に現れるバイトのみを含む最長の文字列を末尾から取り除きます。

trim([ LEADING | TRAILING | BOTH ] bytesremoved from bytes)

`<parameter>bytes</parameter>`から`<parameter>bytesremoved</parameter>`に現れるバイトのみを含む最長の文字列を先頭、末尾、あるいはその両方（<literal>BOTH</literal>がデフォルト）から取り除きます。

or 

`<parameter>bytesremoved</parameter>`に現れるバイトのみを含む最長の文字列を`<parameter>bytes</parameter>`の先頭、末尾、あるいはその両方（<literal>BOTH</literal>がデフォルト）から取り除きます。

どうでしょうか？

2024-02-13 08:26 UTC, noborus commented on doc/src/sgml/func3.sgml
> -《機械翻訳》SQL環境内のJSONデータタイプにネイティブサポートを提供するには、<productname>PostgreSQL</productname><firstterm>SQL/JSONデータモデル</firstterm>を実装します。
この上のindextermでマージのときに間違って「関数と演算子」が2回入ってしまっていました。
関数と式に修正お願いできますでしょうか。

```xml
  <indexterm zone="functions-json">
    <primary>SQL/JSON</primary>
    <secondary>functions and expressions</secondary>
   </indexterm>
  <indexterm zone="functions-json">
   <primary>SQL/JSON</primary>
   <secondary>関数と式</secondary>
  </indexterm>
```

2024-02-17 06:42 UTC, tatsuo-ishii commented on doc/src/sgml/func1.sgml
> +<parameter>bytesremoved</parameter>に現れるバイトのみを含む最長の文字列を<parameter>bytes</parameter>の最初と最後から取り除きます。
他の方いかがですか？あまり私はこだわり無いので、反対の方がいなければ斉藤さん案で修正します。

2024-02-17 07:21 UTC, koizumistr commented on doc/src/sgml/func1.sgml
> +<parameter>bytesremoved</parameter>に現れるバイトのみを含む最長の文字列を<parameter>bytes</parameter>の最初と最後から取り除きます。
特に反対はないです。

2024-02-18 08:05 UTC, tatsuo-ishii commented on doc/src/sgml/func1.sgml
> +<parameter>bytesremoved</parameter>に現れるバイトのみを含む最長の文字列を<parameter>bytes</parameter>の最初と最後から取り除きます。
では斉藤さん案で進めます。

2024-02-18 08:05 UTC, tatsuo-ishii commented on doc/src/sgml/func3.sgml
> -《機械翻訳》SQL環境内のJSONデータタイプにネイティブサポートを提供するには、<productname>PostgreSQL</productname><firstterm>SQL/JSONデータモデル</firstterm>を実装します。
了解です。

2024-02-18 12:17 UTC, noborus commented
確認しました。対応ありがとうございます。
他はレビュー済みなのでマージします。

2024-02-18 12:17 UTC, merged