update syntax for 16.0
pgsql-jp/jpug-doc pull request #2800
Opened 2023-12-16 06:22 UTC by koizumistr

syntax.sgml の 16.0 対応です。

2024-01-10 23:13 UTC, KenichiroTanaka requested changes
1箇所だけ気づくところがありましたので見ていただいてもいいでしょうか

2024-01-10 23:13 UTC, KenichiroTanaka commented on doc/src/sgml/syntax.sgml
> +数値定数または数値グループの先頭または末尾にアンダースコアを使用できません（つまり、小数点や指数記号の直前または直後にアンダースコアを使用できません）し、複数のアンダースコアを続けて使用することもできません。
細かいですが、「and more than one underscore in a row is not  allowed.」の「in a row」が訳出されていません。
「複数のアンダースコアを続けて使用することもできません。」は
「1行に複数のアンダースコアを続けて使用することもできません。」
とするのはどうでしょうか

2024-01-13 12:05 UTC, koizumistr commented on doc/src/sgml/syntax.sgml
> +数値定数または数値グループの先頭または末尾にアンダースコアを使用できません（つまり、小数点や指数記号の直前または直後にアンダースコアを使用できません）し、複数のアンダースコアを続けて使用することもできません。
このrowはデータベースとは関係なくて、"in a row"で「連続的に」という意味の熟語だと思います。なので「続けて」と訳しています。

2024-01-14 22:53 UTC, KenichiroTanaka commented on doc/src/sgml/syntax.sgml
> +数値定数または数値グループの先頭または末尾にアンダースコアを使用できません（つまり、小数点や指数記号の直前または直後にアンダースコアを使用できません）し、複数のアンダースコアを続けて使用することもできません。
!
確認ありがとうございます。
データベースの用語と理解していましたが確かに熟語ですね。１行で、というのも技術的に変でした。

2024-01-14 22:53 UTC, KenichiroTanaka approved these changes

2024-01-14 22:54 UTC, merged