docguide.sgmlの16.0対応です
pgsql-jp/jpug-doc pull request #2801
Opened 2023-12-16 11:05 UTC by noborus

2023-12-17 09:23 UTC, koizumistr reviewed
確認しました。


中間子で忍者か、、、、と意味不明な感想に浸れるツールみたいですね、Mesonは。

2023-12-17 09:23 UTC, koizumistr commented on doc/src/sgml/docguide.sgml
> +これらのコマンドのいずれかを実行して<filename>build</filename>ディレクトリ前に変更するか、コマンドに <option>-C build</option>を追加します。
これらのコマンドのいずれかを実行する前にbuildディレクトリに移動するか、

ということだと思います。元は"Change"ですが、「カレントディレクトリを変更」という意味かなと。

2023-12-17 22:53 UTC, noborus commented on doc/src/sgml/docguide.sgml
> +これらのコマンドのいずれかを実行して<filename>build</filename>ディレクトリ前に変更するか、コマンドに <option>-C build</option>を追加します。
ありがとうございます。修正します。

2023-12-18 01:11 UTC, koizumistr approved these changes
対応ありがとうございます。確認しました。

2023-12-29 04:45 UTC, tatsuo-ishii requested changes

2023-12-29 04:45 UTC, tatsuo-ishii commented on doc/src/sgml/docguide.sgml
> +出力はサブディレクトリ<filename>build/doc/src/sgml</filename>に表示されます。
build/doc/src/sgml以下にファイルが作成されるということだと思うので、"appears"は、「作成されます」と訳した方がわかりやすいのではないでしょうか。

2024-01-02 23:55 UTC, noborus commented on doc/src/sgml/docguide.sgml
> +出力はサブディレクトリ<filename>build/doc/src/sgml</filename>に表示されます。
ありがとうございます。修正します。

2024-01-03 00:27 UTC, tatsuo-ishii approved these changes
対応ありがとうございます。確認したのでマージします。

2024-01-03 00:27 UTC, merged