update for 16.0 - new part 15
pgsql-jp/jpug-doc pull request #2805
Opened 2023-12-29 02:02 UTC by koizumistr

以下のファイルの 16.0 対応です。

- ref/grant.sgml
- ref/revoke.sgml

2024-01-16 23:03 UTC, KenichiroTanaka requested changes
少し気づくところがありましたので見ていただけないでしょうか。

2024-01-17 12:29 UTC, koizumistr commented
確認ありがとうございます。

確かに「認可」は違和感がありました。grantの方の修正はとってもいい感じです。revokeの方は（「認可」よりはいいと思いますが）もう一声何か欲しい気もしますが、「付与」以上のものが思いつきませんでした、、、

2024-01-24 22:50 UTC, KenichiroTanaka approved these changes

2024-01-24 22:53 UTC, KenichiroTanaka commented
> 確認ありがとうございます。
> 
> 確かに「認可」は違和感がありました。grantの方の修正はとってもいい感じです。revokeの方は（「認可」よりはいいと思いますが）もう一声何か欲しい気もしますが、「付与」以上のものが思いつきませんでした、、、

そうですね・・。
私も思いついていません。

@tatsuo-ishii さん
@noborus さん
@kitayama さん
良い案ありましたらお知らせください

2024-02-24 03:45 UTC, KenichiroTanaka commented
他に良い案もありませんのでこの辺りでマージします。

2024-02-24 03:45 UTC, merged