glossary.sgmlの16.0対応です
pgsql-jp/jpug-doc pull request #2810
Opened 2024-01-23 23:25 UTC by noborus

2024-01-28 10:16 UTC, koizumistr reviewed
確認しました。

2024-01-28 10:16 UTC, koizumistr commented on doc/src/sgml/glossary.sgml
> +<glossterm linkend="glossary-autovacuum">自動バキュームランチャー</glossterm>（自動バキュームワーカーではありません）、<glossterm linkend="glossary-background-writer">バックグラウンドライタ</glossterm>、<glossterm linkend="glossary-checkpointer
「WALレシーバ」という表現は他のところで使っているようです。
が、「WALセンダ」というのは見当たらないので、「WAL送信」とすべきで、それに対応して「WAL受信」としたくなりますね、、、

2024-01-28 10:16 UTC, koizumistr commented on doc/src/sgml/glossary.sgml
> +このユーザは、各システムカタログテーブルのすべてのデータベースを所有しています。
各データベースでシステムカタログテーブルをすべて所有しています。
（機械翻訳め！）

2024-01-28 10:16 UTC, koizumistr commented on doc/src/sgml/glossary.sgml
> +これは、ページのダーティデータと恒久的なストレージへの可能性もある<glossterm linkend="glossary-wal">WAL</glossterm>のフラッシュが必要になる場合があります。
- 「ページのダーティデータ」のフラッシュが必要になることもある
- それに加えて、「フラッシュされていないWAL」のフラッシュが必要になることもある

フラッシュ先はどちらも永続的なストレージ
ということだと思うのですが、、、

2024-01-28 10:16 UTC, koizumistr commented on doc/src/sgml/glossary.sgml
> +<glossterm linkend="glossary-autovacuum">自動バキュームランチャー</glossterm>（自動バキュームワーカーではありません）、<glossterm linkend="glossary-background-writer">バックグラウンドライタ</glossterm>、<glossterm linkend="glossary-checkpointer
下まで見ると、glossary内で一貫しているんですね。なら、WALレシーバを修正した方がいい？

2024-01-29 06:02 UTC, noborus commented on doc/src/sgml/glossary.sgml
> +<glossterm linkend="glossary-autovacuum">自動バキュームランチャー</glossterm>（自動バキュームワーカーではありません）、<glossterm linkend="glossary-background-writer">バックグラウンドライタ</glossterm>、<glossterm linkend="glossary-checkpointer
WALセンダーがなくてWAL受信／WALレシーバが混在だったなのでWAL受信に統一するのが良いと思いました。

2024-01-29 06:03 UTC, noborus commented on doc/src/sgml/glossary.sgml
> +このユーザは、各システムカタログテーブルのすべてのデータベースを所有しています。
すみません。修正します。

2024-01-29 06:25 UTC, noborus commented on doc/src/sgml/glossary.sgml
> +これは、ページのダーティデータと恒久的なストレージへの可能性もある<glossterm linkend="glossary-wal">WAL</glossterm>のフラッシュが必要になる場合があります。
すみません。係りが複数で長いのでわからなくなってました。

> これは、ページのダーティデータとフラッシュされていない<glossterm postgresql=glossary-wal>WAL</glossterm>を永続的なストレージにフラッシュする必要がある場合もあります。

にします。

2024-02-01 13:32 UTC, KenichiroTanaka requested changes
いくつか気のなるところがありましたので見ていただいてもいいでしょうか。

2024-02-01 13:32 UTC, KenichiroTanaka commented on doc/src/sgml/glossary.sgml
> +このロールも標準<glossterm linkend="glossary-database-superuser">データベーススーパーユーザ</glossterm>として動作します。
細かなニュアンスかもですが、「標準データベースユーザ」というものが規定されているのかと（SQL標準のように）読んでしまいました。原文はstandardではなくnormalなので、「通常のデータベースユーザ」や「標準的なデータベースユーザ」などの訳でどうでしょうか。

2024-02-01 13:32 UTC, KenichiroTanaka commented on doc/src/sgml/glossary.sgml
> +バッファアクセスストラテジは、ラージテーブルのシーケンシャルスキャン、<command>VACUUM</command>、<command>COPY</command>、<command>CREATE TABLE AS SELECT</command>、<command>ALTER TABLE</command>、<command>CREATE DATABASE</command>、<comma
「ラージテーブルのシーケンシャルスキャン」ですがラージテーブルという用語（ラージオブジェクトのような）ではありませんので「大きなテーブルのシーケンシャルスキャン」くらいの訳でどうでしょうか。

2024-02-01 13:32 UTC, KenichiroTanaka commented on doc/src/sgml/glossary.sgml
>  ディスク上ではxidは32ビット幅しかないので、約4億の書き込みトランザクションIDしか生成できません。
以前からのところですが「約4億」→「40億」です。

2024-02-04 01:14 UTC, noborus commented on doc/src/sgml/glossary.sgml
> +このロールも標準<glossterm linkend="glossary-database-superuser">データベーススーパーユーザ</glossterm>として動作します。
たしかに。修正します。

2024-02-04 01:14 UTC, noborus commented on doc/src/sgml/glossary.sgml
> +バッファアクセスストラテジは、ラージテーブルのシーケンシャルスキャン、<command>VACUUM</command>、<command>COPY</command>、<command>CREATE TABLE AS SELECT</command>、<command>ALTER TABLE</command>、<command>CREATE DATABASE</command>、<comma
修正します。

2024-02-04 01:14 UTC, noborus commented on doc/src/sgml/glossary.sgml
>  ディスク上ではxidは32ビット幅しかないので、約4億の書き込みトランザクションIDしか生成できません。
なんと。修正します。

2024-02-07 22:48 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。

2024-02-07 22:48 UTC, merged