update psql-ref for 16.0
pgsql-jp/jpug-doc pull request #2854
Opened 2024-03-21 15:14 UTC by koizumistr

ref/psql-ref.sgml の 16.0 対応です。

2024-03-25 01:03 UTC, noborus commented on doc/src/sgml/ref/psql-ref.sgml
> +<literal>\df+</literal>構文が使われた場合、各関数の、揮発性、並列処理での安全性、所有者、セキュリティ分類、アクセス権限、言語、内部名（Cと内部関数に対してのみ）や説明を含む付加的情報も表示されます。
最後の行の`\sf`が抜けてます。

> 特定の関数のソースコードは、<literal>\sf</literal>を使用して表示できます。`

2024-03-26 10:37 UTC, koizumistr commented
確認ありがとうございます。対応しました。

2024-03-27 23:44 UTC, noborus approved these changes
修正ありがとうございます。確認しました。

2024-04-10 23:19 UTC, KenichiroTanaka requested changes
細かいですが1箇所だけ気づくところがありましたので見ていただいてもいいでしょうか。

2024-04-10 23:19 UTC, KenichiroTanaka commented on doc/src/sgml/ref/psql-ref.sgml
> +割り当てられたオプション(<literal>ADMIN</literal>、<literal>INHERIT</literal>、<literal>SET</literal>)および認可者を含む、付与されたロールのメンバ資格に関する情報を一覧表示します。
「認可者」は他でも使っていないので、ここでは「権限付与者」などの表現でどうでしょうか。

2024-04-12 09:28 UTC, koizumistr commented
確認ありがとうございます。対応しました。

2024-04-14 22:46 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。

2024-04-14 22:47 UTC, KenichiroTanaka commented
一通り確認しましたのでマージします。

2024-04-14 22:47 UTC, merged