xact.sgmlのPostgreSQL 16.0対応です。
pgsql-jp/jpug-doc pull request #2860
Opened 2024-03-23 09:21 UTC by tatsuo-ishii

このファイルは新規です。

2024-04-01 22:55 UTC, noborus commented on doc/src/sgml/xact.sgml
> +この章では、<productname>PostgreSQL</productname>のトランザクション管理システムの内部構造について概説します。
#2851 でもコメント書きましたが、他のファイルではtransaction managementをトランザクション制御にしているところがあるので、統一したほうが良いのでコメントを残しておきます。

2024-04-01 22:55 UTC, noborus commented on doc/src/sgml/xact.sgml
> +読み出し専用のトランザクションは<structfield>virtualxid</structfield>はありますが、<structfield>transactionid</structfield>は NULLです。
> は NULLです。

一つ余分なスペースがあります。

2024-04-01 22:55 UTC, noborus commented on doc/src/sgml/xact.sgml
> +トップレベルのトランザクションとその子トランザクションは階層またはツリーを形成するため、主トランザクションをトップレベルのトランザクションと呼びます。
ここだけしか出てこなくて、間違いとは言えないですが、サブトランザクションの対語としてメイントランザクションの方がよくないでしょうか。

2024-04-02 00:33 UTC, tatsuo-ishii reviewed
レビューありがとうございます。

2024-04-02 00:33 UTC, tatsuo-ishii commented on doc/src/sgml/xact.sgml
> +読み出し専用のトランザクションは<structfield>virtualxid</structfield>はありますが、<structfield>transactionid</structfield>は NULLです。
失礼、修正します。

2024-04-02 00:33 UTC, tatsuo-ishii commented on doc/src/sgml/xact.sgml
> +トップレベルのトランザクションとその子トランザクションは階層またはツリーを形成するため、主トランザクションをトップレベルのトランザクションと呼びます。
他にlogicaldecoding.sgmlでも"main transaction"を「メイントランザクション」と訳しているので、こちらも合わせます。

2024-04-02 00:33 UTC, tatsuo-ishii commented on doc/src/sgml/xact.sgml
> +この章では、<productname>PostgreSQL</productname>のトランザクション管理システムの内部構造について概説します。
トランザクション制御、にします。

2024-04-03 00:29 UTC, tatsuo-ishii commented
斉藤さん、commit 
https://github.com/pgsql-jp/jpug-doc/pull/2860/commits/d2716e047f608c166886f396658401f6078ff297
以降で何か新しい指摘事項がありますか？

2024-04-03 00:35 UTC, noborus reviewed
すみません。コメントPendingになってました。

2024-04-03 04:29 UTC, tatsuo-ishii commented on doc/src/sgml/xact.sgml
> +トランザクションがオープンしたサブトランザクション数が多いほど（ロールバックや解放されない)、トランザクション制御のオーバーヘッドが大きくなります。
了解です。修正しました。

2024-04-03 10:56 UTC, noborus approved these changes
ありがとうございます。確認しました。

2024-04-05 14:05 UTC, koizumistr reviewed
確認しました。

2024-04-05 14:05 UTC, koizumistr commented on doc/src/sgml/xact.sgml
> +チェックポイントをまたいで準備されたトランザクションは<filename>pg_twophase</filename>ディレクトリに記録されます。
原文には「準備された」に対応するものがないです。

2024-04-12 09:21 UTC, koizumistr approved these changes
対応ありがとうございます。確認しました。

2024-04-16 03:24 UTC, KenichiroTanaka requested changes
細かいですが１箇所だけ気づくところがありましたので見ていただいてもいいでしょうか

2024-04-16 04:48 UTC, tatsuo-ishii commented on doc/src/sgml/xact.sgml
> +親xidは常に子xidのいずれよりも小さいことが保証されます。
ありがとうございます。修正します。

2024-04-17 23:09 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。

2024-04-17 23:09 UTC, merged