update backup for 16.0
pgsql-jp/jpug-doc pull request #2863
Opened 2024-03-26 11:11 UTC by koizumistr

backup.sgml の 16.0 対応です。

2024-04-02 23:50 UTC, noborus approved these changes
確認しました。

2024-04-09 23:42 UTC, tatsuo-ishii requested changes
一通り確認しました。

2024-04-09 23:42 UTC, tatsuo-ishii commented on doc/src/sgml/backup.sgml
> +まれに、<productname>PostgreSQL</productname>は以前にアーカイブされたWALアーカイブを再ファイルしようとすることがあります。
> WALアーカイブを再ファイルしようとすることがあります

「WALファイルを再アーカイブしようとすることがあります」ではないでしょうか。

2024-04-09 23:42 UTC, tatsuo-ishii commented on doc/src/sgml/backup.sgml
> +アーカイブ復旧が完了したときはいつでも、その復旧後に生成されたWAL記録を識別するための新しいタイムラインが生成されます。
"WAL record"は、他の箇所では「WAL記録」ではなく、「WALレコード」と訳しているようです。

2024-04-10 08:38 UTC, koizumistr commented
確認ありがとうございます。対応しました。

2024-04-10 09:20 UTC, tatsuo-ishii approved these changes
確認しました。対応ありがとうございます。

2024-04-10 09:20 UTC, merged