update plpgsql for 16.0
pgsql-jp/jpug-doc pull request #2867
Opened 2024-04-02 12:14 UTC by koizumistr

plpgsql.sgml の 16,0 対応です。

2024-04-03 23:03 UTC, noborus commented on doc/src/sgml/plpgsql.sgml
> +<productname>PostgreSQL</productname> 16以前は、バウンドカーソル変数は、デフォルトでカーソル変数の名前と同じになるように、NULLではなく自身の名前を含むように初期化されていました。
`so that the underlying portal name would`の部分が抜けています。

2024-04-04 03:04 UTC, koizumistr commented
確認ありがとうございます。
「デフォルトでカーソル変数の名前と同じになるように」が対応する部分のつもりでしたが、そうだとしてもunderlyingに対応するものがないですね、、、と言うことで訳し方を変えてみました。

2024-04-04 23:54 UTC, noborus commented
> 確認ありがとうございます。 「デフォルトでカーソル変数の名前と同じになるように」が対応する部分のつもりでしたが、そうだとしてもunderlyingに対応するものがないですね、、、と言うことで訳し方を変えてみました。

the underlying portal の訳が統一されていたほうがよくないでしょうか？

2024-04-05 13:26 UTC, koizumistr commented
underlying がこの文書内で使われているという発想がありませんでした。
揃っていた方が良いと思いますので合わせました。
（既存の文章が逆
> ポータルの背後にあるカーソル

になっていましたのでそちらも直しています）

2024-04-08 08:24 UTC, noborus commented
修正ありがとうございます。
確認しました。

2024-04-14 01:01 UTC, tatsuo-ishii requested changes
一通り確認しました。

2024-04-14 08:51 UTC, koizumistr commented on doc/src/sgml/plpgsql.sgml
> +カーソルを使用して行を取り出す前に、<firstterm>開かれる</firstterm>必要があります。
>「開かれる」の主語がない

のはご指摘通りですが

>「カーソルを」→「カーソルは」

とすると今度は文の前半とのつながりが分かりにくくなりそうだったので、「カーソル」がしつこいですが「カーソルは」を「開かれる」の開かれるの前に追加してみました。

2024-04-14 08:58 UTC, koizumistr commented on doc/src/sgml/plpgsql.sgml
> +バウンドカーソル変数は<xref linkend="plpgsql-cursor-for-loop"/>で説明されている<command>FOR</command>文で、明示的にカーソルを開かなくても使用することができます。
バウンド/アンバウンド（カーソル） について検索してみたところ、そういう言葉を使っているのはどうやらこのマニュアルだけのようでした。（一見そうではないっぽいサイトもありましたが、実はこの文書を引用してました。）
なので、
バウンド/アンバウンド -> バインドされた/バインドされていない
と全体的に変えてみました。
（それに「Lispのバインド」とかあるので、コンピューター用語としてバウンドよりバインドにより馴染みがあるのではないかと、、、）

2024-04-16 02:47 UTC, tatsuo-ishii commented on doc/src/sgml/plpgsql.sgml
> +カーソルを使用して行を取り出す前に、<firstterm>開かれる</firstterm>必要があります。
それでも良いと思います。

2024-04-16 02:48 UTC, tatsuo-ishii commented on doc/src/sgml/plpgsql.sgml
> +バウンドカーソル変数は<xref linkend="plpgsql-cursor-for-loop"/>で説明されている<command>FOR</command>文で、明示的にカーソルを開かなくても使用することができます。
了解です。

2024-04-16 02:50 UTC, tatsuo-ishii approved these changes
対応ありがとうございます。確認しました。

2024-04-16 02:51 UTC, tatsuo-ishii commented
二人でレビューしているので、マージします。

2024-04-16 02:52 UTC, merged