installation.sgmlの16.0対応です
pgsql-jp/jpug-doc pull request #2868
Opened 2024-04-04 23:29 UTC by noborus

2024-04-08 23:07 UTC, koizumistr reviewed
3500行くらいまで見ました。

2024-04-08 23:07 UTC, koizumistr commented on doc/src/sgml/installation.sgml
> +この多くがデフォルトでないのは、<xref linkend="install-requirements"/>で書かれているように追加のソフトウェアを必要であり、必要なソフトウェアが見つかった場合は自動的に有効になります。
追加のソフトウェアを必要であり
-> 追加のソフトウェアが必要であり

2024-04-08 23:07 UTC, koizumistr commented on doc/src/sgml/installation.sgml
> +この多くがデフォルトでないのは、<xref linkend="install-requirements"/>で書かれているように追加のソフトウェアを必要であり、必要なソフトウェアが見つかった場合は自動的に有効になります。
この多くがデフォルトでないのは、-> この（オプションの）ほとんどは、

「この多くがデフォルトでないのは、」のデフォルトは不要かと。
「この多くがデフォルトでないのは、」で始まると「〜だからだ」とデフォルトでない理由の説明を期待してしまうかと。

2024-04-08 23:07 UTC, koizumistr commented on doc/src/sgml/installation.sgml
> +デフォルトは自動で、<productname>ICU4C</productname>パッケージをインストールされていることが必要です。
パッケージをインストールされていること
-> パッケージがインストールされていること

2024-04-09 12:01 UTC, noborus commented on doc/src/sgml/installation.sgml
> +一般的に使用されるオプションは、以下のセクションで説明します。
節ですね。修正します。

2024-04-09 12:02 UTC, noborus commented on doc/src/sgml/installation.sgml
> +多くの場合、それらの1つは開発（「デバッグ」ビルド）に使用され、他のものは時々（「静的分析」ビルドなど）だけ使用されます。
「だけ」が単純に要らないですかね

2024-04-09 12:09 UTC, noborus commented on doc/src/sgml/installation.sgml
> +この多くがデフォルトでないのは、<xref linkend="install-requirements"/>で書かれているように追加のソフトウェアを必要であり、必要なソフトウェアが見つかった場合は自動的に有効になります。
修正します

2024-04-14 14:41 UTC, koizumistr commented on doc/src/sgml/installation.sgml
> +ICUサポートを使用するには、<productname>ICU4C</productname>パッケージをインストールされていることが必要です。
それでも構わないです。（個人的には「が」の連続はそこまで気にしませんが）少なくとも
> パッケージをインストールされていること

だと（皇室級に）偉い人がインストールしないといけなくなりますので:)

2024-04-14 14:42 UTC, koizumistr commented on doc/src/sgml/installation.sgml
> +多くの場合、それらの1つは開発（「デバッグ」ビルド）に使用され、他のものは時々（「静的分析」ビルドなど）だけ使用されます。
原文には忠実ではなくなりますが、日本語としてはそちらの方が好ましいような、、、

2024-04-14 14:44 UTC, koizumistr commented on doc/src/sgml/installation.sgml
> +<ulink url="https://mesonbuild.com/Commands.html#install">Mesonのドキュメント</ulink>でMesonインストールとそのオプションについて学んでください。
揃っていればどちらでも構わないです。

ここ、「本家では何と言っているのかな」と気になったのですが、確かそもそも日本語訳がなかったような、、、

2024-04-29 08:37 UTC, KenichiroTanaka requested changes
いくつか気づくところがありましたので見ていただいてもいいでしょうか。

2024-04-30 22:12 UTC, noborus commented on doc/src/sgml/installation.sgml
> +<phrase condition="standalone-ignore">詳細は<xref linkend="server-start"/>を参照してください。</phrase>
修正します

2024-04-30 22:13 UTC, noborus commented on doc/src/sgml/installation.sgml
> +これは、必要なソフトウェアが見つかった場合に、それぞれを手動で設定することなく、すべての<quote>optional</quote>機能を一度に無効または有効にする場合に便利です。
ありがとうございます。いただきます。

2024-04-30 22:14 UTC, noborus commented on doc/src/sgml/installation.sgml
> +<replaceable>DIRECTORIES</replaceable>には、コンパイラがヘッダファイルを検索するディレクトリのリストをコロンで区切って指定します。
colon-separated なのでコロンでいいと思います

2024-04-30 22:14 UTC, noborus commented on doc/src/sgml/installation.sgml
> +<replaceable>DIRECTORIES</replaceable>には、ライブラリを検索するディレクトリのリストをコロンで区切って指定します。
こちらも`--with-libraries=/opt/gnu/lib:/usr/sup/lib`なのでコロンで良いと思います

2024-04-30 22:15 UTC, noborus commented on doc/src/sgml/installation.sgml
> +<productname>PostgreSQL</productname>の実行ファイルがインストレーションのライブラリディレクトリ(<option>--libdir</option>を参照してください)にある共有ライブラリを探すよう指示する印を付けません。
修正します

2024-05-01 13:26 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。

2024-05-01 13:35 UTC, KenichiroTanaka requested changes

2024-05-01 13:35 UTC, KenichiroTanaka commented on doc/src/sgml/installation.sgml
> +<replaceable>DIRECTORIES</replaceable>には、コンパイラがヘッダファイルを検索するディレクトリのリストをコロンで区切って指定します。
私の目にはcomma-separatedに見えます。

```
$git diff REL_15_4 REL_16_0 installation.sgml |grep comma-
+        <replaceable>DIRECTORIES</replaceable> is a comma-separated list of
+        <replaceable>DIRECTORIES</replaceable> is a comma-separated list of
$git diff REL_15_4 REL_16_0 installation.sgml |grep colon
$
```
これは・・どこから違いが来るのでしょう。。

2024-05-05 12:49 UTC, merged