update libpq for 16.0
pgsql-jp/jpug-doc pull request #2870
Opened 2024-04-06 12:29 UTC by koizumistr

libpq.sgml の 16.0 対応です。

2024-04-08 20:49 UTC, noborus reviewed
それから、前からでしたが、libpq.sgmlの9065行付近

```
       Ends the <literal>COPY_IN</literal> operation successfully if
       <parameter>errormsg</parameter> is <symbol>NULL</symbol>.  If
       <parameter>errormsg</parameter> is not <symbol>NULL</symbol> then the
       <command>COPY</command> is forced to fail, with the string pointed to by
       <parameter>errormsg</parameter> used as the error message.  (One should not
       assume that this exact error message will come back from the server,
       however, as the server might have already failed the
       <command>COPY</command> for its own reasons.)
<parameter>errormsg</parameter>が<symbol>NULL</symbol>なら、<literal>COPY_IN</literal>を成功として終了させます。
<parameter>errormsg</parameter>が<symbol>NULL</symbol>ではないなら、errmsgの指し示す文字列をエラーメッセージとして用いて<command>COPY</command>を強制的に失敗させます。
（しかし、このエラーメッセージがサーバからそのまま返ってくると仮定すべきではありません。サーバは既に別の原因で<command>COPY</command>に失敗していた可能性があります。）
```

errmsgの指し示す文字列
↓
`<parameter>errormsg</parameter>の指し示す文字列`

2024-04-08 22:38 UTC, koizumistr commented
確認ありがとうございます。対応しました。

2024-04-14 22:06 UTC, noborus reviewed
修正後に./split-libpq.shの実行がされてないようです。

2024-04-15 00:46 UTC, koizumistr commented
失礼しました。splitしました。

2024-04-30 05:38 UTC, KenichiroTanaka requested changes
一通り確認しました。
いくつか気づいたところがありますので見ていただいてもいいでしょうか。

2024-05-02 02:04 UTC, koizumistr commented on doc/src/sgml/libpq0.sgml
> +サーバは<acronym>GSSAPI</acronym>を介してKerberosハンドシェイクを要求するか、<acronym>GSS</acronym>で暗号化されたチャネルを確立しなければなりません（<xref linkend="libpq-connect-gssencmode" />も参照してください）。
「チャネルバインディング」というのが一般的なようなのでチャネルに揃えました。「チャネルバインディング」に揃えるためprotocol.sgmlにも手を出しています。

2024-05-02 02:08 UTC, koizumistr commented on doc/src/sgml/libpq0.sgml
> +サーバはクライアントに認証交換を要求してはなりません。
認証交換方式についてずらずら並べてきて、最後のnoneに対する説明ですから、ここはおそらく画面だけの話をしているのではないと思います。「要求する」がpromptに対応するつもりでした。

2024-05-02 02:08 UTC, koizumistr commented
確認ありがとうございます。基本的には対応しましたが、対応の仕方が微妙な２点については個別に回答しています。

2024-05-03 01:12 UTC, noborus commented
修正ありがとうございます。確認しました。

2024-05-03 01:17 UTC, noborus approved these changes

2024-05-05 12:51 UTC, KenichiroTanaka commented on doc/src/sgml/libpq0.sgml
> +サーバはクライアントに認証交換を要求してはなりません。
確かにそうですね。承知しました。

2024-05-06 22:58 UTC, KenichiroTanaka commented
対応ありがとうございます。
マージします。

2024-05-06 22:58 UTC, merged