update logical-replication for 16.0
pgsql-jp/jpug-doc pull request #2871
Opened 2024-04-11 11:57 UTC by koizumistr

logical-replication.sgml の 16.0 対応です。

2024-04-14 05:24 UTC, tatsuo-ishii requested changes
一通り確認しました。

2024-04-14 05:24 UTC, tatsuo-ishii commented on doc/src/sgml/logical-replication.sgml
> +なお、一部の拡張機能やパラレルクエリも<varname>max_worker_processes</varname>からワーカースロットを取得します。
"Note"を訳出したほうが良いと思います。

2024-04-25 00:51 UTC, noborus commented on doc/src/sgml/logical-replication.sgml
> +初期データ同期では、既存のテーブルデータをコピーする際に<link linkend="sql-createpublication-with-publish"><literal>publish</literal></link>パラメータが考慮されないため、DMLを使用してレプリケーションされない行がコピーされる場合があります。
`<literal>publish</literal>`は`<literal>パブリッシュ</literal>`にしないと他と整合が取れないと思います。

2024-04-25 00:51 UTC, noborus commented on doc/src/sgml/logical-replication.sgml
> +パブリケーションにパーティション化テーブルが含まれている場合、パブリケーションパラメータ<link linkend="sql-createpublication-with-publish-via-partition-root"><literal>publish_via_partition_root</literal></link>によって使用される行フィルタが決定されます。
この上の 1048行ぐらいで`replica identity`がレプリカIDとなっていて他のレプリカアイデンティティと統一されていません。

> `パブリケーションが<command>UPDATE</command>または<command>DELETE</command>操作をパブリッシュする場合、行フィルタ<literal>WHERE</literal>句には、レプリカIDの対象となる列のみを含める必要があります(<xref linkend="sql-altertable-replica-identity"/>を参照)。`

その他identityがIDや識別子になっているところがあって統一されていないですが...

2024-05-02 02:20 UTC, koizumistr commented
確認ありがとうございます。対応しました。
（流石に「その他identityがIDや識別子になっているところがあって統一されていないですが...」には対応していませんが、、、）

2024-05-03 01:16 UTC, noborus commented
修正ありがとうございます。確認しました。

2024-05-03 01:16 UTC, noborus approved these changes

2024-05-08 23:21 UTC, KenichiroTanaka requested changes
いくつか気づくところがありましたので見ていただいてもいいでしょうか。

2024-05-08 23:21 UTC, KenichiroTanaka commented on doc/src/sgml/logical-replication.sgml
> +<link linkend="guc-max-replication-slots"><varname>max_replication_slots</varname></link>は、接続する予定のサブスクリプション数と、テーブル同期用の予備の数を加えた数以上に設定することが必要です。
reserveを機械翻訳は「予備」としていますが、予備だと「必要になった時に使う→必要ないときは不要」のニュアンスがあり、正しくないように思います。他と同様、予約の方がよいと思います。

「テーブル同期用の予備の数を加えた数以上に設定することが必要です。」
は
「テーブル同期のために予約された数を加えた数以上に設定することが必要です。」
などとするのはどうでしょうか。

2024-05-08 23:21 UTC, KenichiroTanaka commented on doc/src/sgml/logical-replication.sgml
> +<link linkend="guc-max-replication-slots-subscriber"><varname>max_replication_slots</varname></link>は、少なくともサブスクライバーに追加される予約の数に、テーブル同期用の予約を加えた数以上に設定することが必要です。
「少なくともサブスクライバーに追加される予約の数に」の箇所は機械翻訳が正しく訳せていないと思います。
subscriberとsubscriptionの扱いが難しそうです。

<link linkend="guc-max-replication-slots-subscriber"><varname>max_replication_slots</varname></link>は、少なくともサブスクライバーに追加されるサブスクリプションの数に、テーブル同期用の予約を加えた数以上に設定することが必要です。

などとするのはどうでしょうか。

2024-05-08 23:21 UTC, KenichiroTanaka commented on doc/src/sgml/logical-replication.sgml
> +<link linkend="guc-max-logical-replication-workers"><varname>max_logical_replication_workers</varname></link>は、少なくともサブスクリプション数（リーダー適用ワーカー用）に加えて、テーブル同期ワーカーとパラレル適用ワーカー用の予備を加えた数以上に設定することが必要です。
こちらも「予備」→「予約」が良いと思います

2024-05-09 07:40 UTC, koizumistr commented
確認ありがとうございます。対応しました。

> 以前からのところですが、パブリッシュはパラメーターなのでpublishが良いと思います。

基本的にliteralの中のpublishは「パブリッシュ」になっていたのでそちらに揃えるのがいいのかと思っていたのですが、よく読むと確かに

- パブリッシュ操作
- publishパラメータ

がそれぞれありますね。上記のような形にします。

2024-05-09 10:20 UTC, KenichiroTanaka approved these changes
publishの箇所はいただいているとおりかと思います。
対応ありがとうございます。

2024-05-13 13:28 UTC, KenichiroTanaka commented
@tatsuo-ishii さん
レビューありがとうございました。
問題なければapprobeをお願いしてもいいでしょうか？

2024-05-14 00:53 UTC, merged

2024-05-14 23:30 UTC, tatsuo-ishii reviewed
遅くなりましたが、確認しました。