charset.sgmlの16.0対応です
pgsql-jp/jpug-doc pull request #2872
Opened 2024-04-13 00:08 UTC by noborus

16.0対応に加えて
並び換えを並べ替えに修正しました。
記号 `<literal>&lt;</literal>`の前後はスペースを入れるように変更しました。
`Unicode Technical Standard #51` はそのままの方が使われてるので修正

2024-04-13 10:56 UTC, tatsuo-ishii requested changes
一通り確認しました。

2024-04-13 10:56 UTC, tatsuo-ishii commented on doc/src/sgml/charset.sgml
> + <title>多言語対応</title>
"localization"が「多言語対応」と訳されていますが、これは違うと思います。「多言語対応」の英訳は"multilingualization"ですよね。「地域化」が適当ではないでしょうか。あるいは「ローカライゼーション」でも良いと思います。
ちなみに、他のファイルでもlocalization(あるいはlocalize)の訳は統一されていないので、この機会に統一したほうが良いでしょう。(別pull requestで)

2024-04-13 10:56 UTC, tatsuo-ishii commented on doc/src/sgml/charset.sgml
> +照合順序設定は、言語タグに含めて照合順序の動作をカスタマイズすることができます。
「照合順序設定は」→「照合順序設定を」

2024-04-13 10:56 UTC, tatsuo-ishii commented on doc/src/sgml/charset.sgml
> +ICUでは、アクセント、ケース、および句読点に対する感度（または非感度）、テキスト内の数字の処理、およびさまざまな用途を満たすその他の多くのオプションなど、広範なカスタマイズが可能です。
「ケース」は「大文字小文字の区別」だと思います。

2024-04-13 10:56 UTC, tatsuo-ishii commented on doc/src/sgml/charset.sgml
>  これらの設定は、照合順序がケースに依存せず、数字のシーケンスを単一の数字として扱うことを意味します:
「ケースに依存せず」→「大文字小文字を区別せず」
「数字のシーケンス」→「一続きの数字」

2024-04-13 10:56 UTC, tatsuo-ishii commented on doc/src/sgml/charset.sgml
> +<xref linkend="icu-collation-levels"/>は、特定の機能での等価性を決定する際に、どのテキストレベルの差異が重要であると考えられるかを示します。
「特定の機能「→「特定のレベル」
「テキストレベル」→「テキストの特徴」

2024-04-13 10:56 UTC, tatsuo-ishii commented on doc/src/sgml/charset.sgml
>  Unicode文字<literal>U+2063</literal>は非表示のセパレータであり、表に示すように、比較より小さいのすべてのレベルで無視されます<literal>identic</literal>。
比較より小さいのすべてのレベルで無視されます<literal>identic</literal>。
→
<literal>identic</literal>より小さいすべてのレベルでの比較で無視されます。

2024-04-13 10:56 UTC, tatsuo-ishii commented on doc/src/sgml/charset.sgml
>  コードポイント表現形式内の差を個別として扱うには、<symbol>deterministic</symbol>を<literal>真</literal>に設定して作成された照合順序を使用します。
「<literal>真</literal>」→「<literal>true</literal>」

2024-04-13 10:56 UTC, tatsuo-ishii commented on doc/src/sgml/charset.sgml
>  基本正規化は、<literal>偽</literal>に設定されている場合でも実行されます。
偽→false

2024-04-13 10:56 UTC, tatsuo-ishii commented on doc/src/sgml/charset.sgml
> +正規化マルチプルが1つの文字に適用される場合など、場合によっては完全なアクセントが重要になります。
「複数のアクセントが1つの文字に適用される場合など、場合によっては完全な正規化が重要になります。」ですね。

2024-04-13 10:56 UTC, tatsuo-ishii commented on doc/src/sgml/charset.sgml
>  例の場合、コードポイントシーケンス<literal>U&amp;'\0065\0323\0302'</literal>および<literal>U&amp;'\0065\0302\0323'</literal>は、異なる順序で適用されるアクセントの下の回転およびドットを持つ<literal>e</literal>を表します。
「アクセントの下の回転およびドット」→「曲折アクセントおよび下ドットアクセント」
ですかね。「下ドット」は自信ありません。

2024-04-13 10:56 UTC, tatsuo-ishii commented on doc/src/sgml/charset.sgml
> +多くの照合順序設定では、目的の効果を得るために、<option>deterministic</option>を<literal>false</literal>に設定された<literal>照合順序</literal>を作成する必要があります（<xref linkend="collation-nondeterministic"/>を参照）。
「設定された」→「設定した」

2024-04-14 21:55 UTC, noborus reviewed
レビューありがとうございました。
最初のpull requestで2回コミットしていた関係で、修正していた箇所もあります。

2024-04-14 21:55 UTC, noborus commented on doc/src/sgml/charset.sgml
> + <title>多言語対応</title>
了解です。
「ローカライゼーション」を使っても大丈夫なような気がしてきました。

2024-04-14 21:55 UTC, noborus commented on doc/src/sgml/charset.sgml
> +照合順序設定は、言語タグに含めて照合順序の動作をカスタマイズすることができます。
修正します。

2024-04-14 21:55 UTC, noborus commented on doc/src/sgml/charset.sgml
> +ICUでは、アクセント、ケース、および句読点に対する感度（または非感度）、テキスト内の数字の処理、およびさまざまな用途を満たすその他の多くのオプションなど、広範なカスタマイズが可能です。
漏れてました。修正します。

2024-04-14 21:55 UTC, noborus commented on doc/src/sgml/charset.sgml
>  これらの設定は、照合順序がケースに依存せず、数字のシーケンスを単一の数字として扱うことを意味します:
修正します

2024-04-14 21:55 UTC, noborus commented on doc/src/sgml/charset.sgml
> +多くの照合順序設定では、目的の効果を得るために、<option>deterministic</option>を<literal>false</literal>に設定された<literal>照合順序</literal>を作成する必要があります（<xref linkend="collation-nondeterministic"/>を参照）。
修正します

2024-04-14 21:59 UTC, noborus commented
Localization はまだ修正していません。
訳語が決まった後に一括で修正します。

2024-04-15 02:59 UTC, tatsuo-ishii approved these changes
確認しました。
"Localization"の訳は別のpull requestで修正するということで了解しました。

2024-04-16 10:29 UTC, koizumistr commented on doc/src/sgml/charset.sgml
> +例えば、コードポイントシーケンス<literal>U&amp;'\0065\0323\0302'</literal>と<literal>U&amp;'\0065\0302\0323'</literal>は、異なる順序で適用されたサーカムフレックスとドット下のアクセントを持つ<literal>e</literal>を表します。
https://0g0.org/unicode/0323/ のことなのは間違いないですが、記号としての名前は見つかりません。ベトナムの知り合いがいれば、、、
「ドット下」より「下ドット」の方が日本語の印象としてより近い気がしますが。

2024-04-19 05:34 UTC, noborus commented on doc/src/sgml/charset.sgml
> +例えば、コードポイントシーケンス<literal>U&amp;'\0065\0323\0302'</literal>と<literal>U&amp;'\0065\0302\0323'</literal>は、異なる順序で適用されたサーカムフレックスとドット下のアクセントを持つ<literal>e</literal>を表します。
ありがとうございます。「下ドット」の方が一般的に使用されているようなので変更しました。

2024-04-28 07:13 UTC, noborus commented
一箇所typo見つけたので修正しました

2024-05-05 23:57 UTC, tatsuo-ishii commented
このあたりでマージします。

2024-05-05 23:57 UTC, merged