update for 16.3 - part 1
pgsql-jp/jpug-doc pull request #2909
Opened 2024-05-16 12:49 UTC by koizumistr

以下のファイルの 16.3 対応です。

- ref/pg_rewind.sgml
- ref/psql-ref.sgml
- ref/select.sgml
- ref/set_role.sgml
- ref/vacuum.sgml

2024-05-20 22:52 UTC, KenichiroTanaka requested changes
1箇所気づくところがありますので見ていただいてもいいでしょうか

2024-05-21 01:25 UTC, koizumistr commented
確認ありがとうございます。対応しました。

こことは別にnominallyが「普通」と訳されていたところがありましたので、そちらも合わせて直しています。

2024-05-21 01:27 UTC, koizumistr commented on doc/src/sgml/ref/select.sgml
>  問い合わせ出力列は次のステップで公式に計算されますが、<literal>GROUP BY</literal>句で（名前または序数によって）参照することもできます。
翻訳ソフトによってはnominallyは飛ばして訳してしまうみたいですね、、、

2024-05-24 23:20 UTC, KenichiroTanaka commented
> 確認ありがとうございます。対応しました。
> 
> こことは別にnominallyが「普通」と訳されていたところがありましたので、そちらも合わせて直しています。
見落としていました。対応ありがとうございます。

2024-05-24 23:20 UTC, KenichiroTanaka approved these changes

2024-05-24 23:20 UTC, merged