update for 16.3 - part 3
pgsql-jp/jpug-doc pull request #2914
Opened 2024-05-20 12:05 UTC by koizumistr

以下のファイルの 16.3 対応です。

- logical-replication.sgml
- nls.sgml
- postgres-fdw.sgml
- uuid-ossp.sgml
- wal.sgml

2024-05-20 23:09 UTC, KenichiroTanaka requested changes
1箇所気づくところがありました。見ていただいてもいいでしょうか。

2024-05-20 23:09 UTC, KenichiroTanaka commented on doc/src/sgml/logical-replication.sgml
> +WAL送信プロセスはWALのロジカルデコーディング（<xref linkend="logicaldecoding"/>に記載）を開始し、標準のロジカルデコーディング出力プラグイン（pgoutput）をロードします。
pgoutput→<literal>pgoutput</literal>の変更も併せて対応が必要そうです。

2024-05-21 01:15 UTC, koizumistr commented
確認ありがとうございます。対応しました。

コメントだと正誤の区別が見えなくなっていますが＜literal＞の件ですよね。

2024-05-24 23:22 UTC, KenichiroTanaka commented
> 確認ありがとうございます。対応しました。
> 
> コメントだと正誤の区別が見えなくなっていますが＜literal＞の件ですよね。
上記の通りです。わかりづらくなっていました。失礼しました＆対応ありがとうございます。

2024-05-24 23:22 UTC, KenichiroTanaka approved these changes

2024-05-24 23:22 UTC, merged