update for 16.3 - part 4
pgsql-jp/jpug-doc pull request #2918
Opened 2024-05-21 13:37 UTC by koizumistr

以下のファイルの 16.3 対応です。

- ref/pg_dump.sgml
- ref/pg_dumpall.sgml

2024-05-24 23:32 UTC, KenichiroTanaka requested changes
細かいですが１箇所だけ気づくところがありましたので見ていただけますでしょうか。

2024-05-24 23:32 UTC, KenichiroTanaka commented on doc/src/sgml/ref/pg_dump.sgml
> +ダンプされたデータベースオブジェクトを作成するコマンドを出力する前に、それらをすべて<command>DROP</command>するコマンドを出力します。
細かいですが、
「それらすべて」→「それらすべてを」が良いと思います。

2024-05-25 11:54 UTC, koizumistr commented on doc/src/sgml/ref/pg_dump.sgml
> +ダンプされたデータベースオブジェクトを作成するコマンドを出力する前に、それらをすべて<command>DROP</command>するコマンドを出力します。
「それらをすべて」となっていますので、「を」を入れてはいるのですが、

「それらをすべて」→「それらすべてを」

という指摘でしょうか。

2024-05-26 23:14 UTC, KenichiroTanaka commented on doc/src/sgml/ref/pg_dump.sgml
> +ダンプされたデータベースオブジェクトを作成するコマンドを出力する前に、それらをすべて<command>DROP</command>するコマンドを出力します。
失礼しました。何か読み間違えたようです。「を」が無いように見えていました。

2024-05-26 23:15 UTC, KenichiroTanaka approved these changes
確認ありがとうございました。

2024-05-26 23:15 UTC, merged