update pgstatstatements for 16.3
pgsql-jp/jpug-doc pull request #2927
Opened 2024-05-26 03:52 UTC by koizumistr

pgstatstatements.sgml の 16.3 対応です。

2024-06-08 12:16 UTC, KenichiroTanaka requested changes
1箇所だけ気づくところがありました。見ていただいてもいいでしょうか。

2024-06-08 12:16 UTC, KenichiroTanaka commented on doc/src/sgml/pgstatstatements.sgml
> +マイナーバージョン間で互換性が破壊されるのは、最後の手段としてのみでしょう。
「マイナーバージョン間で互換性が破壊されるのは、最後の手段としてのみでしょう。」の一文がうまく理解できませんでした。
https://ejje.weblio.jp/content/as+a+last+resort
のニュアンスを使うと
「マイナーバージョン間で互換性が破壊されるのは仕方ないでしょう。」
だと理解できるのですが、どうでしょうか。

2024-06-10 05:57 UTC, koizumistr commented on doc/src/sgml/pgstatstatements.sgml
> +マイナーバージョン間で互換性が破壊されるのは、最後の手段としてのみでしょう。
> 「マイナーバージョン間で互換性が破壊されるのは仕方ないでしょう。」

これだけ読むと、「互換性が破壊されるのは仕方ないよね、だってマイナーとはいえバージョンが違うのだもの」（てへぺろ）と読めてしまって、直前にある

> マイナーバージョンリリース間で安定していると仮定できます。

（「マイナーバージョン間での互換性は基本的に維持される」と私は理解しています。）と矛盾するように受け取られてしまうのではないかと思います。なので「できる限りマイナーバージョンリリース間の互換性を維持するように努めるけれども、『絶対』とまでは約束できないよ。進退極まった場合には、マイナーバージョンリリース間であっても互換性が破壊される場合があるよ。」という意図だと思って「最後の手段としてのみ」としました。

2024-06-12 22:40 UTC, KenichiroTanaka commented on doc/src/sgml/pgstatstatements.sgml
> +マイナーバージョン間で互換性が破壊されるのは、最後の手段としてのみでしょう。
ご説明ありがとうございます。
確かに直前の説明との整合性も合わなくなりますね。
いただいている案でマージを進めます。

2024-06-12 22:40 UTC, KenichiroTanaka approved these changes

2024-06-12 22:41 UTC, merged