update maintenance for 16.3
pgsql-jp/jpug-doc pull request #2947
Opened 2024-06-22 06:52 UTC by koizumistr

maintenance.sgml の 16.3 対応です。

2024-07-03 00:02 UTC, noborus commented on doc/src/sgml/maintenance.sgml
> +パーティション化テーブルはタプルを直接格納しないため、autovacuumによって処理されません。
他が自動バキュームですが、ここだけautovacuumになっています。

2024-07-04 22:38 UTC, KenichiroTanaka requested changes
1箇所気づくところがありましたのでご確認をお願いします。

2024-07-15 22:36 UTC, KenichiroTanaka approved these changes

2024-07-15 22:37 UTC, KenichiroTanaka commented
斉藤さんの指摘も反映されていますのでここでマージします。

2024-07-15 22:37 UTC, merged