ddl.sgmlの16.3対応です
pgsql-jp/jpug-doc pull request #2963
Opened 2024-07-02 23:46 UTC by noborus

2024-07-07 04:16 UTC, tatsuo-ishii requested changes
確認しました。

2024-07-07 04:16 UTC, tatsuo-ishii commented on doc/src/sgml/ddl.sgml
>  たとえば、<literal>calvin=r*w/hobbes</literal>は、ロール<literal>calvin</literal>が許可オプション（<literal>*</literal>）ありの<literal>SELECT</literal>（<literal>r</literal>）と許可オプションなしの<literal>UPDATE</literal> (<literal>w
> Specific privileges are
>    represented by one-letter abbreviations from
>    <xref linkend="privilege-abbrevs-table"/>, with <literal>*</literal>
>    appended if the privilege was granted with grant option.

が約抜けしています。

2024-07-07 04:18 UTC, tatsuo-ishii requested changes
追加のレビューです。

2024-07-07 04:18 UTC, tatsuo-ishii commented on doc/src/sgml/ddl.sgml
> +<literal>ONLY</literal>を使ってパーティションテーブルについてのみ制約を追加または削除することは、パーティションが存在しない場合はサポートされます。
"partitioned table"の訳は「パーティション化されたテーブル」で統一している認識です。また、"as long as"が訳出されていません。以上から、機械翻訳の方が良いと思います。

> 機械翻訳》パーティション化されたテーブルに対してのみ制約を追加または削除する場合、パーティションが存在しない限り、<literal>ONLY</literal>を使用することがサポートされています。

2024-07-08 15:58 UTC, noborus commented on doc/src/sgml/ddl.sgml
> +<literal>ONLY</literal>を使ってパーティションテーブルについてのみ制約を追加または削除することは、パーティションが存在しない場合はサポートされます。
"partitioned table" はまだ統一出来てませんでした。 #2719  #1724 #2227 変更は多くなるので別のpull requestで統一をしようと思います。
他を修正します。

2024-07-09 02:53 UTC, tatsuo-ishii requested changes
確認しました。一箇所修正をお願いできますでしょうか。

2024-07-09 02:53 UTC, tatsuo-ishii commented on doc/src/sgml/ddl.sgml
> +パーティションが存在する場合、<literal>ONLY</literal>を使用すると、<literal>UNIQUE</literal>および<literal>PRIMARY KEY</literal>以外の制約に対してエラーが発生します。
"Once"が訳出されていません。

2024-07-10 07:04 UTC, noborus commented on doc/src/sgml/ddl.sgml
> +パーティションが存在する場合、<literal>ONLY</literal>を使用すると、<literal>UNIQUE</literal>および<literal>PRIMARY KEY</literal>以外の制約に対してエラーが発生します。
すみません。前の文を「存在しない限り」にしたので、「ひとたびパーティションが存在すれば」はバランスが悪いかと思ったのですが、戻します。

2024-07-12 04:07 UTC, tatsuo-ishii approved these changes
確認しました。対応ありがとうざいました。

2024-07-15 23:06 UTC, KenichiroTanaka requested changes
細かいですが1箇所だけ見ていただいてもいいでしょうか。

2024-07-17 03:18 UTC, noborus commented on doc/src/sgml/ddl.sgml
> +これは、被参照列は常にインデックスがあり、参照する行に一致があるかどうかを効率的に検索できることを意味します。
ありがとうございます。修正します。

2024-07-17 22:30 UTC, KenichiroTanaka approved these changes
対応ありがとうございました。マージします。

2024-07-17 22:30 UTC, merged