ecpg.sgmlの16.3対応です
pgsql-jp/jpug-doc pull request #2967
Opened 2024-07-08 16:06 UTC by noborus

int typeとinteger typeを整数型にしています。

2024-07-08 16:07 UTC, noborus commented
説明の中でint typeがあるのはecpg.sgmlだけで、これは統一漏れだと思いましたがどうでしょうか？

2024-07-14 06:46 UTC, tatsuo-ishii requested changes
一通り確認しました。

2024-07-14 06:46 UTC, tatsuo-ishii commented on doc/src/sgml/ecpg.sgml
> +整数型変数をnumeric型変数に変換します。
次行の例を見ると、ここで"int"はC言語のint型のことを言っているのであり、「整数型」と訳すと原文の意図とずれると思います。「int型」で良いのではないでしょうか。

2024-07-14 06:46 UTC, tatsuo-ishii commented on doc/src/sgml/ecpg.sgml
> +この関数は符号付整数型の変数を受付け、numeric型変数<literal>var</literal>内に格納します。
一つ前と同様に、「signed int型の変数」で良いと思います。

2024-07-14 06:46 UTC, tatsuo-ishii commented on doc/src/sgml/ecpg.sgml
> +long整数型変数をnumeric型変数に変換します。
こちらも「long int型」で良いと思います。

2024-07-14 06:46 UTC, tatsuo-ishii commented on doc/src/sgml/ecpg.sgml
> +この関数は符号付long整数型の変数を受付け、numeric型変数<literal>var</literal>内に格納します。
こちらも「long int型」で良いと思います。

2024-07-14 06:46 UTC, tatsuo-ishii commented on doc/src/sgml/ecpg.sgml
> +numeric 型変数を整数型に変換します。
こちらも「int型」で良いと思います。

2024-07-14 06:46 UTC, tatsuo-ishii commented on doc/src/sgml/ecpg.sgml
> +この関数は<literal>nv</literal>が指し示すnumeric型の変数の値を<literal>lp</literal>が指し示すlong整数値に変換します。
ここで"long interger"と言っているのは省略形である"long"を省略しない形に言い換えているだけなので、ここは「long integer変数」と訳すのがわかりやすいと思います。

2024-07-14 06:46 UTC, tatsuo-ishii commented on doc/src/sgml/ecpg.sgml
> +整数型の値をdecimal型の値に変換します。
上と同じ理由で「int型の値をdecimal型の値に変換します。」の方が良さそうです。

2024-07-14 06:46 UTC, tatsuo-ishii commented on doc/src/sgml/ecpg.sgml
> +この関数は最初の引数として、変換対象の整数型変数(<literal>in</literal>)を受付けます。
「整数型変数」→「int型変数」

2024-07-14 06:46 UTC, tatsuo-ishii commented on doc/src/sgml/ecpg.sgml
> +この関数は変換対象のdecimal型変数(<literal>np</literal>)のポインタと処理結果を格納する整数型変数(<literal>ip</literal>)へのポインタを受け付けます。
「整数型変数」→「int型変数」

2024-07-14 06:46 UTC, tatsuo-ishii commented on doc/src/sgml/ecpg.sgml
> +decimal型変数をlong整数型に変換します。
「long整数型」→「long integer型」

2024-07-14 06:46 UTC, tatsuo-ishii commented on doc/src/sgml/ecpg.sgml
> +<productname>Informix</productname>では、long整数範囲に-2,147,483,647から2,147,483,647までという制限をしていますが、ECPGでの制限はアーキテクチャに依存(<literal>-LONG_MAX .. LONG_MAX</literal>)します。
「long整数」→「long integer」

2024-07-14 06:48 UTC, tatsuo-ishii commented
> 説明の中でint typeがあるのはecpg.sgmlだけで、これは統一漏れだと思いましたがどうでしょうか？

ここで言っている"int"はC言語のデータ型”int"のことなので、これはこれで合っていると思います。

2024-07-15 06:54 UTC, noborus commented
> > 説明の中でint typeがあるのはecpg.sgmlだけで、これは統一漏れだと思いましたがどうでしょうか？
> 
> ここで言っている"int"はC言語のデータ型”int"のことなので、これはこれで合っていると思います。

ありがとうございます。
一部だけみて混乱してました。ただ、そうすると
long integer → long int,
short integer → short int
の方が良いことにならないでしょうか？

現状だとint->int, integer->整数にしてしまうと、原文がそこまで使い分け出来てないのに違いが強調されてしまうように思います。
そのため、int->int, integer->integerの原文に合わせるように修正しようと思います。

2024-07-15 11:33 UTC, tatsuo-ishii commented
> long integer → long int,
> short integer → short int
> の方が良いことにならないでしょうか？

そうは思いません。たとえば"long int"はC言語固有の型名ですが、文章中ではその意味として、"long integer"と表現していると考えられます。この例では違いがわかりにくいですが、たとえば"&"を文章で説明するとしたら"pointer to a variable"というようになるのと同じです。

2024-07-15 23:31 UTC, tatsuo-ishii approved these changes
確認しました。対応ありがとうございます。

2024-07-17 22:49 UTC, KenichiroTanaka approved these changes
一通り確認しました。石井さんから指摘があった箇所以外には特に気づくものはありませんでした。

2024-07-17 22:49 UTC, merged