config.sgmlのPostgreSQL 16.3対応です。
pgsql-jp/jpug-doc pull request #2973
Opened 2024-07-15 05:27 UTC by tatsuo-ishii

2024-07-23 23:48 UTC, noborus commented on doc/src/sgml/config0.sgml
> +値は、ホスト名のコンマ区切りリストあるいは数字のIPアドレスの形式をとります。
「リスニング」にするのは良いと思うのですが、config.sgmlでも他のところが監視だったり、listenだったりするので統一したほうが良いと思います。

2024-07-23 23:48 UTC, noborus commented on doc/src/sgml/config2.sgml
> +他の文字は<link linkend="sql-syntax-strings-escape">によってCスタイルの16進エスケープ文字に置き換えられます</link>。
C-style hexadecimal escapes が下の方で「C-style hexadecimal escape」にしていて統一されていません。

2024-07-24 03:59 UTC, KenichiroTanaka requested changes
1箇所気づくところがありましたので見ていただいてもいいでしょうか。

2024-07-24 03:59 UTC, KenichiroTanaka commented on doc/src/sgml/config0.sgml
> +サーバがクライアントアプリケーションからの接続をリスニングするTCP/IPアドレスを指定します。
英文としては変更箇所がなどほんの一部なのですが、２つの<para>に分割されたせいか、新しい文と認識されたいます（マッチ度が出てません）。以前の訳がほとんど使えますのでこちらを利用いただいてもいいでしょうか。

```
+         to it.  If the list is not empty, the server will start if it
+         can listen on at least one TCP/IP address.  A warning will be
+         emitted for any TCP/IP address which cannot be opened.
```

https://www.postgresql.jp/docs/16/runtime-config-connection.html

```
クライアントアプリケーションからの接続をサーバが監視する TCP/IP アドレスを指定します。 この値は、ホスト名をカンマで区切ったリスト、そして/もしくは、数値によるIPアドレスです。 *という特別なエントリは利用可能な全てのIPインタフェースに対応します。 エントリ0.0.0.0は全てのIPv4アドレスの監視を、そしてエントリ::は全てのIPv6アドレスの監視を許容します。 リストが空の場合、サーバはいかなるIPインタフェースも全く監視しないで、Unixドメインソケットのみを使用して接続が行われます。 デフォルトの値はlocalhostで、ローカルなTCP/IP 「loopback」接続のみ許可します。 クライアント認証 ([第21章](https://www.postgresql.jp/docs/16/client-authentication.html))は誰がサーバにアクセス可能かをきめ細かく制御するのに対し、listen_addressesはどのインタフェースが接続を試みるかを制御します。 これにより、安全でないネットワークインタフェース上において繰り返して行われる悪意のある接続要求の防止に役立ちます。 このパラメータはサーバ起動時のみ設定可能です。
```

2024-08-01 00:00 UTC, noborus approved these changes
#2989 によりマージします

2024-08-01 00:01 UTC, merged