deleteとupdateの翻訳を原文に沿うように修正
pgsql-jp/jpug-doc pull request #3007
Opened 2024-08-04 22:49 UTC by noborus

countが0の場合の説明が条件を満たすではなく、結果に対してなので
原文に沿うように修正。
updateとdeleteの類似文を同じ書き方になるように修正。
sub-selectの修正漏れを修正

2024-08-04 23:16 UTC, tatsuo-ishii requested changes
一通り確認しました。

2024-08-04 23:16 UTC, tatsuo-ishii commented on doc/src/sgml/ref/delete.sgml
> +<replaceable class="parameter">count</replaceable>が0の場合、問い合わせによって行が削除されなかったことを示します
"no rows were deleted"なので、「問い合わせによって削除された行がなかったことを示します」の方が原文の意味を反映しているような気がしますがいかがでしょう？

2024-08-04 23:16 UTC, tatsuo-ishii commented on doc/src/sgml/ref/update.sgml
> +<replaceable class="parameter">count</replaceable>が0の場合、問い合わせによって行が更新されなかったことを示します
"no rows were updated"なので、「問い合わせによって更新された行がなかったことを示します」の方が原文の意味を反映しているような気がしますがいかがでしょう？

2024-08-05 09:13 UTC, noborus commented on doc/src/sgml/ref/delete.sgml
> +<replaceable class="parameter">count</replaceable>が0の場合、問い合わせによって行が削除されなかったことを示します
確かに、その通りですね。修正します。

2024-08-05 09:13 UTC, noborus commented on doc/src/sgml/ref/update.sgml
> +<replaceable class="parameter">count</replaceable>が0の場合、問い合わせによって行が更新されなかったことを示します
こちらも修正します。

2024-08-07 22:54 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。一通り確認しました。

2024-08-13 00:16 UTC, KenichiroTanaka commented
石井さんからのご指摘内容は反映されていると思いますので、この辺りでマージします。

2024-08-13 00:17 UTC, merged