update logical-replication for 16.4
pgsql-jp/jpug-doc pull request #3029
Opened 2024-08-15 12:05 UTC by koizumistr

logical-replication.sgml の 16.4 対応です。

2024-08-17 12:32 UTC, HUUTFJ reviewed
「後でテーブル追加された列」となっていますが、「後でテーブルへと(に)追加された列」のほうが自然ではないでしょうか？

2024-08-19 23:08 UTC, KenichiroTanaka requested changes
細かいですが１箇所見ていただいてもいいでしょうか。

2024-08-19 23:08 UTC, KenichiroTanaka commented on doc/src/sgml/logical-replication.sgml
> +列リストが指定されていない場合、後でテーブル追加された列は自動的にレプリケーションされます。
細かいですが、
「後でテーブル追加された列は」は「後でテーブルに追加された列は」
かと思います。

2024-08-24 15:01 UTC, koizumistr commented
確認ありがとうございます。対応しました。

2024-08-27 12:02 UTC, noborus approved these changes
確認しました。
指摘箇所は修正されているのでマージします。

2024-08-27 12:03 UTC, merged