system-views.sgmlの16.4対応です
pgsql-jp/jpug-doc pull request #3032
Opened 2024-08-15 22:58 UTC by noborus

2024-08-20 12:08 UTC, KenichiroTanaka requested changes
細かいですが１箇所気づくところがありましたので見ていただいてもいいでしょうか

2024-08-20 12:08 UTC, KenichiroTanaka commented on doc/src/sgml/system-views.sgml
> +シーケンスはログを取らないシーケンスで、サーバはスタンバイ。
細かいですがシーケンスが続くので、
「ログを取らないシーケンスで、サーバはスタンバイ」
とするのはどうでしょうか

2024-08-21 13:55 UTC, noborus commented on doc/src/sgml/system-views.sgml
> +シーケンスはログを取らないシーケンスで、サーバはスタンバイ。
ありがとうございます。確かにその方が自然でした。修正します。

2024-08-30 10:15 UTC, KenichiroTanaka approved these changes
対応ありがとうございました。一通り確認しました。

2024-08-30 10:15 UTC, merged