plpgsql.sgmlの16.4対応です
pgsql-jp/jpug-doc pull request #3039
Opened 2024-08-21 13:46 UTC by noborus

2024-08-29 05:13 UTC, tatsuo-ishii requested changes
一通り確認しました。

2024-08-29 10:01 UTC, noborus commented on doc/src/sgml/plpgsql.sgml
> +この構文は、キーワードのない<replaceable>direction</replaceable>句と全く省略された<replaceable>direction</replaceable>句の場合と曖昧であるため、<replaceable>count</replaceable>が定数でない場合は失敗する可能性があります。）
ありがとうございます。確かに変でした。
ご指摘の通り修正します。

2024-08-29 11:17 UTC, tatsuo-ishii approved these changes
確認しました。対応ありがとうございます。

2024-08-30 10:35 UTC, KenichiroTanaka approved these changes
一通り確認しました。

2024-08-30 10:35 UTC, merged