Update release-16.sgml for 16.4
pgsql-jp/jpug-doc pull request #3044
Opened 2024-08-29 05:56 UTC by kitayama

2024-08-29 07:12 UTC, tatsuo-ishii requested changes
一通り確認しました。

2024-08-29 07:12 UTC, tatsuo-ishii commented on doc/src/sgml/release-16.sgml
> +論理レプリケーションスロットの誤った初期設定を防止します。
「防止します。」→「防止するようにしました。」

2024-08-29 07:12 UTC, tatsuo-ishii commented on doc/src/sgml/release-16.sgml
> +統計情報の共有メモリに接続する新しいバックエンドプロセスは、参照カウントを増加させましたが、終了時にカウントを減少できませんでした。
「減少できませんでした。」→「減じていませんでした。」

2024-08-29 07:12 UTC, tatsuo-ishii commented on doc/src/sgml/release-16.sgml
> +マルチトランザクションのSLRUログの切り捨て中のデッドロックとアサーションエラーを防止します。
「防止します。」→「防止しました。」

2024-08-29 07:12 UTC, tatsuo-ishii commented on doc/src/sgml/release-16.sgml
> +通常は無害ですが、原則的にはクラッシュを引き起こす可能性がありました。
「原則的」→「原理的」

2024-08-29 07:12 UTC, tatsuo-ishii commented on doc/src/sgml/release-16.sgml
> +OpenSSLによるステートフルTLSセッションチケットの作成を無効にします。
「無効にします。」→「無効にしました。」

2024-08-29 07:12 UTC, tatsuo-ishii commented on doc/src/sgml/release-16.sgml
> +システムが提供する<filename>&lt;regex.h&gt;</filename>ヘッダとの衝突を回避します。
「回避します。」→「回避しました。」

2024-08-29 07:12 UTC, tatsuo-ishii commented on doc/src/sgml/release-16.sgml
> +外部キー強制トリガによって更新されるタプルが追加の可視性クロスチェックに失敗した場合、<function>heap_update()</function>と<function>heap_delete()</function>でのアサーションエラーを回避します。
「回避します。」→「回避しました。」

2024-08-29 10:26 UTC, noborus commented on doc/src/sgml/release-16.sgml
> +パーティションテーブルに、制約と関連付けられていないインデックスがあり、パーティションに同等の制約を持つインデックスがある場合、パーティションをデタッチすると不正な動作となり、元のパーティションの制約に誤った<structfield>cominncount</structfield>値が残ります。
機械翻訳の方が何故か改変してしまってますが、`<structfield>coninhcount</structfield>値`です。

2024-08-29 10:26 UTC, noborus commented on doc/src/sgml/release-16.sgml
> +<literal>ON CONFLICT</literal>を使用する問い合わせが、更新可能なビューを介してターゲットテーブルにアクセスする場合、適合するインデックスが存在する場合でも、<quote>there is no unique or exclusion constrant matching the ON CONFLICT specification</quote>というエラーで失敗する
スペルミスがあるようです。 constrant -> constraint

2024-08-29 23:50 UTC, kitayama commented on doc/src/sgml/release-16.sgml
> +これを防ぐために、組み込み以外のビューの拡張や外部テーブルへのアクセスを無効にすることができる新しいサーバパラメータ<varname>restrict_nonsystem_relation_kind</varname>を導入し、利用可能な場合にはそれを設定するよう<application>pg_dump</application>に指示します。
確認ありがとうございます。展開に修正しました。

2024-08-29 23:52 UTC, kitayama commented on doc/src/sgml/release-16.sgml
> +<literal>DETACH PARTITION</literal>の<literal>CONCURRENTLY</literal>オプションが導入されてからこれは成り立たなくなり、このオプションが使用するとクエリの実行が一時的に失敗する可能性がありました。
修正しました。

2024-08-29 23:53 UTC, kitayama commented on doc/src/sgml/release-16.sgml
> +パーティションテーブルから最後の子パーティションが削除された後、<structname>pg_class</structname>.<structfield>reltuples</structfield>フィールドを正しくゼロに更新します。
修正しました。

2024-08-29 23:59 UTC, kitayama commented on doc/src/sgml/release-16.sgml
> +<command>CALL</command>がアトミックなコンテキスト内にある場合（例えば、外側のトランザクションブロックがある場合）、そのような関数には間違ったスナップショットが渡され、外側トランザクションの開始以降に変更された行の古い値が表示される原因となっていました。
「原子的コンテキスト」に戻しました。

2024-08-30 00:00 UTC, kitayama commented on doc/src/sgml/release-16.sgml
> +<type>money</type>型の計算で整数オーバーフローを検出します。
修正しました。

2024-08-30 00:00 UTC, kitayama commented on doc/src/sgml/release-16.sgml
> +代わりに、<type>numeric</type>型の実際の許容範囲に制限します。
修正しました。

2024-08-30 00:02 UTC, kitayama commented on doc/src/sgml/release-16.sgml
> +新しい配列の次元を計算するときに別の整数オーバーフローのケースを検出します。
いただいた案で修正しました。

2024-08-30 00:02 UTC, kitayama commented on doc/src/sgml/release-16.sgml
> +新しいカタログキャッシュエントリが、そのフィールドのTOAST展開中に古くなる別のケースを検出します。
修正しました。

2024-08-30 00:03 UTC, kitayama commented on doc/src/sgml/release-16.sgml
> +<literal>INSERT</literal> ... <literal>DEFAULT</literal>の対象となるビュー列の更新可能性を正しくチェックします。
修正しました。

2024-08-30 00:03 UTC, kitayama commented on doc/src/sgml/release-16.sgml
> +<literal>ALTER TABLE SET LOGGED|UNLOGGED</literal>の実行中に所有シーケンスをロックします。
修正しました。

2024-08-30 00:12 UTC, kitayama commented on doc/src/sgml/release-16.sgml
> +これらのコマンドは、テーブルとともにテーブルの所有シーケンスの永続性を変更しますが、その際にシーケンス上のロックを取得できませんでした。
修正しました。

2024-08-30 00:13 UTC, kitayama commented on doc/src/sgml/release-16.sgml
> +キューに入れられた<literal>AFTER</literal>トリガーがもはや存在しない場合は、エラーを発生しません。
修正しました。

2024-08-30 00:16 UTC, kitayama commented on doc/src/sgml/release-16.sgml
> +これは、テーブルのOIDが別のリレーションに再利用されるまでは無害でしたが、再利用されると<application>pg_dump</application>がそのリレーションに対してダンプする内容に干渉する可能性がありました。
訳出しました。

2024-08-30 00:18 UTC, kitayama commented on doc/src/sgml/release-16.sgml
> +望ましいインデックスに式または述語がある場合、<literal>ON CONFLICT</literal>に対する仲裁インデックスの選択を修正します。
「調停」に修正しました。

2024-08-30 00:18 UTC, kitayama commented on doc/src/sgml/release-16.sgml
> +<literal>ALTER TABLE</literal>を使用して別のセッションの一時テーブルを変更することを拒否します。
修正しました。

2024-08-30 00:23 UTC, kitayama commented on doc/src/sgml/release-16.sgml
> +これは、外部問い合わせがハッシュ集約で実装された<literal>DISTINCT</literal>を使用する場合にのみ発生しますが、他のケースも存在する可能性があります。
訳出しました。

2024-08-30 00:24 UTC, kitayama commented on doc/src/sgml/release-16.sgml
> +論理レプリケーションスロットの誤った初期設定を防止します。
修正しました。

2024-08-30 00:25 UTC, kitayama commented on doc/src/sgml/release-16.sgml
> +統計情報の共有メモリに接続する新しいバックエンドプロセスは、参照カウントを増加させましたが、終了時にカウントを減少できませんでした。
修正しました。

2024-08-30 00:26 UTC, kitayama commented on doc/src/sgml/release-16.sgml
> +通常は無害ですが、原則的にはクラッシュを引き起こす可能性がありました。
修正しました。

2024-08-30 00:26 UTC, kitayama commented on doc/src/sgml/release-16.sgml
> +OpenSSLによるステートフルTLSセッションチケットの作成を無効にします。
修正しました。

2024-08-30 00:27 UTC, kitayama commented on doc/src/sgml/release-16.sgml
> +システムが提供する<filename>&lt;regex.h&gt;</filename>ヘッダとの衝突を回避します。
修正しました。

2024-08-30 00:27 UTC, kitayama commented on doc/src/sgml/release-16.sgml
> +外部キー強制トリガによって更新されるタプルが追加の可視性クロスチェックに失敗した場合、<function>heap_update()</function>と<function>heap_delete()</function>でのアサーションエラーを回避します。
修正しました。

2024-08-30 00:28 UTC, kitayama commented on doc/src/sgml/release-16.sgml
> +パーティションテーブルに、制約と関連付けられていないインデックスがあり、パーティションに同等の制約を持つインデックスがある場合、パーティションをデタッチすると不正な動作となり、元のパーティションの制約に誤った<structfield>cominncount</structfield>値が残ります。
修正しました。

2024-08-30 00:29 UTC, kitayama commented on doc/src/sgml/release-16.sgml
> +<literal>ON CONFLICT</literal>を使用する問い合わせが、更新可能なビューを介してターゲットテーブルにアクセスする場合、適合するインデックスが存在する場合でも、<quote>there is no unique or exclusion constrant matching the ON CONFLICT specification</quote>というエラーで失敗する
修正しました。

2024-08-30 01:08 UTC, tatsuo-ishii approved these changes
対応ありがとうございます。修正されているのを確認しました。

2024-08-30 04:29 UTC, tatsuo-ishii commented
斉藤さんの確認もいただいたので、マージします。

2024-08-30 04:29 UTC, merged