update for 17.0 - part 1
pgsql-jp/jpug-doc pull request #3091
Opened 2024-09-27 14:23 UTC by koizumistr

以下のファイルの17.0対応です。

- ref/lock.sgml
- ref/pg_recvlogical.sgml
- ref/set_session_auth.sgml

2024-09-29 07:09 UTC, tatsuo-ishii requested changes
pg_recvlogical.sgmlだけ見ました。

2024-09-29 07:09 UTC, tatsuo-ishii commented on doc/src/sgml/ref/pg_recvlogical.sgml
>  このオプションは<option>--create-slot</option>でのみ指定できます
細かいですが、原文の最後に"."があるので(16.4にはない)、翻訳文の最後に「。」が必要かと。

2024-09-30 14:04 UTC, koizumistr commented
確認ありがとうございます。対応しました。

2024-10-01 12:26 UTC, tatsuo-ishii approved these changes
残りも確認しました。

2024-10-01 14:58 UTC, KenichiroTanaka approved these changes
一通り確認しました。

2024-10-01 14:58 UTC, merged