Translate logicaldecoding.sgml
pgsql-jp/jpug-doc pull request #3103
Opened 2024-09-29 09:02 UTC by HUUTFJ

第2節が完全に新規の内容(スロット同期機能について)だったので、レビューが大変かもしれません。

2024-10-08 11:47 UTC, KenichiroTanaka requested changes
量が多いファイルの対応ありがとうございました。
１箇所だけ気づくところがありましたので見ていただいてもいいでしょうか。

2024-10-08 11:47 UTC, KenichiroTanaka commented on doc/src/sgml/logicaldecoding.sgml
> +フェイルオーバー後にロジカルレプリケーションを再開できるかどうかは、フェイルオーバー時のスタンバイ上で同期されていたスロットの持つ<link linkend="view-pg-replication-slots">pg_replication_slots</link>.<structfield>synced</structfield>によって決まります。
細かいですが
原文にvalueがあるので
<structfield>synced</structfield> **value** for the synchronized

<structfield>synced</structfield>によって決まります。
は
<structfield>synced</structfield>の値によって決まります。
が良いと思います。

2024-10-08 14:45 UTC, HUUTFJ commented on doc/src/sgml/logicaldecoding.sgml
> +フェイルオーバー後にロジカルレプリケーションを再開できるかどうかは、フェイルオーバー時のスタンバイ上で同期されていたスロットの持つ<link linkend="view-pg-replication-slots">pg_replication_slots</link>.<structfield>synced</structfield>によって決まります。
ありがとうございます。対応しました。

2024-10-09 22:48 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。この辺りでマージします。

2024-10-09 22:48 UTC, merged