config.sgmlのPostgreSQL 17.0対応です。
pgsql-jp/jpug-doc pull request #3105
Opened 2024-09-30 11:25 UTC by tatsuo-ishii

"WAL Summarization"のSummarizationの訳で迷いました。今の所、次のようにしています。

WAL Summarization -> WAL要約
WAL summarizer process -> WAL要約プロセス
WAL summarizer -> WAL要約処理
the summarizer -> 要約処理
summary files -> WALの要約ファイル
WAL summaries -> WAL要約

WAL SummarizationとWAL summariesが同じ「WAL要約」になっているのが気になっています。

2024-10-02 14:54 UTC, koizumistr reviewed
config[1-3]見ました。

2024-10-02 14:54 UTC, koizumistr commented on doc/src/sgml/config1.sgml
> +サーバスタートアップの後で<literal>summarize_wal=on</literal>が<literal>wal_level=minimal</literal>に設定されている場合、要約処理は動作しますが、<literal>wal_level=minimal</literal>で生成されたWALの要約ファイルの生成は拒否します。
wal_level=minimal に設定されており、サーバスタートアップの後でsummarize_wal=onが設定された場合、

ということなのではないかと思います。

2024-10-02 14:54 UTC, koizumistr commented on doc/src/sgml/config1.sgml
> +WAL要約処理は、先行するバックアップと新しいバックアップの間のWALレコードの全範囲に対して利用可能でなければなりません。そうでない場合、インクリメンタルバックアップは失敗します。
WAL要約処理 -> WAL要約

2024-10-02 14:54 UTC, koizumistr commented on doc/src/sgml/config1.sgml
> +<literal>summarize_wal=off</literal>の場合、WAL要約処理が動作しないため、このパラメータの値に関わらず、既存のWAL要約は削除されません。
原文は summarize_wal = offと「=」の周りに空白があります。が、原文の違うところでは周りに空白がないものも、、、

2024-10-02 14:54 UTC, koizumistr commented on doc/src/sgml/config3.sgml
> +すべてのセッションに影響することがあるので、<filename>postgresql.conf</filename>内で<varname>statement_timeout</varname>を設定することは推奨されません。
statement_timeout -> transaction_timeout
（機械翻訳が犯人ですね）

2024-10-02 14:54 UTC, koizumistr commented on doc/src/sgml/config3.sgml
>  値を<literal>true</literal>に設定すると、すべてのイベント・トリガーが起動します。
ここも イベントトリガー と揃えるべきかと。

が、「トリガー」なのでしたっけ、「トリガ」なのでしたっけ、、、、

2024-10-02 14:54 UTC, koizumistr commented on doc/src/sgml/config3.sgml
>  これにより、外部ツールがポイントを更新したときに、後の設定で変更を上書きするなど、意図しない動作が発生する可能性があります。
これにより、後で外部ツールが設定を更新する際に、その変更を上書きしてしまうなど、意図しない動作が発生する可能性があります。
ということだと思います。

2024-10-02 14:54 UTC, koizumistr commented on doc/src/sgml/config3.sgml
> +<filename>Postgresql.auto.conf</filename>に保存された設定は、<literal>allow_alter_system</literal>が<literal>off</literal>に設定されていても有効になります。
-> postgresql.auto.conf

2024-10-02 14:54 UTC, koizumistr commented on doc/src/sgml/config3.sgml
> +現在インスタンスのhuge pagesの状態を報告します:<literal>on</literal>、<literal>off</literal>、または<literal>unknown</literal><literal>のどれかです（postgres -C</literal>で表示される場合）。
「のどれかです」の直前の＜literal＞は余分かと。

2024-10-02 14:54 UTC, koizumistr commented on doc/src/sgml/config3.sgml
> +<literal>immediate</literal>に設定すると、<link linkend="sql-createsubscription-params-with-streaming"><literal>ストリーミング</literal></link>オプションが有効になっている場合は各変更をストリームし、それ以外の場合は各変更をシリアル化します。
CREATE SUBSCRIPTIONの は消さなくて良かったような。
また、（元からの問題ですが）ストリーミングオプションのストリーミングはstreamingのままでいい気がします。（＜literal＞の中ですから）

2024-10-02 14:54 UTC, koizumistr commented on doc/src/sgml/config1.sgml
> +ロジカルWAL送信側プロセスが待機する、カンマで区切られたストリーミングレプリケーションのスタンバイサーバのスロット名です。
直後の文では「ロジカルWAL送信プロセス」となっています。"WAL sender process"
を「WAL送信プロセス」としている例はありますので、ここも「ロジカルWAL送信プロセス」とすべきかと。

2024-10-02 22:47 UTC, noborus commented on doc/src/sgml/config3.sgml
>  値を<literal>true</literal>に設定すると、すべてのイベント・トリガーが起動します。
トリガです。
doc_ja_16の修正とNGリストが反映によって１７のリリース前に統一する予定です。

2024-10-03 02:36 UTC, tatsuo-ishii commented on doc/src/sgml/config3.sgml
>  値を<literal>true</literal>に設定すると、すべてのイベント・トリガーが起動します。
トリガーは、現状NGリストに入っていないので、make checkでエラーにならないのですよね。
なのでレビューしてもらうまで、合っているかどうかわからないという...

2024-10-03 02:38 UTC, tatsuo-ishii commented on doc/src/sgml/config3.sgml
> +<filename>Postgresql.auto.conf</filename>に保存された設定は、<literal>allow_alter_system</literal>が<literal>off</literal>に設定されていても有効になります。
機械翻訳にやられました。
ところで、機械翻訳はこの間違いを頻繁にするので、NGリストに"PostgreSQL.conf"とか、"PostgreSQL.auto.conf"を入れられないですかね。

2024-10-03 03:49 UTC, tatsuo-ishii reviewed
長大なファイルのレビュー、ありがとうございました。

2024-10-03 03:49 UTC, tatsuo-ishii commented on doc/src/sgml/config1.sgml
> +サーバスタートアップの後で<literal>summarize_wal=on</literal>が<literal>wal_level=minimal</literal>に設定されている場合、要約処理は動作しますが、<literal>wal_level=minimal</literal>で生成されたWALの要約ファイルの生成は拒否します。
確かにそうですね。修正します。

2024-10-03 03:49 UTC, tatsuo-ishii commented on doc/src/sgml/config1.sgml
> +WAL要約処理は、先行するバックアップと新しいバックアップの間のWALレコードの全範囲に対して利用可能でなければなりません。そうでない場合、インクリメンタルバックアップは失敗します。
修正します。

2024-10-03 03:49 UTC, tatsuo-ishii commented on doc/src/sgml/config1.sgml
> +<literal>summarize_wal=off</literal>の場合、WAL要約処理が動作しないため、このパラメータの値に関わらず、既存のWAL要約は削除されません。
修正します。

2024-10-03 03:49 UTC, tatsuo-ishii commented on doc/src/sgml/config1.sgml
> +ロジカルWAL送信側プロセスが待機する、カンマで区切られたストリーミングレプリケーションのスタンバイサーバのスロット名です。
機械翻訳に引きずられましたが、仰るとおりですね。

2024-10-03 03:49 UTC, tatsuo-ishii commented on doc/src/sgml/config3.sgml
> +すべてのセッションに影響することがあるので、<filename>postgresql.conf</filename>内で<varname>statement_timeout</varname>を設定することは推奨されません。
いえ、私の間違いかと。

2024-10-03 03:49 UTC, tatsuo-ishii commented on doc/src/sgml/config3.sgml
>  これにより、外部ツールがポイントを更新したときに、後の設定で変更を上書きするなど、意図しない動作が発生する可能性があります。
機械翻訳の変な訳を見逃してました。

2024-10-03 03:49 UTC, tatsuo-ishii commented on doc/src/sgml/config3.sgml
> +現在インスタンスのhuge pagesの状態を報告します:<literal>on</literal>、<literal>off</literal>、または<literal>unknown</literal><literal>のどれかです（postgres -C</literal>で表示される場合）。
余分なのではなく、入れる場所を間違ったようです。

2024-10-03 03:49 UTC, tatsuo-ishii commented on doc/src/sgml/config3.sgml
> +<literal>immediate</literal>に設定すると、<link linkend="sql-createsubscription-params-with-streaming"><literal>ストリーミング</literal></link>オプションが有効になっている場合は各変更をストリームし、それ以外の場合は各変更をシリアル化します。
> CREATE SUBSCRIPTIONの は消さなくて良かったような。

うわ、失礼しました。

2024-10-03 03:49 UTC, tatsuo-ishii commented on doc/src/sgml/config3.sgml
>  値を<literal>true</literal>に設定すると、すべてのイベント・トリガーが起動します。
トリガーはそのまま残しておきます。

2024-10-04 12:31 UTC, noborus commented on doc/src/sgml/config3.sgml
> +<filename>Postgresql.auto.conf</filename>に保存された設定は、<literal>allow_alter_system</literal>が<literal>off</literal>に設定されていても有効になります。
ちょっと前から特定のインラインタグ内の単語を翻訳しないように設定してみているのですが、大文字小文字変換は入ってしまう（入ったり入らなかったりですが）ので、
「翻訳後書換えデータ集」で"PostgreSQL.conf"と"PostgreSQL.auto.conf"は"postgresql.conf"とか、"postgresql.auto.conf"に変換するように入れました。
たまに全部大文字になったりする場合があって、その場合は抜けてしまいます...

2024-10-04 23:59 UTC, koizumistr commented on doc/src/sgml/config0.sgml
>  この値が単位なしで指定した場合、ブロック、つまり<symbol>BLCKSZ</symbol>バイト、通常は8キロバイトとして扱われます。
この値が単位なしで指定された場合
もしくは
この値を単位なしで指定した場合

直前は前者で訳しているようです。（機械翻訳さん、なぜここでブレる、、、）

2024-10-05 00:19 UTC, koizumistr reviewed
対応ありがとうございます。確認しました。
あと残りのconfig0も見ました。

2024-10-05 00:19 UTC, koizumistr commented on doc/src/sgml/config0.sgml
> +<literal>pg_multixact/offsets</literal>の内容を共有メモリするために使用するキャッシュの量を指定します（<xref linkend="pgdata-contents-table"/>を参照してください）。
内容をキャッシュするために使用する共有メモリの量を
だと思います。

2024-10-05 00:19 UTC, koizumistr commented on doc/src/sgml/config3.sgml
>  値を<literal>true</literal>に設定すると、すべてのイベント・トリガーが起動します。
トリガーを残すのは了解です。
ただ、直前で「イベントトリガー」と何度も書いてあるので、ここも「イベント・トリガー」ではなく「イベントトリガー」としておくべきかと（「え？何で最後だけ「・」があるの？もしかしてこれだけは別の概念？」とかなりそうですので）

2024-10-05 00:19 UTC, koizumistr commented on doc/src/sgml/config3.sgml
> +<filename>Postgresql.auto.conf</filename>に保存された設定は、<literal>allow_alter_system</literal>が<literal>off</literal>に設定されていても有効になります。
ここはまだ
Postgresql.auto.conf
のままのようです。

2024-10-05 07:42 UTC, tatsuo-ishii commented on doc/src/sgml/config3.sgml
> +<filename>Postgresql.auto.conf</filename>に保存された設定は、<literal>allow_alter_system</literal>が<literal>off</literal>に設定されていても有効になります。
> ここはまだ
> Postgresql.auto.conf
> のままのようです

修正します。

2024-10-05 07:52 UTC, tatsuo-ishii reviewed
再度の小泉さんの指摘に対応しました。

2024-10-05 07:52 UTC, tatsuo-ishii commented on doc/src/sgml/config0.sgml
>  この値が単位なしで指定した場合、ブロック、つまり<symbol>BLCKSZ</symbol>バイト、通常は8キロバイトとして扱われます。
> この値が単位なしで指定された場合

としました。

2024-10-05 07:52 UTC, tatsuo-ishii commented on doc/src/sgml/config0.sgml
> +<literal>pg_multixact/offsets</literal>の内容を共有メモリするために使用するキャッシュの量を指定します（<xref linkend="pgdata-contents-table"/>を参照してください）。
自動翻訳に引きづられました。

2024-10-05 07:52 UTC, tatsuo-ishii commented on doc/src/sgml/config3.sgml
>  値を<literal>true</literal>に設定すると、すべてのイベント・トリガーが起動します。
「イベントトリガー」にします。

2024-10-12 13:14 UTC, koizumistr commented
対応ありがとうございます。確認しました。

2024-10-15 02:19 UTC, KenichiroTanaka requested changes
細かいですが３点気づくところがありましたので見ていただいてもいいでしょうか。

2024-10-15 02:27 UTC, tatsuo-ishii commented on doc/src/sgml/config0.sgml
> +<xref linkend="sql-notify"/>/<xref linkend="sql-listen"/>キューのために割り当てられたページの最大量を指定します。
そうですね。修正します。

2024-10-15 02:44 UTC, tatsuo-ishii commented on doc/src/sgml/config1.sgml
> +有効にすると、プランナはより効率的プランの生成を試みます。
確かにonlyが訳出されてませんね。ただ、訳出としてはonlyが
`only sorted to match the <literal>ORDER BY</literal> clause`
と"sorted to match"にかかっていると思うので、
`<literal>GROUP BY</literal>句があれば、<literal>GROUP BY</literal>キーを<literal>ORDER BY</literal>句にのみ合わせたソート順を持つプランを生成します。`
としてみました。

2024-10-15 02:46 UTC, tatsuo-ishii commented on doc/src/sgml/config3.sgml
>  このパラメータは、<filename>PostgreSQL.conf</filename>ファイルまたはサーバコマンドラインでのみ設定できます。
見逃してました。

2024-10-15 11:35 UTC, KenichiroTanaka commented on doc/src/sgml/config1.sgml
> +有効にすると、プランナはより効率的プランの生成を試みます。
承知しました。いただいた案の方が良いように思います。

2024-10-15 11:36 UTC, KenichiroTanaka approved these changes
大きなファイルの対応及びレビューありがとうございました。この辺りでマージします。

2024-10-15 11:37 UTC, merged