pg_createsubscriber.sgmlのPostgreSQL 17.0対応です。
pgsql-jp/jpug-doc pull request #3110
Opened 2024-10-05 05:53 UTC by tatsuo-ishii

新規ファイルです。

2024-10-15 11:34 UTC, KenichiroTanaka requested changes
細かいですが1箇所気づくところがありましたので見ていただいていいでしょうか。

2024-10-16 00:18 UTC, noborus commented on doc/src/sgml/ref/pg_createsubscriber.sgml
> +  <refpurpose>物理レプリカを論理レプリカに変換する</refpurpose>
こちらの「new」が抜けています。

2024-10-18 12:44 UTC, tatsuo-ishii reviewed
レビューありがとうございました。

2024-10-18 12:44 UTC, tatsuo-ishii commented on doc/src/sgml/ref/pg_createsubscriber.sgml
> +  <refpurpose>物理レプリカを論理レプリカに変換する</refpurpose>
失礼しました。修正します。

2024-10-18 12:44 UTC, tatsuo-ishii commented on doc/src/sgml/ref/pg_createsubscriber.sgml
> +データディレクトリ外に保存されている場合は、実際の<filename>postgresql.conf</filename>コンフィギュレーションファイルを指定できます。
はい、「設定ファイル」とします。
あと、264行目が機械翻訳に引きずられて結構でたらめな訳だったのを修正しました。

2024-10-20 22:38 UTC, KenichiroTanaka approved these changes
対応ありがとうございました。

2024-10-20 22:40 UTC, merged