update for 17.0 - part 5
pgsql-jp/jpug-doc pull request #3113
Opened 2024-10-05 08:45 UTC by koizumistr

以下のファイルの17.0対応です。

- indices.sgml
- json.sgml
- manage-ag.sgml
- pageinspect.sgml
- parallel.sgml

2024-10-08 02:34 UTC, noborus commented on doc/src/sgml/parallel.sgml
> +データベースに書き込むか、（エラー回復のためにサブトランザクションを使う場合以外で）トランザクションの状態を変更するか、シーケンスにアクセスするか、あるいは、恒久的な設定変更を行う関数あるいは集約は、<literal>PARALLEL UNSAFE</literal>とマークされなければなりません。
訳だと「関数あるいは集約は」に辿りつくまでが長いのが気になります。
関数あるいは集約は、データベースに書き込むか〜場合、`<literal>PARALLEL UNSAFE</literal>`とマークされなければなりません。
同様に関数は、一時テーブル、〜アクセスする場合、`<literal>PARALLEL RESTRICTED</literal>`とマークされなければなりません。
とするのはどうでしょう（前からでしたが、Similarly, functions must be なので、こっちは関数だけですね）。

2024-10-08 14:04 UTC, koizumistr commented
確認ありがとうございます。対応しました。

2024-10-09 01:20 UTC, noborus approved these changes
ありがとうございます。
確認しました。

2024-10-15 10:24 UTC, tatsuo-ishii requested changes
一通り確認しました。

2024-10-15 10:24 UTC, tatsuo-ishii commented on doc/src/sgml/indices.sgml
> +派生した式が、行挿入と<link linkend="storage-hot">非HOT更新</link>の度に計算されなければなりませんので、インデックス式は相対的に見て維持が高価です。
以前からですが、「計算されなければなりませんので」は「計算されなければならないので」の方が自然ではないでしょうか。

2024-10-15 11:42 UTC, KenichiroTanaka approved these changes

2024-10-20 15:36 UTC, koizumistr commented
確認ありがとうございます。対応しました。


> 「計算されなければなりませんので」は「計算されなければならないので」の方が自然ではないでしょうか。

「計算されなければなりませんので」も間違いではないと思いますが、ここでは「計算されなければならないので」とした方が短くてより好ましいのではないか、というのはその通りと思います。

2024-10-22 12:44 UTC, tatsuo-ishii approved these changes
対応ありがとうございました。

2024-10-22 12:44 UTC, merged