update sepgsql for 17.0
pgsql-jp/jpug-doc pull request #3115
Opened 2024-10-05 15:07 UTC by koizumistr

sepgsql.sgml の17.0対応です。

2024-10-08 05:29 UTC, noborus approved these changes
確認しました。

2024-10-15 10:32 UTC, tatsuo-ishii commented on doc/src/sgml/sepgsql.sgml
> +ビルド時に<filename>libselinux-devel</filename>パッケージがインストールされている事を確認してください。
RPMを「パッケージ」に言い換えていますが、そういう方針なのでしたっけ？もしそういう決まり事があるのを見逃していたらすいません。

2024-10-15 11:44 UTC, KenichiroTanaka commented on doc/src/sgml/sepgsql.sgml
> +ビルド時に<filename>libselinux-devel</filename>パッケージがインストールされている事を確認してください。
RPMをパッケージに言い換えるルールはなかったと思います。

2024-10-15 11:44 UTC, KenichiroTanaka requested changes
1箇所、RPM->パッケージとなってしまっているところの対応をお願いできないでしょうか。

2024-10-15 14:34 UTC, koizumistr commented
確認ありがとうございます。対応しました。

2024-10-16 05:59 UTC, tatsuo-ishii commented
確認しました。マージします。

2024-10-16 06:00 UTC, tatsuo-ishii approved these changes
対応ありがとうございます。

2024-10-20 22:41 UTC, KenichiroTanaka approved these changes
対応ありがとうございました

2024-10-20 22:41 UTC, merged