Translate installation.sgml
pgsql-jp/jpug-doc pull request #3120
Opened 2024-10-06 10:43 UTC by k-zshiba

2024-10-08 14:08 UTC, noborus commented on doc/src/sgml/installation.sgml
>     <para>
この下の`<title>Collecting Crash Dumps</title>`も翻訳対象です。

2024-10-08 14:08 UTC, noborus commented on doc/src/sgml/installation.sgml
>  <!--
この上の `<title>Special Considerations for 64-Bit Windows</title>`も翻訳対象です。

2024-10-08 14:08 UTC, noborus commented on doc/src/sgml/installation.sgml
>  こうした場合、64ビット版のPostgreSQLで使用することはできません。
この下の`<title>Collecting Crash Dumps</title>`も翻訳対象です。

2024-10-16 13:07 UTC, k-zshiba commented on doc/src/sgml/installation.sgml
> +SElinux サポート付きで構築します。
修正します。

2024-10-16 13:07 UTC, k-zshiba commented on doc/src/sgml/installation.sgml
> +SElinux サポート付きでビルドします。
修正します。

2024-10-16 13:07 UTC, k-zshiba commented on doc/src/sgml/installation.sgml
> +<application>PL/Tcl</application>を構築する時に必要です （注意：バージョン8.4が必要です。
修正します。

2024-10-16 13:07 UTC, k-zshiba commented on doc/src/sgml/installation.sgml
> -《機械翻訳》個々のビルドターゲットは<command>ninja</command> <replaceable>target</replaceable>を使用してビルドできます。
修正します。

2024-10-16 13:07 UTC, k-zshiba commented on doc/src/sgml/installation.sgml
>     <para>
修正します。

2024-10-16 13:08 UTC, k-zshiba commented on doc/src/sgml/installation.sgml
>  <!--
修正します。

2024-10-16 13:08 UTC, k-zshiba commented on doc/src/sgml/installation.sgml
>  こうした場合、64ビット版のPostgreSQLで使用することはできません。
修正します。

2024-10-22 00:16 UTC, KenichiroTanaka requested changes
変更量が多いファイルの対応ありがとうございました。
細かいですが２箇所だけ気づくところがありましたので見ていただいてもいいでしょうか。

2024-10-22 00:16 UTC, KenichiroTanaka commented on doc/src/sgml/installation.sgml
>  フリー版の標準配布で十分です）。
機械翻訳の箇所ですが、
「free Standard Distribution」が「フリー版の標準配布」と「無料のStandard Distribution」（5599行目）で
ぶれているのでどちらかに統一したいです。
リンク先のActiveStateのHPを見ましたがエディションはFree,Term,Enterpriseでマニュアルが表記を合わせているわけでもないのでどちらでも良さそうですね。
「無料の標準配布」あたりが良いでしょうか。

2024-10-22 00:16 UTC, KenichiroTanaka commented on doc/src/sgml/installation.sgml
>  ソースは<ulink url="http://www.ossp.org/pkg/lib/uuid/"></ulink>にあります。
こちらも機械翻訳の場所です。
細かいですが、他の行に合わせて
```
ソースは<ulink url="http://www.ossp.org/pkg/lib/uuid/"></ulink>にあります。
```
は
```
ソースは<ulink url="http://www.ossp.org/pkg/lib/uuid/"></ulink>からダウンロードできます。
```
としていただいてもいいでしょうか。

2024-10-22 14:18 UTC, k-zshiba commented on doc/src/sgml/installation.sgml
>  フリー版の標準配布で十分です）。
レビューありがとうございます。修正します。

2024-10-22 14:18 UTC, k-zshiba commented on doc/src/sgml/installation.sgml
>  ソースは<ulink url="http://www.ossp.org/pkg/lib/uuid/"></ulink>にあります。
こちらも修正します。

2024-10-24 10:40 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。
この辺りでマージします。

2024-10-24 10:40 UTC, merged