catalogs.sgmlの17.0対応です
pgsql-jp/jpug-doc pull request #3128
Opened 2024-10-12 01:00 UTC by noborus

2024-10-12 01:02 UTC, noborus commented
provider: プロバイダ
Provider-specific: 提供者固有
で統一されていますが、気になりました。

2024-10-22 12:16 UTC, KenichiroTanaka requested changes
２箇所だけ（同じ内容です）気づくところがありましたので見ていただけないでしょうか。

2024-10-24 03:28 UTC, noborus commented on doc/src/sgml/catalogs0.sgml
> +照合順序のプロバイダ： <literal>d</literal> = データベースのデフォルト、 <literal>b</literal> = builtin、 <literal>c</literal> = libc、 <literal>i</literal> = icu
レビューありがとうございます。
「builtin」はプロバイダ名なので、このままが良いと思いました。
例えば `initdb --locale-provider=builtin`で指定して、それが"b"と表示されるので、bultinの補足説明は別途するのが良いと思います。

2024-10-24 10:52 UTC, KenichiroTanaka commented on doc/src/sgml/catalogs0.sgml
> +照合順序のプロバイダ： <literal>d</literal> = データベースのデフォルト、 <literal>b</literal> = builtin、 <literal>c</literal> = libc、 <literal>i</literal> = icu
確かにプロバイダ名ですね。失礼しました。このままが良いです。

2024-10-24 10:53 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。この辺りでマージします。

2024-10-24 10:53 UTC, merged