fileのにファイルが抜けている箇所の修正
pgsql-jp/jpug-doc pull request #3133
Opened 2024-10-13 23:52 UTC by noborus

. #3123 の修正です。

2024-10-15 14:54 UTC, koizumistr reviewed
確認しました。

2024-10-15 14:54 UTC, koizumistr commented on doc/src/sgml/datetime.sgml
> +しかし、(歴史的な理由で)IANA時間帯データベースのファイルにこれらの名前があるため、実際には名前付き時間帯として扱われます。
データベースにこれらの名前のファイルがあるため

ということではないでしょうか（byをどう解釈すべきかよく分かっていませんが、、、）

2024-10-16 00:15 UTC, noborus commented on doc/src/sgml/datetime.sgml
> +しかし、(歴史的な理由で)IANA時間帯データベースのファイルにこれらの名前があるため、実際には名前付き時間帯として扱われます。
やっぱりここだけ元のままにしておいた方が良いかもしれません。
ここだけファイルシステムのファイルではない（EST5EDTという名前のファイルはない）ので
ファイルは入れない方が良い気がしてきました。

2024-10-19 08:49 UTC, noborus commented on doc/src/sgml/datetime.sgml
> +しかし、(歴史的な理由で)IANA時間帯データベースのファイルにこれらの名前があるため、実際には名前付き時間帯として扱われます。
元に戻しました。

2024-10-20 14:55 UTC, koizumistr commented
対応ありがとうございます。確認しました。（というか変更しないということになるので、ファイル自体がここには出てこなくなるんですね、、、）

2024-11-03 11:03 UTC, tatsuo-ishii requested changes
一通り確認しました。

2024-11-03 11:03 UTC, tatsuo-ishii commented on doc/src/sgml/high-availability.sgml
> +例えば、<varname>max_standby_archive_delay</varname>が増大し、切断している期間WALアーカイブファイルのコンフリクト発生による問い合わせの中断が速やかに行われないことを考えてみてください。
"consider"は"increase"にかかっていると思うのでこれだと意味が違うような。こんな感じだと思います。
`例えば、<varname>max_standby_archive_delay</varname>を増やし、接続をしていない間、WALアーカイブファイルのコンフリクトによって問い合わせの急速な中断が起きないようにすることを考慮してください。`

2024-11-09 00:13 UTC, noborus commented on doc/src/sgml/high-availability.sgml
> +例えば、<varname>max_standby_archive_delay</varname>が増大し、切断している期間WALアーカイブファイルのコンフリクト発生による問い合わせの中断が速やかに行われないことを考えてみてください。
ありがとうございます。いただきます。
また、次の行も不足があったようなので修正します。

2024-12-28 07:01 UTC, KenichiroTanaka commented
石井さんの指摘事項も反映されているようですのでこの辺りでマージします。

2024-12-28 07:01 UTC, merged