標準SQに統一（２）と「準拠」に統一
pgsql-jp/jpug-doc pull request #3139
Opened 2024-10-19 04:57 UTC by noborus

SQL標準を標準SQLに統一。
conforms to ～を準拠するに統一。

2024-10-19 08:45 UTC, noborus commented
#3135 の対応です。

2024-10-30 22:26 UTC, KenichiroTanaka requested changes
1箇所だけ気づくところがありましたので見ていただいてもいいでしょうか。

2024-10-30 22:26 UTC, KenichiroTanaka commented on doc/src/sgml/func.sgml
> +これらのアプリケーションをSQL標準に準拠するように変更することを強くお勧めします。
ここは修正が逆になってしまっているでしょうか？

2024-11-01 03:47 UTC, noborus commented on doc/src/sgml/func.sgml
> +これらのアプリケーションをSQL標準に準拠するように変更することを強くお勧めします。
なんと。修正します。

2024-11-01 09:24 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。マージします。

2024-11-01 09:25 UTC, merged