「。」と「）」を原文の「.」と「)」に合わせる修正
pgsql-jp/jpug-doc pull request #3145
Opened 2024-10-23 14:15 UTC by noborus

2024-10-24 00:28 UTC, noborus commented
#3144 対応

2024-10-31 02:27 UTC, KenichiroTanaka requested changes
一通り確認しました。
1箇所だけ気づくところがありましたので見ていただけないでしょうか。

2024-10-31 02:27 UTC, KenichiroTanaka commented on doc/src/sgml/backup.sgml
> +同様に、デフォルトのポートは<envar>PGPORT</envar>環境変数で指定されているか、うまく行かない場合にはコンパイル時の設定がデフォルトとなります（そこはうまくできていて、サーバは通常コンパイル時の設定をデフォルトとします。）
かっこの前の
「コンパイル時の設定がデフォルトとなります（」
は
「コンパイル時の設定がデフォルトとなります。（」
でなくていいでしょうか。

2024-11-01 03:50 UTC, noborus commented on doc/src/sgml/backup.sgml
> +同様に、デフォルトのポートは<envar>PGPORT</envar>環境変数で指定されているか、うまく行かない場合にはコンパイル時の設定がデフォルトとなります（そこはうまくできていて、サーバは通常コンパイル時の設定をデフォルトとします。）
修正します。

2024-11-01 09:25 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。マージします。

2024-11-01 09:25 UTC, merged