「。」と「）」を原文の「.」と「)」に合わせる修正（２）
pgsql-jp/jpug-doc pull request #3146
Opened 2024-10-24 00:28 UTC by noborus

2024-10-24 00:28 UTC, noborus commented
#3144 対応

2024-10-31 04:18 UTC, KenichiroTanaka requested changes
一通り確認しました。
１箇所だけ気づくところがありましたので見ていただいてもいいでしょうか。

2024-11-01 03:52 UTC, noborus commented on doc/src/sgml/ref/select.sgml
> -詳しくは、後述の<xref linkend="sql-distinct"/>を参照してください）。
修正します。

2024-11-01 09:26 UTC, KenichiroTanaka approved these changes
対応ありがとうございます。マージします。

2024-11-01 09:26 UTC, merged