client-auth.sgmlの17.0対応です
pgsql-jp/jpug-doc pull request #3150
Opened 2024-10-27 08:22 UTC by noborus

2024-11-07 11:51 UTC, tatsuo-ishii requested changes
一通り確認しました。

2024-11-07 11:51 UTC, tatsuo-ishii commented on doc/src/sgml/client-auth.sgml
> +その二番目のバインドが成功するとデータベースアクセスを認められます。
好みの範囲かも知れませんが、「データベースアクセスを認められます。」は、「データベースアクセスが認められます。」ないし「データベースアクセスは認められます。」の方が、自然だと思います。

2024-11-09 01:31 UTC, noborus commented on doc/src/sgml/client-auth.sgml
> +その二番目のバインドが成功するとデータベースアクセスを認められます。
確かに。ありがとうございます。修正します。

2024-11-10 09:18 UTC, tatsuo-ishii approved these changes
修正ありがとうございます。確認しました。

2024-11-10 09:18 UTC, merged