訳抜けの修正
pgsql-jp/jpug-doc pull request #3151
Opened 2024-11-06 08:22 UTC by noborus

チェックのため括弧の全角に修正したものを含みます。
.と。の対応の修正も含みます。

2024-11-08 15:13 UTC, KenichiroTanaka requested changes
対応ありがとうございます。
一通り確認しました。
1箇所だけ気づくところがありましたので見ていただいてもいいでしょうか。

2024-11-08 15:13 UTC, KenichiroTanaka commented on doc/src/sgml/config.sgml
> +それらは機密データを含む可能性があるため、ログファイルを誰もが読み取り可能にすることは賢明ではありません。
細かいですが、In any caseの訳出があった方が良いように思います。

2024-11-09 01:30 UTC, noborus commented on doc/src/sgml/config.sgml
> +それらは機密データを含む可能性があるため、ログファイルを誰もが読み取り可能にすることは賢明ではありません。
ありがとうございます。修正しました。

2024-11-11 22:52 UTC, KenichiroTanaka approved these changes
複数名のレビューが通ってますのでこの辺りでマージします。

2024-11-11 22:52 UTC, merged