charset.sgmlのPostgreSQL 17.0対応です。
pgsql-jp/jpug-doc pull request #3173
Opened 2024-12-01 08:05 UTC by tatsuo-ishii

2024-12-11 03:08 UTC, noborus commented on doc/src/sgml/charset.sgml
> +ロケールプロバイダは、照合と文字分類のロケール動作を定義するライブラリを指定します。
照合順序で統一で良いのではないでしょうか。

2024-12-11 03:09 UTC, noborus commented on doc/src/sgml/charset.sgml
> +<literal>C</literal>と<literal>POSIX</literal>の照合は、<quote>従来のC</quote>の動作に基づいています。
ここの照合順序で良いと思います。

2024-12-11 03:10 UTC, noborus commented on doc/src/sgml/charset.sgml
> +<literal>デフォルト</literal>照合順序は、データベース作成時に指定したロケールを選択します。
ここは`<literal>default</literal>`のままで良いのでは？

2024-12-11 03:11 UTC, noborus commented on doc/src/sgml/charset.sgml
>  これらの追加の照合の効率性と安定度は、照合順序プロバイダ、プロバイダバージョン、およびロケールによって異なります。
ここも照合順序。

2024-12-11 03:21 UTC, noborus reviewed
一通り確認しました。
照合→照合順序への統一と`<literal>default</literal>`の確認をお願いします。

2024-12-12 03:32 UTC, tatsuo-ishii commented on doc/src/sgml/charset.sgml
> +ロケールプロバイダは、照合と文字分類のロケール動作を定義するライブラリを指定します。
でも、"collation order"っていうのも出てくるんですよね。"collation"も"collation order"も「照合順序」と訳してしまうと区別がつかなくなるので、単独の"collation"をここでは「照合」と訳しています。

2024-12-12 03:34 UTC, tatsuo-ishii commented on doc/src/sgml/charset.sgml
> +<literal>デフォルト</literal>照合順序は、データベース作成時に指定したロケールを選択します。
おっと、そうですね。

2024-12-12 03:34 UTC, tatsuo-ishii commented on doc/src/sgml/charset.sgml
>  これらの追加の照合の効率性と安定度は、照合順序プロバイダ、プロバイダバージョン、およびロケールによって異なります。
同上。

2024-12-12 23:15 UTC, noborus commented on doc/src/sgml/charset.sgml
> +ロケールプロバイダは、照合と文字分類のロケール動作を定義するライブラリを指定します。
確かに"collation"を照合"collation order"を照合順序とした方がすっきりしますが、
他で統一されてなくて"collation"を照合順序としている場合が多いです。
統一されていないのでissueを立てます。

2024-12-13 22:08 UTC, noborus approved these changes
ありがとうございます。確認しました。
collationは全体で見直して修正するということでここではおいておきます。

2024-12-17 00:09 UTC, KenichiroTanaka requested changes
いくつか気づいたところがありますので見ていただいてもいいでしょうか。

2024-12-17 00:09 UTC, KenichiroTanaka commented on doc/src/sgml/charset.sgml
>  パターンマッチ（正規表現を含む）の場合は、POSIX互換のUnicode<ulink url="https://www.unicode.org/reports/tr18/#Compatibility_Properties">互換性プロパティを使用します</ulink>。
POSIX Compatible variantのvariantを訳出すべきか判断できていません。
互換に亜種のニュアンスを含むのでこのままでもいい気がしています。
（どなたかご意見いただけないでしょうか）

2024-12-31 02:11 UTC, tatsuo-ishii reviewed
レビューありがとうございます。

2024-12-31 02:11 UTC, tatsuo-ishii commented on doc/src/sgml/charset.sgml
>  パターンマッチ（正規表現を含む）の場合は、POSIX互換のUnicode<ulink url="https://www.unicode.org/reports/tr18/#Compatibility_Properties">互換性プロパティを使用します</ulink>。
リンク先の表[Annex C: Compatibility Properties](https://www.unicode.org/reports/tr18/#Compatibility_Properties)を見ると、Unicode標準とPOSIX標準を対比させる形で解説しており、ここではPostgreSQLはUnicode標準ではなく、POSIX標準の方を使っているという意図が込められていると思います。だとすると、variantを訳出した方がよいと思い、variantを訳すように修正してみました。

2025-01-05 23:16 UTC, KenichiroTanaka approved these changes
対応ありがとうございました。
いただいている修正で問題ないかと思いますのでこの辺りでマージします。

2025-01-05 23:16 UTC, merged