Update for release-17
pgsql-jp/jpug-doc pull request #3174
Opened 2024-12-06 04:56 UTC by kitayama

現在、半分近くの進捗ですが、量が多くてレビューにも時間がかかるので、現時点でプルリクエストを出します。翻訳は継続して進めていきます。

2024-12-10 22:14 UTC, noborus commented on doc/src/sgml/release-17.sgml
> +     <title>モニタリング</title>
このタイトルは共通にしてしまう方針で決めていたものです。 #2893
変更または統一しないほうがよいでしょうか？

2024-12-10 22:16 UTC, noborus commented on doc/src/sgml/release-17.sgml
>       <itemizedlist>
タイトルの後、`<itemizedlist>`の前に空行が入っていたのが削除されています。削除しないでもらえると助かります。

2024-12-10 22:17 UTC, noborus commented on doc/src/sgml/release-17.sgml
>       <itemizedlist>
ここも元はタイトルの後に空行がありました。

2024-12-10 22:20 UTC, noborus commented on doc/src/sgml/release-17.sgml
> +<link linkend="monitoring-pg-stat-subscription"><structname>pg_stat_subscription</structname></link>にworker_type列が追加されました。
これは日本語訳のほうが正しくてcolumnなんだから原文の方もworkter_typeにしてほしいですね

2024-12-10 22:39 UTC, noborus commented on doc/src/sgml/release-17.sgml
> +ストリーミングI/Oを使用したシーケンシャル読み取り、高い同時実行時の書き込みスループット、<link linkend="btree">btree</link>インデックス内の複数の値の検索など、さまざまなクエリ性能が向上しました。
"sequential reads"が他で使われてなかったので、正解はないのですが、
シーケンシャルリードの方が使用されていると思います。

2024-12-10 22:40 UTC, noborus reviewed
ざっくりチェックしました

2024-12-30 04:44 UTC, kitayama commented on doc/src/sgml/release-17.sgml
> +     <title>モニタリング</title>
レビューありがとうございます。監視に戻しました。

2024-12-30 04:44 UTC, kitayama commented on doc/src/sgml/release-17.sgml
>       <itemizedlist>
対応しました。

2024-12-30 04:44 UTC, kitayama commented on doc/src/sgml/release-17.sgml
>       <itemizedlist>
対応しました。

2024-12-30 04:45 UTC, kitayama commented on doc/src/sgml/release-17.sgml
> +ストリーミングI/Oを使用したシーケンシャル読み取り、高い同時実行時の書き込みスループット、<link linkend="btree">btree</link>インデックス内の複数の値の検索など、さまざまなクエリ性能が向上しました。
シーケンシャルリードに変更しました。

2024-12-31 07:41 UTC, noborus requested changes

2024-12-31 07:41 UTC, noborus commented on doc/src/sgml/release-17.sgml
>       <itemizedlist>
ツールの都合もあるのですが、全体的に統一して欲しいため、空行は原文として含めずに後に入れてほしいです。

```suggestion
<!--
     <title>Streaming Replication and Recovery</title>
-->
     <title>ストリーミングレプリケーションとリカバリ</title>

     <itemizedlist>
```

2024-12-31 07:41 UTC, noborus commented on doc/src/sgml/release-17.sgml
>       <itemizedlist>
こちらも
```suggestion
    <sect4 id="release-17-logical">
<!--
     <title><link linkend="logical-replication">Logical Replication</link></title>
-->
     <title><link linkend="logical-replication">論理レプリケーション</link></title>

     <itemizedlist>
```

2025-01-03 08:35 UTC, kitayama commented on doc/src/sgml/release-17.sgml
>       <itemizedlist>
修正しました。

2025-01-03 08:35 UTC, kitayama commented on doc/src/sgml/release-17.sgml
>       <itemizedlist>
こちらも修正しました。

2025-01-17 10:24 UTC, KenichiroTanaka requested changes
膨大な量のファイルの対応ありがとうございます。
一通り確認しました。
いくつか気づいたところがあるため見ていただいてもいいでしょうか。

2025-01-17 10:24 UTC, KenichiroTanaka commented on doc/src/sgml/release-17.sgml
> +いくるかのクライアントアプリケーションに<option>&#45;-sync-method</option>パラメータが追加されました。
いくるか→いくつか
のTYPOです。

2025-01-17 10:24 UTC, KenichiroTanaka commented on doc/src/sgml/release-17.sgml
> +オプション
「オプション」のゴミが残ってしまったようです。

2025-01-24 07:32 UTC, kitayama commented on doc/src/sgml/release-17.sgml
> +コンストラクタ、ID関数、JSONデータをテーブル表現に変換する<link linkend="functions-sqljson-table"><function>JSON_TABLE()</function></link>関数を含む新しい<acronym>SQL/JSON</acronym>関数。
確かに「capabilities」なので「機能」ですね。たくさんある「関数」に引っ張られてしまったのかな。修正しました。

2025-01-24 07:35 UTC, kitayama commented on doc/src/sgml/release-17.sgml
> +新しいクライアント側コネクションオプション<link linkend="libpq-connect-sslnegotiation"><literal>sslnegotiation=direct</literal></link>は、ラウンドトリップハンドシェークを回避するために直接TLSネゴシエーションを実行します。
おお、逆ですね。見逃してました。修正しました。

2025-01-24 07:43 UTC, kitayama commented on doc/src/sgml/release-17.sgml
> +メンテナンス操作中に安全な<xref linkend="guc-search-path"/>を使用するように機能が変更されました。
いただいた案で修正しました。

2025-01-24 07:46 UTC, kitayama commented on doc/src/sgml/release-17.sgml
>         Allow granting the right to perform maintenance operations
commitのタイトルと異なりますね。

2025-01-24 07:46 UTC, kitayama commented on doc/src/sgml/release-17.sgml
> +いくるかのクライアントアプリケーションに<option>&#45;-sync-method</option>パラメータが追加されました。
修正しました。

2025-01-24 07:49 UTC, kitayama commented on doc/src/sgml/release-17.sgml
> +オプション
削除しました。

2025-01-31 09:04 UTC, noborus requested changes
謝辞のparaに《機械翻訳》が残ってしまってます。

次からは機械翻訳でなく定型文として修正しなくて良いようにしようと思います。

2025-01-31 09:20 UTC, noborus commented on doc/src/sgml/release-17.sgml
> +<application><xref linkend="unaccent"/></application>の文字変換ルールに空白と引用符を含めることができるようにしました。
ほかは「できるようになりました。」にしてますが、ここだけ「できるようにしました。」のままです。

2025-02-10 03:02 UTC, KenichiroTanaka approved these changes

2025-02-12 07:56 UTC, kitayama commented on doc/src/sgml/release-17.sgml
> +<application><xref linkend="unaccent"/></application>の文字変換ルールに空白と引用符を含めることができるようにしました。
「できるようになりました。」に修正しました。

2025-02-12 07:57 UTC, kitayama commented
> 謝辞のparaに《機械翻訳》が残ってしまってます。
気付きませんでした。削除しました。

2025-02-12 10:21 UTC, noborus approved these changes
ありがとうございます。確認しました。

2025-02-12 10:22 UTC, noborus commented
レビュー済みなのでマージします。

2025-02-12 10:22 UTC, merged