high-availability.sgmlのPostgreSQL 17.0対応
pgsql-jp/jpug-doc pull request #3187
Opened 2024-12-18 07:52 UTC by kiskk

はじめてのPRです。対応漏れや不足がありましたらご指摘いただければと思います、よろしくお願いします。

「これらの方法の欠点は、しばしば必要以上のWALセグメントを保持することで、これらに対してレプリケーションスロットは必要とされる数のセグメントしか保持しません。」
英語では1センテンスでしたが、日本語では2つに分けた方がわかりやすいかもしれません。原本をふまえ1センテンスで書いています。

「ロジカルレプリケーションスロット」とするか、「論理レプリケーションスロット」とするかで悩みましたが、多くの文言が「論理レプリケーション」としていたためこちらを採用しています。

`pg_statio_` という書き方は原本を踏襲しています。 `pg_statio_*` とした方がわかりやすいかもしれませんが好みの範疇と思いました。

2024-12-20 00:39 UTC, noborus reviewed
> 「これらの方法の欠点は、しばしば必要以上のWALセグメントを保持することで、これらに対してレプリケーションスロットは必要とされる数のセグメントしか保持しません。」
英語では1センテンスでしたが、日本語では2つに分けた方がわかりやすいかもしれません。原本をふまえ1センテンスで書いています。

もうちょっと長くなると分ける方がよいですが、これぐらいだとこのままで良いと思いました。

>「ロジカルレプリケーションスロット」とするか、「論理レプリケーションスロット」とするかで悩みましたが、多くの文言が「論理レプリケーション」としていたためこちらを採用しています。

はい。「論理レプリケーション」で良いです。

> pg_statio_ という書き方は原本を踏襲しています。 pg_statio_* とした方がわかりやすいかもしれませんが好みの範疇と思いました。

これは変えないでください。変えるなら原文からでお願いします。

2024-12-20 00:39 UTC, noborus commented on doc/src/sgml/high-availability.sgml
> +トランザクションの待機中にスタンバイサーバを再作成する必要がある場合、<function>pg_backup_start()</function>関数および<function>pg_backup_stop()</function>関数を実行するコマンドを<varname>synchronous_commit</varname> = <literal>off</literal>であるセッション内で
commands -> functions なので「実行するコマンドを」は単純に削って良いと思います

2024-12-21 00:44 UTC, kiskk commented on doc/src/sgml/high-availability.sgml
> +トランザクションの待機中にスタンバイサーバを再作成する必要がある場合、<function>pg_backup_start()</function>関数および<function>pg_backup_stop()</function>関数を実行するコマンドを<varname>synchronous_commit</varname> = <literal>off</literal>であるセッション内で
ありがとうございます、コメントのとおり、原文がcommandsからfunctionsに変更されているので該当箇所を削除しました

2024-12-21 02:59 UTC, noborus approved these changes
修正ありがとうございます。確認しました。

2024-12-24 00:42 UTC, KenichiroTanaka requested changes
対応ありがとうございます。
細かいですが１点だけ、気づくところがありましたので見ていただいてもいいでしょうか。

2024-12-24 00:42 UTC, KenichiroTanaka commented on doc/src/sgml/high-availability.sgml
>  <xref linkend="guc-max-slot-wal-keep-size"/>は、レプリケーションスロットが保持するWALファイルのサイズを制限するために使用できます。
細かいですが１点だけ、修正をお願いします。
機械翻訳の箇所ですが、
「レプリケーションスロットが保持するWALファイルのサイズを制限する」
は、原文通り受け身形で
「レプリケーションスロットによって保持されるWALファイルのサイズを制限する」
でお願いしてもいいでしょうか。
今のままだとレプリケーションスロットがWALを保持する機能を持つようにも理解できるためです。
レプリケーションスロットの概念が少し難しいため、誤解を招く表現はできるだけ減らせればと考えています。

2024-12-24 02:58 UTC, kiskk commented on doc/src/sgml/high-availability.sgml
>  <xref linkend="guc-max-slot-wal-keep-size"/>は、レプリケーションスロットが保持するWALファイルのサイズを制限するために使用できます。
ご確認ありがとうございます。
該当箇所をコメントいただいたとおり
「レプリケーションスロットによって保持されるWALファイルのサイズを制限する」
に修正しました。

2024-12-24 04:26 UTC, KenichiroTanaka approved these changes
早速の対応ありがとうございました。
複数名のレビューが通りましたので本ファイルはここでマージします。

2024-12-24 04:32 UTC, merged