tableに対してテーブルが入っていないところの見直し
pgsql-jp/jpug-doc pull request #3193
Opened 2024-12-27 02:44 UTC by noborus

テーブルが抜けている箇所の修正。
information_schema.sgmlは記述を統一するように見直しました。

2024-12-28 07:16 UTC, KenichiroTanaka requested changes
修正いただいたところ以外の箇所なのですが１つだけ気づいてしまったので
見ていただけないでしょうか。

2024-12-28 07:16 UTC, KenichiroTanaka commented on doc/src/sgml/perform.sgml
>  こうすると、WALデータを処理する保管処理またはWAL送信処理にかかる時間がかからないことの他に、実際のところ、特定のコマンドをより高速にします。
今回のレビュー対象外なのですが、
「WALデータを処理する保管処理またはWAL送信処理にかかる時間」
の箇所ですがarchiverは「保管処理」よりも「アーカイブ処理」の方が分かりやすかなと思います。
（直前の2534行目もそのようになっています。）
あと処理（process）も多く訳出されているため、
「WALデータをアーカイブまたはWAL送信処理するためにかかる時間」
くらいの訳とするのはどうでしょうか。

2024-12-30 06:29 UTC, noborus commented on doc/src/sgml/perform.sgml
>  こうすると、WALデータを処理する保管処理またはWAL送信処理にかかる時間がかからないことの他に、実際のところ、特定のコマンドをより高速にします。
ちょっと見直して、
「こうすると、アーカイブやWAL送信にWALデータを処理する時間を避けることの他に、実際のところ、特定のコマンドをより高速にします。」としてみました。

ほんとは、複数ファイルにまたがっての修正の場合は、関係ない行は他のPRにした方がよいですね。

2025-01-05 22:37 UTC, KenichiroTanaka commented
対応ありがとうございます。
そうですね。
複数ファイル修正の時は別prにするようにします。

2025-01-05 22:37 UTC, KenichiroTanaka approved these changes

2025-01-05 22:37 UTC, merged